package io.github.testlens.selenium.assertions;

public enum UiAssertionFailureReason {
    ELEMENT_NOT_FOUND,
    ELEMENT_NOT_VISIBLE,
    ELEMENT_STILL_VISIBLE,
    ELEMENT_NOT_ENABLED,
    ELEMENT_NOT_DISABLED,
    TEXT_MISMATCH,
    VALUE_MISMATCH,
    COUNT_MISMATCH,
    ATTRIBUTE_MISMATCH,
    CLASS_MISMATCH,
    CSS_MISMATCH,
    ELEMENT_NOT_SELECTED,
    ELEMENT_NOT_CHECKED,
    ELEMENT_STILL_CHECKED,
    ELEMENT_NOT_ATTACHED,
    ELEMENT_STILL_ATTACHED,
    UNSUPPORTED_ELEMENT_STATE,
    STALE_ELEMENT,
    TIMEOUT,
    UNKNOWN
}

