package io.github.testlens.application.tooling.ai;

import io.github.testlens.application.model.ApplicationModel;
import io.github.testlens.core.redaction.RedactionPolicy;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/** Creates a small dependency-closed and redacted context from explicit stable IDs. @since 0.5.0 */
public final class ContextSlicer {
    public AgentContextPack slice(ApplicationModel model,AgentTask task,Map<String,List<String>>pageObjectApis,
                                  List<String>existingTestConventions,RedactionPolicy redaction,Limits limits){
        Objects.requireNonNull(model,"model");Objects.requireNonNull(task,"task");Objects.requireNonNull(redaction,"redaction");Objects.requireNonNull(limits,"limits");
        pageObjectApis=pageObjectApis==null?Map.of():pageObjectApis;existingTestConventions=existingTestConventions==null?List.of():existingTestConventions;
        Budget budget=new Budget(redaction,limits);
        String safeRequirement=budget.text(task.requirement());
        ContractHeader safeTaskHeader=new ContractHeader(task.header().schemaVersion(),task.header().status(),budget.texts(task.header().evidence()),budget.texts(task.header().limitations()),task.header().confidence());
        AgentTask safeTask=new AgentTask(safeTaskHeader,task.type(),safeRequirement,budget.texts(task.requiredPageIds()),budget.texts(task.requiredStateIds()),budget.texts(task.requiredElementIds()),budget.texts(task.constraints()));
        Map<String,ApplicationModel.PageModel>pages=new LinkedHashMap<>();model.pages().forEach(page->pages.put(page.pageId(),page));
        LinkedHashSet<String>selected=new LinkedHashSet<>();ArrayDeque<QueueEntry>queue=new ArrayDeque<>();
        for(String pageId:task.requiredPageIds())if(pages.containsKey(pageId)){selected.add(pageId);queue.add(new QueueEntry(pageId,0));}
        for(ApplicationModel.PageModel page:model.pages())if(page.elements().stream().anyMatch(element->task.requiredElementIds().contains(element.elementId()))||page.states().stream().anyMatch(state->task.requiredStateIds().contains(state.stateId())))if(selected.add(page.pageId()))queue.add(new QueueEntry(page.pageId(),0));
        List<ApplicationModel.Transition>allTransitions=new ArrayList<>(model.transitions());model.pages().forEach(page->allTransitions.addAll(page.transitions()));
        while(!queue.isEmpty()){
            QueueEntry current=queue.removeFirst();if(current.depth()>=limits.transitionDepth())continue;
            for(ApplicationModel.Transition transition:allTransitions)if(transition.sourcePageId().equals(current.pageId())&&transition.targetPageId()!=null&&pages.containsKey(transition.targetPageId())&&selected.size()<limits.maxPages()&&selected.add(transition.targetPageId()))queue.addLast(new QueueEntry(transition.targetPageId(),current.depth()+1));
        }
        List<AgentContextPack.PageContext>contexts=new ArrayList<>();DecisionCollector decisions=new DecisionCollector(limits.maxScopeDecisions());int elementCount=0,transitionCount=0,stateCount=0,stateElementRefs=0;boolean truncated=false;
        Set<String>knownStates=new HashSet<>(),knownElements=new HashSet<>();model.pages().forEach(page->{page.states().forEach(state->knownStates.add(state.stateId()));page.elements().forEach(element->knownElements.add(element.elementId()));});
        for(String pageId:task.requiredPageIds())if(!pages.containsKey(pageId)){decisions.exclude(decision(budget,pageId,"PAGE","Required stable ID is unknown"));truncated=true;}
        for(String stateId:task.requiredStateIds())if(!knownStates.contains(stateId)){decisions.exclude(decision(budget,stateId,"STATE","Required stable ID is unknown"));truncated=true;}
        for(String elementId:task.requiredElementIds())if(!knownElements.contains(elementId)){decisions.exclude(decision(budget,elementId,"ELEMENT","Required stable ID is unknown"));truncated=true;}
        for(ApplicationModel.PageModel page:model.pages()){
            if(!selected.contains(page.pageId())){decisions.exclude(decision(budget,page.pageId(),"PAGE","Not required by explicit IDs or bounded transition closure"));continue;}
            if(contexts.size()>=limits.maxPages()){decisions.exclude(decision(budget,page.pageId(),"PAGE","maxPages reached"));truncated=true;continue;}
            List<AgentContextPack.StateContext>states=new ArrayList<>();for(var state:page.states()){if(stateCount>=limits.maxStates()){decisions.exclude(decision(budget,state.stateId(),"STATE","maxStates reached"));truncated=true;continue;}List<String>refs=new ArrayList<>();for(String ref:state.elementIds()){if(stateElementRefs>=limits.maxStateElementRefs()){decisions.exclude(decision(budget,state.stateId(),"STATE_ELEMENT_REFERENCE","maxStateElementRefs reached"));truncated=true;break;}refs.add(budget.text(ref));stateElementRefs++;}states.add(new AgentContextPack.StateContext(budget.text(state.stateId()),budget.text(state.semanticName()),refs));stateCount++;}
            List<AgentContextPack.ElementContext>elements=new ArrayList<>();for(var element:page.elements()){if(elementCount>=limits.maxElements()){decisions.exclude(decision(budget,element.elementId(),"ELEMENT","maxElements reached"));truncated=true;continue;}elements.add(new AgentContextPack.ElementContext(budget.text(element.elementId()),budget.text(element.semanticName()),budget.text(element.type().name()),budget.texts(element.actions().stream().map(Enum::name).toList()),budget.text(element.selectorQuality().name())));decisions.include(decision(budget,element.elementId(),"ELEMENT","Member of included page"));elementCount++;}
            List<AgentContextPack.TransitionContext>transitions=new ArrayList<>();Set<String>seenTransitions=new HashSet<>();for(var transition:allTransitions.stream().filter(value->value.sourcePageId().equals(page.pageId())).sorted(java.util.Comparator.comparing(ApplicationModel.Transition::transitionId)).toList()){if(!seenTransitions.add(transition.transitionId()))continue;if(transitionCount>=limits.maxTransitions()){decisions.exclude(decision(budget,transition.transitionId(),"TRANSITION","maxTransitions reached"));truncated=true;continue;}transitions.add(transition(budget,transition));transitionCount++;}
            contexts.add(new AgentContextPack.PageContext(budget.text(page.pageId()),budget.text(page.canonicalName()),budget.url(page.identity().normalizedUrlPattern()),states,elements,transitions));decisions.include(decision(budget,page.pageId(),"PAGE","Explicit requirement or transition dependency"));
        }
        Map<String,List<String>>safeApis=new LinkedHashMap<>();int apiCount=0;for(var entry:pageObjectApis.entrySet().stream().sorted(Map.Entry.comparingByKey()).toList())if(selected.contains(entry.getKey())){List<String>apis=new ArrayList<>();for(String api:(entry.getValue()==null?List.<String>of():entry.getValue()).stream().filter(Objects::nonNull).distinct().sorted().toList()){if(apiCount>=limits.maxPageObjectApis()){decisions.exclude(decision(budget,entry.getKey(),"PAGE_OBJECT_API","maxPageObjectApis reached"));truncated=true;break;}apis.add(budget.text(api));apiCount++;}safeApis.put(budget.text(entry.getKey()),List.copyOf(apis));}else decisions.exclude(decision(budget,entry.getKey(),"PAGE_OBJECT_API","Page excluded from task slice"));
        List<String>conventions=new ArrayList<>();for(String convention:existingTestConventions.stream().filter(Objects::nonNull).distinct().sorted().toList()){if(conventions.size()>=limits.maxConventions()){decisions.exclude(decision(budget,"conventions","CONVENTION","maxConventions reached"));truncated=true;break;}conventions.add(budget.text(convention));}
        if(budget.truncated()){decisions.exclude(new AgentContextPack.ScopeDecision("context","CONTEXT_BUDGET","maxStringCharacters or maxTotalCharacters reached"));truncated=true;}
        decisions.finish();truncated|=decisions.truncated();
        AgentContextPack.Completeness completeness=truncated?AgentContextPack.Completeness.PARTIAL:AgentContextPack.Completeness.COMPLETE_FOR_REQUESTED_SCOPE;
        ContractHeader header=new ContractHeader(ContractHeader.SCHEMA_VERSION,truncated?ContractHeader.Status.PARTIAL:ContractHeader.Status.READY,List.of("Explicit stable-ID selection","Bounded transition dependency closure"),truncated?List.of("Context limits truncated the requested graph"):List.of(),ContractHeader.Confidence.OBSERVED);
        return new AgentContextPack(header,safeTask,contexts,safeApis,conventions,decisions.included(),decisions.excluded(),completeness);
    }
    private static AgentContextPack.TransitionContext transition(Budget budget,ApplicationModel.Transition t){return new AgentContextPack.TransitionContext(budget.text(t.transitionId()),budget.text(t.action().name()),budget.text(t.elementId()),budget.text(t.targetPageId()),budget.text(t.targetStateId()),budget.text(t.confidence().name()));}
    private static AgentContextPack.ScopeDecision decision(Budget budget,String id,String kind,String reason){String safeId=budget.text(id);return safeId==null||safeId.isBlank()?null:new AgentContextPack.ScopeDecision(safeId,kind,reason);}
    private record QueueEntry(String pageId,int depth){}
    public record Limits(int maxPages,int maxElements,int maxTransitions,int transitionDepth,int maxStates,int maxStateElementRefs,int maxPageObjectApis,int maxConventions,int maxStringCharacters,int maxTotalCharacters,int maxScopeDecisions){public Limits(int maxPages,int maxElements,int maxTransitions,int transitionDepth){this(maxPages,maxElements,maxTransitions,transitionDepth,100,1_000,200,50,4_096,256_000,1_000);}public Limits(int maxPages,int maxElements,int maxTransitions,int transitionDepth,int maxStates,int maxStateElementRefs,int maxPageObjectApis,int maxConventions,int maxStringCharacters,int maxTotalCharacters){this(maxPages,maxElements,maxTransitions,transitionDepth,maxStates,maxStateElementRefs,maxPageObjectApis,maxConventions,maxStringCharacters,maxTotalCharacters,1_000);}public Limits{if(maxPages<1||maxPages>500||maxElements<1||maxElements>10_000||maxTransitions<0||maxTransitions>10_000||transitionDepth<0||transitionDepth>10||maxStates<0||maxStates>10_000||maxStateElementRefs<0||maxStateElementRefs>100_000||maxPageObjectApis<0||maxPageObjectApis>10_000||maxConventions<0||maxConventions>10_000||maxStringCharacters<16||maxStringCharacters>1_048_576||maxTotalCharacters<256||maxTotalCharacters>16_777_216||maxScopeDecisions<1||maxScopeDecisions>100_000)throw new IllegalArgumentException("Context limits are outside supported bounds");}public static Limits defaults(){return new Limits(12,200,100,2);}}
    private static final class DecisionCollector{private final int max;private final List<AgentContextPack.ScopeDecision>included=new ArrayList<>(),excluded=new ArrayList<>();private int omitted;private boolean finished;private DecisionCollector(int max){this.max=max;}private void include(AgentContextPack.ScopeDecision value){add(included,value);}private void exclude(AgentContextPack.ScopeDecision value){add(excluded,value);}private void add(List<AgentContextPack.ScopeDecision>target,AgentContextPack.ScopeDecision value){if(value!=null&&size()<max-1)target.add(value);else omitted++;}private int size(){return included.size()+excluded.size();}private void finish(){if(finished)return;finished=true;if(omitted>0)excluded.add(new AgentContextPack.ScopeDecision("scope-decisions","SCOPE_DECISION_LIMIT","maxScopeDecisions reached; "+omitted+" additional decisions omitted"));}private boolean truncated(){return omitted>0;}private List<AgentContextPack.ScopeDecision>included(){return included;}private List<AgentContextPack.ScopeDecision>excluded(){return excluded;}}
    private static final class Budget{private final RedactionPolicy redaction;private final Limits limits;private int characters;private boolean truncated;private Budget(RedactionPolicy redaction,Limits limits){this.redaction=redaction;this.limits=limits;}private String text(String value){return value==null?null:bounded(redaction.redact(value));}private String url(String value){return value==null?null:bounded(redaction.redactUrl(value));}private List<String>texts(List<String>values){return(values==null?List.<String>of():values).stream().filter(Objects::nonNull).map(this::text).toList();}private String bounded(String value){String result=value;if(result.length()>limits.maxStringCharacters()){result=result.substring(0,limits.maxStringCharacters());truncated=true;}int remaining=limits.maxTotalCharacters()-characters;if(remaining<=0){truncated=true;return "";}if(result.length()>remaining){result=result.substring(0,remaining);truncated=true;}characters+=result.length();return result;}private boolean truncated(){return truncated;}}
}
