package io.github.testlens.application.tooling.ai;

import io.github.testlens.application.tooling.ai.security.AgentArtifactSecurityGate;
import io.github.testlens.core.redaction.RedactionPolicy;

import java.util.List;
import java.util.Objects;
import java.util.Map;

/** Deterministic provider-neutral prompt packs for specialized test-engineering roles. @since 0.5.0 */
public final class PromptPackRenderer {
    public String render(Role role,AgentContextPack context,int maxCharacters){
        return render(role,context,maxCharacters,RedactionPolicy.defaults(),List.of());
    }
    public String render(Role role,AgentContextPack context,int maxCharacters,RedactionPolicy redaction,List<String>canaries){
        Objects.requireNonNull(role,"role");Objects.requireNonNull(context,"context");if(maxCharacters<1_000||maxCharacters>1_000_000)throw new IllegalArgumentException("maxCharacters must be in [1000,1000000]");if(maxCharacters<2_048)throw new PromptLimitException("Prompt budget is below the minimum safe contract size");
        StringBuilder out=new StringBuilder("TEST_LENS_AGENT_CONTRACT_V1\n[IMMUTABLE_INSTRUCTIONS]\nrole: ").append(role).append('\n').append(instructions(role)).append("[END_IMMUTABLE_INSTRUCTIONS]\n[CONTEXT_DATA_JSON]\n{");
        property(out,"status",context.header().status().name(),true);property(out,"completeness",context.completeness().name(),true);property(out,"requirement",context.task().requirement(),true);arrayProperty(out,"taskConstraints",context.task().constraints(),true);arrayProperty(out,"existingTestConventions",context.existingTestConventions(),true);
        out.append("\"pages\":[");boolean firstPage=true;for(var page:context.pages().stream().sorted(java.util.Comparator.comparing(AgentContextPack.PageContext::pageId)).toList()){if(!firstPage)out.append(',');firstPage=false;out.append('{');property(out,"pageId",page.pageId(),true);property(out,"canonicalName",page.canonicalName(),true);property(out,"urlPattern",page.urlPattern(),true);out.append("\"states\":[");boolean first=true;for(var state:page.states()){if(!first)out.append(',');first=false;out.append('{');property(out,"stateId",state.stateId(),true);property(out,"semanticName",state.semanticName(),true);arrayProperty(out,"elementIds",state.elementIds(),false);out.append('}');}out.append("],\"elements\":[");first=true;for(var element:page.elements()){if(!first)out.append(',');first=false;out.append('{');property(out,"elementId",element.elementId(),true);property(out,"semanticName",element.semanticName(),true);property(out,"type",element.type(),true);arrayProperty(out,"actions",element.actions(),true);property(out,"selectorQuality",element.selectorQuality(),false);out.append('}');}out.append("],\"transitions\":[");first=true;for(var transition:page.transitions()){if(!first)out.append(',');first=false;out.append('{');property(out,"transitionId",transition.transitionId(),true);property(out,"action",transition.action(),true);property(out,"elementId",transition.elementId(),true);property(out,"targetPageId",transition.targetPageId(),true);property(out,"targetStateId",transition.targetStateId(),true);property(out,"confidence",transition.confidence(),false);out.append('}');}out.append("]}");}out.append("],\"pageObjectApis\":{");boolean firstEntry=true;for(var entry:context.pageObjectApis().entrySet().stream().sorted(Map.Entry.comparingByKey()).toList()){if(!firstEntry)out.append(',');firstEntry=false;out.append(quote(entry.getKey())).append(':');array(out,entry.getValue().stream().sorted().toList());}out.append("},\"source\":{");source(out,context.source());out.append("},\"excluded\":[");boolean first=true;for(var item:context.excluded()){if(!first)out.append(',');first=false;out.append('{');property(out,"kind",item.kind(),true);property(out,"id",item.id(),true);property(out,"reason",item.reason(),false);out.append('}');}out.append("]}\n[END_CONTEXT_DATA_JSON]\n");
        if(out.length()>maxCharacters)throw new PromptLimitException("Prompt pack exceeds maxCharacters; reduce the context slice rather than truncating contracts");String rendered=out.toString();var security=new AgentArtifactSecurityGate().validate(rendered,List.of(),redaction,canaries);if(security.status()!=AgentArtifactSecurityGate.Status.PASS)throw new PromptSecurityException("Prompt blocked by security gate: "+security.findings().stream().map(AgentArtifactSecurityGate.Finding::code).toList());return rendered;
    }
    private static void property(StringBuilder out,String name,String value,boolean comma){out.append(quote(name)).append(':').append(quote(value));if(comma)out.append(',');}
    private static void arrayProperty(StringBuilder out,String name,java.util.List<String>values,boolean comma){out.append(quote(name)).append(':');array(out,values);if(comma)out.append(',');}
    private static void array(StringBuilder out,java.util.List<String>values){out.append('[');boolean first=true;for(String value:values){if(!first)out.append(',');first=false;out.append(quote(value));}out.append(']');}
    private static void source(StringBuilder out,AgentContextPack.SourceContext source){
        out.append("\"classes\":[");boolean first=true;for(var value:source.classes()){if(!first)out.append(',');first=false;out.append('{');property(out,"classId",value.classId(),true);property(out,"pageId",value.pageId(),true);property(out,"qualifiedName",value.qualifiedName(),true);property(out,"logicalPath",value.logicalPath(),true);property(out,"classification",value.classification(),true);arrayProperty(out,"includedBecause",value.includedBecause(),false);out.append('}');}
        out.append("],\"methods\":[");first=true;for(var value:source.methods()){if(!first)out.append(',');first=false;out.append('{');property(out,"methodId",value.methodId(),true);property(out,"ownerClassId",value.ownerClassId(),true);property(out,"signature",value.signature(),true);property(out,"classification",value.classification(),true);arrayProperty(out,"actions",value.actions(),true);arrayProperty(out,"applicationElementIds",value.referencedApplicationElementIds(),true);arrayProperty(out,"includedBecause",value.includedBecause(),false);out.append('}');}
        out.append("],\"declarations\":[");first=true;for(var value:source.declarations()){if(!first)out.append(',');first=false;out.append('{');property(out,"declarationRef",value.declarationRef(),true);property(out,"ownerClassId",value.ownerClassId(),true);property(out,"fieldName",value.fieldName(),true);property(out,"strategy",value.strategy(),true);property(out,"selectorValueFingerprint",value.selectorValueFingerprint(),true);property(out,"applicationElementId",value.applicationElementId(),true);property(out,"correlationState",value.correlationState(),false);out.append('}');}
        out.append("],\"tests\":[");first=true;for(var value:source.tests()){if(!first)out.append(',');first=false;out.append('{');property(out,"testId",value.testId(),true);property(out,"ownerClassId",value.ownerClassId(),true);property(out,"framework",value.framework(),true);arrayProperty(out,"relevantMethodIds",value.relevantMethodIds(),true);arrayProperty(out,"includedBecause",value.includedBecause(),false);out.append('}');}out.append(']');
    }
    private static String quote(String value){if(value==null)return"null";StringBuilder out=new StringBuilder(value.length()+2).append('"');for(char character:value.toCharArray())switch(character){case'"'->out.append("\\\"");case'\\'->out.append("\\\\");case'\b'->out.append("\\b");case'\f'->out.append("\\f");case'\n'->out.append("\\n");case'\r'->out.append("\\r");case'\t'->out.append("\\t");default->{if(character<0x20||character==0x7f)out.append(String.format("\\u%04x",(int)character));else out.append(character);}}return out.append('"').toString();}
    private static String instructions(Role role){return switch(role){
        case TEST_ARCHITECT->"output: TestPlan\nDo not invent pages, states, permissions, or capabilities absent from context. Preserve UNKNOWN.\n";
        case TEST_SCENARIO_DESIGNER->"output: TestPlan.TestScenario[]\nCover justified happy, negative, boundary, and state-transition cases only. Preserve UNKNOWN.\n";
        case TEST_IMPLEMENTER->"output: TestImplementationProposal\nPAGE_OBJECTS_ONLY\nRAW_SELECTORS_FORBIDDEN\nIf an API is missing return PAGE_OBJECT_CAPABILITY_MISSING; do not emit By.*, XPath, CSS, findElement, or invented selectors.\n";
        case TEST_VERIFIER->"output: TestExecutionResult\nUse compile, targeted execution, Test Lens trace, screenshots, assertions, runtime events, and selector diagnostics as separate evidence.\n";
        case TEST_STABILIZER->"output: FailureClassification and optionally RepairProposal\nDo not assume failure means selector instability. No sleeps, global timeout inflation, blind retries, or JavaScript click fallback without evidence. Selector repair must use Selector Intelligence live/same-target evidence. PROPOSE_ONLY.\n";
        case TEST_REVIEWER->"output: CodeReviewResult\nCheck Page Object reuse, raw selectors, sleeps, retries, assertions, Test Lens API use, maintainability, and isolation.\n";
        case UNIT_TEST_AGENT->"output: TestImplementationProposal\nWrite focused tests for the assigned production delta only. Do not modify production sources or expand scope.\n";};}
    public enum Role{TEST_ARCHITECT,TEST_SCENARIO_DESIGNER,TEST_IMPLEMENTER,TEST_VERIFIER,TEST_STABILIZER,TEST_REVIEWER,UNIT_TEST_AGENT}
    public static final class PromptLimitException extends IllegalArgumentException{public PromptLimitException(String message){super(message);}}
    public static final class PromptSecurityException extends IllegalArgumentException{public PromptSecurityException(String message){super(message);}}
}
