package io.github.testlens.core.trace;

/**
 * Neutral event categories used in trace timelines.
 */
public enum TraceEventType {
    SESSION_STARTED,
    SESSION_FINISHED,
    STEP_STARTED,
    STEP_PASSED,
    STEP_FAILED,
    ACTION_STARTED,
    ACTION_PASSED,
    ACTION_FAILED,
    ASSERTION_STARTED,
    ASSERTION_PASSED,
    ASSERTION_FAILED,
    BUSINESS_ASSERTION_STARTED,
    BUSINESS_ASSERTION_PASSED,
    BUSINESS_ASSERTION_FAILED,
    OVERLAY_DETECTED,
    OVERLAY_HANDLED,
    ACTIONABILITY_CHECK,
    LOCATOR_RESOLVE,
    LOCATOR_ACTION,
    RETRY,
    RETRY_SUMMARY,
    FAILURE_BUNDLE,
    NETWORK_EVENT,
    NETWORK_WAIT,
    SCREENSHOT,
    VIDEO,
    ARTIFACT_ATTACHED,
    CUSTOM
}

