package io.github.testlens.browser;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chromium.HasCdp;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.Duration;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** Real-browser acceptance gate for the standalone HTML generated by the public exporter. */
class HtmlReportReadabilityIT {
    private static final Duration WAIT = Duration.ofSeconds(5);
    private static final Path ROOT = Path.of("target", "report-readability").toAbsolutePath().normalize();
    private static HtmlReportFixtureFactory.FixturePaths fixtures;
    private static HttpServer server;
    private static String baseUrl;

    private WebDriver driver;

    @BeforeAll
    static void generatePublicApiFixtures() throws IOException {
        fixtures = HtmlReportFixtureFactory.generate(ROOT.resolve("after-0.3.1"));
        server = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
        server.createContext("/", HtmlReportReadabilityIT::serveFixture);
        server.start();
        baseUrl = "http://127.0.0.1:" + server.getAddress().getPort();
    }

    @AfterAll
    static void stopServer() {
        if (server != null) server.stop(0);
    }

    @AfterEach
    void closeDriver() {
        if (driver != null) {
            driver.quit();
            driver = null;
        }
    }

    @Test
    void failureSummaryHasReadableComputedColorsInLightDarkAndReactiveAuto() throws Exception {
        driver = BrowserTestHarness.createDriver();
        driver.manage().window().setSize(new Dimension(1366, 900));

        assertFailureContrast(fixtures.failLight(), "light");
        capture("after-failure-light.png");
        assertFailureContrast(fixtures.failDark(), "dark");

        if (driver instanceof HasCdp cdp) {
            emulateColorScheme(cdp, "light");
            open(fixtures.failAuto());
            String lightBackground = css("body", "backgroundColor");
            assertFailureContrastOnOpenPage("auto-light");
            emulateColorScheme(cdp, "dark");
            new WebDriverWait(driver, WAIT).until(ignored -> !css("body", "backgroundColor").equals(lightBackground));
            assertFailureContrastOnOpenPage("auto-dark");
            assertNotEquals(lightBackground, css("body", "backgroundColor"));
        }

        capturePublishedBaselineIfAvailable();
    }

    @Test
    void timelineUsesViewportWidthFullRowAttributesStickyHeadersAndSynchronizedScroll() throws Exception {
        driver = BrowserTestHarness.createDriver();
        for (Path themedPass : List.of(fixtures.passLight(), fixtures.passDark(), fixtures.passAuto())) {
            open(themedPass);
            assertTrue(driver.findElements(By.cssSelector(".timeline")).size() > 2);
            assertNoDocumentHorizontalOverflow();
        }
        for (int width : List.of(1366, 1920, 2560)) {
            driver.manage().window().setSize(new Dimension(width, 900));
            open(fixtures.passLight());
            double sectionWidth = number("return document.querySelector('body > section').getBoundingClientRect().width");
            double viewportWidth = number("return document.documentElement.clientWidth");
            assertTrue(sectionWidth / viewportWidth > 0.94, "main report content must use the viewport at " + width);
            assertNoDocumentHorizontalOverflow();
        }

        driver.manage().window().setSize(new Dimension(1920, 900));
        open(fixtures.passLight());
        List<WebElement> timelines = driver.findElements(By.cssSelector(".timeline-wrap"));
        assertTrue(timelines.size() > 2, "grouped report must exercise multiple timelines");
        WebElement firstOverflowing = timelines.stream()
                .filter(table -> scriptNumber("return arguments[0].scrollWidth-arguments[0].clientWidth", table) > 1)
                .findFirst().orElseThrow();
        js("arguments[0].scrollIntoView({block:'center'})", firstOverflowing);
        WebElement proxy = waitForVisible(By.cssSelector(".timeline-scroll-proxy"));
        new WebDriverWait(driver, WAIT).until(ignored -> firstOverflowing.getAttribute("id")
                .equals(proxy.getAttribute("data-active-timeline")));

        js("arguments[0].scrollLeft=240;arguments[0].dispatchEvent(new Event('scroll'))", proxy);
        new WebDriverWait(driver, WAIT).until(ignored -> Math.abs(
                scrollRatio(firstOverflowing) - scrollRatio(proxy)) < 0.002);
        js("arguments[0].scrollLeft=420;arguments[0].dispatchEvent(new Event('scroll'))", firstOverflowing);
        new WebDriverWait(driver, WAIT).until(ignored -> Math.abs(
                scrollRatio(firstOverflowing) - scrollRatio(proxy)) < 0.002);
        double maximumScroll = scriptNumber("return arguments[0].scrollWidth-arguments[0].clientWidth", firstOverflowing);
        js("arguments[0].scrollLeft=arguments[1];arguments[0].dispatchEvent(new Event('scroll'))",
                firstOverflowing, maximumScroll);
        double proxyMaximum = scriptNumber("return arguments[0].scrollWidth-arguments[0].clientWidth", proxy);
        new WebDriverWait(driver, WAIT).until(ignored -> Math.abs(
                scriptNumber("return arguments[0].scrollLeft", proxy) - proxyMaximum) < 2);
        assertTrue(Math.abs(scriptNumber("return arguments[0].scrollLeft", firstOverflowing) - maximumScroll) < 2);

        WebElement toggle = firstOverflowing.findElements(By.cssSelector(".details-toggle")).stream()
                .filter(candidate -> String.valueOf(js("return document.getElementById(arguments[0]).textContent",
                        candidate.getAttribute("aria-controls"))).contains("request.url"))
                .findFirst().orElseThrow();
        toggle.sendKeys(Keys.ENTER);
        assertEquals("true", toggle.getAttribute("aria-expanded"));
        String controlledId = toggle.getAttribute("aria-controls");
        WebElement detailRow = driver.findElement(By.id(controlledId));
        WebElement panel = detailRow.findElement(By.cssSelector(".event-details-panel"));
        WebElement value = detailRow.findElement(By.cssSelector(".kv dd"));
        assertTrue(panel.isDisplayed());
        assertTrue(panel.getRect().getWidth() >= firstOverflowing.getRect().getWidth() * 0.80,
                "attribute panel must use the visible timeline width");
        assertTrue(value.getRect().getWidth() > 300, "attribute value must not collapse into a narrow strip");
        assertTrue(panel.getRect().getX() >= firstOverflowing.getRect().getX() - 2,
                "full-row details must remain visible after horizontal scrolling");
        capture("after-attributes-pass.png");

        WebElement vertical = timelines.stream()
                .filter(table -> scriptNumber("return arguments[0].scrollHeight-arguments[0].clientHeight", table) > 10)
                .findFirst().orElseThrow();
        js("arguments[0].scrollTop=300", vertical);
        WebElement header = vertical.findElement(By.cssSelector("th"));
        double headerTop = scriptNumber("return arguments[0].getBoundingClientRect().top", header);
        double wrapperTop = scriptNumber("return arguments[0].getBoundingClientRect().top", vertical);
        assertTrue(Math.abs(headerTop - wrapperTop) < 3, "timeline header must remain sticky inside its scroll region");

        WebElement another = timelines.stream().filter(table -> !table.equals(firstOverflowing))
                .filter(table -> scriptNumber("return arguments[0].scrollWidth-arguments[0].clientWidth", table) > 1)
                .findFirst().orElseThrow();
        js("arguments[0].scrollIntoView({block:'center'})", another);
        new WebDriverWait(driver, WAIT).until(ignored -> another.getAttribute("id")
                .equals(proxy.getAttribute("data-active-timeline")));
    }

    @Test
    void narrowHighScaleSuiteAnchorsOptionsAndOfflineBundleRemainUsable() throws Exception {
        driver = BrowserTestHarness.createDriver();
        driver.manage().window().setSize(new Dimension(1366, 900));
        for (Path themedSuite : List.of(fixtures.suiteLight(), fixtures.suiteDark(), fixtures.suiteAuto())) {
            open(themedSuite);
            assertTrue(driver.findElements(By.cssSelector(".session-detail")).size() == 3);
            assertNoDocumentHorizontalOverflow();
        }
        driver.manage().window().setSize(new Dimension(480, 800));
        open(fixtures.suiteAuto());
        assertNoDocumentHorizontalOverflow();
        assertTrue(driver.findElements(By.cssSelector(".timeline-wrap")).stream()
                .anyMatch(table -> scriptNumber("return arguments[0].scrollWidth-arguments[0].clientWidth", table) > 1));

        WebElement eventLink = driver.findElements(By.linkText("Open timeline event")).get(0);
        eventLink.click();
        String targetId = driver.getCurrentUrl().substring(driver.getCurrentUrl().indexOf('#') + 1);
        assertTrue((Boolean) js("return document.getElementById(arguments[0]).matches(':target')", targetId),
                "hash navigation must target the suite-scoped event row");

        if (driver instanceof HasCdp cdp) {
            cdp.executeCdpCommand("Emulation.setScriptExecutionDisabled", Map.of("value", true));
            open(fixtures.passLight());
            assertTrue(driver.findElements(By.cssSelector(".event-details-row")).get(0).isDisplayed(),
                    "native details row remains reachable without JavaScript");
            assertTrue(driver.findElements(By.cssSelector(".timeline-scroll-proxy")).isEmpty());
            cdp.executeCdpCommand("Emulation.setScriptExecutionDisabled", Map.of("value", false));

            cdp.executeCdpCommand("Emulation.setDeviceMetricsOverride", Map.of(
                    "width", 683, "height", 450, "deviceScaleFactor", 2, "mobile", false));
            open(fixtures.suiteAuto());
            assertEquals(2.0, number("return window.devicePixelRatio"), 0.01);
            assertNoDocumentHorizontalOverflow();
            cdp.executeCdpCommand("Emulation.clearDeviceMetricsOverride", Map.of());
        }

        driver.get(baseUrl + "/after-0.3.1/pass-light.html");
        assertTrue(driver.findElements(By.cssSelector(".timeline")).size() > 2,
                "the same generated standalone report must render over local HTTP");

        open(ROOT.resolve("after-0.3.1/pass-no-attributes.html"));
        assertTrue(driver.findElements(By.cssSelector(".details-toggle,.event-details-row")).isEmpty());
        open(ROOT.resolve("after-0.3.1/pass-compact.html"));
        assertTrue(driver.findElements(By.cssSelector(".details-toggle,.event-details-row")).isEmpty());

        Path unpacked = ROOT.resolve("bundle-unpacked");
        unpack(fixtures.bundle(), unpacked);
        Path bundleIndex = unpacked.resolve("index.html");
        open(bundleIndex);
        assertTrue(driver.getTitle().length() > 0);
        assertTrue(driver.findElements(By.cssSelector(".details-toggle")).isEmpty(),
                "bundle keeps its includeAttributes=false contract");
        WebElement relativeArtifact = driver.findElements(By.cssSelector("a[href^='artifacts/']")).get(0);
        String relativeHref = String.valueOf(js("return arguments[0].getAttribute('href')", relativeArtifact));
        assertTrue(Files.exists(unpacked.resolve(relativeHref.replace('/', java.io.File.separatorChar))));

        open(fixtures.failLight());
        WebElement failureDetails = driver.findElements(By.cssSelector(".event-details-row")).stream()
                .filter(row -> String.valueOf(js("return arguments[0].textContent", row)).contains("actual"))
                .filter(row -> String.valueOf(js("return arguments[0].textContent", row)).contains("expected"))
                .findFirst().orElseThrow();
        WebElement failureToggle = failureDetails.findElement(By.xpath("preceding-sibling::tr[1]"))
                .findElement(By.cssSelector(".details-toggle"));
        js("arguments[0].click()", failureToggle);
        js("arguments[0].scrollIntoView({block:'center'})", failureDetails);
        capture("after-attributes-fail.png");
    }

    private void assertFailureContrast(Path report, String label) {
        open(report);
        assertFailureContrastOnOpenPage(label);
        assertNoDocumentHorizontalOverflow();
    }

    private void assertFailureContrastOnOpenPage(String label) {
        WebElement box = driver.findElement(By.cssSelector(".failure-box"));
        js("arguments[0].scrollIntoView({block:'center'})", box);
        WebElement summary = box.findElement(By.cssSelector("summary"));
        assertTrue(contrast(box, box) >= 4.5, label + " failure text contrast");
        assertTrue(contrast(summary, box) >= 4.5, label + " failure summary contrast");
        List<WebElement> muted = box.findElements(By.cssSelector(".muted"));
        if (!muted.isEmpty()) {
            assertTrue(contrast(muted.get(0), box) >= 4.5, label + " failure helper contrast");
        }
        summary.click();
        WebElement stackTrace = box.findElement(By.cssSelector("pre"));
        assertTrue(contrast(stackTrace, stackTrace) >= 4.5, label + " stack trace contrast");
        WebElement failureCard = box.findElement(By.xpath("ancestor::article[1]"));
        WebElement link = failureCard.findElement(By.cssSelector("a"));
        assertTrue(contrast(link, failureCard) >= 4.5, label + " failure link contrast");
        assertFalse(css(".failure-box", "color").equals(css(".failure-box", "backgroundColor")));
    }

    private double contrast(WebElement textElement, WebElement backgroundElement) {
        return scriptNumber("""
                const parse = value => {
                  const parts=value.match(/[\\d.]+/g).map(Number);
                  return [parts[0],parts[1],parts[2],parts.length>3?parts[3]:1];
                };
                const lum = rgb => {
                  const values = rgb.map(value => { const x=value/255; return x<=.04045?x/12.92:Math.pow((x+.055)/1.055,2.4); });
                  return .2126*values[0]+.7152*values[1]+.0722*values[2];
                };
                const effectiveBackground = element => {
                  let result=[0,0,0,0];
                  for(let current=element;current;current=current.parentElement){
                    const behind=parse(getComputedStyle(current).backgroundColor);
                    const alpha=result[3]+behind[3]*(1-result[3]);
                    if(alpha>0) result=[0,1,2].map(i=>(result[i]*result[3]+behind[i]*behind[3]*(1-result[3]))/alpha).concat(alpha);
                    if(result[3]>=.999) break;
                  }
                  return result;
                };
                const foreground=lum(parse(getComputedStyle(arguments[0]).color).slice(0,3));
                const background=lum(effectiveBackground(arguments[1]).slice(0,3));
                return (Math.max(foreground,background)+.05)/(Math.min(foreground,background)+.05);
                """, textElement, backgroundElement);
    }

    private void capturePublishedBaselineIfAvailable() throws Exception {
        Path baseline = ROOT.resolve("before-0.3.0/fail-light.html");
        if (!Files.exists(baseline)) return;
        open(baseline);
        WebElement failure = driver.findElement(By.cssSelector(".failure-box"));
        js("arguments[0].scrollIntoView({block:'center'})", failure);
        capture("before-failure-light-0.3.0.png");
        Path baselinePass = ROOT.resolve("before-0.3.0/pass-light.html");
        open(baselinePass);
        WebElement details = driver.findElements(By.cssSelector(".timeline details")).get(0);
        js("arguments[0].open=true;arguments[0].scrollIntoView({block:'center'})", details);
        capture("before-attributes-pass-0.3.0.png");
    }

    private void emulateColorScheme(HasCdp cdp, String scheme) {
        cdp.executeCdpCommand("Emulation.setEmulatedMedia", Map.of("features",
                List.of(Map.of("name", "prefers-color-scheme", "value", scheme))));
    }

    private void assertNoDocumentHorizontalOverflow() {
        assertTrue(number("return document.documentElement.scrollWidth")
                        <= number("return document.documentElement.clientWidth") + 1,
                "horizontal overflow must stay inside designated regions");
    }

    private void capture(String name) throws IOException {
        Path screenshots = ROOT.resolve("screenshots");
        Files.createDirectories(screenshots);
        Files.write(screenshots.resolve(name), ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES));
    }

    private void open(Path path) {
        driver.get(path.toUri().toString());
    }

    private WebElement waitForVisible(By locator) {
        return new WebDriverWait(driver, WAIT).until(ignored -> {
            WebElement element = driver.findElement(locator);
            return element.isDisplayed() ? element : null;
        });
    }

    private String css(String selector, String property) {
        return driver.findElement(By.cssSelector(selector)).getCssValue(property);
    }

    private double number(String source) {
        return ((Number) js(source)).doubleValue();
    }

    private double scriptNumber(String source, Object... arguments) {
        return ((Number) js(source, arguments)).doubleValue();
    }

    private double scrollRatio(WebElement element) {
        return scriptNumber("const m=arguments[0].scrollWidth-arguments[0].clientWidth;"
                + "return m<=0?0:arguments[0].scrollLeft/m", element);
    }

    private Object js(String source, Object... arguments) {
        return ((JavascriptExecutor) driver).executeScript(source, arguments);
    }

    private static void unpack(Path zip, Path target) throws IOException {
        if (Files.exists(target)) {
            try (var paths = Files.walk(target)) {
                paths.sorted(Comparator.reverseOrder()).filter(path -> !path.equals(target)).forEach(path -> {
                    try {
                        Files.delete(path);
                    } catch (IOException e) {
                        throw new IllegalStateException(e);
                    }
                });
            }
        }
        Files.createDirectories(target);
        try (ZipInputStream input = new ZipInputStream(Files.newInputStream(zip))) {
            ZipEntry entry;
            while ((entry = input.getNextEntry()) != null) {
                Path output = target.resolve(entry.getName()).normalize();
                if (!output.startsWith(target)) throw new IOException("Unsafe ZIP entry: " + entry.getName());
                if (entry.isDirectory()) {
                    Files.createDirectories(output);
                } else {
                    Files.createDirectories(output.getParent());
                    Files.copy(input, output, StandardCopyOption.REPLACE_EXISTING);
                }
            }
        }
    }

    private static void serveFixture(HttpExchange exchange) throws IOException {
        String relative = exchange.getRequestURI().getPath().replaceFirst("^/+", "");
        Path file = ROOT.resolve(relative).normalize();
        if (!file.startsWith(ROOT) || !Files.isRegularFile(file)) {
            exchange.sendResponseHeaders(404, -1);
            exchange.close();
            return;
        }
        byte[] body = Files.readAllBytes(file);
        exchange.getResponseHeaders().set("Content-Type", file.toString().endsWith(".html")
                ? "text/html; charset=utf-8" : "application/octet-stream");
        exchange.sendResponseHeaders(200, body.length);
        try (var output = exchange.getResponseBody()) {
            output.write(body);
        }
    }
}
