package io.github.testlens.browser;

import com.sun.net.httpserver.HttpServer;
import io.github.testlens.TestLens;
import io.github.testlens.application.tooling.ai.AgentContextPack;
import io.github.testlens.application.tooling.ai.AgentTask;
import io.github.testlens.application.tooling.ai.ContractHeader;
import io.github.testlens.application.tooling.ai.FailureClassification;
import io.github.testlens.application.tooling.ai.workflow.AgentExecutor;
import io.github.testlens.application.tooling.ai.workflow.AgentWorkflowCoordinator;
import io.github.testlens.application.tooling.ai.workflow.CompiledTargetedTestExecutor;
import io.github.testlens.application.tooling.ai.workflow.GeneratedTestPolicyValidator;
import io.github.testlens.application.tooling.ai.workflow.TargetedJavaCompiler;
import io.github.testlens.application.tooling.ai.workflow.TargetedTestExecutor;
import io.github.testlens.application.tooling.ai.workflow.TestEngineeringRequest;
import io.github.testlens.application.tooling.ai.workflow.TestEngineeringRun;
import io.github.testlens.application.tooling.ai.workflow.TestEngineeringWorkflow;
import io.github.testlens.application.tooling.ai.workflow.WorkflowPolicy;
import io.github.testlens.application.tooling.ai.workflow.runner.CodexCliDetector;
import io.github.testlens.application.tooling.ai.workflow.runner.CodexCliProfiles;
import io.github.testlens.application.tooling.ai.workflow.runner.ExternalAgentRunner;
import io.github.testlens.application.tooling.ai.workflow.runner.RoleDispatchingAgentExecutor;
import io.github.testlens.core.trace.UiTestLensSession;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.openqa.selenium.WebDriver;

import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/** Opt-in real-agent proof: generated bytecode drives an existing Page Object through an observed browser. */
class RealCodexExistingPageObjectWorkflowIT {
    @TempDir Path temporaryDirectory;

    @Test void realCodexGeneratedTestExecutesExistingPageObjectAndProducesWorkflowReport() throws Exception {
        Assumptions.assumeTrue(Boolean.getBoolean("testlens.codex.dogfood"),
                "Set -Dtestlens.codex.dogfood=true for authenticated local Codex dogfood");
        Path executable = CodexCliDetector.detect().orElseThrow(() ->
                new AssertionError("Opt-in dogfood requested but native Codex executable was not detected"));

        EnumMap<AgentExecutor.Role, AgentExecutor> roles = new EnumMap<>(AgentExecutor.Role.class);
        for (AgentExecutor.Role role : List.of(AgentExecutor.Role.TEST_ARCHITECT,
                AgentExecutor.Role.TEST_IMPLEMENTER, AgentExecutor.Role.CODE_REVIEWER)) {
            roles.put(role, new ExternalAgentRunner(CodexCliProfiles.readOnly(executable,
                    "codex-browser-" + role.name().toLowerCase(), role, Duration.ofMinutes(3),
                    CodexCliProfiles.defaultEnvironmentAllowlist()),
                    temporaryDirectory.resolve("agents-" + role.name())));
        }

        try (LoginFixture fixture = LoginFixture.start()) {
            WebDriver driver = BrowserTestHarness.createDriver();
            try {
                driver.get(fixture.url());
                String binaryName = "io.github.testlens.browser.GeneratedRealCodexInvalidPasswordTest";
                CompiledTargetedTestExecutor execution = (request, output) -> {
                    TestLens lens = TestLens.attach(driver);
                    UiTestLensSession session = lens.startSession("real Codex generated invalid-password test");
                    Class<?> generated = output.loadClass(request.testClass(), getClass().getClassLoader());
                    boolean visible = (boolean) generated.getMethod("execute",
                                    ExistingProjectCorrelationBrowserIT.RuntimeLoginPage.class,
                                    ExistingProjectCorrelationBrowserIT.TestCredentials.class)
                            .invoke(null, new ExistingProjectCorrelationBrowserIT.RuntimeLoginPage(lens.observeDriver()),
                                    new ExistingProjectCorrelationBrowserIT.TestCredentials("fixture-user", "invalid-password"));
                    if (visible) lens.finishPassed();
                    else lens.finishFailed(new AssertionError("login error was not visible"));
                    assertTrue(session.events().size() >= 3, "generated bytecode must leave Lens trace evidence");
                    return new TargetedTestExecutor.ExecutionResult(visible, 1,
                            List.of("generated bytecode invoked", "trace events=" + session.events().size()));
                };
                AgentWorkflowCoordinator coordinator = new AgentWorkflowCoordinator(
                        new TestEngineeringWorkflow(WorkflowPolicy.defaults()),
                        new RoleDispatchingAgentExecutor(roles), new TargetedJavaCompiler(), execution,
                        new GeneratedTestPolicyValidator(GeneratedTestPolicyValidator.Policy.defaults()),
                        result -> new FailureClassification(header(), FailureClassification.Category.UNKNOWN,
                                "No failure", List.of(), List.of(), List.of()),
                        AgentWorkflowCoordinator.Stabilizer.none(),
                        new AgentWorkflowCoordinator.Configuration(
                                Path.of("src/test/java/io/github/testlens/browser/GeneratedRealCodexInvalidPasswordTest.java"),
                                binaryName, null, 17, System.getProperty("java.class.path"), 20,
                                Duration.ofSeconds(20), List.of("invalid-password"), 2));

                AgentContextPack context = context(binaryName);
                AgentWorkflowCoordinator.Result result = coordinator.run("real-codex-browser", request(), context);
                assertEquals(TestEngineeringRun.State.SUCCESS, result.run().state());
                long contextBytes = io.github.testlens.application.tooling.json.StrictJson.write(context).length;
                byte[] report = result.toWorkflowReport(contextBytes,
                        List.of("opt-in local Codex/browser certification")).json();
                Path reportPath = temporaryDirectory.resolve("workflow-report.json");
                Files.write(reportPath, report);
                assertTrue(Files.size(reportPath) > 0);
            } finally {
                driver.quit();
            }
        }
    }

    private static AgentContextPack context(String binaryName) {
        String signature = "public static boolean execute(ExistingProjectCorrelationBrowserIT.RuntimeLoginPage page, "
                + "ExistingProjectCorrelationBrowserIT.TestCredentials credentials)";
        AgentTask task = new AgentTask(header(), AgentTask.TaskType.CREATE_TEST,
                "Add a test that invalid password shows the login error", List.of("LOGIN"),
                List.of("LOGIN_ERROR"), List.of("LOGIN_SUBMIT"), List.of(
                "Return a complete Java source file in sourcePatch",
                "Use package io.github.testlens.browser and public final class " + binaryName.substring(binaryName.lastIndexOf('.') + 1),
                "Expose exactly: " + signature,
                "The method must call page.loginAs(credentials.username(), credentials.password()) and return page.loginErrorVisible()",
                "Use only the supplied Page Object API; no By, WebDriver, findElement, sleep, retry, or JavascriptExecutor"));
        return new AgentContextPack(header(), task, List.of(), Map.of("RuntimeLoginPage", List.of(
                "void loginAs(String username, String password)", "boolean loginErrorVisible()")),
                List.of("JUnit 5 browser fixture; generated source is invoked through its static execute method"),
                List.of(new AgentContextPack.ScopeDecision("LOGIN", "PAGE", "REQUIRED_PAGE")), List.of(),
                AgentContextPack.Completeness.COMPLETE_FOR_REQUESTED_SCOPE);
    }

    private static TestEngineeringRequest request() {
        return new TestEngineeringRequest(new TestEngineeringRequest.Requirement(
                "Add a test that invalid password shows the login error", List.of("login error is visible")),
                new TestEngineeringRequest.Scope(List.of("RuntimeLoginPage"), List.of()),
                new TestEngineeringRequest.Framework("JUnit", "5", "junit-jupiter"),
                new TestEngineeringRequest.Target("browser-tests", "GeneratedRealCodexInvalidPasswordTest",
                        "invalid-password"), List.of("src/test/java"),
                TestEngineeringRequest.ExecutionPolicy.TARGETED_AFTER_COMPILE);
    }

    private static ContractHeader header() {
        return new ContractHeader(ContractHeader.SCHEMA_VERSION, ContractHeader.Status.READY,
                List.of("bounded existing Page Object context"), List.of(), ContractHeader.Confidence.OBSERVED);
    }

    private static final class LoginFixture implements AutoCloseable {
        private final HttpServer server;
        private LoginFixture(HttpServer server) { this.server = server; }
        static LoginFixture start() throws Exception {
            HttpServer server = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
            byte[] html = ("<!doctype html><input id='username'><input id='password' type='password'>"
                    + "<button data-testid='login-submit'>Log in</button><p id='login-error' hidden>Invalid</p>"
                    + "<script>document.querySelector('[data-testid=login-submit]').onclick=() => "
                    + "document.getElementById('login-error').hidden=false;</script>").getBytes(StandardCharsets.UTF_8);
            server.createContext("/login", exchange -> {
                exchange.sendResponseHeaders(200, html.length);
                try (var body = exchange.getResponseBody()) { body.write(html); }
            });
            server.start();
            return new LoginFixture(server);
        }
        String url() { return "http://127.0.0.1:" + server.getAddress().getPort() + "/login"; }
        @Override public void close() { server.stop(0); }
    }
}
