package io.github.testlens.selector.engine;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/** Side-effect-free preview over an explicitly supplied static/history catalog. */
public final class FederatedPatternPreview {
    public Result preview(PatternProposal.Result proposal,List<SimilaritySubject> catalog,CompiledPolicySet policies,Map<String,ObservationEvidence> evidence,boolean incompleteHistory){
        if(proposal==null||!proposal.useful())return new Result(proposal,List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),incompleteHistory,List.of(),0);
        List<Entry> matchedStatic=new ArrayList<>(),matchedHistory=new ArrayList<>(),excluded=new ArrayList<>(),unsupported=new ArrayList<>();List<StabilityAssessment>policyConflicts=new ArrayList<>(),evidenceConflicts=new ArrayList<>();
        for(SimilaritySubject s:catalog){StructuralFamily.Match shape=s.structuralFamily()==null?null:s.structuralFamily().matchDigestOnly(proposal.pattern());boolean direct=proposal.pattern().matches(s.subject());boolean match=direct||shape==StructuralFamily.Match.MATCH;Entry entry=new Entry(s.subjectRef(),s.subject().declarationRef(),match?"MATCHED":shape==StructuralFamily.Match.UNSUPPORTED_FROM_DIGEST_ONLY?"UNSUPPORTED_FROM_DIGEST_ONLY":"PATTERN_MISMATCH");if(match){if(s.subject().kind()==SelectorSubject.SubjectKind.STATIC_DECLARATION)matchedStatic.add(entry);else matchedHistory.add(entry);StabilityAssessment a=new SelectorStabilityEngine().analyzeIndexed(s.subject(),s.appearanceSignals(),s.exactDigest(),s.structuralFamily(),evidence.getOrDefault(s.subjectRef(),ObservationEvidence.unavailable()),policies);if(a.effectiveDisposition()==StabilityAssessment.EffectiveDisposition.POLICY_POLICY_CONFLICT)policyConflicts.add(a);if(a.effectiveDisposition()==StabilityAssessment.EffectiveDisposition.POLICY_EVIDENCE_CONFLICT)evidenceConflicts.add(a);}else if(shape==StructuralFamily.Match.UNSUPPORTED_FROM_DIGEST_ONLY)unsupported.add(entry);else excluded.add(entry);}
        java.util.Comparator<Entry> order=java.util.Comparator.comparing(Entry::subjectRef);matchedStatic.sort(order);matchedHistory.sort(order);excluded.sort(order);unsupported.sort(order);List<String>refs=java.util.stream.Stream.concat(matchedStatic.stream(),matchedHistory.stream()).map(Entry::declarationRef).filter(java.util.Objects::nonNull).distinct().sorted().toList();int usages=catalog.stream().filter(s->matchedStatic.stream().anyMatch(e->e.subjectRef().equals(s.subjectRef()))||matchedHistory.stream().anyMatch(e->e.subjectRef().equals(s.subjectRef()))).mapToInt(s->s.usages().size()).sum();return new Result(proposal,matchedStatic,matchedHistory,excluded,unsupported,policyConflicts,evidenceConflicts,List.of(),incompleteHistory,refs,usages);
    }
    public record Entry(String subjectRef,String declarationRef,String reasonCode){}
    public record Result(PatternProposal.Result proposal,List<Entry> matchedStaticSubjects,List<Entry> matchedHistorySubjects,List<Entry> excludedNearMatches,List<Entry> unsupportedDigestOnlySubjects,List<StabilityAssessment> policyConflicts,List<StabilityAssessment> evidenceConflicts,List<String> limitations,boolean incompleteHistory,List<String> affectedDeclarationRefs,int usageCount){public Result{matchedStaticSubjects=List.copyOf(matchedStaticSubjects);matchedHistorySubjects=List.copyOf(matchedHistorySubjects);excludedNearMatches=List.copyOf(excludedNearMatches);unsupportedDigestOnlySubjects=List.copyOf(unsupportedDigestOnlySubjects);policyConflicts=List.copyOf(policyConflicts);evidenceConflicts=List.copyOf(evidenceConflicts);limitations=List.copyOf(limitations);affectedDeclarationRefs=List.copyOf(affectedDeclarationRefs);}}
}
