package io.github.testlens.selector.engine;

import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

/** Immutable indexed Find Similar catalog. */
public final class SimilarityIndex {
    public static final int MAX_SUBJECTS=100_000;
    private final List<SimilaritySubject> all;private final boolean complete;private final List<String>catalogLimitations;private final Map<String,List<SimilaritySubject>> declarations,exact,templates,patterns,families,prefixes,appearances,paths,modules;
    public SimilarityIndex(List<SimilaritySubject> subjects){this(subjects,true,List.of());}
    public SimilarityIndex(List<SimilaritySubject> subjects,boolean complete,List<String>limitations){if(subjects.size()>MAX_SUBJECTS)throw new IllegalArgumentException("Similarity catalog exceeds "+MAX_SUBJECTS);this.complete=complete;catalogLimitations=List.copyOf(limitations);all=subjects.stream().sorted(Comparator.comparing(SimilaritySubject::subjectRef)).toList();declarations=index(SimilaritySubject::subject,s->s.declarationRef());exact=index(s->s.exactDigest()==null?null:s.subject().strategy()+'\0'+s.exactDigest());templates=index(SimilaritySubject::templateFingerprint);patterns=multiIndex(SimilaritySubject::explicitPatternRefs);families=index(s->s.structuralFamily()==null?null:s.structuralFamily().fingerprint());prefixes=index(s->s.structuralFamily()==null?null:s.structuralFamily().prefixFingerprint());paths=index(s->s.subject().logicalPath());modules=index(s->s.subject().modulePath());appearances=new HashMap<>();for(SimilaritySubject s:all)for(AppearanceSignal signal:s.appearanceSignals())appearances.computeIfAbsent(s.subject().strategy()+'\0'+signal.family(),ignored->new ArrayList<>()).add(s);freeze(appearances);}
    public SimilarityResult find(SimilaritySubject source,SimilarityResult.QueryScope scope,CompiledPolicySet policies,Map<String,ObservationEvidence> evidence){
        LinkedHashMap<String,SimilaritySubject> candidates=new LinkedHashMap<>();add(candidates,lookup(declarations,source.subject().declarationRef()));add(candidates,lookup(exact,source.exactDigest()==null?null:source.subject().strategy()+'\0'+source.exactDigest()));add(candidates,lookup(templates,source.templateFingerprint()));for(String pattern:source.explicitPatternRefs())add(candidates,lookup(patterns,pattern));if(source.structuralFamily()!=null){add(candidates,lookup(families,source.structuralFamily().fingerprint()));add(candidates,lookup(prefixes,source.structuralFamily().prefixFingerprint()));}for(AppearanceSignal a:source.appearanceSignals())add(candidates,lookup(appearances,source.subject().strategy()+'\0'+a.family()));candidates.remove(source.subjectRef());
        List<SimilarityResult.RelatedSubject> out=candidates.values().stream().filter(s->inScope(source,s,scope)).map(s->related(source,s,policies,evidence.get(s.subjectRef()))).filter(r->r.relationClass()!=SimilarityResult.RelationClass.INSUFFICIENT_RELATION).sorted(order()).toList();
        return new SimilarityResult(SimilarityResult.SCHEMA_VERSION,SimilarityResult.ALGORITHM_VERSION,source.subjectRef(),scope,new SimilarityResult.Completeness(complete,all.size(),candidates.size(),catalogLimitations),out);
    }
    private SimilarityResult.RelatedSubject related(SimilaritySubject a,SimilaritySubject b,CompiledPolicySet policies,ObservationEvidence evidence){List<SimilarityResult.Signal>s=new ArrayList<>();same(s,a.subject().declarationRef(),b.subject().declarationRef(),SimilarityResult.Signal.SAME_DECLARATION_REF);if(eq(a.exactDigest(),b.exactDigest())&&a.subject().strategy().equals(b.subject().strategy()))s.add(SimilarityResult.Signal.SAME_EXACT_DIGEST);same(s,a.templateFingerprint(),b.templateFingerprint(),SimilarityResult.Signal.SAME_TEMPLATE_FINGERPRINT);if(a.explicitPatternRefs().stream().anyMatch(b.explicitPatternRefs()::contains))s.add(SimilarityResult.Signal.MATCHES_SAME_EXPLICIT_PATTERN);if(a.structuralFamily()!=null&&b.structuralFamily()!=null){same(s,a.structuralFamily().fingerprint(),b.structuralFamily().fingerprint(),SimilarityResult.Signal.SAME_STRUCTURAL_FAMILY);same(s,a.structuralFamily().prefixFingerprint(),b.structuralFamily().prefixFingerprint(),SimilarityResult.Signal.SAME_PREFIX_FAMILY);}if(a.appearanceSignals().stream().map(AppearanceSignal::family).anyMatch(f->b.appearanceSignals().stream().anyMatch(x->x.family()==f)))s.add(SimilarityResult.Signal.SAME_APPEARANCE_FAMILY);same(s,a.subject().strategy(),b.subject().strategy(),SimilarityResult.Signal.SAME_STRATEGY);same(s,a.component().componentRef(),b.component().componentRef(),SimilarityResult.Signal.SAME_COMPONENT_REF);same(s,a.component().componentRole(),b.component().componentRole(),SimilarityResult.Signal.SAME_COMPONENT_ROLE);same(s,a.subject().contextFingerprint(),b.subject().contextFingerprint(),SimilarityResult.Signal.SAME_CONTEXT_FINGERPRINT);same(s,a.subject().declaringSymbol(),b.subject().declaringSymbol(),SimilarityResult.Signal.SAME_DECLARING_SYMBOL);same(s,a.subject().logicalPath(),b.subject().logicalPath(),SimilarityResult.Signal.SAME_LOGICAL_PATH);same(s,a.subject().modulePath(),b.subject().modulePath(),SimilarityResult.Signal.SAME_MODULE);same(s,a.usageSourceFamily(),b.usageSourceFamily(),SimilarityResult.Signal.SAME_USAGE_SOURCE_FAMILY);if(a.candidateOrigins().stream().anyMatch(b.candidateOrigins()::contains))s.add(SimilarityResult.Signal.SAME_CANDIDATE_ORIGIN);same(s,a.semanticAttributeFamily(),b.semanticAttributeFamily(),SimilarityResult.Signal.SAME_SEMANTIC_ATTRIBUTE_FAMILY);
        SimilarityResult.RelationClass relation=relation(s);ObservationEvidence ev=evidence==null?ObservationEvidence.unavailable():evidence;StabilityAssessment assessment=new SelectorStabilityEngine().analyzeIndexed(b.subject(),b.appearanceSignals(),b.exactDigest(),b.structuralFamily(),ev,policies);List<AppearanceSignal.Family> fs=b.appearanceSignals().stream().map(AppearanceSignal::family).distinct().sorted().toList();return new SimilarityResult.RelatedSubject(b.subjectRef(),relation,s,b.correlation().confidence(),b.correlation().supportingSignals(),b.correlation().conflictingSignals(),b.subject().declarationRef(),b.subject().logicalPath(),b.usages().stream().limit(8).toList(),b.usages().size(),fs,assessment,limitations(b),explain(relation,s));}
    private static SimilarityResult.RelationClass relation(List<SimilarityResult.Signal>s){if(s.contains(SimilarityResult.Signal.SAME_DECLARATION_REF))return SimilarityResult.RelationClass.SAME_DECLARATION;if(s.contains(SimilarityResult.Signal.SAME_EXACT_DIGEST))return SimilarityResult.RelationClass.EXACT_LOCATOR;if(s.contains(SimilarityResult.Signal.SAME_TEMPLATE_FINGERPRINT))return SimilarityResult.RelationClass.SAME_TEMPLATE;if(s.contains(SimilarityResult.Signal.MATCHES_SAME_EXPLICIT_PATTERN))return SimilarityResult.RelationClass.EXPLICIT_PATTERN_RELATED;if(s.contains(SimilarityResult.Signal.SAME_STRUCTURAL_FAMILY)||s.contains(SimilarityResult.Signal.SAME_PREFIX_FAMILY))return SimilarityResult.RelationClass.SAME_STRUCTURAL_FAMILY;if(s.contains(SimilarityResult.Signal.SAME_APPEARANCE_FAMILY)&&s.contains(SimilarityResult.Signal.SAME_STRATEGY))return SimilarityResult.RelationClass.APPEARANCE_RELATED;return SimilarityResult.RelationClass.INSUFFICIENT_RELATION;}
    private static Comparator<SimilarityResult.RelatedSubject> order(){return Comparator.comparingInt((SimilarityResult.RelatedSubject r)->r.relationClass().ordinal()).thenComparingInt(SimilarityIndex::structuralStrength).thenComparingInt(r->r.correlationConfidence().ordinal()).thenComparing(r->n(r.logicalPath())).thenComparing(r->n(r.declarationRef())).thenComparing(SimilarityResult.RelatedSubject::subjectRef);}
    private static int structuralStrength(SimilarityResult.RelatedSubject r){if(r.relationClass()!=SimilarityResult.RelationClass.SAME_STRUCTURAL_FAMILY)return 0;if(r.signals().contains(SimilarityResult.Signal.SAME_STRUCTURAL_FAMILY)){boolean supporting=r.signals().stream().anyMatch(s->s==SimilarityResult.Signal.SAME_CONTEXT_FINGERPRINT||s==SimilarityResult.Signal.SAME_DECLARING_SYMBOL||s==SimilarityResult.Signal.SAME_LOGICAL_PATH||s==SimilarityResult.Signal.SAME_MODULE);return supporting?0:1;}return 2;}
    private static String explain(SimilarityResult.RelationClass r,List<SimilarityResult.Signal>s){return r+" through "+s.stream().map(Enum::name).sorted().collect(Collectors.joining(", "));}
    private static List<String> limitations(SimilaritySubject s){List<String>x=new ArrayList<>();if(s.sourceState()!=SimilaritySubject.SourceState.CURRENT)x.add(s.sourceState().name());if(s.subject().inputTrust()==SelectorSubject.InputTrust.RUNTIME_REDACTED)x.add("RUNTIME_VALUE_REDACTED");return List.copyOf(x);}
    private boolean inScope(SimilaritySubject a,SimilaritySubject b,SimilarityResult.QueryScope scope){return switch(scope){case SAME_DECLARATION->eq(a.subject().declarationRef(),b.subject().declarationRef());case SAME_FILE->eq(a.subject().logicalPath(),b.subject().logicalPath());case SAME_MODULE->eq(a.subject().modulePath(),b.subject().modulePath());case PROJECT,SUPPLIED_HISTORY->true;};}
    private Map<String,List<SimilaritySubject>> index(Function<SimilaritySubject,String> key){Map<String,List<SimilaritySubject>>m=new HashMap<>();for(SimilaritySubject s:all){String k=key.apply(s);if(k!=null)m.computeIfAbsent(k,ignored->new ArrayList<>()).add(s);}freeze(m);return Map.copyOf(m);}
    private Map<String,List<SimilaritySubject>> multiIndex(Function<SimilaritySubject,List<String>> keys){Map<String,List<SimilaritySubject>>m=new HashMap<>();for(SimilaritySubject s:all)for(String key:keys.apply(s))m.computeIfAbsent(key,ignored->new ArrayList<>()).add(s);freeze(m);return Map.copyOf(m);}
    private Map<String,List<SimilaritySubject>> index(Function<SimilaritySubject,SelectorSubject> f,Function<SelectorSubject,String> key){return index(s->key.apply(f.apply(s)));}
    private static void freeze(Map<String,List<SimilaritySubject>>m){m.replaceAll((k,v)->v.stream().sorted(Comparator.comparing(SimilaritySubject::subjectRef)).toList());}
    private static void add(Map<String,SimilaritySubject>m,List<SimilaritySubject>v){if(v!=null)for(SimilaritySubject s:v)m.putIfAbsent(s.subjectRef(),s);}
    private static List<SimilaritySubject> lookup(Map<String,List<SimilaritySubject>> map,String key){return key==null?null:map.get(key);}
    private static void same(List<SimilarityResult.Signal>s,String a,String b,SimilarityResult.Signal signal){if(eq(a,b))s.add(signal);}private static boolean eq(String a,String b){return a!=null&&a.equals(b);}private static String n(String v){return v==null?"":v;}
}
