package io.github.testlens.selector.tooling;

import io.github.testlens.selector.engine.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;
import java.util.Map;

import static io.github.testlens.selector.engine.CandidateAnalysis.Candidate;
import static io.github.testlens.selector.engine.CandidateAnalysis.Completeness;
import static io.github.testlens.selector.engine.CandidateAnalysis.Complexity;
import static io.github.testlens.selector.engine.CandidateAnalysis.Locator;
import static io.github.testlens.selector.engine.CandidateAnalysis.Origin;
import static io.github.testlens.selector.engine.CandidateAnalysis.Recommendation;
import static io.github.testlens.selector.engine.CandidateAnalysis.ScopeFragility;
import static io.github.testlens.selector.engine.CandidateAnalysis.SemanticPreference;
import static io.github.testlens.selector.engine.CandidateAnalysis.TargetComparison;
import static io.github.testlens.selector.engine.CandidateAnalysis.UsageIntent;
import static io.github.testlens.selector.engine.CandidateAnalysis.Validation;
import static io.github.testlens.selector.engine.CandidateAnalysis.ValidationState;
import static io.github.testlens.selector.tooling.SelectorAuditModel.AnalysisMode;
import static io.github.testlens.selector.tooling.SelectorAuditModel.AuditFinding;
import static io.github.testlens.selector.tooling.SelectorAuditModel.AuditReport;
import static io.github.testlens.selector.tooling.SelectorAuditModel.CandidateDetail;
import static io.github.testlens.selector.tooling.SelectorAuditModel.CompletenessStatus;
import static io.github.testlens.selector.tooling.SelectorAuditModel.DeclarationAudit;
import static io.github.testlens.selector.tooling.SelectorAuditModel.DimensionStatus;
import static io.github.testlens.selector.tooling.SelectorAuditModel.FindingCode;
import static io.github.testlens.selector.tooling.SelectorAuditModel.FindingState;
import static io.github.testlens.selector.tooling.SelectorAuditModel.ProjectIssueCode;
import static io.github.testlens.selector.tooling.SelectorAuditModel.Severity;
import static io.github.testlens.selector.tooling.SelectorAuditModel.SourceFreshness;
import static io.github.testlens.selector.tooling.SelectorHistoryModel.*;
import static io.github.testlens.selector.tooling.SelectorIndexModel.*;
import static org.junit.jupiter.api.Assertions.*;

class SelectorAuditTest {
    @TempDir Path temp;

    @Test void staticOnlyIsUsefulGeneratedLookingAndSanitized(){DeclarationRecord d=declaration("550e8400-e29b-41d4-a716-446655440000",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"a");AuditReport report=audit(index(List.of(d),List.of(),coverage(1,1,0)),CompiledPolicySet.empty(),null,List.of(),Map.of());DeclarationAudit entry=report.declarations().get(0);assertEquals(AnalysisMode.STATIC_ONLY,report.analysisMode());assertEquals(DimensionStatus.NOT_PROVIDED,report.coverage().historyCoverage().status());assertTrue(has(entry,FindingCode.APPEARANCE_GENERATED_LOOKING));assertTrue(has(entry,FindingCode.EVIDENCE_NOT_AVAILABLE));String json=new String(SelectorAuditJson.serialize(report),StandardCharsets.UTF_8);assertFalse(json.contains("550e8400-e29b-41d4-a716-446655440000"));assertFalse(json.contains("By.id"));assertTrue(json.contains("APPEARANCE_GENERATED_LOOKING"));}

    @Test void stablePolicyCoversAppearanceWithoutClaimingVerification(){DeclarationRecord d=declaration("550e8400-e29b-41d4-a716-446655440000",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"b");SelectorSubject subject=SelectorEngineAdapter.subjects(d).get(0);SelectorPolicy.Rule rule=SelectorPolicy.Rule.create(SelectorPolicy.Decision.STABLE,0,new SelectorPolicy.Scope(null,null,d.declarationRef(),null,null,null,null),SelectorPolicy.ExactMatcher.from(subject),new SelectorPolicy.Reason("PROJECT_CONTRACT","secret note"));AuditReport report=audit(index(List.of(d),List.of(),coverage(1,1,0)),CompiledPolicySet.compile(new SelectorPolicy.Document(1,1,List.of(rule))),null,List.of(),Map.of());AuditFinding appearance=find(report.declarations().get(0),FindingCode.APPEARANCE_GENERATED_LOOKING);assertEquals(FindingState.COVERED_BY_POLICY,appearance.state());assertEquals(Severity.INFO,appearance.severity());assertTrue(has(report.declarations().get(0),FindingCode.POLICY_DECLARED_STABLE));String json=new String(SelectorAuditJson.serialize(report),StandardCharsets.UTF_8);assertFalse(json.contains("secret note"));assertFalse(json.contains("verified stable"));}

    @Test void staticResolutionUncertaintyIsReviewButProvenAnnotationMisuseIsError(){DeclarationRecord uncertain=declaration(null,ResolutionStatus.ERROR,DeclarationKind.BY_FIELD,"c");DeclarationRecord proven=declaration(null,ResolutionStatus.ERROR,DeclarationKind.FIND_BY_ANNOTATION,"d");SelectorIndex index=index(List.of(uncertain,proven),List.of(new Issue("FINDBY_MULTIPLE_STRATEGIES","bad",proven.logicalPath())),coverage(2,0,2));AuditReport report=audit(index,CompiledPolicySet.empty(),null,List.of(),Map.of());AuditFinding first=find(byRef(report,uncertain.declarationRef()),FindingCode.SOURCE_RESOLUTION_ERROR),second=find(byRef(report,proven.declarationRef()),FindingCode.SOURCE_RESOLUTION_ERROR);assertEquals(Severity.REVIEW,first.severity());assertEquals(FindingState.INCOMPLETE,first.state());assertEquals(Severity.ERROR,second.severity());assertTrue(report.projectIssues().stream().anyMatch(x->x.code()==ProjectIssueCode.STATIC_ANALYSIS_INTERNAL_ERROR));}

    @Test void dynamicAndCustomAreNotDefects(){DeclarationRecord dynamic=declaration(null,ResolutionStatus.DYNAMIC,DeclarationKind.HELPER_METHOD,"e"),custom=declaration(null,ResolutionStatus.CUSTOM,DeclarationKind.CUSTOM,"f");AuditReport report=audit(index(List.of(dynamic,custom),List.of(),coverage(2,0,0)),CompiledPolicySet.empty(),null,List.of(),Map.of());assertEquals(Severity.INFO,find(byRef(report,dynamic.declarationRef()),FindingCode.SOURCE_DYNAMIC_DECLARATION).severity());assertEquals(FindingState.UNSUPPORTED,find(byRef(report,custom.declarationRef()),FindingCode.SOURCE_CUSTOM_LOCATOR).state());}

    @Test void exactCandidateCanCreateCurrentFailureButStrongCannot(){DeclarationRecord exact=declaration("save",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"g"),strong=declaration("other",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"h");CandidateAnalysis wrong=candidate(exact.declarationRef(),ValidationState.WRONG_TARGET,Recommendation.NO_VALID_CANDIDATE);CandidateAnalysis strongWrong=candidate(strong.declarationRef(),ValidationState.WRONG_TARGET,Recommendation.CONSIDER_REPLACEMENT);List<SelectorAuditOrchestrator.CandidateInput>inputs=List.of(new SelectorAuditOrchestrator.CandidateInput(wrong),new SelectorAuditOrchestrator.CandidateInput(strongWrong,SimilaritySubject.Confidence.STRONG,strong.declarationRef()));AuditReport report=audit(index(List.of(exact,strong),List.of(),coverage(2,2,0)),CompiledPolicySet.empty(),null,inputs,Map.of());assertEquals(Severity.ERROR,find(byRef(report,exact.declarationRef()),FindingCode.CURRENT_WRONG_TARGET).severity());assertFalse(has(byRef(report,strong.declarationRef()),FindingCode.CURRENT_WRONG_TARGET));assertNotEquals(SelectorAuditModel.Recommendation.CONSIDER_REPLACEMENT,byRef(report,strong.declarationRef()).primaryRecommendation());assertTrue(byRef(report,strong.declarationRef()).limitations().stream().anyMatch(x->x.contains("STRONG")));}

    @Test void invalidAlternativeDoesNotBecomeCurrentFailureAndCandidateOrderIsPreserved(){DeclarationRecord d=declaration("save",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"i");Candidate original=candidate("original",true,ValidationState.VERIFIED_IN_SCOPE),bad=candidate("bad",false,ValidationState.INVALID_SELECTOR),review=candidate("review",false,ValidationState.VALID_BUT_AMBIGUOUS);CandidateAnalysis analysis=new CandidateAnalysis(1,UsageIntent.FIND_ONE,null,d.declarationRef(),d.logicalPath(),"original",List.of(original,bad,review),Recommendation.KEEP_CURRENT,new Completeness(true,false,false,0,3,3,3),List.of());AuditReport report=audit(index(List.of(d),List.of(),coverage(1,1,0)),CompiledPolicySet.empty(),null,List.of(new SelectorAuditOrchestrator.CandidateInput(analysis)),Map.of());DeclarationAudit entry=report.declarations().get(0);assertFalse(has(entry,FindingCode.CURRENT_INVALID_SELECTOR));assertTrue(has(entry,FindingCode.CURRENT_LOCATOR_ALREADY_BEST));assertEquals(List.of("bad","review"),entry.candidateSummary().alternatives().stream().map(CandidateDetail::candidateId).toList());}

    @Test void comparableHistoryChangesButNonComparableDoesNot(){DeclarationRecord d=declaration("value",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"j");String component=ComponentIdentity.of("TARGET","primary").componentRef();History changed=history(d,component,Comparability.State.COMPARABLE,true,false,false);AuditReport report=audit(index(List.of(d),List.of(),coverage(1,1,0)),CompiledPolicySet.empty(),changed,List.of(),Map.of());assertTrue(has(report.declarations().get(0),FindingCode.EVIDENCE_OBSERVED_VARIABLE));History different=history(d,component,Comparability.State.NOT_COMPARABLE,true,false,false);AuditReport nonComparable=audit(index(List.of(d),List.of(),coverage(1,1,0)),CompiledPolicySet.empty(),different,List.of(),Map.of());assertFalse(has(nonComparable.declarations().get(0),FindingCode.EVIDENCE_OBSERVED_VARIABLE));}

    @Test void incompleteHistoryAndOrphansAreProjectInformation(){DeclarationRecord d=declaration("save",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"k");DeclarationRecord deleted=declaration("gone",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"deleted");History history=history(deleted,ComponentIdentity.of("TARGET","primary").componentRef(),Comparability.State.UNKNOWN,false,true,true);SelectorPolicy.Rule orphan=SelectorPolicy.Rule.create(SelectorPolicy.Decision.UNSTABLE,0,new SelectorPolicy.Scope(null,null,deleted.declarationRef(),null,null,null,null),new SelectorPolicy.ExactMatcher("id","0".repeat(64),null),new SelectorPolicy.Reason("OLD",null));AuditReport report=audit(index(List.of(d),List.of(),coverage(1,1,0)),CompiledPolicySet.compile(new SelectorPolicy.Document(1,1,List.of(orphan))),history,List.of(),Map.of());assertTrue(report.projectIssues().stream().anyMatch(x->x.code()==ProjectIssueCode.ORPHANED_HISTORY_SUBJECT));assertTrue(report.projectIssues().stream().anyMatch(x->x.code()==ProjectIssueCode.ORPHANED_POLICY_RULE));assertEquals(1,report.runtimeOnlySubjects().size());}

    @Test void indexReaderIsStrictAndRoundTrips()throws Exception{SelectorIndex index=index(List.of(declaration("save",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"l")),List.of(),coverage(1,1,0));Path file=temp.resolve("index.json");Files.writeString(file,SelectorIndexJson.serialize(index),StandardCharsets.UTF_8);assertEquals(index,SelectorIndexJson.read(file));String duplicate=SelectorIndexJson.serialize(index).replaceFirst("\\{","{\"schemaVersion\":1,");Files.writeString(file,duplicate);assertThrows(SelectorIndexJson.IndexFormatException.class,()->SelectorIndexJson.read(file));String unknown=SelectorIndexJson.serialize(index).replaceFirst("\"generator\"","\"unknown\":1,\"generator\"");Files.writeString(file,unknown);assertThrows(SelectorIndexJson.IndexFormatException.class,()->SelectorIndexJson.read(file));String extension=SelectorIndexJson.serialize(index).replaceFirst("\"generator\"","\"x-extra\":1,\"generator\"");Files.writeString(file,extension);assertEquals(index,SelectorIndexJson.read(file));}

    @Test void deterministicJsonHtmlAndMaliciousTextIsEscaped(){DeclarationRecord d=declaration("<script>alert('secret')</script>",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"m");SelectorIndex base=index(List.of(d),List.of(),coverage(1,1,0));SourceFileIndex old=base.files().get(0);SourceFileIndex malicious=new SourceFileIndex("src/<script>.java",old.sourceLanguage(),old.encoding(),old.contentHash(),false,false,old.parseStatus(),old.issues(),old.declarations().stream().map(x->new DeclarationRecord(x.schemaVersion(),x.declarationRef(),x.sourceLanguage(),"src/<script>.java",x.sourceRange(),x.declaringSymbol(),x.declarationKind(),x.locatorExpression(),x.resolvedLocator(),x.resolutionStatus(),x.generated(),x.readOnly(),x.contentFingerprint())).toList());AuditReport report=audit(new SelectorIndex(base.project(),List.of(malicious),base.coverage(),List.of()),CompiledPolicySet.empty(),null,List.of(),Map.of());byte[]j1=SelectorAuditJson.serialize(report),j2=SelectorAuditJson.serialize(report),h1=SelectorAuditHtml.render(report),h2=SelectorAuditHtml.render(report);assertArrayEquals(j1,j2);assertArrayEquals(h1,h2);String json=new String(j1,StandardCharsets.UTF_8),html=new String(h1,StandardCharsets.UTF_8);assertFalse(json.contains("alert('secret')"));assertFalse(json.contains("normalizedExpression"));assertFalse(html.contains("<script>.java"));assertTrue(html.contains("&lt;script&gt;.java"));assertFalse(html.contains("http://"));assertFalse(html.contains("https://"));assertFalse(html.contains("apply"));}

    @Test void staleHashAndOutputPathSafetyAreReported()throws Exception{DeclarationRecord d=declaration("save",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"n");AuditReport report=audit(index(List.of(d),List.of(),coverage(1,1,0)),CompiledPolicySet.empty(),null,List.of(),Map.of(d.logicalPath(),"sha256:"+"f".repeat(64)));assertEquals(SourceFreshness.STALE_INDEX,report.declarations().get(0).freshness());assertTrue(report.projectIssues().stream().anyMatch(x->x.code()==ProjectIssueCode.STALE_SELECTOR_INDEX));Files.createDirectories(temp.resolve("target"));assertThrows(IllegalArgumentException.class,()->SelectorAuditJson.writeLocal(report,temp,temp.resolve("outside.json")));SelectorAuditJson.writeLocal(report,temp,Path.of("target/test-lens/selector-audit/audit-v1.json"));SelectorAuditHtml.writeLocal(report,temp,Path.of("target/test-lens/selector-audit/audit-v1.html"));assertTrue(Files.exists(temp.resolve("target/test-lens/selector-audit/audit-v1.json")));}

    @Test void malformedRequiredIndexIsFatalWhileOptionalInputsArePartial()throws Exception{Path indexFile=temp.resolve("index.json");Files.writeString(indexFile,"{}");assertThrows(SelectorAuditOrchestrator.AuditInputException.class,()->new SelectorAuditRunner().audit(indexFile,null,null,List.of(),null,Map.of(),Map.of()));SelectorIndex index=index(List.of(declaration("save",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"o")),List.of(),coverage(1,1,0));Files.writeString(indexFile,SelectorIndexJson.serialize(index));Path policy=temp.resolve("policy.json"),history=temp.resolve("history.json");Files.writeString(policy,"{");Files.writeString(history,"{");AuditReport report=new SelectorAuditRunner().audit(indexFile,policy,history,List.of(),null,Map.of(),Map.of());assertTrue(report.projectIssues().stream().anyMatch(x->x.code()==ProjectIssueCode.MALFORMED_OPTIONAL_POLICY));assertTrue(report.projectIssues().stream().anyMatch(x->x.code()==ProjectIssueCode.MALFORMED_OPTIONAL_HISTORY));assertEquals(CompletenessStatus.PARTIAL,report.overallCompleteness());}

    @Test void exactAttachmentCannotBeSpoofedByWrapperReference(){DeclarationRecord a=declaration("a",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"p"),b=declaration("b",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"q");CandidateAnalysis analysis=candidate(a.declarationRef(),ValidationState.WRONG_TARGET,Recommendation.NO_VALID_CANDIDATE);SelectorAuditOrchestrator.CandidateInput spoofed=new SelectorAuditOrchestrator.CandidateInput(analysis,SimilaritySubject.Confidence.EXACT,b.declarationRef());AuditReport report=audit(index(List.of(a,b),List.of(),coverage(2,2,0)),CompiledPolicySet.empty(),null,List.of(spoofed),Map.of());assertTrue(report.declarations().stream().noneMatch(x->has(x,FindingCode.CURRENT_WRONG_TARGET)));assertTrue(report.projectIssues().stream().anyMatch(x->x.code()==ProjectIssueCode.CANDIDATE_INPUT_REJECTED));}

    @Test void candidateDetailsAreBoundedWithoutReranking(){DeclarationRecord d=declaration("save",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"r");List<Candidate>all=new java.util.ArrayList<>();all.add(candidate("original",true,ValidationState.VERIFIED_IN_SCOPE));for(int i=0;i<8;i++)all.add(candidate("alternative-"+i,false,ValidationState.VERIFIED_IN_SCOPE));CandidateAnalysis analysis=new CandidateAnalysis(1,UsageIntent.FIND_ONE,null,d.declarationRef(),d.logicalPath(),"original",all,Recommendation.CONSIDER_REPLACEMENT,new Completeness(true,false,false,0,9,9,9),List.of());DeclarationAudit entry=audit(index(List.of(d),List.of(),coverage(1,1,0)),CompiledPolicySet.empty(),null,List.of(new SelectorAuditOrchestrator.CandidateInput(analysis)),Map.of()).declarations().get(0);assertEquals(5,entry.candidateSummary().alternatives().size());assertEquals(9,entry.candidateSummary().totalCandidateCount());assertTrue(entry.candidateSummary().candidatesTruncated());assertEquals(List.of("alternative-0","alternative-1","alternative-2","alternative-3","alternative-4"),entry.candidateSummary().alternatives().stream().map(CandidateDetail::candidateId).toList());}

    @Test void htmlViewerContainsCoverageFiltersAndNoLabControls(){DeclarationRecord d=declaration("save",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"s");String html=new String(SelectorAuditHtml.render(audit(index(List.of(d),List.of(),coverage(1,1,0)),CompiledPolicySet.empty(),null,List.of(),Map.of())),StandardCharsets.UTF_8);assertTrue(html.contains("Selector Audit"));assertTrue(html.contains("Coverage"));for(String severity:List.of("ERROR","WARNING","REVIEW","INFO"))assertTrue(html.contains("data-filter=\""+severity+"\""));assertTrue(html.contains("<details"));assertTrue(html.contains("Families"));assertTrue(html.contains("Project issues"));assertFalse(html.contains("Element picker"));assertFalse(html.contains("Save policy"));assertFalse(html.contains("Apply fix"));}

    @Test void indexReaderRejectsUnsupportedSchemaAndWrongTypes()throws Exception{SelectorIndex index=index(List.of(declaration("save",ResolutionStatus.RESOLVED,DeclarationKind.BY_FIELD,"t")),List.of(),coverage(1,1,0));Path file=temp.resolve("strict-index.json");String json=SelectorIndexJson.serialize(index);Files.writeString(file,json.replaceFirst("\"schemaVersion\":1","\"schemaVersion\":2"));assertThrows(SelectorIndexJson.IndexFormatException.class,()->SelectorIndexJson.read(file));Files.writeString(file,json.replaceFirst("\"schemaVersion\":1","\"schemaVersion\":\"1\""));assertThrows(SelectorIndexJson.IndexFormatException.class,()->SelectorIndexJson.read(file));}

    private AuditReport audit(SelectorIndex index,CompiledPolicySet policies,History history,List<SelectorAuditOrchestrator.CandidateInput>candidates,Map<String,String>hashes){return new SelectorAuditOrchestrator().audit(new SelectorAuditOrchestrator.Request(index,policies,history,candidates,null,hashes,Map.of(),null,null,null,List.of()));}
    private static DeclarationAudit byRef(AuditReport r,String ref){return r.declarations().stream().filter(x->x.declarationRef().equals(ref)).findFirst().orElseThrow();}
    private static boolean has(DeclarationAudit d,FindingCode code){return d.findings().stream().anyMatch(x->x.code()==code);}
    private static AuditFinding find(DeclarationAudit d,FindingCode code){return d.findings().stream().filter(x->x.code()==code).findFirst().orElseThrow();}
    private static String ref(String suffix){return "java-decl-v1:sha256:"+CanonicalDigests.digest("audit-test-declaration-v1",suffix);}
    private static DeclarationRecord declaration(String value,ResolutionStatus status,DeclarationKind kind,String suffix){String path="module/src/test/java/sample/"+suffix+".java";LocatorExpression expression=new LocatorExpression(value==null?ExpressionKind.TEMPLATE:ExpressionKind.SINGLE,value==null?"By.id(value)":"By.id(\""+value+"\")",List.of(),List.of());ResolvedLocator resolved=value==null?null:new ResolvedLocator("id",value);return new DeclarationRecord(1,ref(suffix),"java",path,new SourceRange(1,1,1,Math.max(2,10+(value==null?0:value.length())),0,Math.max(1,9+(value==null?0:value.length()))),new DeclaringSymbol("FIELD","sample.Page","field",null),kind,expression,resolved,status,false,false,"sha256:"+CanonicalDigests.digest("audit-test-content-v1",suffix));}
    private static SelectorIndex index(List<DeclarationRecord>d,List<SelectorIndexModel.Issue>issues,SelectorIndexModel.Coverage coverage){Map<String,List<DeclarationRecord>>files=d.stream().collect(java.util.stream.Collectors.groupingBy(DeclarationRecord::logicalPath));List<SourceFileIndex>source=files.entrySet().stream().sorted(Map.Entry.comparingByKey()).map(e->new SourceFileIndex(e.getKey(),"java","UTF-8","sha256:"+CanonicalDigests.digest("audit-test-file-v1",e.getKey()),false,false,ParseStatus.PARSED,issues.stream().filter(i->i.logicalPath()==null||i.logicalPath().equals(e.getKey())).toList(),e.getValue())).toList();return new SelectorIndex(new ProjectMetadata(null,List.of("module/src/test/java"),"3.28.2","JAVA_17","UTF-8","sha256:"+"1".repeat(64),"sha256:"+"2".repeat(64)),source,coverage,issues);}
    private static SelectorIndexModel.Coverage coverage(int declarations,int resolved,int errors){return new SelectorIndexModel.Coverage(1,1,Math.max(1,declarations),Math.max(1,declarations),0,0,0,0,declarations,resolved,0,0,0,0,errors,false,0);}
    private static CandidateAnalysis candidate(String declarationRef,ValidationState state,CandidateAnalysis.Recommendation recommendation){Candidate original=candidate("original",true,state),alternative=candidate("alternative",false,ValidationState.VERIFIED_IN_SCOPE);return new CandidateAnalysis(1,UsageIntent.FIND_ONE,null,declarationRef,"module/src/test/java/sample.java","original",List.of(original,alternative),recommendation,new Completeness(true,false,false,0,2,2,2),List.of());}
    private static Candidate candidate(String id,boolean original,ValidationState state){return new Candidate(id,new Locator("id",id),false,List.of(original?Origin.ORIGINAL:Origin.ID),List.of(),new Validation(state,state==ValidationState.NO_MATCH?0:1,state==ValidationState.WRONG_TARGET?TargetComparison.DIFFERENT_TARGET:TargetComparison.SAME_TARGET,List.of()),new Complexity(ScopeFragility.DIRECT,SemanticPreference.ID,0,0,id.length(),1),List.of(),List.of(),original);}
    private static History history(DeclarationRecord d,String component,Comparability.State comparability,boolean changed,boolean incomplete,boolean pruned){SimilaritySubject.Correlation correlation=new SimilaritySubject.Correlation(SimilaritySubject.Confidence.EXACT,List.of("DECLARATION_REF"),List.of(),List.of(),1);DomainSummary domain=new DomainSummary(ObservationEvidence.Domain.NEW_RUN,comparability,comparability==Comparability.State.COMPARABLE?2:0,changed?2:1,changed,List.of());Subject subject=new Subject("selector-history-subject-v1:sha256:"+CanonicalDigests.digest("audit-test-history-subject-v1",d.declarationRef()),"id","TARGET",List.of("primary"),component,d.declarationRef(),null,null,List.of(),List.of(),changed?List.of(new ValueSummary(CanonicalDigests.digest("selector-exact-value-v1","one"),1,1),new ValueSummary(CanonicalDigests.digest("selector-exact-value-v1","two"),1,1)):List.of(new ValueSummary(CanonicalDigests.digest("selector-exact-value-v1","one"),2,2)),List.of(domain),new SelectorHistoryModel.UsageSummary(1,List.of()),List.of(),Comparability.ComparisonMode.EXACT_VALUE,correlation,SimilaritySubject.SourceState.CURRENT);Run run=new Run("selector-run-v1:sha256:"+"1".repeat(64),"selector-logical-test-v1:sha256:"+"2".repeat(64),null,null,null,null,0,null,null,null,null,null,Instant.EPOCH,null,null,false);return new History(1,1,1,1,1,new Generator("test","0.4.0"),new SelectorHistoryModel.Project(null),List.of(run),List.of(subject),new SelectorHistoryModel.Coverage(0,0,1,1,0,0,incomplete?1:0,incomplete,List.of()),new Retention(1,1,1,0,pruned,true,List.of()));}
}
