package io.github.testlens.studio.workspace;

import io.github.testlens.application.tooling.ai.*;
import org.junit.jupiter.api.Test;
import java.time.Instant;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

class WorkflowSessionSnapshotTest{
    @Test void roundTripRetainsReviewedArtifactsAndAvailableAction(){
        ContractHeader header=new ContractHeader(ContractHeader.SCHEMA_VERSION,ContractHeader.Status.READY,List.of("fixture"),List.of(),ContractHeader.Confidence.OBSERVED);
        TestPlan plan=new TestPlan(header,List.of());TestImplementationProposal implementation=new TestImplementationProposal(header,"invalid-password","class Test {}",TestImplementationProposal.SelectorAccessPolicy.PAGE_OBJECTS_ONLY,List.of("LoginPage.login"),List.of());
        Instant now=Instant.parse("2026-01-01T00:00:00Z");WorkflowSessionSnapshot snapshot=new WorkflowSessionSnapshot(1,"run-1","invalid password",WorkflowSessionSnapshot.State.IMPLEMENTATION_READY_FOR_REVIEW,now,now,"project","source",WorkflowSessionSnapshot.Freshness.FRESH,plan,implementation,null,null,null,null,null,false,List.of());
        WorkflowSessionSnapshot restored=WorkflowSessionSnapshot.fromDocument(snapshot.toDocument());
        assertEquals(snapshot.workflowId(),restored.workflowId());assertEquals(implementation.sourcePatch(),restored.implementation().sourcePatch());assertEquals(List.of("RUN"),restored.availableActions());
    }
    @Test void staleReviewedImplementationCannotRun(){Instant now=Instant.EPOCH;WorkflowSessionSnapshot snapshot=new WorkflowSessionSnapshot(1,"run-2","requirement",WorkflowSessionSnapshot.State.IMPLEMENTATION_READY_FOR_REVIEW,now,now,"p","s",WorkflowSessionSnapshot.Freshness.STALE,null,null,null,null,null,null,null,true,List.of("SOURCE_CHANGED"));assertEquals(List.of("REGENERATE_PLAN"),snapshot.availableActions());}
    @Test void futureSchemaAndMissingArtifactsFailClosed(){Map<String,Object> document=new LinkedHashMap<>();Instant now=Instant.EPOCH;WorkflowSessionSnapshot valid=new WorkflowSessionSnapshot(1,"run-3","requirement",WorkflowSessionSnapshot.State.CREATED,now,now,null,null,WorkflowSessionSnapshot.Freshness.FRESH,null,null,null,null,null,null,null,false,List.of());document.putAll(valid.toDocument());document.put("schemaVersion",2);assertThrows(RuntimeException.class,()->WorkflowSessionSnapshot.fromDocument(document));}
    @Test void runningOperationsRestoreAsInterruptedWithoutImplicitRetry(){Instant now=Instant.EPOCH;WorkflowSessionSnapshot generating=new WorkflowSessionSnapshot(1,"run-4","requirement",WorkflowSessionSnapshot.State.PLAN_GENERATING,now,now,"p","s",WorkflowSessionSnapshot.Freshness.FRESH,null,null,null,null,null,null,null,false,List.of());WorkflowSessionSnapshot restored=generating.restoredAfterInterruption(WorkflowSessionSnapshot.Freshness.FRESH,List.of());assertEquals(WorkflowSessionSnapshot.State.AGENT_EXECUTION_INTERRUPTED,restored.state());assertEquals(List.of("GENERATE_PLAN"),restored.availableActions());}
    @Test void interruptedInitialExecutionIsRunAgainWithoutPretendingRepairWasApplied(){ContractHeader header=new ContractHeader(ContractHeader.SCHEMA_VERSION,ContractHeader.Status.READY,List.of(),List.of(),ContractHeader.Confidence.OBSERVED);TestImplementationProposal implementation=new TestImplementationProposal(header,"scenario","class Test {}",TestImplementationProposal.SelectorAccessPolicy.PAGE_OBJECTS_ONLY,List.of(),List.of());Instant now=Instant.EPOCH;WorkflowSessionSnapshot interrupted=new WorkflowSessionSnapshot(1,"run-5","requirement",WorkflowSessionSnapshot.State.EXECUTION_INTERRUPTED,now,now,"p","s",WorkflowSessionSnapshot.Freshness.FRESH,null,implementation,null,null,null,null,null,true,List.of("EXECUTION_INTERRUPTED"));assertEquals(List.of("RUN"),interrupted.availableActions());}
    @Test void distinctRepairClearsOldApprovalAcrossPersistenceRoundTrip(){ContractHeader header=new ContractHeader(ContractHeader.SCHEMA_VERSION,ContractHeader.Status.READY,List.of("verified"),List.of(),ContractHeader.Confidence.LIVE_VALIDATED);RepairProposal.SelectorEvidence evidence=new RepairProposal.SelectorEvidence("cssSelector","[data-testid='new']","candidate-new","VERIFIED_IN_SCOPE","SAME_TARGET",true,List.of("STABLE"),"LIVE_CANDIDATE_ANALYSIS");RepairProposal.SourceTarget target=new RepairProposal.SourceTarget("element","declaration","src/test/java/Page.java",new RepairProposal.SourceRange(1,1,1,10,0,9),"file-fp","declaration-fp","EXACT","id","old");RepairProposal next=new RepairProposal(header,"repair-new",RepairProposal.ApplicationPolicy.PROPOSE_ONLY,"selector","changed","id:old","cssSelector:[data-testid='new']","declaration","candidate-old","candidate-new","classification","drift",List.of("SAME_TARGET"),List.of("STABLE"),List.of("Test"),List.of(),List.of("rerun"),target,evidence,List.of());Instant now=Instant.EPOCH;WorkflowSessionSnapshot approved=new WorkflowSessionSnapshot(1,"run-6","requirement",WorkflowSessionSnapshot.State.REPAIR_APPLIED_VERIFICATION_PENDING,now,now,"p","s",WorkflowSessionSnapshot.Freshness.FRESH,null,null,null,null,next,"APPROVED","APPLIED",false,List.of());WorkflowSessionSnapshot restored=WorkflowSessionSnapshot.fromDocument(approved.withNewRepair(next,now.plusSeconds(1)).toDocument());assertEquals(WorkflowSessionSnapshot.State.REPAIR_READY_FOR_REVIEW,restored.state());assertNull(restored.repairDecision());assertNull(restored.repairApplyStatus());assertEquals(List.of("DIAGNOSE","APPROVE_REPAIR","REJECT_REPAIR"),restored.availableActions());}
}
