package io.github.testlens.selector.engine;

import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class SimilarityEngineTest {
    @Test void digestDomainsAreSeparatedAndComponentPathsAreStable(){assertNotEquals(CanonicalDigests.digest("selector-run-v1","same"),CanonicalDigests.digest("selector-dataset-key-v1","same"));ComponentIdentity a=ComponentIdentity.of("TARGET","classes","0"),b=ComponentIdentity.of("TARGET","classes","0"),c=ComponentIdentity.of("TARGET","classes","1");assertEquals(a.componentRef(),b.componentRef());assertNotEquals(a.componentRef(),c.componentRef());}
    @Test void proposesPrefixUuidWithoutOverlappingHex(){PatternProposal.Result r=new PatternProposal().propose(subject("id","user-card-550e8400-e29b-41d4-a716-446655440000"));assertTrue(r.useful());assertEquals(List.of(SelectorPolicy.SegmentKind.LITERAL,SelectorPolicy.SegmentKind.UUID_LIKE),r.pattern().segments().stream().map(SelectorPolicy.Segment::kind).toList());}
    @Test void proposesUuidOnlyAndBoundedNumericAndHex(){assertEquals(SelectorPolicy.SegmentKind.UUID_LIKE,new PatternProposal().propose(subject("id","550e8400-e29b-41d4-a716-446655440000")).pattern().segments().get(0).kind());SelectorPolicy.Segment numeric=new PatternProposal().propose(subject("id","row-123456789")).pattern().segments().get(1);assertEquals(9,numeric.minLength());assertEquals(9,numeric.maxLength());assertEquals(SelectorPolicy.SegmentKind.HEX_RUN,new PatternProposal().propose(subject("id","hash-abcdef123456")).pattern().segments().get(1).kind());}
    @Test void refusesShortNumericEntropyWildcardAndRedactedInput(){assertFalse(new PatternProposal().propose(subject("id","order-123")).useful());PatternProposal.Result entropy=new PatternProposal().propose(subject("id","item-z9x8c7v6b5n4"));assertTrue(entropy.pattern()==null||entropy.pattern().segments().stream().noneMatch(s->s.kind()==SelectorPolicy.SegmentKind.OPAQUE_RUN));SelectorSubject redacted=new SelectorSubject(SelectorSubject.SubjectKind.RUNTIME_OBSERVATION,"id",SelectorSubject.ValueState.KNOWN,"[REDACTED]",null,null,null,null,null,null,null,SelectorSubject.InputTrust.RUNTIME_REDACTED,null);assertFalse(new PatternProposal().propose(redacted).useful());}
    @Test void unicodeRangesRemainCodePointBased(){PatternProposal.Result r=new PatternProposal().propose(subject("id","konto-✅-550e8400-e29b-41d4-a716-446655440000"));AppearanceSignal uuid=r.findings().stream().filter(s->s.family()==AppearanceSignal.Family.UUID_LIKE).findFirst().orElseThrow();assertEquals("konto-✅-".codePointCount(0,"konto-✅-".length()),uuid.startCodePoint());}
    @Test void structuralFamilyStoresLiteralDigestNotLiteral(){SelectorSubject s=subject("id","user-card-550e8400-e29b-41d4-a716-446655440000");StructuralFamily f=StructuralFamily.from(s,ComponentIdentity.of("TARGET","primary"),new PatternProposal().propose(s));assertNotNull(f);assertEquals(StructuralFamily.Kind.LITERAL_DIGEST,f.segments().get(0).kind());assertFalse(f.segments().get(0).literalDigest().contains("user-card"));}
    @Test void findsDeclarationExactTemplateFamilyAndAppearanceRelationsDeterministically(){SimilaritySubject source=similar("a",subject("id","user-card-550e8400-e29b-41d4-a716-446655440000"),"D1","template",ComponentIdentity.of("TARGET","primary"));SimilaritySubject declaration=similar("b",subject("id","other"),"D1","other",ComponentIdentity.of("TARGET","primary"));SimilaritySubject exact=similar("c",subject("id",source.subject().canonicalValue()),"D2","other",ComponentIdentity.of("TARGET","primary"));SimilaritySubject template=similar("d",subject("id","x"),"D3","template",ComponentIdentity.of("TARGET","primary"));SimilarityResult result=new SimilarityIndex(List.of(template,exact,declaration,source)).find(source,SimilarityResult.QueryScope.PROJECT,CompiledPolicySet.empty(),Map.of());assertEquals(List.of(SimilarityResult.RelationClass.SAME_DECLARATION,SimilarityResult.RelationClass.EXACT_LOCATOR,SimilarityResult.RelationClass.SAME_TEMPLATE),result.relatedSubjects().stream().limit(3).map(SimilarityResult.RelatedSubject::relationClass).toList());}
    @Test void sameDigestDifferentStrategyIsNotExactAndModuleOnlyIsInsufficient(){SimilaritySubject a=similar("a",subject("id","save"),null,null,ComponentIdentity.of("TARGET","primary"));SimilaritySubject b=new SimilaritySubject(subject("name","save"),"b",ComponentIdentity.of("TARGET","primary"),null,null,List.of(),a.exactDigest(),List.of(),List.of(),null,null,List.of(),correlation(),SimilaritySubject.SourceState.CURRENT);assertTrue(new SimilarityIndex(List.of(a,b)).find(a,SimilarityResult.QueryScope.PROJECT,CompiledPolicySet.empty(),Map.of()).relatedSubjects().isEmpty());SimilaritySubject c=similar("c",new SelectorSubject(SelectorSubject.SubjectKind.STATIC_DECLARATION,"name",SelectorSubject.ValueState.KNOWN,"other",null,"same",null,null,null,null,null,SelectorSubject.InputTrust.SOURCE_CANONICAL,null),null,null,ComponentIdentity.of("TARGET","primary"));assertTrue(new SimilarityIndex(List.of(a,c)).find(a,SimilarityResult.QueryScope.PROJECT,CompiledPolicySet.empty(),Map.of()).relatedSubjects().isEmpty());}
    @Test void explicitPatternRelationIsIndexedWithoutTextualSimilarity(){
        SimilaritySubject a=withPatterns(similar("a",subject("id","alpha"),null,null,ComponentIdentity.of("TARGET","primary")),List.of("pattern-one"));
        SimilaritySubject b=withPatterns(similar("b",subject("name","omega"),null,null,ComponentIdentity.of("TARGET","primary")),List.of("pattern-one"));
        SimilarityResult result=new SimilarityIndex(List.of(a,b)).find(a,SimilarityResult.QueryScope.PROJECT,CompiledPolicySet.empty(),Map.of());
        assertEquals(SimilarityResult.RelationClass.EXPLICIT_PATTERN_RELATED,result.relatedSubjects().get(0).relationClass());
    }
    @Test void similarityDoesNotExpandPolicyScope(){SelectorSubject base=subject("id","550e8400-e29b-41d4-a716-446655440000");SimilaritySubject a=similar("a",withDeclaration(base,"A"),"A",null,ComponentIdentity.of("TARGET","primary"));SimilaritySubject b=similar("b",withDeclaration(base,"B"),"B",null,ComponentIdentity.of("TARGET","primary"));SelectorPolicy.Rule rule=SelectorPolicy.Rule.create(SelectorPolicy.Decision.STABLE,0,new SelectorPolicy.Scope(null,null,"A",null,null,null,null),SelectorPolicy.ExactMatcher.from(a.subject()),new SelectorPolicy.Reason("TEST",null));SimilarityResult r=new SimilarityIndex(List.of(a,b)).find(a,SimilarityResult.QueryScope.PROJECT,CompiledPolicySet.compile(new SelectorPolicy.Document(1,1,List.of(rule))),Map.of());assertEquals(StabilityAssessment.EffectiveDisposition.REVIEW_GENERATED_LOOKING,r.relatedSubjects().get(0).policyAndEvidence().effectiveDisposition());}
    @Test void digestOnlyHistoryCanMatchExactPolicyWithoutRawValue(){
        SimilaritySubject source=similar("source",subject("id","550e8400-e29b-41d4-a716-446655440000"),null,null,ComponentIdentity.of("TARGET","primary"));
        SelectorSubject unavailable=new SelectorSubject(SelectorSubject.SubjectKind.RUNTIME_OBSERVATION,"id",SelectorSubject.ValueState.UNAVAILABLE,null,null,"module",null,null,null,null,null,SelectorSubject.InputTrust.RUNTIME_REDACTED,null);
        SimilaritySubject history=new SimilaritySubject(unavailable,"history",source.component(),null,source.structuralFamily(),source.appearanceSignals(),source.exactDigest(),List.of(),List.of(),null,null,List.of(),correlation(),SimilaritySubject.SourceState.UNKNOWN);
        SelectorPolicy.Rule stable=SelectorPolicy.Rule.create(SelectorPolicy.Decision.STABLE,0,SelectorPolicy.Scope.project(),SelectorPolicy.ExactMatcher.from(source.subject()),new SelectorPolicy.Reason("TEST",null));
        SimilarityResult result=new SimilarityIndex(List.of(source,history)).find(source,SimilarityResult.QueryScope.PROJECT,CompiledPolicySet.compile(new SelectorPolicy.Document(1,1,List.of(stable))),Map.of());
        assertEquals(StabilityAssessment.EffectiveDisposition.DECLARED_STABLE,result.relatedSubjects().get(0).policyAndEvidence().effectiveDisposition());
        assertEquals(SelectorSubject.ValueState.UNAVAILABLE,result.relatedSubjects().get(0).policyAndEvidence().subject().valueState());
    }
    @Test void comparabilitySeparatesRunRetryDatasetBuildAndDynamic(){RunDescriptor a=run("one",0,"data","build"),b=run("two",0,"data","build"),retry=run("one",1,"data","build"),dataset=run("two",0,"other","build"),build=run("two",0,"data","next");assertEquals(Comparability.State.COMPARABLE,Comparability.evaluate(a,b,ObservationEvidence.Domain.NEW_RUN,Comparability.ComparisonMode.EXACT_VALUE).state());assertEquals(Comparability.State.UNKNOWN,Comparability.evaluate(a,retry,ObservationEvidence.Domain.NEW_RUN,Comparability.ComparisonMode.EXACT_VALUE).state());assertEquals(Comparability.State.NOT_COMPARABLE,Comparability.evaluate(a,dataset,ObservationEvidence.Domain.DIFFERENT_DATASET,Comparability.ComparisonMode.EXACT_VALUE).state());assertEquals(Comparability.State.UNKNOWN,Comparability.evaluate(a,build,ObservationEvidence.Domain.DIFFERENT_BUILD,Comparability.ComparisonMode.EXACT_VALUE).state());assertEquals(Comparability.State.NOT_COMPARABLE,Comparability.evaluate(a,b,ObservationEvidence.Domain.NEW_RUN,Comparability.ComparisonMode.EXPECTED_DYNAMIC_VALUE).state());assertNotEquals(b.runRef(),dataset.runRef());}
    @Test void digestOnlyPreviewSupportsUuidAndRejectsOpaque(){SelectorSubject s=subject("id","user-550e8400-e29b-41d4-a716-446655440000");PatternProposal.Result p=new PatternProposal().propose(s);StructuralFamily f=StructuralFamily.from(s,ComponentIdentity.of("TARGET","primary"),p);assertEquals(StructuralFamily.Match.MATCH,f.matchDigestOnly(p.pattern()));SelectorPolicy.StructuralPattern opaque=new SelectorPolicy.StructuralPattern("id",List.of(SelectorPolicy.Segment.literal("user-"),SelectorPolicy.Segment.opaque("abc123",1,10)));assertEquals(StructuralFamily.Match.UNSUPPORTED_FROM_DIGEST_ONLY,f.matchDigestOnly(opaque));}
    @Test void federatedPreviewEvaluatesEntireSuppliedScopeWithoutMutatingPolicies(){
        SelectorSubject sourceSubject=withDeclaration(subject("id","user-550e8400-e29b-41d4-a716-446655440000"),"A");
        PatternProposal.Result proposal=new PatternProposal().propose(sourceSubject);
        SimilaritySubject source=similar("static-a",sourceSubject,"A",null,ComponentIdentity.of("TARGET","primary"));
        SelectorSubject historySubject=new SelectorSubject(SelectorSubject.SubjectKind.RUNTIME_OBSERVATION,"id",SelectorSubject.ValueState.UNAVAILABLE,null,null,"module",null,null,null,null,null,SelectorSubject.InputTrust.RUNTIME_REDACTED,null);
        SimilaritySubject history=new SimilaritySubject(historySubject,"history-a",ComponentIdentity.of("TARGET","primary"),null,source.structuralFamily(),source.appearanceSignals(),null,List.of(),List.of(),null,null,List.of(),correlation(),SimilaritySubject.SourceState.UNKNOWN);
        SimilaritySubject excluded=similar("excluded",subject("id","user-save"),"B",null,ComponentIdentity.of("TARGET","primary"));
        SelectorPolicy.Document before=SelectorPolicy.Document.empty();
        FederatedPatternPreview.Result result=new FederatedPatternPreview().preview(proposal,List.of(excluded,history,source),CompiledPolicySet.compile(before),Map.of(),true);
        assertEquals(List.of("static-a"),result.matchedStaticSubjects().stream().map(FederatedPatternPreview.Entry::subjectRef).toList());
        assertEquals(List.of("history-a"),result.matchedHistorySubjects().stream().map(FederatedPatternPreview.Entry::subjectRef).toList());
        assertEquals(List.of("excluded"),result.excludedNearMatches().stream().map(FederatedPatternPreview.Entry::subjectRef).toList());
        assertTrue(result.incompleteHistory());
        assertTrue(before.rules().isEmpty());
    }
    private static SelectorSubject subject(String strategy,String value){return new SelectorSubject(SelectorSubject.SubjectKind.STATIC_DECLARATION,strategy,SelectorSubject.ValueState.KNOWN,value,null,"module","src/P.java","P#m",null,null,null,SelectorSubject.InputTrust.SOURCE_CANONICAL,null);}private static SelectorSubject withDeclaration(SelectorSubject s,String ref){return new SelectorSubject(s.kind(),s.strategy(),s.valueState(),s.canonicalValue(),ref,s.modulePath(),s.logicalPath(),s.declaringSymbol(),s.usageClass(),s.usageMethod(),s.contextFingerprint(),s.inputTrust(),s.templateInformation());}
    private static SimilaritySubject similar(String ref,SelectorSubject subject,String declaration,String template,ComponentIdentity component){SelectorSubject s=declaration==null?subject:withDeclaration(subject,declaration);SimilaritySubject made=SimilaritySubject.create(s,component,template,List.of(),List.of(),null,null,List.of(),correlation(),SimilaritySubject.SourceState.CURRENT);return new SimilaritySubject(made.subject(),ref,made.component(),made.templateFingerprint(),made.structuralFamily(),made.appearanceSignals(),made.exactDigest(),made.explicitPatternRefs(),made.candidateOrigins(),made.semanticAttributeFamily(),made.usageSourceFamily(),made.usages(),made.correlation(),made.sourceState());}
    private static SimilaritySubject withPatterns(SimilaritySubject subject,List<String>patterns){return new SimilaritySubject(subject.subject(),subject.subjectRef(),subject.component(),subject.templateFingerprint(),subject.structuralFamily(),subject.appearanceSignals(),subject.exactDigest(),patterns,subject.candidateOrigins(),subject.semanticAttributeFamily(),subject.usageSourceFamily(),subject.usages(),subject.correlation(),subject.sourceState());}
    private static SimilaritySubject.Correlation correlation(){return new SimilaritySubject.Correlation(SimilaritySubject.Confidence.EXACT,List.of("DECLARATION_REF"),List.of(),List.of(),1);}private static RunDescriptor run(String invocation,int attempt,String dataset,String build){return new RunDescriptor("junit5","PTest","test","PTest#test",invocation,attempt,dataset,"tests-r1",build,"local",null,null,null);}
}
