package io.github.testlens.compatibility.tooling;

import io.github.testlens.compatibility.engine.CompatibilityRunManifest;
import io.github.testlens.compatibility.engine.CompatibilityManifestIdentity;
import io.github.testlens.compatibility.engine.CompatibilityRunManifest.*;
import tools.jackson.core.JsonGenerator;
import tools.jackson.core.ObjectWriteContext;
import tools.jackson.core.json.JsonFactory;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Canonical streaming JSON codec and path-safe atomic local writer for manifest schema V1. */
public final class CompatibilityManifestJson {
    public static final long MAX_DOCUMENT_BYTES=16L*1024*1024;
    private static final JsonFactory FACTORY=JsonFactory.builder().build();
    private final AtomicReplacer replacer;

    public CompatibilityManifestJson(){this(CompatibilityManifestJson::replaceAtomically);}
    CompatibilityManifestJson(AtomicReplacer replacer){this.replacer=java.util.Objects.requireNonNull(replacer);}

    public byte[] write(CompatibilityRunManifest manifest){
        try{BoundedOutput out=new BoundedOutput(MAX_DOCUMENT_BYTES);try(JsonGenerator g=FACTORY.createGenerator(ObjectWriteContext.empty(),out)){writeValue(g,toMap(manifest));g.writeRaw('\n');}return out.bytes();}
        catch(IOException e){throw new ManifestFormatException("Manifest serialization failed",e);}
    }
    public CompatibilityRunManifest read(byte[] bytes){return fromMap(StrictJson.object(bytes));}
    public Path writeDefault(CompatibilityRunManifest manifest,Path projectRoot)throws IOException{return writeTo(manifest,projectRoot,Path.of("target","test-lens","compatibility","runs",fileName(manifest)+".json"));}
    public Path writeTo(CompatibilityRunManifest manifest,Path projectRoot,Path relative)throws IOException{
        if(projectRoot==null)throw new IllegalArgumentException("projectRoot required");Path root=projectRoot.toAbsolutePath().normalize().toRealPath();Path allowed=root.resolve("target").normalize();Path requested=relative==null?Path.of("target","test-lens","compatibility","runs",fileName(manifest)+".json"):relative;if(requested.isAbsolute())throw new IllegalArgumentException("manifest output must be relative");Path destination=root.resolve(requested).normalize();if(!destination.startsWith(allowed))throw new IllegalArgumentException("manifest output must stay under project target/");Files.createDirectories(allowed);Path allowedReal=allowed.toRealPath();Path parent=destination.getParent();Path cursor=allowed;for(Path part:allowed.relativize(parent)){cursor=cursor.resolve(part);if(!Files.exists(cursor))Files.createDirectory(cursor);if(!cursor.toRealPath().startsWith(allowedReal))throw new IllegalArgumentException("manifest output escapes through a link");}if(Files.exists(destination)&&!destination.toRealPath().startsWith(allowedReal))throw new IllegalArgumentException("manifest destination escapes through a link");byte[]data=write(manifest);Path temp=Files.createTempFile(parent,"compatibility-manifest-",".tmp");try{Files.write(temp,data);replacer.replace(temp,destination);}finally{Files.deleteIfExists(temp);}return destination;
    }
    private static String fileName(CompatibilityRunManifest manifest){return "compatibility-manifest-v1-sha256-"+manifest.manifestId().substring(manifest.manifestId().lastIndexOf(':')+1);}
    private static void replaceAtomically(Path temp,Path destination)throws IOException{try{Files.move(temp,destination,StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}catch(AtomicMoveNotSupportedException ignored){Files.move(temp,destination,StandardCopyOption.REPLACE_EXISTING);}}
    @FunctionalInterface interface AtomicReplacer{void replace(Path temp,Path destination)throws IOException;}

    private Map<String,Object> toMap(CompatibilityRunManifest r){Map<String,Object>m=o();m.put("schemaVersion",r.schemaVersion());m.put("manifestAlgorithmVersion",r.manifestAlgorithmVersion());m.put("manifestId",r.manifestId());m.put("testIdentity",testFact(r.testIdentity()));m.put("execution",execution(r.execution()));m.put("browser",browser(r.browser()));m.put("display",display(r.display()));m.put("context",context(r.context()));m.put("configuration",configuration(r.configuration()));m.put("attempts",r.attempts().stream().map(this::attempt).toList());m.put("terminalResult",terminal(r.terminalResult()));m.put("completeness",completeness(r.completeness()));m.put("issues",r.issues().stream().map(this::issue).toList());m.put("evidenceDigests",r.evidenceDigests());return m;}
    private Map<String,Object> testFact(Fact<TestKey>f){Map<String,Object>m=factBase(f);if(f.knowledge()==Knowledge.KNOWN){TestKey x=f.value();Map<String,Object>v=o();v.put("framework",x.framework().name());v.put("testClass",x.testClass());v.put("testMethod",x.testMethod());v.put("logicalTestKey",x.logicalTestKey());v.put("parameterizedOrDynamic",x.parameterizedOrDynamic());v.put("invocationDiscriminator",fact(x.invocationDiscriminator()));v.put("suiteContextDigest",fact(x.suiteContextDigest()));v.put("testIdentityRef",x.testIdentityRef());m.put("value",v);}return m;}
    private Map<String,Object> execution(Execution x){Map<String,Object>m=o();m.put("requestedHeadless",fact(x.requestedHeadless()));m.put("requestedHeadlessProvenance",fact(x.requestedHeadlessProvenance()));m.put("effectiveHeadless",fact(x.effectiveHeadless()));m.put("effectiveHeadlessProvenance",fact(x.effectiveHeadlessProvenance()));m.put("observabilityMode",fact(x.observabilityMode()));m.put("hudPreset",fact(x.hudPreset()));m.put("driverScope",fact(x.driverScope()));m.put("lifecycle",fact(x.lifecycle()));return m;}
    private Map<String,Object> browser(Browser x){Map<String,Object>m=o();m.put("name",fact(x.name()));m.put("version",fact(x.version()));m.put("driverName",fact(x.driverName()));m.put("driverVersion",fact(x.driverVersion()));m.put("platform",fact(x.platform()));m.put("allowlistedCapabilityFacts",x.allowlistedCapabilityFacts());m.put("capabilityDigest",x.capabilityDigest());return m;}
    private Map<String,Object> display(Display x){Map<String,Object>m=o();m.put("windowWidth",fact(x.windowWidth()));m.put("windowHeight",fact(x.windowHeight()));m.put("viewportWidth",fact(x.viewportWidth()));m.put("viewportHeight",fact(x.viewportHeight()));m.put("devicePixelRatio",fact(x.devicePixelRatio()));return m;}
    private Map<String,Object> context(Context x){Map<String,Object>m=o();m.put("datasetDigest",fact(x.datasetDigest()));m.put("environmentDigest",fact(x.environmentDigest()));m.put("testSourceRevision",fact(x.testSourceRevision()));m.put("systemUnderTestRevision",fact(x.systemUnderTestRevision()));m.put("locale",fact(x.locale()));m.put("timezone",fact(x.timezone()));return m;}
    private Map<String,Object> configuration(Configuration x){Map<String,Object>m=o();m.put("liveHud",fact(x.liveHud()));m.put("automaticFeedback",fact(x.automaticFeedback()));m.put("sourceNavigation",fact(x.sourceNavigation()));m.put("passedTraceRetention",fact(x.passedTraceRetention()));m.put("networkCaptureState",fact(x.networkCaptureState()));m.put("semanticConfigurationDigest",x.semanticConfigurationDigest());return m;}
    private Map<String,Object> attempt(Attempt x){Map<String,Object>m=o();m.put("ordinal",x.ordinal());m.put("attemptRef",x.attemptRef());m.put("attemptIdentity",fact(x.attemptIdentity()));m.put("result",x.result().name());m.put("failure",failure(x.failure()));m.put("behavior",behavior(x.behavior()));m.put("timing",timing(x.timing()));m.put("evidence",evidence(x.evidence()));return m;}
    private Map<String,Object> failure(FailureSignature x){Map<String,Object>m=o();m.put("exceptionClass",fact(x.exceptionClass()));m.put("category",fact(x.category()));m.put("operationCategory",fact(x.operationCategory()));m.put("safeSubjectRef",fact(x.safeSubjectRef()));m.put("reasonCodes",x.reasonCodes());m.put("normalizedMessageDigest",fact(x.normalizedMessageDigest()));m.put("phase",x.phase().name());return m;}
    private Map<String,Object> behavior(BehaviorSummary x){Map<String,Object>m=o();m.put("operationRetries",x.operationRetries());m.put("retryTimeMillis",x.retryTimeMillis());m.put("retryReasons",groups(x.retryReasons()));m.put("locators",locators(x.locators()));m.put("waits",waits(x.waits()));m.put("interactions",interactions(x.interactions()));m.put("browserContext",browserContext(x.browserContext()));m.put("authOutcomes",groups(x.authOutcomes()));m.put("uploadOperations",x.uploadOperations());m.put("warnings",groups(x.warnings()));m.put("artifactCount",x.artifactCount());return m;}
    private List<Map<String,Object>> groups(List<GroupCount>g){return g.stream().map(x->{Map<String,Object>m=o();m.put("code",x.code());m.put("count",x.count());return m;}).toList();}
    private Map<String,Object> locators(LocatorSummary x){Map<String,Object>m=o();m.put("observations",x.observations());m.put("resolved",x.resolved());m.put("notFound",x.notFound());m.put("errors",x.errors());m.put("knownCardinalityAnomalies",x.knownCardinalityAnomalies());m.put("durationNanos",x.durationNanos());m.put("outcomes",groups(x.outcomes()));return m;}
    private Map<String,Object> waits(WaitSummary x){Map<String,Object>m=o();m.put("observations",x.observations());m.put("attempts",x.attempts());m.put("timeouts",x.timeouts());m.put("failures",x.failures());m.put("elapsedMillis",x.elapsedMillis());return m;}
    private Map<String,Object> interactions(InteractionSummary x){Map<String,Object>m=o();m.put("observations",x.observations());m.put("recoveries",x.recoveries());m.put("fallbacks",x.fallbacks());m.put("smartClickDetail",x.smartClickDetail().name());m.put("fallbackTypes",groups(x.fallbackTypes()));return m;}
    private Map<String,Object> browserContext(ContextSummary x){Map<String,Object>m=o();m.put("frameOperations",x.frameOperations());m.put("shadowContexts",x.shadowContexts());m.put("newWindowOperations",x.newWindowOperations());m.put("windowSwitches",x.windowSwitches());m.put("contextFailures",x.contextFailures());return m;}
    private Map<String,Object> timing(TimingSummary x){Map<String,Object>m=o();m.put("sampleCount",x.sampleCount());m.put("totalDurationMillis",x.totalDurationMillis());m.put("logicalDurationMillis",fact(x.logicalDurationMillis()));return m;}
    private Map<String,Object> evidence(EvidenceCompleteness x){Map<String,Object>m=o();m.put("retention",x.retention().name());m.put("behavior",x.behavior().name());m.put("locatorObservations",x.locatorObservations());m.put("detailedRetries",x.detailedRetries());m.put("screenshots",x.screenshots());m.put("network",x.network());m.put("viewport",x.viewport());m.put("smartClickDetail",x.smartClickDetail().name());return m;}
    private Map<String,Object> terminal(TerminalResult x){Map<String,Object>m=o();m.put("status",x.status().name());m.put("attemptCount",x.attemptCount());m.put("passedAfterRetry",x.passedAfterRetry());m.put("failedAfterRetry",x.failedAfterRetry());return m;}
    private Map<String,Object> completeness(Completeness x){Map<String,Object>m=o();m.put("testIdentity",x.testIdentity().name());m.put("execution",x.execution().name());m.put("browser",x.browser().name());m.put("display",x.display().name());m.put("context",x.context().name());m.put("behavior",x.behavior().name());m.put("failure",x.failure().name());return m;}
    private Map<String,Object> issue(Issue x){Map<String,Object>m=o();m.put("code",x.code());m.put("severity",x.severity().name());m.put("references",x.references());return m;}
    private Map<String,Object> fact(Fact<?>f){Map<String,Object>m=factBase(f);if(f.knowledge()==Knowledge.KNOWN)m.put("value",f.value() instanceof Enum<?>e?e.name():f.value());return m;}
    private Map<String,Object> factBase(Fact<?>f){Map<String,Object>m=o();m.put("knowledge",f.knowledge().name());m.put("provenance",f.provenance().name());return m;}

    private CompatibilityRunManifest fromMap(Map<String,Object>r){requireKeys(r,List.of("schemaVersion","manifestAlgorithmVersion","manifestId","testIdentity","execution","browser","display","context","configuration","attempts","terminalResult","completeness","issues","evidenceDigests"));int schema=integer(r,"schemaVersion"),algorithm=integer(r,"manifestAlgorithmVersion");if(schema!=1||algorithm!=1)throw new ManifestFormatException("Unsupported manifest version");List<Attempt>attempts=objects(r.get("attempts")).stream().map(this::readAttempt).toList();CompatibilityRunManifest manifest=new CompatibilityRunManifest(schema,algorithm,string(r,"manifestId"),readTestFact(object(r,"testIdentity")),readExecution(object(r,"execution")),readBrowser(object(r,"browser")),readDisplay(object(r,"display")),readContext(object(r,"context")),readConfiguration(object(r,"configuration")),attempts,readTerminal(object(r,"terminalResult")),readCompleteness(object(r,"completeness")),objects(r.get("issues")).stream().map(this::readIssue).toList(),strings(r.get("evidenceDigests")));if(!manifest.manifestId().equals(CompatibilityManifestIdentity.id(manifest)))throw new ManifestFormatException("manifestId does not match semantic content");return manifest;}
    private Fact<TestKey> readTestFact(Map<String,Object>m){rejectUnknown(m,"knowledge","provenance","value");Knowledge k=knowledge(m);Provenance p=provenance(m);if(k!=Knowledge.KNOWN)return new Fact<>(k,null,p);Map<String,Object>v=object(m,"value");rejectUnknown(v,"framework","testClass","testMethod","logicalTestKey","parameterizedOrDynamic","invocationDiscriminator","suiteContextDigest","testIdentityRef");TestKey key=new TestKey(en(v,"framework",Framework.class),string(v,"testClass"),string(v,"testMethod"),string(v,"logicalTestKey"),bool(v,"parameterizedOrDynamic"),stringFact(object(v,"invocationDiscriminator")),stringFact(object(v,"suiteContextDigest")),string(v,"testIdentityRef"));return Fact.known(key,p);}
    private Execution readExecution(Map<String,Object>m){rejectUnknown(m,"requestedHeadless","requestedHeadlessProvenance","effectiveHeadless","effectiveHeadlessProvenance","observabilityMode","hudPreset","driverScope","lifecycle");return new Execution(enumFact(object(m,"requestedHeadless"),RequestedHeadlessMode.class),enumFact(object(m,"requestedHeadlessProvenance"),RequestedHeadlessProvenance.class),enumFact(object(m,"effectiveHeadless"),EffectiveHeadlessState.class),enumFact(object(m,"effectiveHeadlessProvenance"),EffectiveHeadlessProvenance.class),enumFact(object(m,"observabilityMode"),ObservabilityMode.class),enumFact(object(m,"hudPreset"),HudPreset.class),enumFact(object(m,"driverScope"),DriverScope.class),enumFact(object(m,"lifecycle"),Lifecycle.class));}
    private Browser readBrowser(Map<String,Object>m){rejectUnknown(m,"name","version","driverName","driverVersion","platform","allowlistedCapabilityFacts","capabilityDigest");Map<String,String>facts=new java.util.TreeMap<>();object(m,"allowlistedCapabilityFacts").forEach((k,v)->facts.put(k,String.valueOf(v)));return new Browser(stringFact(object(m,"name")),stringFact(object(m,"version")),stringFact(object(m,"driverName")),stringFact(object(m,"driverVersion")),stringFact(object(m,"platform")),facts,string(m,"capabilityDigest"));}
    private Display readDisplay(Map<String,Object>m){rejectUnknown(m,"windowWidth","windowHeight","viewportWidth","viewportHeight","devicePixelRatio");return new Display(intFact(object(m,"windowWidth")),intFact(object(m,"windowHeight")),intFact(object(m,"viewportWidth")),intFact(object(m,"viewportHeight")),doubleFact(object(m,"devicePixelRatio")));}
    private Context readContext(Map<String,Object>m){rejectUnknown(m,"datasetDigest","environmentDigest","testSourceRevision","systemUnderTestRevision","locale","timezone");return new Context(stringFact(object(m,"datasetDigest")),stringFact(object(m,"environmentDigest")),stringFact(object(m,"testSourceRevision")),stringFact(object(m,"systemUnderTestRevision")),stringFact(object(m,"locale")),stringFact(object(m,"timezone")));}
    private Configuration readConfiguration(Map<String,Object>m){rejectUnknown(m,"liveHud","automaticFeedback","sourceNavigation","passedTraceRetention","networkCaptureState","semanticConfigurationDigest");return new Configuration(boolFact(object(m,"liveHud")),boolFact(object(m,"automaticFeedback")),boolFact(object(m,"sourceNavigation")),stringFact(object(m,"passedTraceRetention")),stringFact(object(m,"networkCaptureState")),string(m,"semanticConfigurationDigest"));}
    private Attempt readAttempt(Map<String,Object>m){rejectUnknown(m,"ordinal","attemptRef","attemptIdentity","result","failure","behavior","timing","evidence");return new Attempt(integer(m,"ordinal"),string(m,"attemptRef"),stringFact(object(m,"attemptIdentity")),en(m,"result",ResultStatus.class),readFailure(object(m,"failure")),readBehavior(object(m,"behavior")),readTiming(object(m,"timing")),readEvidence(object(m,"evidence")));}
    private FailureSignature readFailure(Map<String,Object>m){rejectUnknown(m,"exceptionClass","category","operationCategory","safeSubjectRef","reasonCodes","normalizedMessageDigest","phase");return new FailureSignature(stringFact(object(m,"exceptionClass")),stringFact(object(m,"category")),stringFact(object(m,"operationCategory")),stringFact(object(m,"safeSubjectRef")),strings(m.get("reasonCodes")),stringFact(object(m,"normalizedMessageDigest")),en(m,"phase",FailurePhase.class));}
    private BehaviorSummary readBehavior(Map<String,Object>m){rejectUnknown(m,"operationRetries","retryTimeMillis","retryReasons","locators","waits","interactions","browserContext","authOutcomes","uploadOperations","warnings","artifactCount");return new BehaviorSummary(number(m,"operationRetries"),number(m,"retryTimeMillis"),readGroups(m.get("retryReasons")),readLocators(object(m,"locators")),readWaits(object(m,"waits")),readInteractions(object(m,"interactions")),readBrowserContext(object(m,"browserContext")),readGroups(m.get("authOutcomes")),number(m,"uploadOperations"),readGroups(m.get("warnings")),number(m,"artifactCount"));}
    private List<GroupCount>readGroups(Object v){return objects(v).stream().map(m->{rejectUnknown(m,"code","count");return new GroupCount(string(m,"code"),number(m,"count"));}).toList();}
    private LocatorSummary readLocators(Map<String,Object>m){rejectUnknown(m,"observations","resolved","notFound","errors","knownCardinalityAnomalies","durationNanos","outcomes");return new LocatorSummary(number(m,"observations"),number(m,"resolved"),number(m,"notFound"),number(m,"errors"),number(m,"knownCardinalityAnomalies"),number(m,"durationNanos"),readGroups(m.get("outcomes")));}
    private WaitSummary readWaits(Map<String,Object>m){rejectUnknown(m,"observations","attempts","timeouts","failures","elapsedMillis");return new WaitSummary(number(m,"observations"),number(m,"attempts"),number(m,"timeouts"),number(m,"failures"),number(m,"elapsedMillis"));}
    private InteractionSummary readInteractions(Map<String,Object>m){rejectUnknown(m,"observations","recoveries","fallbacks","smartClickDetail","fallbackTypes");return new InteractionSummary(number(m,"observations"),number(m,"recoveries"),number(m,"fallbacks"),en(m,"smartClickDetail",SmartClickDetail.class),readGroups(m.get("fallbackTypes")));}
    private ContextSummary readBrowserContext(Map<String,Object>m){rejectUnknown(m,"frameOperations","shadowContexts","newWindowOperations","windowSwitches","contextFailures");return new ContextSummary(number(m,"frameOperations"),number(m,"shadowContexts"),number(m,"newWindowOperations"),number(m,"windowSwitches"),number(m,"contextFailures"));}
    private TimingSummary readTiming(Map<String,Object>m){rejectUnknown(m,"sampleCount","totalDurationMillis","logicalDurationMillis");return new TimingSummary(number(m,"sampleCount"),number(m,"totalDurationMillis"),longFact(object(m,"logicalDurationMillis")));}
    private EvidenceCompleteness readEvidence(Map<String,Object>m){rejectUnknown(m,"retention","behavior","locatorObservations","detailedRetries","screenshots","network","viewport","smartClickDetail");return new EvidenceCompleteness(en(m,"retention",EvidenceRetention.class),en(m,"behavior",CompletenessState.class),bool(m,"locatorObservations"),bool(m,"detailedRetries"),bool(m,"screenshots"),bool(m,"network"),bool(m,"viewport"),en(m,"smartClickDetail",SmartClickDetail.class));}
    private TerminalResult readTerminal(Map<String,Object>m){rejectUnknown(m,"status","attemptCount","passedAfterRetry","failedAfterRetry");return new TerminalResult(en(m,"status",ResultStatus.class),integer(m,"attemptCount"),bool(m,"passedAfterRetry"),bool(m,"failedAfterRetry"));}
    private Completeness readCompleteness(Map<String,Object>m){rejectUnknown(m,"testIdentity","execution","browser","display","context","behavior","failure");return new Completeness(en(m,"testIdentity",CompletenessState.class),en(m,"execution",CompletenessState.class),en(m,"browser",CompletenessState.class),en(m,"display",CompletenessState.class),en(m,"context",CompletenessState.class),en(m,"behavior",CompletenessState.class),en(m,"failure",CompletenessState.class));}
    private Issue readIssue(Map<String,Object>m){rejectUnknown(m,"code","severity","references");return new Issue(string(m,"code"),en(m,"severity",IssueSeverity.class),strings(m.get("references")));}
    private Fact<String>stringFact(Map<String,Object>m){return readFact(m,v->String.valueOf(v));}private Fact<Integer>intFact(Map<String,Object>m){return readFact(m,v->((Number)v).intValue());}private Fact<Long>longFact(Map<String,Object>m){return readFact(m,v->((Number)v).longValue());}private Fact<Double>doubleFact(Map<String,Object>m){return readFact(m,v->((Number)v).doubleValue());}private Fact<Boolean>boolFact(Map<String,Object>m){return readFact(m,v->(Boolean)v);}private <E extends Enum<E>>Fact<E>enumFact(Map<String,Object>m,Class<E>t){return readFact(m,v->Enum.valueOf(t,String.valueOf(v)));}
    private <T>Fact<T>readFact(Map<String,Object>m,java.util.function.Function<Object,T>convert){rejectUnknown(m,"knowledge","provenance","value");Knowledge k=knowledge(m);Provenance p=provenance(m);if(k!=Knowledge.KNOWN){if(m.containsKey("value"))throw new ManifestFormatException("non-KNOWN fact has value");return new Fact<>(k,null,p);}if(!m.containsKey("value"))throw new ManifestFormatException("KNOWN fact missing value");try{return Fact.known(convert.apply(m.get("value")),p);}catch(RuntimeException e){throw new ManifestFormatException("Invalid fact value",e);}}
    private Knowledge knowledge(Map<String,Object>m){return en(m,"knowledge",Knowledge.class);}private Provenance provenance(Map<String,Object>m){return en(m,"provenance",Provenance.class);}

    private static void writeValue(JsonGenerator g,Object v)throws IOException{if(v==null){g.writeNull();return;}if(v instanceof Map<?,?>m){g.writeStartObject();for(var e:m.entrySet()){g.writeName(String.valueOf(e.getKey()));writeValue(g,e.getValue());}g.writeEndObject();}else if(v instanceof List<?>l){g.writeStartArray();for(Object x:l)writeValue(g,x);g.writeEndArray();}else if(v instanceof String s)g.writeString(s);else if(v instanceof Integer i)g.writeNumber(i);else if(v instanceof Long l)g.writeNumber(l);else if(v instanceof Double d)g.writeNumber(d);else if(v instanceof Boolean b)g.writeBoolean(b);else throw new ManifestFormatException("Unsupported JSON value "+v.getClass());}
    private static Map<String,Object>o(){return new LinkedHashMap<>();}
    @SuppressWarnings("unchecked")private static Map<String,Object>object(Map<String,Object>m,String k){Object v=m.get(k);if(!(v instanceof Map<?,?>))throw new ManifestFormatException("Expected object "+k);return(Map<String,Object>)v;}@SuppressWarnings("unchecked")private static List<Map<String,Object>>objects(Object v){if(!(v instanceof List<?>l))throw new ManifestFormatException("Expected array");List<Map<String,Object>>out=new ArrayList<>();for(Object x:l){if(!(x instanceof Map<?,?>m))throw new ManifestFormatException("Expected object array item");out.add((Map<String,Object>)m);}return out;}
    private static String string(Map<String,Object>m,String k){Object v=m.get(k);if(!(v instanceof String s))throw new ManifestFormatException("Expected string "+k);return s;}private static int integer(Map<String,Object>m,String k){long v=number(m,k);if(v>Integer.MAX_VALUE)throw new ManifestFormatException("Integer overflow "+k);return(int)v;}private static long number(Map<String,Object>m,String k){Object v=m.get(k);if(!(v instanceof Number n))throw new ManifestFormatException("Expected number "+k);return n.longValue();}private static boolean bool(Map<String,Object>m,String k){Object v=m.get(k);if(!(v instanceof Boolean b))throw new ManifestFormatException("Expected boolean "+k);return b;}private static <E extends Enum<E>>E en(Map<String,Object>m,String k,Class<E>t){try{return Enum.valueOf(t,string(m,k));}catch(RuntimeException e){throw new ManifestFormatException("Unknown "+k,e);}}private static List<String>strings(Object v){if(!(v instanceof List<?>l))throw new ManifestFormatException("Expected string array");return l.stream().map(x->{if(!(x instanceof String))throw new ManifestFormatException("Expected string array item");return(String)x;}).toList();}
    private static void requireKeys(Map<String,Object>m,List<String>keys){for(String k:keys)if(!m.containsKey(k))throw new ManifestFormatException("Missing field "+k);for(String k:m.keySet())if(!keys.contains(k)&&!k.startsWith("x-"))throw new ManifestFormatException("Unknown field "+k);}
    private static void rejectUnknown(Map<String,Object>m,String...allowed){List<String>keys=List.of(allowed);for(String key:m.keySet())if(!keys.contains(key))throw new ManifestFormatException("Unknown nested field "+key);}
    public static final class ManifestFormatException extends IllegalArgumentException{public ManifestFormatException(String m){super(m);}public ManifestFormatException(String m,Throwable c){super(m,c);}}
    private static final class BoundedOutput extends OutputStream{private final long max;private final ByteArrayOutputStream out=new ByteArrayOutputStream();BoundedOutput(long max){this.max=max;}@Override public void write(int b)throws IOException{ensure(1);out.write(b);}@Override public void write(byte[]b,int o,int l)throws IOException{ensure(l);out.write(b,o,l);}void ensure(int n)throws IOException{if(out.size()+(long)n>max)throw new IOException("Manifest exceeds 16 MiB");}byte[]bytes(){return out.toByteArray();}}
}
