package io.github.testlens.compatibility.tooling;

import io.github.testlens.compatibility.engine.CompatibilityComparisonReport;
import tools.jackson.core.JsonGenerator;
import tools.jackson.core.ObjectWriteContext;
import tools.jackson.core.json.JsonFactory;

import java.io.IOException;
import java.io.OutputStream;
import java.lang.reflect.InvocationTargetException;
import java.nio.file.*;
import java.util.*;

/** Canonical sanitized streaming JSON writer for compatibility comparison report V1. */
public final class CompatibilityReportJson {
    public static final long MAX_OUTPUT_BYTES=64L*1024*1024;
    private static final JsonFactory FACTORY=JsonFactory.builder().build();
    private final long maximumOutputBytes;

    public CompatibilityReportJson(){this(MAX_OUTPUT_BYTES);}
    CompatibilityReportJson(long maximumOutputBytes){if(maximumOutputBytes<1||maximumOutputBytes>MAX_OUTPUT_BYTES)throw new IllegalArgumentException("invalid report output bound");this.maximumOutputBytes=maximumOutputBytes;}

    public byte[] write(CompatibilityComparisonReport report){
        Objects.requireNonNull(report);try{return BoundedByteRendering.render(maximumOutputBytes,out->render(report,out));}catch(IOException|RuntimeException e){if(limitExceeded(e))throw new ReportFormatException("OUTPUT_LIMIT_EXCEEDED",e);throw new ReportFormatException("Report cannot be serialized",e);}
    }
    public Path writeDefault(CompatibilityComparisonReport report,Path projectRoot)throws IOException{return writeTo(report,projectRoot,Path.of("target","test-lens","compatibility","reports","compatibility-v1.json"));}
    public Path writeTo(CompatibilityComparisonReport report,Path projectRoot,Path relative)throws IOException{Path destination=safeDestination(projectRoot,relative,"compatibility-v1.json");atomic(destination,write(report));return destination;}

    static Path safeDestination(Path projectRoot,Path relative,String defaultName)throws IOException{if(projectRoot==null)throw new IllegalArgumentException("projectRoot required");Path root=projectRoot.toAbsolutePath().normalize().toRealPath();Path allowed=root.resolve("target").normalize();Path rel=relative==null?Path.of("target","test-lens","compatibility","reports",defaultName):relative;if(rel.isAbsolute())throw new IllegalArgumentException("report output must be relative");Path destination=root.resolve(rel).normalize();if(!destination.startsWith(allowed))throw new IllegalArgumentException("report output must stay under project target/");Files.createDirectories(allowed);Path allowedReal=allowed.toRealPath();if(!allowedReal.startsWith(root))throw new IllegalArgumentException("report target escapes project root through a link");Path cursor=allowed;for(Path part:allowed.relativize(destination.getParent())){cursor=cursor.resolve(part);if(!Files.exists(cursor))Files.createDirectory(cursor);if(!cursor.toRealPath().startsWith(allowedReal))throw new IllegalArgumentException("report path escapes through a link");}return destination;}
    static void atomic(Path destination,byte[]bytes)throws IOException{Path temp=Files.createTempFile(destination.getParent(),"compatibility-report-",".tmp");try{Files.write(temp,bytes);try{Files.move(temp,destination,StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}catch(AtomicMoveNotSupportedException ignored){Files.move(temp,destination,StandardCopyOption.REPLACE_EXISTING);}}finally{Files.deleteIfExists(temp);}}
    private static Map<String,Object>summary(CompatibilityComparisonReport r){Map<String,Object>m=new LinkedHashMap<>();m.put("axis",r.intent().axis());m.put("baselineRole",r.intent().baselineRole());m.put("variantRole",r.intent().variantRole());m.put("matched",r.coverage().matched());m.put("regressions",r.coverage().regressions());m.put("behavioralDeltas",r.coverage().behavioralDeltas());return m;}
    private static Map<String,Long>comparability(CompatibilityComparisonReport r){Map<String,Long>m=new TreeMap<>();r.testComparisons().forEach(x->m.merge(x.comparability().status().name(),1L,Long::sum));return m;}
    private static void render(CompatibilityComparisonReport report,OutputStream out)throws IOException{try(JsonGenerator g=FACTORY.createGenerator(ObjectWriteContext.empty(),out)){g.writeStartObject();g.writeNumberProperty("schemaVersion",report.schemaVersion());g.writeNumberProperty("algorithmVersion",report.algorithmVersion());g.writeObjectPropertyStart("engineVersions");g.writeNumberProperty("compareEngine",1);g.writeNumberProperty("manifest",1);g.writeEndObject();g.writeStringProperty("analysisMode",report.analysisMode().name());g.writeName("comparisonIntent");writeValue(g,report.intent());g.writeName("summary");writeValue(g,summary(report));g.writeName("coverage");writeValue(g,report.coverage());g.writeName("comparabilitySummary");writeValue(g,comparability(report));g.writeArrayPropertyStart("configurationDifferences");for(var comparison:report.testComparisons())for(var dimension:comparison.comparability().dimensions())if(dimension.state().name().equals("DIFFERENT")){g.writeStartObject();g.writeStringProperty("dimension",dimension.dimension());g.writeStringProperty("reasonCode",dimension.reasonCode());g.writeStringProperty("testIdentityRef",comparison.testIdentityRef());g.writeEndObject();}g.writeEndArray();g.writeName("testComparisons");writeValue(g,report.testComparisons());g.writeName("findings");writeValue(g,report.findings());g.writeArrayPropertyStart("inconclusiveCases");for(var comparison:report.testComparisons())if(comparison.outcome().name().equals("INCONCLUSIVE")||comparison.outcome().name().equals("NOT_COMPARABLE"))g.writeString(comparison.testIdentityRef());g.writeEndArray();g.writeName("recommendations");writeValue(g,report.recommendations());g.writeName("unmatchedBaseline");writeValue(g,report.unmatchedBaseline());g.writeName("unmatchedVariant");writeValue(g,report.unmatchedVariant());g.writeName("ambiguousMatches");writeValue(g,report.ambiguousMatches());g.writeName("issues");writeValue(g,report.issues());g.writeName("outputLimitations");writeValue(g,report.outputLimitations());g.writeEndObject();g.writeRaw('\n');}}
    private static void writeValue(JsonGenerator g,Object value)throws IOException{if(value==null){g.writeNull();return;}if(value instanceof String s){g.writeString(s);return;}if(value instanceof Integer i){g.writeNumber(i);return;}if(value instanceof Long l){g.writeNumber(l);return;}if(value instanceof Double d){g.writeNumber(d);return;}if(value instanceof Boolean b){g.writeBoolean(b);return;}if(value instanceof Enum<?>e){g.writeString(e.name());return;}if(value instanceof Map<?,?>m){g.writeStartObject();List<? extends Map.Entry<?,?>>entries=new ArrayList<>(m.entrySet());entries.sort(Comparator.comparing(e->String.valueOf(e.getKey())));for(var entry:entries){g.writeName(String.valueOf(entry.getKey()));writeValue(g,entry.getValue());}g.writeEndObject();return;}if(value instanceof Collection<?>c){g.writeStartArray();for(Object x:c)writeValue(g,x);g.writeEndArray();return;}if(value.getClass().isRecord()){g.writeStartObject();for(var component:value.getClass().getRecordComponents())try{g.writeName(component.getName());writeValue(g,component.getAccessor().invoke(value));}catch(IllegalAccessException|InvocationTargetException failure){throw new IOException("Cannot serialize report record",failure);}g.writeEndObject();return;}throw new IOException("Unsupported report value "+value.getClass());}
    private static boolean limitExceeded(Throwable failure){for(Throwable current=failure;current!=null;current=current.getCause())if(current instanceof BoundedByteRendering.LimitExceeded)return true;return false;}
    public static final class ReportFormatException extends RuntimeException{public ReportFormatException(String m){super(m);}public ReportFormatException(String m,Throwable c){super(m,c);}}
}
