package io.github.testlens.compatibility.tooling;

import io.github.testlens.compatibility.engine.StaticCompatibilityReport;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.Objects;

/** Standalone escaped HTML view of the same STATIC report model. */
public final class StaticCompatibilityReportHtml {
    public byte[] write(StaticCompatibilityReport r){Objects.requireNonNull(r);StringBuilder s=new StringBuilder(16384);var c=r.coverage();
        s.append("<!doctype html><html lang=\"en\"><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Test Lens static compatibility evidence</title><style>body{font:14px system-ui;margin:2rem;color:#18202b}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ccd3dc;padding:.45rem;text-align:left;vertical-align:top}select{margin:0 .7rem .8rem 0}.notice{font-weight:700}code{overflow-wrap:anywhere}:focus{outline:3px solid #1565c0}</style><body>");
        s.append("<h1>Static compatibility evidence</h1><p class=\"notice\">Source-only findings are hypotheses, never proof that a test is headless-incompatible.</p><h2>Coverage</h2><p>Parsed ").append(c.filesParsed()).append('/').append(c.javaFiles()).append(" Java files; failed ").append(c.filesFailed()).append("; excluded generated ").append(c.generatedFilesExcluded()).append("; unsupported languages ").append(c.unsupportedLanguages()).append("; symbol issues ").append(c.symbolResolutionIssues()).append(".</p>");
        s.append("<label>Severity <select id=\"severity\"><option value=\"\">all</option></select></label><label>Category <select id=\"category\"><option value=\"\">all</option></select></label><label>Confidence <select id=\"confidence\"><option value=\"\">all</option></select></label><h2>Findings</h2><table><thead><tr><th>Location</th><th>Code</th><th>Category</th><th>Severity</th><th>State/confidence</th><th>Evidence</th><th>Recommendation</th></tr></thead><tbody>");
        for(var f:r.findings())s.append("<tr data-severity=\"").append(e(f.severity().name())).append("\" data-category=\"").append(e(f.category().name())).append("\" data-confidence=\"").append(e(f.confidence().name())).append("\"><td><code>").append(e(f.logicalPath())).append(':').append(f.sourceRange().beginLine()).append("</code><br>").append(e(f.declaringSymbol())).append("</td><td>").append(e(f.code())).append("</td><td>").append(e(f.category().name())).append("</td><td>").append(e(f.severity().name())).append("</td><td>HYPOTHESIS / ").append(e(f.confidence().name())).append("</td><td>").append(e(f.descriptor())).append("</td><td>").append(e(f.recommendation().name())).append("<br>code change: UNKNOWN</td></tr>");
        s.append("</tbody></table><h2>Limitations</h2><p>").append(e(r.limitations().toString())).append("</p><h2>Detector scope</h2><table><thead><tr><th>Code</th><th>Status</th><th>Reason</th></tr></thead><tbody>");for(var d:r.detectorDecisions())s.append("<tr><td>").append(e(d.code())).append("</td><td>").append(e(d.status().name())).append("</td><td>").append(e(d.reason())).append("</td></tr>");
        s.append("</tbody></table><script>(()=>{for(const k of ['severity','category','confidence']){const q='tr[data-'+k+']',rows=[...document.querySelectorAll(q)],sel=document.getElementById(k);for(const v of [...new Set(rows.map(r=>r.dataset[k]))].sort()){const o=document.createElement('option');o.value=v;o.textContent=v;sel.append(o)}sel.addEventListener('change',()=>rows.forEach(r=>r.hidden=!!sel.value&&r.dataset[k]!==sel.value))}})()</script></body></html>\n");byte[]b=s.toString().getBytes(StandardCharsets.UTF_8);if(b.length>StaticCompatibilityReportJson.MAX_OUTPUT_BYTES)throw new CompatibilityReportJson.ReportFormatException("OUTPUT_LIMIT_EXCEEDED");return b;}
    public Path writeDefault(StaticCompatibilityReport r,Path root)throws IOException{Path p=CompatibilityReportJson.safeDestination(root,Path.of("target","test-lens","compatibility","reports","compatibility-static-v1.html"),"compatibility-static-v1.html");CompatibilityReportJson.atomic(p,write(r));return p;}
    private static String e(String x){return CompatibilityReportHtml.e(x);}
}
