package io.github.testlens.migration.tooling;

import io.github.testlens.compatibility.engine.ComparisonIntent;
import io.github.testlens.compatibility.engine.CompatibilityComparisonReport;
import org.junit.jupiter.api.Test;
import java.util.ArrayList;
import java.util.List;

class MigrationVerificationPerformanceHarnessTest {
    @Test void boundedPlanMergeResultSerializationAndComparisonPlanning(){for(int count:new int[]{10,100,512}){List<MigrationVerificationPlan.Requirement>requirements=new ArrayList<>();for(int i=0;i<count;i++)requirements.add(MigrationVerificationPlan.Requirement.create("RUN_DIRECTLY_AFFECTED_TEST",MigrationVerificationPlan.StageType.DIRECT_TESTS,MigrationVerificationPlan.Necessity.REQUIRED,"test-"+i,"test-"+i,MigrationRunPlan.ExecutionMode.CUSTOM_TRUSTED,MigrationProposal.SideEffect.UNKNOWN,MigrationVerificationPlan.Expectation.TEST_PASS,MigrationVerificationPlan.SourceScope.PROJECT_SOURCE,List.of(proposal())));MigrationApplyPlan apply=apply(requirements);long memory=used(),start=System.nanoTime();var plan=MigrationVerificationPlan.create(apply,MigrationApplyTransaction.id(apply),checkpoint(),source(),requirements,List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),null);long merge=System.nanoTime()-start;List<MigrationVerificationResult.StageResult>stages=plan.stages().stream().map(s->new MigrationVerificationResult.StageResult(s.stageRef(),s.type(),s.necessity(),MigrationVerificationResult.StageStatus.PASSED,null,List.of(),List.of())).toList();start=System.nanoTime();var result=MigrationVerificationResult.create(plan.transactionId(),apply.applyPlanId(),plan.verificationPlanId(),checkpoint(),MigrationVerificationResult.Status.VERIFIED,stages,List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),null);byte[]bytes=new MigrationVerificationJson().write(result);long serialization=System.nanoTime()-start;System.out.printf("MIGRATION_S11B2_VERIFY steps=%d mergeMs=%.2f resultMs=%.2f resultBytes=%d memoryDelta=%d%n",count,merge/1e6,serialization/1e6,bytes.length,Math.max(0,used()-memory));}for(int count:new int[]{10,100,1_000}){long start=System.nanoTime();List<MigrationVerificationPlan.ComparisonPlan>comparisons=new ArrayList<>();for(int i=0;i<count;i++)comparisons.add(MigrationVerificationPlan.ComparisonPlan.create(new ComparisonIntent(ComparisonIntent.Axis.BUILD,"before","after"),"baseline-"+i+".json","variant-"+i+".json",List.of(CompatibilityComparisonReport.Outcome.NO_MEANINGFUL_DIFFERENCE),false,true,List.of("finding-"+i),List.of(proposal())));System.out.printf("MIGRATION_S11B2_COMPARE plans=%d planMs=%.2f%n",count,(System.nanoTime()-start)/1e6);}}
    private static MigrationApplyPlan apply(List<MigrationVerificationPlan.Requirement>requirements){return MigrationApplyPlan.create(domain("migration-repository-binding-v1","1"),domain("migration-worktree-binding-v1","2"),domain("migration-proposal-set-v1","3"),List.of(proposal()),domain("migration-decision-ledger-v1","4"),List.of(),List.of(),List.of(),checkpoint(),checkpoint(),List.of(),MigrationVerificationPlan.requirementsDigest(requirements),0,0,"apply/diffs/plan.patch","sha256:"+"5".repeat(64),0,MigrationApplyPlan.MAX_DIFF_BYTES,List.of());}
    private static String proposal(){return domain("migration-proposal-v1","6");}private static String checkpoint(){return domain("migration-checkpoint-v1","7");}private static String source(){return domain("migration-source-state-v1","8");}private static String domain(String d,String seed){return d+":sha256:"+seed.repeat(64);}private static long used(){Runtime r=Runtime.getRuntime();return r.totalMemory()-r.freeMemory();}
}
