package io.github.testlens.migration.tooling;

import org.junit.jupiter.api.Test;
import java.nio.file.Files;import java.nio.file.Path;import java.time.Duration;import java.util.List;import java.util.Map;
import static org.junit.jupiter.api.Assertions.*;

class MigrationArchitectureTest{
 @Test void processEnvironmentAndDispatcherAreClosedAndReadOnly()throws Exception{assertEquals(Map.of("GIT_TERMINAL_PROMPT","0","GIT_OPTIONAL_LOCKS","0","GIT_PAGER","cat","PAGER","cat","LC_ALL","C"),SafeGit.environment());assertEquals(java.util.Set.of("VERSION","ROOT","COMMON_DIR","OBJECT_FORMAT","HEAD_COMMIT","HEAD_TREE","READ_SYMBOLIC_HEAD","STATUS","WORKTREES","INDEX","READ_BLOB","GIT_PATH","SPARSE","CHECK_BRANCH","CHECK_IGNORE"),java.util.Arrays.stream(SafeGit.Operation.values()).map(Enum::name).collect(java.util.stream.Collectors.toSet()));String source=Files.readString(Path.of("src/main/java/io/github/testlens/migration/tooling/SafeGit.java"));for(String forbidden:List.of("case RESET","case CLEAN","case RESTORE","case CHECKOUT","case SWITCH","case ADD","case COMMIT","case STASH","case FETCH","case PULL","case PUSH"))assertFalse(source.contains(forbidden));assertFalse(source.contains("cmd /c"));assertFalse(source.contains("powershell -Command"));assertFalse(source.contains("sh -c"));}
 @Test void moduleHasOnlyJacksonProductionDependencyAndIsDeploySkipped()throws Exception{String pom=Files.readString(Path.of("pom.xml"));assertTrue(pom.contains("<maven.deploy.skip>true</maven.deploy.skip>"));assertTrue(pom.contains("jackson-core"));assertFalse(pom.contains("jgit"));assertFalse(pom.contains("selenium-api"));assertFalse(pom.contains("javaparser"));assertFalse(pom.contains("selector-tooling"));assertFalse(pom.contains("compatibility-tooling"));}
 @Test void boundedRunnerTimesOutAndCapturesArgsSeparately()throws Exception{String java=Path.of(System.getProperty("java.home"),"bin",System.getProperty("os.name","").toLowerCase().contains("win")?"java.exe":"java").toString();Path working=Path.of(".").toAbsolutePath().normalize();var result=new GitProcessRunner().run(List.of(java,"-cp",System.getProperty("java.class.path"),Sleeper.class.getName()),working,Map.of(),Duration.ofMillis(100),1024);assertTrue(result.timedOut());assertEquals(java,result.args().get(0));assertEquals(working,result.workingDirectory());}
 @Test void boundedRunnerMarksOutputOverflow()throws Exception{String java=Path.of(System.getProperty("java.home"),"bin",System.getProperty("os.name","").toLowerCase().contains("win")?"java.exe":"java").toString();var result=new GitProcessRunner().run(List.of(java,"-cp",System.getProperty("java.class.path"),Printer.class.getName()),Path.of(".").toAbsolutePath(),Map.of(),Duration.ofSeconds(5),128);assertTrue(result.outputTruncated());assertEquals(128,result.stdout().length);}
 public static class Sleeper{public static void main(String[]args)throws Exception{Thread.sleep(30_000);}}
 public static class Printer{public static void main(String[]args){System.out.print("x".repeat(4096));}}
}
