package io.github.testlens.migration.tooling;

import org.junit.jupiter.api.Test;
import java.nio.file.Files;import java.nio.file.Path;import java.time.Duration;import java.util.List;import java.util.Map;
import static org.junit.jupiter.api.Assertions.*;

class MigrationArchitectureTest{
 @Test void processEnvironmentAndDispatcherAreClosedAndReadOnly()throws Exception{assertEquals(Map.of("GIT_TERMINAL_PROMPT","0","GIT_OPTIONAL_LOCKS","0","GIT_PAGER","cat","PAGER","cat","LC_ALL","C"),SafeGit.environment());assertEquals(java.util.Set.of("VERSION","ROOT","COMMON_DIR","OBJECT_FORMAT","HEAD_COMMIT","HEAD_TREE","READ_SYMBOLIC_HEAD","STATUS","WORKTREES","INDEX","READ_BLOB","GIT_PATH","SPARSE","CHECK_BRANCH","CHECK_IGNORE"),java.util.Arrays.stream(SafeGit.Operation.values()).map(Enum::name).collect(java.util.stream.Collectors.toSet()));String source=Files.readString(Path.of("src/main/java/io/github/testlens/migration/tooling/SafeGit.java"));for(String forbidden:List.of("case RESET","case CLEAN","case RESTORE","case CHECKOUT","case SWITCH","case ADD","case COMMIT","case STASH","case FETCH","case PULL","case PUSH"))assertFalse(source.contains(forbidden));assertFalse(source.contains("cmd /c"));assertFalse(source.contains("powershell -Command"));assertFalse(source.contains("sh -c"));}
 @Test void moduleHasOnlyApprovedB2DependenciesAndIsDeploySkipped()throws Exception{String pom=Files.readString(Path.of("pom.xml"));assertTrue(pom.contains("<maven.deploy.skip>true</maven.deploy.skip>"));assertTrue(pom.contains("jackson-core"));assertTrue(pom.contains("selector-engine"));assertTrue(pom.contains("selector-tooling"));assertTrue(pom.contains("compatibility-engine"));assertTrue(pom.contains("javaparser-symbol-solver-core"));assertFalse(pom.contains("jgit"));assertFalse(pom.contains("selenium-api"));assertFalse(pom.contains("compatibility-tooling"));assertFalse(pom.contains("selector-lab"));}
 @Test void proposalCodeCannotWriteSourceOrInvokeProcesses()throws Exception{for(String file:List.of("MigrationProposalEngine.java","MigrationProposal.java","MigrationProposalSet.java")){String source=Files.readString(Path.of("src/main/java/io/github/testlens/migration/tooling",file));assertFalse(source.contains("Files.write"));assertFalse(source.contains("Files.move"));assertFalse(source.contains("FileOutputStream"));assertFalse(source.contains("ProcessBuilder"));assertFalse(source.contains("git apply"));assertFalse(source.contains("git checkout"));assertFalse(source.contains("git restore"));}}
 @Test void boundedRunnerTimesOutAndCapturesArgsSeparately()throws Exception{String java=Path.of(System.getProperty("java.home"),"bin",System.getProperty("os.name","").toLowerCase().contains("win")?"java.exe":"java").toString();Path working=Path.of(".").toAbsolutePath().normalize();var result=new GitProcessRunner().run(List.of(java,"-cp",System.getProperty("java.class.path"),Sleeper.class.getName()),working,Map.of(),Duration.ofMillis(100),1024);assertTrue(result.timedOut());assertEquals(java,result.args().get(0));assertEquals(working,result.workingDirectory());}
 @Test void boundedRunnerMarksOutputOverflow()throws Exception{String java=Path.of(System.getProperty("java.home"),"bin",System.getProperty("os.name","").toLowerCase().contains("win")?"java.exe":"java").toString();var result=new GitProcessRunner().run(List.of(java,"-cp",System.getProperty("java.class.path"),Printer.class.getName()),Path.of(".").toAbsolutePath(),Map.of(),Duration.ofSeconds(5),128);assertTrue(result.outputTruncated());assertEquals(128,result.stdout().length);}
 @Test void b3RunnerAndIsolationCannotWriteSourceOrUseAShell()throws Exception{String runner=Files.readString(Path.of("src/main/java/io/github/testlens/migration/tooling/MigrationTrustedProcessRunner.java")),orchestrator=Files.readString(Path.of("src/main/java/io/github/testlens/migration/tooling/MigrationRunOrchestrator.java")),isolation=Files.readString(Path.of("src/main/java/io/github/testlens/migration/tooling/MigrationGitIsolationService.java"));assertTrue(runner.contains("new ProcessBuilder(command)"));for(String source:List.of(runner,orchestrator,isolation)){assertFalse(source.contains("Runtime.exec"));assertFalse(source.contains("cmd /c"));assertFalse(source.contains("powershell -Command"));assertFalse(source.contains("sh -c"));assertFalse(source.contains("Files.write("));assertFalse(source.contains("FileOutputStream"));}assertTrue(isolation.contains("enum MutationOperation"));assertFalse(isolation.contains("executeGit(List<String>"));}
 @Test void onlyStateStoreAndControlledApplyWriterCanWriteOrMoveFiles()throws Exception{Path root=Path.of("src/main/java/io/github/testlens/migration/tooling");try(var files=Files.list(root)){for(Path file:files.filter(x->x.toString().endsWith(".java")).toList()){String source=Files.readString(file);if(source.contains("Files.write(")||source.contains("Files.move("))assertTrue(List.of("MigrationStateStore.java","MigrationSourceTransactionWriter.java").contains(file.getFileName().toString()),file.toString());if(!file.getFileName().toString().equals("MigrationSourceTransactionWriter.java")){assertFalse(source.contains("git apply"));assertFalse(source.contains("git checkout"));assertFalse(source.contains("git restore"));assertFalse(source.contains("git reset"));}}}}
 @Test void finalReportingIsReadOnlyAndHasNoGitCommitBoundary()throws Exception{for(String file:List.of("MigrationApplyReportingService.java","MigrationApplyReportHtml.java","MigrationRecoveryActionPlan.java")){String source=Files.readString(Path.of("src/main/java/io/github/testlens/migration/tooling",file));assertFalse(source.contains("ProcessBuilder"));assertFalse(source.contains("Runtime.exec"));assertFalse(source.contains("Files.write("));assertFalse(source.contains("Files.move("));assertFalse(source.contains("git add"));assertFalse(source.contains("git commit"));assertFalse(source.contains("git push"));}}
 public static class Sleeper{public static void main(String[]args)throws Exception{Thread.sleep(30_000);}}
 public static class Printer{public static void main(String[]args){System.out.print("x".repeat(4096));}}
}
