package io.github.testlens.migration.tooling;

import io.github.testlens.selector.tooling.TrustedSelectorSourceProjection;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;

class MigrationApplyReportingServiceTest{
    @TempDir Path temporary;
    @Test void verifiedApplyProducesDeterministicSanitizedReportAndManualCommitReadiness()throws Exception{
        Fixture f=fixture("verified",false);Prepared p=applied(f);MigrationApplyReportingService service=new MigrationApplyReportingService();var first=service.generate(input(f,p));var second=service.generate(input(f,p));MigrationApplyReport r=first.report();assertEquals(MigrationApplyReport.Status.APPLIED_VERIFIED,r.status());assertEquals(MigrationApplyReport.CurrentStateRelation.MATCHES_VERIFIED_STATE,r.currentStateRelation());assertEquals(MigrationCommitReadiness.State.COMMIT_READY_MANUAL,r.commitReadiness().state());assertEquals(first.report().reportId(),second.report().reportId());assertArrayEquals(read(f.store(),first.jsonRef()),read(f.store(),second.jsonRef()));assertTrue(r.files().get(0).rollbackState()==MigrationApplyReport.RollbackState.AVAILABLE);assertTrue(r.transactionEvents().stream().anyMatch(x->x.type()==MigrationApplyTransaction.EventType.VERIFICATION_PENDING));String json=Files.readString(f.store().root().resolve(first.jsonRef()));assertFalse(json.contains("By.cssSelector"));assertFalse(json.contains("@@"));assertFalse(json.contains(f.repo().toAbsolutePath().toString()));String html=Files.readString(f.store().root().resolve(first.htmlRef()));assertFalse(html.contains("<button"));assertFalse(html.contains("<script"));assertFalse(html.contains("onclick"));assertTrue(html.contains("Exact hunks are local-sensitive"));assertEquals("&lt;script&gt;&amp;&quot;&#39;",MigrationApplyReportHtml.e("<script>&\"'"));MigrationApplyReportJson codec=new MigrationApplyReportJson();assertEquals(r,codec.read(codec.write(r)));String duplicate=new String(codec.write(r),StandardCharsets.UTF_8).replaceFirst("\\{","{\"schemaVersion\":1,");assertThrows(IllegalArgumentException.class,()->codec.read(duplicate.getBytes(StandardCharsets.UTF_8)));String unknown=new String(codec.write(r),StandardCharsets.UTF_8).replaceFirst("\\{","{\"unknown\":1,");assertThrows(IllegalArgumentException.class,()->codec.read(unknown.getBytes(StandardCharsets.UTF_8)));
    }
    @Test void historicalVerificationSurvivesCurrentDivergenceAndRollbackRemainsGuarded()throws Exception{
        Fixture f=fixture("diverged",false);Prepared p=applied(f);Files.writeString(f.source(),Files.readString(f.source())+"// later user edit\n",StandardCharsets.UTF_8);MigrationApplyReport r=new MigrationApplyReportingService().generate(input(f,p)).report();assertEquals(MigrationApplyReport.Status.CURRENT_STATE_DIVERGED,r.status());assertEquals(MigrationApplyReport.CurrentStateRelation.USER_MODIFIED_AFTER_APPLY,r.currentStateRelation());assertEquals(MigrationVerificationResult.Status.VERIFIED,r.verification().status());assertEquals(MigrationApplyReport.RollbackState.BLOCKED_USER_MODIFICATION,r.files().get(0).rollbackState());assertEquals(MigrationCommitReadiness.State.COMMIT_BLOCKED,r.commitReadiness().state());assertTrue(r.nextActions().contains(MigrationApplyReport.NextAction.REVIEW_USER_MODIFICATIONS));
    }
    @Test void rollbackRestoresOriginalAndPreDirtyBytesRequireManualCommitReview()throws Exception{
        Fixture clean=fixture("rollback",false);Prepared p=applied(clean);var rolled=clean.apply().rollback(p.applied().transactionId(),clean.repo(),clean.store(),rollbackAuth(p.plan(),p.applied().transactionId()));assertEquals(MigrationRollbackResult.Status.ROLLED_BACK,rolled.status());MigrationApplyReport rr=new MigrationApplyReportingService().generate(input(clean,p)).report();assertEquals(MigrationApplyReport.Status.ROLLED_BACK,rr.status());assertEquals(MigrationApplyReport.CurrentStateRelation.RESTORED_TO_ORIGINAL,rr.currentStateRelation());assertEquals(MigrationCommitReadiness.State.COMMIT_BLOCKED,rr.commitReadiness().state());Fixture dirty=fixture("pre-dirty",true);Prepared dp=applied(dirty);MigrationApplyReport dr=new MigrationApplyReportingService().generate(input(dirty,dp)).report();assertTrue(dr.files().get(0).preDirtyTouched());assertEquals(MigrationCommitReadiness.State.MANUAL_COMMIT_REQUIRES_REVIEW,dr.commitReadiness().state());assertTrue(Files.readString(dirty.source()).contains("user-preserved"));
    }
    @Test void recoveryActionsAndS12GapsRemainStructuredAndNeverClaimProviderSuccess(){var tx="migration-apply-transaction-v1:sha256:"+"a".repeat(64);var partial=new MigrationRecoveryPlan(tx,MigrationRecoveryPlan.Situation.ROLLBACK_PARTIALLY_BLOCKED,List.of(new MigrationRecoveryPlan.FileState("src/A.java",MigrationRecoveryPlan.TargetState.UNKNOWN_MODIFIED,"sha256:"+"b".repeat(64))),null,List.of("USER_MODIFIED"));var action=MigrationRecoveryActionPlan.from(partial);assertEquals(List.of(MigrationRecoveryActionPlan.Action.ROLLBACK_TOOL_CHANGES,MigrationRecoveryActionPlan.Action.MANUAL_RECOVERY),action.actions());ReleaseHardeningHandoff h=ReleaseHardeningHandoff.current();assertTrue(h.gaps().stream().anyMatch(x->x.gapCode().equals("BROWSERSTACK_NOT_RUN")&&x.status()==MigrationReleaseGap.Status.NOT_RUN));assertTrue(h.gaps().stream().anyMatch(x->x.gapCode().equals("WINDOWS_SYMLINK_FIXTURE_SKIPPED")));assertTrue(h.gaps().stream().anyMatch(x->x.gapCode().equals("REACTOR_VERSION_SCRIPT_EPHEMERAL_TARGET_PATH_ISSUE")));assertTrue(h.maintenanceTasks().stream().anyMatch(x->x.contains("PATCH_RELEASE_LANE")&&x.contains("0.4.1-SNAPSHOT")&&x.contains("0.4.2-SNAPSHOT")));}
    private Prepared applied(Fixture f)throws Exception{MigrationApplyPlan plan=f.apply().prepare(new MigrationApplyService.PreparationInput(f.repo(),f.set(),f.ledger(),List.of(f.proposal().proposalId()),List.of(),f.checkpoint(),f.proposal().evidenceRefs(),f.store())).plan();MigrationApplyResult applied=f.apply().apply(plan,f.repo(),f.store(),applyAuth(plan),null);assertEquals(MigrationApplyResult.Status.APPLIED,applied.status());MigrationCheckpoint post=checkpoint(f.store(),applied.postApplyCheckpointRef());List<MigrationVerificationPlan.Requirement>requirements=MigrationVerificationPlan.requirements(List.of(f.proposal()));MigrationVerificationPlan verification=MigrationVerificationPlan.create(plan,applied.transactionId(),post.checkpointId(),post.sourceState().sourceStateDigest(),requirements,List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),null);List<MigrationVerificationResult.StageResult>stages=verification.stages().stream().map(x->new MigrationVerificationResult.StageResult(x.stageRef(),x.type(),x.necessity(),MigrationVerificationResult.StageStatus.PASSED,null,List.of(),List.of())).toList();var proposalResult=new MigrationVerificationResult.ProposalResult(f.proposal().proposalId(),MigrationVerificationResult.ProposalStatus.VERIFIED,stages.stream().map(MigrationVerificationResult.StageResult::stageRef).toList(),List.of());MigrationVerificationResult result=MigrationVerificationResult.create(applied.transactionId(),plan.applyPlanId(),verification.verificationPlanId(),post.checkpointId(),MigrationVerificationResult.Status.VERIFIED,stages,List.of(),List.of(),List.of(),List.of(proposalResult),List.of(),List.of(),null);return new Prepared(plan,applied,verification,result);}
    private MigrationApplyReportingService.Input input(Fixture f,Prepared p){return new MigrationApplyReportingService.Input(p.plan(),p.applied(),f.set(),f.checkpoint(),p.verification(),List.of(p.result()),p.result().verificationResultId(),f.repo(),f.store(),ReleaseHardeningHandoff.current());}
    private Fixture fixture(String name,boolean dirty)throws Exception{Path repo=temporary.resolve(name);Files.createDirectory(repo);git(repo,"init");git(repo,"config","user.email","test@example.invalid");git(repo,"config","user.name","Test");Files.writeString(repo.resolve(".gitignore"),"target/\n",StandardCharsets.UTF_8);Path source=repo.resolve("src/p/Page.java");Files.createDirectories(source.getParent());Files.writeString(source,"package p; import org.openqa.selenium.By; class Page { static final By SAVE = By.id(\"old\"); }\n",StandardCharsets.UTF_8);git(repo,"add","--all");git(repo,"commit","-m","base");if(dirty)Files.writeString(source,Files.readString(source)+"// user-preserved\n",StandardCharsets.UTF_8);MigrationGitService gs=new MigrationGitService();var inspected=gs.inspect(repo);MigrationStateStore store=MigrationStateStore.resolve(gs,inspected,temporary.resolve(name+"-state"));var config=MigrationCheckpoint.Configuration.create(MigrationIsolationPlan.Choice.USE_CURRENT_WORKTREE,MigrationCheckpoint.IntendedMode.MIGRATION_REVIEW,store.storage());var checkpoint=MigrationCheckpoint.create(inspected.preflight(),inspected.sourceState(),config,List.of(),null,null);store.write(checkpoint);var declaration=TrustedSelectorSourceProjection.scan(repo,List.of(Path.of("src")),List.of()).declarations().get(0);var candidate=new TrustedCandidateMaterial(declaration.declarationRef(),"candidate","css selector","[data-testid=\"save\"]","trusted-analysis",TrustedCandidateMaterial.ValidationState.VERIFIED_IN_SCOPE,TrustedCandidateMaterial.TargetComparison.SAME_TARGET,TrustedCandidateMaterial.Intent.FIND_ONE,1,true,false,false,List.of(),"sha256:"+"a".repeat(64));MigrationProposal proposal=new MigrationProposalEngine().planLocator(new MigrationProposalEngine.Input(repo,declaration,null,candidate,List.of(),inspected.preflight().repositoryBindingRef(),inspected.preflight().worktreeBindingRef(),checkpoint.checkpointId()));MigrationProposalSet set=MigrationProposalSet.create(checkpoint.checkpointId(),null,List.of(proposal),List.of(),MigrationProposalSet.Completeness.COMPLETE,List.of());var decision=MigrationDecisionLedger.decide(proposal,checkpoint.checkpointId(),MigrationDecisionLedger.Decision.APPROVE_FOR_S11,"host",null,null);return new Fixture(repo,source,store,checkpoint,proposal,set,MigrationDecisionLedger.create(List.of(decision)),new MigrationApplyService());}
    private static byte[]read(MigrationStateStore store,String ref)throws Exception{return Files.readAllBytes(store.root().resolve(ref));}private static MigrationCheckpoint checkpoint(MigrationStateStore store,String id)throws Exception{return store.read(store.root().resolve("checkpoints/"+id.replace(':','-')+".json"));}private static MigrationTargetedAuthorization applyAuth(MigrationApplyPlan p){return MigrationTargetedAuthorization.of(p.applyPlanId(),p.repositoryBindingRef(),p.worktreeBindingRef(),"host",MigrationTargetedAuthorization.Capability.APPLY_APPROVED_SOURCE_CHANGES);}private static MigrationTargetedAuthorization rollbackAuth(MigrationApplyPlan p,String tx){return MigrationTargetedAuthorization.of(tx,p.repositoryBindingRef(),p.worktreeBindingRef(),"host",MigrationTargetedAuthorization.Capability.ROLLBACK_TOOL_CHANGES);}private static void git(Path repo,String...args)throws Exception{var command=new java.util.ArrayList<String>();command.add("git");command.addAll(List.of(args));Process p=new ProcessBuilder(command).directory(repo.toFile()).redirectErrorStream(true).start();String out=new String(p.getInputStream().readAllBytes(),StandardCharsets.UTF_8);assertEquals(0,p.waitFor(),out);}
    private record Fixture(Path repo,Path source,MigrationStateStore store,MigrationCheckpoint checkpoint,MigrationProposal proposal,MigrationProposalSet set,MigrationDecisionLedger ledger,MigrationApplyService apply){}private record Prepared(MigrationApplyPlan plan,MigrationApplyResult applied,MigrationVerificationPlan verification,MigrationVerificationResult result){}
}
