package io.github.testlens.migration.tooling;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

class MigrationOrchestrationPerformanceHarnessTest {
    @TempDir Path temp;
    @Test void recordsRunnerArtifactAndLedgerDiagnostics()throws Exception{String binding="migration-worktree-binding-v1:sha256:"+"1".repeat(64),checkpoint="migration-checkpoint-v1:sha256:"+"2".repeat(64);Path state=temp.resolve("state"),project=temp.resolve("project");Files.createDirectories(state);Files.createDirectories(project);for(int count:new int[]{100,1_000}){List<MigrationRunPlan.ExpectedArtifact>expected=new ArrayList<>();for(int i=0;i<count;i++){String logical="artifacts/a"+i+".txt";Path p=state.resolve(logical);Files.createDirectories(p.getParent());Files.writeString(p,"v"+i);expected.add(new MigrationRunPlan.ExpectedArtifact(logical,MigrationRunPlan.ArtifactRoot.STATE_ROOT,MigrationRunPlan.ArtifactFreshness.MAY_REUSE,MigrationRunPlan.ArtifactKind.GENERIC,1024,null));}MigrationRunPlan plan=MigrationRunPlan.create("trusted-java",List.of("-version"),binding,Map.of(),List.of(),Duration.ofSeconds(5),MigrationRunPlan.OutputBounds.defaults(),expected,MigrationRunPlan.ExecutionMode.CUSTOM_TRUSTED,MigrationRunPlan.Scope.CUSTOM_TRUSTED,MigrationRunPlan.SideEffectClassification.READ_ONLY,checkpoint,MigrationRunPlan.BaselineRole.VARIANT);MigrationRunArtifactValidator validator=new MigrationRunArtifactValidator();long memory=used(),start=System.nanoTime();var before=validator.snapshot(plan,project,state);long snapshot=System.nanoTime()-start;start=System.nanoTime();var results=validator.validate(plan,project,state,before);long validation=System.nanoTime()-start;start=System.nanoTime();byte[]json=new MigrationArtifactJson().write(plan);long serialization=System.nanoTime()-start;System.out.printf("MIGRATION_B3_ARTIFACTS count=%d snapshotMs=%.1f validateMs=%.1f serializeMs=%.1f memoryDelta=%d planBytes=%d validated=%d%n",count,snapshot/1e6,validation/1e6,serialization/1e6,Math.max(0,used()-memory),json.length,results.size());}
        Path java=Path.of(System.getProperty("java.home"),"bin",System.getProperty("os.name","").toLowerCase().contains("win")?"java.exe":"java");MigrationRunPlan startup=MigrationRunPlan.create("trusted-java",List.of("-version"),binding,Map.of(),List.of(),Duration.ofSeconds(5),new MigrationRunPlan.OutputBounds(1024*1024,1024*1024),List.of(),MigrationRunPlan.ExecutionMode.CUSTOM_TRUSTED,MigrationRunPlan.Scope.CUSTOM_TRUSTED,MigrationRunPlan.SideEffectClassification.READ_ONLY,checkpoint,MigrationRunPlan.BaselineRole.VARIANT);long start=System.nanoTime();var raw=new MigrationTrustedProcessRunner().run(startup,new MigrationTrustedProcessRunner.LocalExecution("trusted-java",java,temp,binding,null),MigrationAuthorization.of("performance",MigrationAuthorization.Capability.EXECUTE_PROJECT_TEST_COMMAND,MigrationAuthorization.Capability.RUN_READ_ONLY_TEST),()->false);System.out.printf("MIGRATION_B3_PROCESS startupMs=%.1f stdoutBytes=%d stderrBytes=%d status=%s%n",(System.nanoTime()-start)/1e6,raw.stdoutCount(),raw.stderrCount(),raw.status());
        List<MigrationRunLedger.Entry>entries=new ArrayList<>();for(int i=0;i<1_000;i++)entries.add(new MigrationRunLedger.Entry(startup.planId(),"migration-run-result-v1:sha256:"+String.format("%064x",i),MigrationRunPlan.BaselineRole.VARIANT,checkpoint,checkpoint,List.of("sha256:"+String.format("%064x",i)),MigrationRunResult.Status.SUCCESS,List.of()));start=System.nanoTime();MigrationRunLedger ledger=MigrationRunLedger.create(entries,MigrationRunLedger.OrchestrationState.EVIDENCE_READY,List.of());byte[]ledgerJson=new MigrationArtifactJson().write(ledger);System.out.printf("MIGRATION_B3_LEDGER entries=1000 buildWriteMs=%.1f bytes=%d%n",(System.nanoTime()-start)/1e6,ledgerJson.length);}
    private static long used(){Runtime r=Runtime.getRuntime();return r.totalMemory()-r.freeMemory();}
}
