package io.github.testlens.application.tooling.ai.workflow;

import io.github.testlens.application.tooling.ai.AgentContextPack;
import io.github.testlens.application.tooling.ai.AgentTask;
import io.github.testlens.application.tooling.ai.CodeReviewResult;
import io.github.testlens.application.tooling.ai.ContractHeader;
import io.github.testlens.application.tooling.ai.FailureClassification;
import io.github.testlens.application.tooling.ai.TestImplementationProposal;
import io.github.testlens.application.tooling.ai.TestPlan;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.assertThrows;

class AgentWorkflowCoordinatorTest {
    @TempDir Path temporaryDirectory;
    @Test void runsScriptedPlanImplementationCompileExecutionAndReview() throws Exception {
        AtomicInteger executions = new AtomicInteger();
        var result = coordinator(scripted(plan(), implementation(validSource()), review()),
                (request, output) -> {
                    executions.incrementAndGet();
                    Class<?> generated = output.loadClass(request.testClass(), getClass().getClassLoader());
                    assertEquals("agent-bytecode", generated.getMethod("execute").invoke(null));
                    return new TargetedTestExecutor.ExecutionResult(true, 1, List.of("generated bytecode executed"));
                }, 2)
                .run("run-success", request(), context());

        assertEquals(TestEngineeringRun.State.SUCCESS, result.run().state());
        assertEquals(1, executions.get());
        assertEquals(3, result.metrics().agentAttempts());
        assertEquals(1, result.metrics().compileAttempts());
        assertEquals(1, result.metrics().executionAttempts());
        assertTrue(result.steps().stream().anyMatch(step -> step.name().equals("POLICY_VALIDATION")
                && step.status() == AgentWorkflowCoordinator.Status.PASS));
        assertEquals("REVIEW", result.steps().get(result.steps().size() - 1).name());
        WorkflowReport report = result.toWorkflowReport(777, List.of("fixture execution"));
        assertEquals(777, report.metrics().contextBytes());
        assertEquals(TestEngineeringRun.State.SUCCESS, report.finalState());
        assertEquals(result.steps().size(), report.steps().size());
        assertTrue(report.json().length > 0);
    }

    @Test void policyViolationStopsBeforeCompileAndExecution() throws Exception {
        AtomicInteger executions = new AtomicInteger();
        var result = coordinator(scripted(plan(), implementation("final class GeneratedTest { Object x = By.id(\"x\"); }")),
                (request, output) -> { executions.incrementAndGet(); return new TargetedTestExecutor.ExecutionResult(true, 1, List.of()); }, 2)
                .run("run-policy", request(), context());

        assertEquals(TestEngineeringRun.State.FAILED, result.run().state());
        assertEquals(0, executions.get());
        assertEquals(0, result.metrics().compileAttempts());
        assertTrue(result.steps().stream().anyMatch(step -> step.name().equals("POLICY_VALIDATION")
                && step.status() == AgentWorkflowCoordinator.Status.FAIL));
    }

    @Test void exhaustedCompilationAttemptsStopExecution() throws Exception {
        AtomicInteger executions = new AtomicInteger();
        var result = coordinator(scripted(plan(), implementation("final class GeneratedTest { MissingType missing; }")),
                (request, output) -> { executions.incrementAndGet(); return new TargetedTestExecutor.ExecutionResult(true, 1, List.of()); }, 1)
                .run("run-compile-fail", request(), context());

        assertEquals(TestEngineeringRun.State.NEEDS_HUMAN_REVIEW, result.run().state());
        assertEquals(0, executions.get());
        assertEquals(1, result.metrics().compileAttempts());
        assertEquals(2, result.metrics().agentAttempts());
    }

    @Test void boundedCorrectionCanReplaceBrokenImplementation() throws Exception {
        AtomicInteger executions = new AtomicInteger();
        var result = coordinator(scripted(plan(), implementation("final class GeneratedTest { MissingType missing; }"),
                        implementation(validSource()), review()),
                (request, output) -> { executions.incrementAndGet(); return new TargetedTestExecutor.ExecutionResult(true, 1, List.of("pass")); }, 2)
                .run("run-corrected", request(), context());

        assertEquals(TestEngineeringRun.State.SUCCESS, result.run().state());
        assertEquals(1, executions.get());
        assertEquals(2, result.metrics().compileAttempts());
        assertEquals(4, result.metrics().agentAttempts());
        assertEquals(1, result.run().metrics().corrections());
    }

    @Test void failedExecutionRoutesToClassificationWithoutCallingReviewerOrApplyingSource() throws Exception {
        var result = coordinator(scripted(plan(), implementation(validSource())),
                (request, output) -> new TargetedTestExecutor.ExecutionResult(false, 1, List.of("assertion failed")), 2)
                .run("run-execution-fail", request(), context());

        assertEquals(TestEngineeringRun.State.NEEDS_HUMAN_REVIEW, result.run().state());
        assertEquals(2, result.metrics().agentAttempts());
        assertEquals(1, result.metrics().executionAttempts());
        assertFalse(result.steps().stream().anyMatch(step -> step.name().equals("REVIEW")));
        assertTrue(result.steps().stream().anyMatch(step -> step.name().equals("FAILURE_CLASSIFIED")));
    }

    @Test void rejectsStructuredAgentResultWithNonActionableContractStatus() {
        TestPlan blocked = new TestPlan(new ContractHeader(ContractHeader.SCHEMA_VERSION,
                ContractHeader.Status.BLOCKED, List.of(), List.of("missing application knowledge"),
                ContractHeader.Confidence.UNKNOWN), List.of());
        AgentExecutor.AgentExecutionException failure = assertThrows(AgentExecutor.AgentExecutionException.class,
                () -> coordinator(scripted(blocked), (request, output) ->
                                new TargetedTestExecutor.ExecutionResult(true, 1, List.of()), 2)
                        .run("run-blocked-plan", request(), context()));

        assertEquals(AgentExecutor.AgentFailureCode.AGENT_OUTPUT_INVALID, failure.code());
    }

    @Test void swallowedAssertionProposalFailsPolicyBeforeCompileExecutionOrSourceApplication() throws Exception {
        AtomicInteger executions = new AtomicInteger();
        Path generated = temporaryDirectory.resolve("example/GeneratedTest.java");
        String swallowing = """
                package example;
                public final class GeneratedTest {
                  public static void execute() {
                    try { throw new AssertionError("failed"); }
                    catch (AssertionError ignored) { System.err.println("ignored"); }
                  }
                }
                """;
        var result = coordinator(scripted(plan(), implementation(swallowing), review()),
                (request, output) -> { executions.incrementAndGet(); return new TargetedTestExecutor.ExecutionResult(true, 1, List.of()); }, 2)
                .run("run-swallowed-assertion", request(), context());

        assertEquals(TestEngineeringRun.State.FAILED, result.run().state());
        assertEquals(0, result.metrics().compileAttempts());
        assertEquals(0, result.metrics().executionAttempts());
        assertEquals(0, executions.get());
        AgentWorkflowCoordinator.Step policy = result.steps().stream()
                .filter(step -> step.name().equals("POLICY_VALIDATION")).findFirst().orElseThrow();
        assertEquals(AgentWorkflowCoordinator.Status.FAIL, policy.status());
        assertFalse(policy.summary().isBlank());
        WorkflowReport report = result.toWorkflowReport(0, List.of());
        assertTrue(report.steps().stream().anyMatch(step -> step.name().equals("POLICY_VALIDATION")
                && step.status() == WorkflowReport.Status.FAIL && !step.summary().isBlank()));
        assertFalse(Files.exists(generated), "the coordinator validates and compiles in memory; it must not claim source application");
    }

    @Test void correctedFinalSourceIsRevalidatedBeforeItsCompile() throws Exception {
        AtomicInteger executions = new AtomicInteger();
        String unsafeCorrection = """
                package example;
                public final class GeneratedTest {
                  public static void execute() {
                    try { throw new AssertionError("failed"); } catch (AssertionError ignored) { }
                  }
                }
                """;
        var result = coordinator(scripted(plan(), implementation("package example; final class GeneratedTest { MissingType missing; }"),
                        implementation(unsafeCorrection), review()),
                (request, output) -> { executions.incrementAndGet(); return new TargetedTestExecutor.ExecutionResult(true, 1, List.of()); }, 2)
                .run("run-unsafe-correction", request(), context());

        assertEquals(TestEngineeringRun.State.FAILED, result.run().state());
        assertEquals(1, result.metrics().compileAttempts(), "only the first, policy-safe source reaches compilation");
        assertEquals(0, result.metrics().executionAttempts());
        assertEquals(0, executions.get());
        assertEquals(2, result.steps().stream().filter(step -> step.name().equals("POLICY_VALIDATION")).count());
        assertEquals(AgentWorkflowCoordinator.Status.FAIL, result.steps().stream()
                .filter(step -> step.name().equals("POLICY_VALIDATION")).reduce((a, b) -> b).orElseThrow().status());
    }

    @Test void pageObjectStyleSourceCompilesExecutesAndRealAssertionFailureRemainsFailed() throws Exception {
        String source = """
                package example;
                public final class GeneratedTest {
                  static final class LoginPage { boolean errorVisible() { return true; } }
                  public static String execute() {
                    LoginPage page = new LoginPage();
                    if (!page.errorVisible()) throw new AssertionError("error not visible");
                    return "page-object-bytecode";
                  }
                }
                """;
        var result = coordinator(scripted(plan(), implementation(source)),
                (request, output) -> {
                    Class<?> generated = output.loadClass(request.testClass(), getClass().getClassLoader());
                    assertEquals("page-object-bytecode", generated.getMethod("execute").invoke(null));
                    return new TargetedTestExecutor.ExecutionResult(false, 1, List.of("assertion failed"));
                }, 2).run("run-real-assertion", request(), context());

        assertEquals(TestEngineeringRun.State.NEEDS_HUMAN_REVIEW, result.run().state());
        assertEquals(1, result.metrics().compileAttempts());
        assertEquals(1, result.metrics().executionAttempts());
        assertTrue(result.steps().stream().anyMatch(step -> step.name().equals("EXECUTION_FAIL")));
    }

    private static AgentWorkflowCoordinator coordinator(AgentExecutor executor, CompiledTargetedTestExecutor tests,
                                                        int maxAttempts) {
        return new AgentWorkflowCoordinator(new TestEngineeringWorkflow(WorkflowPolicy.defaults()), executor,
                new TargetedJavaCompiler(), tests,
                new GeneratedTestPolicyValidator(GeneratedTestPolicyValidator.Policy.defaults()),
                execution -> new FailureClassification(ready(), FailureClassification.Category.UNKNOWN,
                        "unclassified", execution.traceEvidenceRefs(), List.of(), List.of()),
                AgentWorkflowCoordinator.Stabilizer.none(),
                new AgentWorkflowCoordinator.Configuration(Path.of("src/test/java/example/GeneratedTest.java"),
                        "example.GeneratedTest", null, 17, "", 10, Duration.ofSeconds(5),
                        List.of("example.GeneratedTest"), maxAttempts));
    }

    private static AgentExecutor scripted(Object... payloads) {
        List<AgentExecutor.AgentResult> results = new ArrayList<>();
        for (int i = 0; i < payloads.length; i++) {
            results.add(new AgentExecutor.AgentResult("scripted-" + i,
                    ArtifactEnvelope.create("scripted-artifact-" + i, "scripted", List.of(), 1, payloads[i])));
        }
        return new ScriptedAgentExecutor(results);
    }

    private static TestEngineeringRequest request() {
        return new TestEngineeringRequest(new TestEngineeringRequest.Requirement(
                "Invalid password shows an error", List.of("error is visible")),
                new TestEngineeringRequest.Scope(List.of("login"), List.of()),
                new TestEngineeringRequest.Framework("JUnit", "5", "junit-jupiter"),
                new TestEngineeringRequest.Target("app", "GeneratedTest", "invalid-password"),
                List.of("src/test/java"), TestEngineeringRequest.ExecutionPolicy.TARGETED_AFTER_COMPILE);
    }

    private static AgentContextPack context() {
        return new AgentContextPack(ready(), new AgentTask(ready(), AgentTask.TaskType.CREATE_TEST,
                "Invalid password shows an error", List.of("login"), List.of("login-error"),
                List.of("login-submit"), List.of("Page Objects only")), List.of(),
                Map.of("LoginPage", List.of("login(String,String)", "errorVisible()")),
                List.of("JUnit 5"), List.of(), List.of(), AgentContextPack.Completeness.COMPLETE_FOR_REQUESTED_SCOPE);
    }

    private static TestPlan plan() { return new TestPlan(ready(), List.of()); }
    private static TestImplementationProposal implementation(String source) {
        return new TestImplementationProposal(ready(), "invalid-password", source,
                TestImplementationProposal.SelectorAccessPolicy.PAGE_OBJECTS_ONLY, List.of("LoginPage.login"), List.of());
    }
    private static CodeReviewResult review() {
        return new CodeReviewResult(ready(), CodeReviewResult.Verdict.APPROVE, List.of("implementation"), List.of());
    }
    private static String validSource() {
        return "package example; public final class GeneratedTest { public static String execute() { return \"agent-bytecode\"; } }";
    }
    private static ContractHeader ready() {
        return new ContractHeader(ContractHeader.SCHEMA_VERSION, ContractHeader.Status.READY,
                List.of("fixture"), List.of(), ContractHeader.Confidence.OBSERVED);
    }
}
