package io.github.testlens.application.tooling.codegen;

import io.github.testlens.application.model.ApplicationIds;
import io.github.testlens.application.model.ApplicationModel;
import io.github.testlens.application.tooling.drift.ApplicationDrift;
import io.github.testlens.application.tooling.drift.ApplicationModelDiffer;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Offline deterministic Java generator. It emits Selenium source text but has no Selenium compile dependency. @since 0.5.0 */
public final class PageObjectGenerator {
    public List<GeneratedPageObject> generate(ApplicationModel model, PageObjectGenerationOptions options) {
        Objects.requireNonNull(model,"model"); Objects.requireNonNull(options,"options");
        Map<String,String> pageClasses = classNames(model.pages());
        List<GeneratedPageObject> output = new ArrayList<>();
        for (ApplicationModel.PageModel page : model.pages()) output.add(generatePage(page,pageClasses,model.transitions(),options));
        return List.copyOf(output);
    }

    /** Returns source changes together with semantic drift rather than presenting a textual diff without reasons. */
    public List<PageObjectDiff> diff(ApplicationModel before,ApplicationModel after,PageObjectGenerationOptions options){
        Map<String,GeneratedPageObject>oldPages=generate(before,options).stream().collect(java.util.stream.Collectors.toMap(GeneratedPageObject::pageId,java.util.function.Function.identity()));
        Map<String,GeneratedPageObject>newPages=generate(after,options).stream().collect(java.util.stream.Collectors.toMap(GeneratedPageObject::pageId,java.util.function.Function.identity()));
        ApplicationDrift drift=new ApplicationModelDiffer().compare(before,after);java.util.Set<String>ids=new java.util.TreeSet<>();ids.addAll(oldPages.keySet());ids.addAll(newPages.keySet());List<PageObjectDiff>result=new ArrayList<>();
        for(String pageId:ids){String oldSource=oldPages.containsKey(pageId)?oldPages.get(pageId).generatedSource():null,newSource=newPages.containsKey(pageId)?newPages.get(pageId).generatedSource():null;if(Objects.equals(oldSource,newSource))continue;List<ApplicationDrift.Change>changes=drift.changes().stream().filter(change->pageId.equals(change.entityId())||pageId.equals(change.parentId())).toList();result.add(new PageObjectDiff(pageId,oldSource,newSource,changes));}return List.copyOf(result);
    }

    private GeneratedPageObject generatePage(ApplicationModel.PageModel page,Map<String,String>pageClasses,List<ApplicationModel.Transition>globalTransitions,PageObjectGenerationOptions options){
        String extension=pageClasses.get(page.pageId()),generated="Generated"+extension;
        List<ApplicationModel.ElementModel> accepted=new ArrayList<>(); List<String>warnings=new ArrayList<>();
        for(ApplicationModel.ElementModel element:page.elements()){
            if(element.preferredSelector()==null||element.selectorQuality()==ApplicationModel.SelectorQuality.UNAVAILABLE){warnings.add(element.elementId()+": selector unavailable");continue;}
            if(element.selectorQuality()==ApplicationModel.SelectorQuality.REVIEW_REQUIRED&&options.reviewSelectorPolicy()==PageObjectGenerationOptions.ReviewSelectorPolicy.SKIP){warnings.add(element.elementId()+": selector review required; skipped");continue;}
            if(SelectorJavaExpression.byExpression(element.preferredSelector())==null){warnings.add(element.elementId()+": unsupported selector strategy "+element.preferredSelector().strategy());continue;}
            accepted.add(element);
        }
        Map<String,String>fields=fieldNames(accepted);Map<String,ElementMethods>methodNames=methodNames(accepted,fields);List<GeneratedPageObject.ElementBinding>bindings=new ArrayList<>();
        StringBuilder source=new StringBuilder("package ").append(options.packageName()).append(";\n\n")
                .append("import io.github.testlens.TestLens;\nimport io.github.testlens.selenium.locator.UiLocator;\nimport org.openqa.selenium.By;\n\n")
                .append("/** Generated by Selenium Test Lens. Regenerate this class; customize ").append(extension).append(" instead. */\n")
                .append("public class ").append(generated).append(" {\n    protected final TestLens lens;\n\n")
                .append("    protected ").append(generated).append("(TestLens lens) { this.lens = java.util.Objects.requireNonNull(lens, \"lens\"); }\n\n");
        for(ApplicationModel.ElementModel element:accepted){String field=fields.get(element.elementId());ApplicationModel.SelectorProjection selector=element.preferredSelector();bindings.add(new GeneratedPageObject.ElementBinding(element.elementId(),field,selector.candidateId(),element.selectorQuality().name()));source.append("    /** Test Lens element ").append(escapeJavadoc(element.elementId())).append("; candidate ").append(escapeJavadoc(selector.candidateId())).append("; quality ").append(element.selectorQuality()).append(". */\n");if(element.selectorQuality()==ApplicationModel.SelectorQuality.REVIEW_REQUIRED)source.append("    // REVIEW_REQUIRED: verify this selector before production use.\n");source.append("    protected UiLocator ").append(field).append("() { return lens.locator(").append(SelectorJavaExpression.byExpression(selector)).append(", \"").append(javaString(element.semanticName())).append("\"); }\n\n");}
        Map<String,ApplicationModel.Transition>transitions=new HashMap<>();List<ApplicationModel.Transition>allTransitions=new ArrayList<>(page.transitions());globalTransitions.stream().filter(transition->transition.sourcePageId().equals(page.pageId())).forEach(allTransitions::add);for(ApplicationModel.Transition transition:allTransitions)if(transition.confidence()==ApplicationModel.TransitionConfidence.OBSERVED&&transition.elementId()!=null&&transition.targetPageId()!=null)transitions.putIfAbsent(transition.elementId(),transition);
        for(ApplicationModel.ElementModel element:accepted)methods(source,generated,element,methodNames.get(element.elementId()),transitions.get(element.elementId()),pageClasses,options.createUserExtensions());
        source.append("}\n");
        String extensionSource="package "+options.packageName()+";\n\nimport io.github.testlens.TestLens;\n\n/** User-maintained extensions for "+escapeJavadoc(page.canonicalName())+". */\npublic final class "+extension+" extends "+generated+" {\n    public "+extension+"(TestLens lens) { super(lens); }\n}\n";
        return new GeneratedPageObject(page.pageId(),generated,extension,source.toString(),extensionSource,bindings,warnings);
    }
    private static void methods(StringBuilder out,String owner,ApplicationModel.ElementModel element,ElementMethods names,ApplicationModel.Transition transition,Map<String,String>pageClasses,boolean extensions){
        boolean typed=element.actions().contains(ApplicationModel.Action.TYPE);boolean clicked=element.actions().contains(ApplicationModel.Action.CLICK)||element.actions().contains(ApplicationModel.Action.OPEN);
        if(typed)out.append("    public ").append(owner).append(" ").append(names.fill()).append("(String value) { ").append(names.locator()).append("().fill(value); return this; }\n\n");
        if(element.actions().contains(ApplicationModel.Action.CLEAR))out.append("    public ").append(owner).append(" ").append(names.clear()).append("() { ").append(names.locator()).append("().clear(); return this; }\n\n");
        if(clicked){if(transition!=null&&pageClasses.containsKey(transition.targetPageId())){String target=(extensions?"":"Generated")+pageClasses.get(transition.targetPageId());out.append("    public ").append(target).append(" ").append(names.click()).append("() { ").append(names.locator()).append("().click(); return new ").append(target).append("(lens); }\n\n");}else out.append("    public ").append(owner).append(" ").append(names.click()).append("() { ").append(names.locator()).append("().click(); return this; }\n\n");}
    }
    private static Map<String,String>classNames(List<ApplicationModel.PageModel>pages){Map<String,String>out=new LinkedHashMap<>();java.util.Set<String>used=new java.util.HashSet<>();for(var page:pages){String base=typeName(page.canonicalName(),"Page"),candidate=base;int collision=0;while(used.contains(candidate)||used.contains("Generated"+candidate)){candidate=base+upperFirst(shortHash(page.pageId()+(collision++==0?"":"|"+collision)));}used.add(candidate);used.add("Generated"+candidate);out.put(page.pageId(),candidate);}return Map.copyOf(out);}
    private static Map<String,String>fieldNames(List<ApplicationModel.ElementModel>elements){Map<String,String>out=new LinkedHashMap<>();Map<String,Integer>seen=new HashMap<>();for(var element:elements){String base=identifier(element.semanticName(),"element");int count=seen.merge(base,1,Integer::sum);out.put(element.elementId(),count==1?base:base+upperFirst(shortHash(element.elementId())));}return Map.copyOf(out);}
    private static Map<String,ElementMethods>methodNames(List<ApplicationModel.ElementModel>elements,Map<String,String>locators){Map<String,ElementMethods>out=new LinkedHashMap<>();java.util.Set<String>noArg=new java.util.HashSet<>(locators.values()),oneArg=new java.util.HashSet<>();for(var element:elements){String locator=locators.get(element.elementId()),suffix=upperFirst(locator);String fill=allocate("fill"+suffix,element.elementId()+"|fill",oneArg);String clear=allocate("clear"+suffix,element.elementId()+"|clear",noArg);String click=allocate("click"+suffix,element.elementId()+"|click",noArg);out.put(element.elementId(),new ElementMethods(locator,fill,clear,click));}return Map.copyOf(out);}
    private static String allocate(String base,String identity,java.util.Set<String>used){String candidate=base;int collision=0;while(!used.add(candidate))candidate=base+upperFirst(shortHash(identity+(collision++==0?"":"|"+collision)));return candidate;}
    private record ElementMethods(String locator,String fill,String clear,String click){}
    private static String typeName(String value,String fallback){String raw=identifier(value,fallback);String result=upperFirst(raw);return result.endsWith("Page")?result:result+"Page";}
    private static String identifier(String value,String fallback){String[]parts=Objects.toString(value,"").replaceAll("[^A-Za-z0-9_$]+"," ").trim().split("\\s+");StringBuilder out=new StringBuilder();for(int i=0;i<parts.length;i++){if(parts[i].isEmpty())continue;String p=parts[i];out.append(i==0?Character.toLowerCase(p.charAt(0)):Character.toUpperCase(p.charAt(0))).append(p.substring(1));}String result=out.length()==0?fallback:out.toString();if(!Character.isJavaIdentifierStart(result.charAt(0)))result="_"+result;result=result.chars().mapToObj(c->Character.isJavaIdentifierPart(c)?String.valueOf((char)c):"_").collect(java.util.stream.Collectors.joining());return JAVA_KEYWORDS.contains(result)?result+"Element":result;}
    private static final java.util.Set<String>JAVA_KEYWORDS=java.util.Set.of("abstract","assert","boolean","break","byte","case","catch","char","class","const","continue","default","do","double","else","enum","extends","final","finally","float","for","goto","if","implements","import","instanceof","int","interface","long","native","new","package","private","protected","public","return","short","static","strictfp","super","switch","synchronized","this","throw","throws","transient","try","void","volatile","while","record","sealed","permits","non-sealed","var","yield","true","false","null");
    private static String upperFirst(String value){return Character.toUpperCase(value.charAt(0))+value.substring(1);}
    private static String shortHash(String value){String id=ApplicationIds.id("java-name",value);return id.substring(id.length()-8);}
    private static String javaString(String value){StringBuilder out=new StringBuilder(value.length());for(char c:value.toCharArray())switch(c){case'\\'->out.append("\\\\");case'\"'->out.append("\\\"");case'\n'->out.append("\\n");case'\r'->out.append("\\r");case'\t'->out.append("\\t");case'\b'->out.append("\\b");case'\f'->out.append("\\f");default->{if(c<0x20||c==0x7f)out.append(String.format("\\u%04x",(int)c));else out.append(c);}}return out.toString();}
    private static String escapeJavadoc(String value){return value.replace("*/","*&#47;");}
}
