(function (window, document) {
  'use strict';
  var basePreset='COMPACT', custom=false, frameReady=false, customLogo=null, customLogoName=null, presets=null;
  var shared={};
  var state=Object.assign({},shared);
  var highlightDefaults={enabled:true,automaticFeedback:true,showLabels:true,actionColor:'#ffeb3b',waitingColor:'#2196f3',retryColor:'#ff9800',successColor:'#4caf50',failureColor:'#f44336',durationMs:1500,borderWidthPx:2};
  var sourceNavigationDefaults={enabled:false,previewActive:false,ide:'INTELLIJ',activationModifier:'CTRL_ALT'};
  var highlightState=Object.assign({},highlightDefaults);
  var sourceNavigation=Object.assign({},sourceNavigationDefaults);
  var frame=document.getElementById('preview-frame');

  function presetPattern(format){return format==='TIME_ONLY'?'HH:mm:ss':format==='DATE_TIME'?'dd.MM.yy HH:mm:ss':"yyyy-MM-dd'T'HH:mm:ss.SSSXXX";}
  function resolvedZone(zone){if(zone&&zone!=='SYSTEM')return zone;try{return Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';}catch(ignored){return'UTC';}}
  function validZone(zone){if(zone==='SYSTEM')return true;try{new Intl.DateTimeFormat('en',{timeZone:zone}).format(0);return true;}catch(ignored){return false;}}
  function patternTokens(pattern){
    if(!pattern||/[{}\[\]#]/.test(pattern))throw new Error('Use a valid Java DateTimeFormatter pattern.');
    var tokens=[],i=0,literal='';
    function flush(){if(literal){tokens.push({literal:literal});literal='';}}
    while(i<pattern.length){var ch=pattern.charAt(i);if(ch==="'"){i++;var closed=false;while(i<pattern.length){if(pattern.charAt(i)==="'"){if(pattern.charAt(i+1)==="'"){literal+="'";i+=2;continue;}closed=true;i++;break;}literal+=pattern.charAt(i++);}if(!closed)throw new Error('Unclosed quote in timestamp pattern.');continue;}if(/[A-Za-z]/.test(ch)){flush();var j=i+1;while(j<pattern.length&&pattern.charAt(j)===ch)j++;if('yMdHmsSXzV'.indexOf(ch)<0)throw new Error('Unsupported preview token: '+ch);if(ch==='S'&&j-i>9)throw new Error('Fraction supports at most 9 S characters.');if(ch==='V'&&j-i!==2)throw new Error('Zone ID uses VV.');tokens.push({symbol:ch,length:j-i});i=j;}else{literal+=ch;i++;}}
    flush();return tokens;
  }
  function timestampParts(iso,zone){var date=new Date(iso),resolved=resolvedZone(zone),options={timeZone:resolved,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'};var values={};new Intl.DateTimeFormat('en-CA',options).formatToParts(date).forEach(function(part){if(part.type!=='literal')values[part.type]=part.value;});var offsetName=new Intl.DateTimeFormat('en',{timeZone:resolved,timeZoneName:'longOffset'}).formatToParts(date).find(function(part){return part.type==='timeZoneName';});var offset=offsetName?offsetName.value.replace('GMT','')||'Z':'Z';if(offset==='UTC')offset='Z';var zoneName=new Intl.DateTimeFormat('en',{timeZone:resolved,timeZoneName:'short'}).formatToParts(date).find(function(part){return part.type==='timeZoneName';});var fraction=(String(iso).match(/\.(\d{1,9})/)||['',''])[1].padEnd(9,'0');return{year:values.year,month:values.month,day:values.day,hour:values.hour,minute:values.minute,second:values.second,fraction:fraction,offset:offset,zoneName:zoneName?zoneName.value:resolved,zone:resolved};}
  function formatTimestamp(iso,pattern,zone){var parts=timestampParts(iso,zone);return patternTokens(pattern).map(function(token){if(token.literal!==undefined)return token.literal;var n=token.length;switch(token.symbol){case'y':return n===2?parts.year.slice(-2):parts.year.padStart(n,'0');case'M':return n===1?String(Number(parts.month)):parts.month;case'd':return n===1?String(Number(parts.day)):parts.day;case'H':return n===1?String(Number(parts.hour)):parts.hour;case'm':return n===1?String(Number(parts.minute)):parts.minute;case's':return n===1?String(Number(parts.second)):parts.second;case'S':return parts.fraction.slice(0,n);case'X':if(parts.offset==='Z')return'Z';return n===1?parts.offset.replace(':','').replace(/00$/,''):n===2?parts.offset.replace(':',''):parts.offset;case'z':return parts.zoneName;case'V':return parts.zone;default:return'';}}).join('');}
  function effectivePattern(){return state.timestampPattern||presetPattern(state.timestampFormat||'ISO_UTC');}
  function timestampPreview(){var pattern=effectivePattern(),zone=state.timestampZone||'SYSTEM',events=['2026-07-15T21:59:58.123456789Z','2026-07-15T21:59:59.123456789Z','2026-07-15T22:00:00.123456789Z','2026-07-15T22:00:01.123456789Z','2026-07-15T22:00:02.123456789Z'];return{events:events.map(function(value){return formatTimestamp(value,pattern,zone);}),winter:formatTimestamp('2026-01-15T12:00:00.123456789Z',pattern,zone),summer:formatTimestamp('2026-07-15T12:00:00.123456789Z',pattern,zone)};}

  function typography(value){return Object.assign({},value||{});}
  function config(){var value=Object.assign({preset:basePreset},state);value.typography=typography(state.typography);value.highlight=Object.assign({},highlightState);value.sourceNavigationEnabled=sourceNavigation.enabled;value.sourceNavigationModifier=sourceNavigation.activationModifier;value.sourceNavigationPreviewActive=sourceNavigation.enabled&&sourceNavigation.previewActive;value.timestampPreview=timestampPreview();if(customLogo)value.customLogo=customLogo;return value;}
  function send(){if(frameReady)frame.contentWindow.postMessage({type:'hud-config',config:config()},'*');updateCode();}
  function markCustom(){custom=true;document.querySelectorAll('[data-preset]').forEach(function(b){b.classList.remove('selected');b.setAttribute('aria-pressed','false');});var label=document.getElementById('custom-preset');label.textContent='Custom (base: '+basePreset.charAt(0)+basePreset.slice(1).toLowerCase()+')';label.classList.add('active');}
  function applyPreset(name){if(!presets||!presets[name])return;basePreset=name;custom=false;customLogo=null;customLogoName=null;state=Object.assign({},shared,presets[name]);state.timestampPattern=null;state.typography=typography(state.typography);document.getElementById('logo').value='';document.getElementById('logo-status').textContent='PNG only, at most 1 MiB. The file stays in this page and is not added to your project.';document.querySelectorAll('[data-preset]').forEach(function(b){var selected=b.dataset.preset===name;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});document.getElementById('custom-preset').classList.remove('active');sync();send();}
  function manual(update){Object.assign(state,update);markCustom();sync();send();}
  function setValue(id,value){document.getElementById(id).value=String(value);}
  function sync(){
    document.getElementById('source-navigation-enabled').checked=sourceNavigation.enabled;document.getElementById('source-navigation-preview-active').checked=sourceNavigation.previewActive;document.getElementById('source-navigation-preview-active').disabled=!sourceNavigation.enabled;setValue('source-navigation-ide',sourceNavigation.ide);setValue('source-navigation-modifier',sourceNavigation.activationModifier);
    document.getElementById('highlight-enabled').checked=highlightState.enabled;document.getElementById('highlight-automatic').checked=highlightState.automaticFeedback;document.getElementById('highlight-labels').checked=highlightState.showLabels;document.querySelectorAll('[data-highlight-picker]').forEach(function(i){i.value=highlightState[i.dataset.highlightPicker];});document.querySelectorAll('[data-highlight-text]').forEach(function(i){i.value=highlightState[i.dataset.highlightText];});setValue('highlight-duration',highlightState.durationMs);setValue('highlight-border',highlightState.borderWidthPx);document.getElementById('highlight-duration-output').value=highlightState.durationMs+' ms';document.getElementById('highlight-border-output').value=highlightState.borderWidthPx+' px';
    document.querySelectorAll('[data-key]').forEach(function(i){i.checked=state[i.dataset.key];});
    document.querySelectorAll('[data-color-picker]').forEach(function(i){i.value=state[i.dataset.colorPicker];});
    document.querySelectorAll('[data-color-text]').forEach(function(i){i.value=state[i.dataset.colorText];});
    ['position','branding'].forEach(function(id){setValue(id,state[id]);});setValue('logo-placement',state.logoPlacement);setValue('font-preset',state.fontPreset);setValue('scrollbar-style',state.scrollbarStyle);setValue('timestamp-format',state.timestampFormat||'ISO_UTC');setValue('timestamp-pattern',effectivePattern());setValue('timestamp-zone',state.timestampZone||'SYSTEM');
    document.querySelectorAll('[data-header-layout]').forEach(function(button){var selected=button.dataset.headerLayout===state.headerLayout;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));});
    document.querySelectorAll('[data-typography]').forEach(function(i){i.value=state.typography&&state.typography[i.dataset.typography]||'INHERIT';});
    setValue('offset-x',state.offsetX);setValue('offset-y',state.offsetY);setValue('width',state.width);setValue('max-height',state.maxHeight);setValue('log-height',state.maxLogHeight);setValue('rail-width',state.railWidth);setValue('base-font',state.baseFontSize);setValue('header-font',state.headerFontSize);setValue('timestamp-font',state.typography.timestampFontSize||9);setValue('opacity',state.backgroundOpacity);setValue('scrollbar-width',state.scrollbarWidth);
    var preview=timestampPreview();document.getElementById('timestamp-winter-preview').textContent=preview.winter;document.getElementById('timestamp-summer-preview').textContent=preview.summer;document.getElementById('width-output').value=state.width+' px';document.getElementById('max-height-output').value=state.maxHeight+' px';document.getElementById('height-output').value=state.maxLogHeight+' px';document.getElementById('rail-width-output').value=state.railWidth+' px';document.getElementById('base-font-output').value=state.baseFontSize+' px';document.getElementById('header-font-output').value=state.headerFontSize+' px';document.getElementById('timestamp-font-output').value=(state.typography.timestampFontSize||9)+' px';document.getElementById('opacity-output').value=Number(state.backgroundOpacity).toFixed(2);document.getElementById('scrollbar-width-output').value=state.scrollbarWidth+' px';document.querySelector('.scrollbar-settings').dataset.native=String(state.scrollbarStyle==='NATIVE');
  }
  function differs(key){return state[key]!==Object.assign({},shared,presets[basePreset])[key];}
  function javaString(value){return '"'+String(value).replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\r/g,'\\r').replace(/\n/g,'\\n')+'"';}
  function line(method,value){return '.'+method+'('+value+')\n        ';}
  function scrollbarDefaults(style){return style==='STANDARD'?{scrollbarWidth:10,scrollbarTrack:'#1e293b',scrollbarThumb:'#94a3b8',scrollbarThumbHover:'#cbd5e1'}:{scrollbarWidth:6,scrollbarTrack:'#111827',scrollbarThumb:'#64748b',scrollbarThumbHover:'#94a3b8'};}
  function optionsCode(){
    var text='HudOptions hud = HudOptions.builder()\n        .preset(HudPreset.'+basePreset+')\n        ';
    if(differs('position'))text+=line('position','HudPosition.'+state.position);if(differs('headerLayout'))text+=line('headerLayout','HudHeaderLayout.'+state.headerLayout);if(differs('offsetX'))text+=line('offsetXPx',state.offsetX);if(differs('offsetY'))text+=line('offsetYPx',state.offsetY);if(differs('width'))text+=line('widthPx',state.width);if(differs('maxHeight'))text+=line('maxHeightPx',state.maxHeight);if(differs('maxLogHeight'))text+=line('maxLogHeightPx',state.maxLogHeight);if(differs('railWidth'))text+=line('railWidthPx',state.railWidth);if(differs('fontPreset'))text+=line('fontPreset','HudFontPreset.'+state.fontPreset);if(differs('baseFontSize'))text+=line('baseFontSizePx',state.baseFontSize);if(differs('headerFontSize'))text+=line('headerFontSizePx',state.headerFontSize);var scrollbarBase=differs('scrollbarStyle')?scrollbarDefaults(state.scrollbarStyle):Object.assign({},shared,presets[basePreset]);if(differs('scrollbarStyle'))text+=line('scrollbarStyle','HudScrollbarStyle.'+state.scrollbarStyle);if(state.scrollbarWidth!==scrollbarBase.scrollbarWidth)text+=line('scrollbarWidthPx',state.scrollbarWidth);if(state.scrollbarTrack!==scrollbarBase.scrollbarTrack)text+=line('scrollbarTrackColor','"'+state.scrollbarTrack+'"');if(state.scrollbarThumb!==scrollbarBase.scrollbarThumb)text+=line('scrollbarThumbColor','"'+state.scrollbarThumb+'"');if(state.scrollbarThumbHover!==scrollbarBase.scrollbarThumbHover)text+=line('scrollbarThumbHoverColor','"'+state.scrollbarThumbHover+'"');
    var sectionTypography=state.typography||{},sectionLines='';[['header','header'],['currentStep','currentStep'],['eventLog','eventLog'],['metadata','metadata']].forEach(function(pair){if(sectionTypography[pair[0]])sectionLines+='                .'+pair[1]+'(HudFontPreset.'+sectionTypography[pair[0]]+')\n';});var presetTimestampSize=(presets[basePreset].typography&&presets[basePreset].typography.timestampFontSize)||9;if((sectionTypography.timestampFontSize||9)!==presetTimestampSize)sectionLines+='                .timestampFontSizePx('+sectionTypography.timestampFontSize+')\n';if(sectionLines)text+='.typography(HudTypography.builder()\n'+sectionLines+'                .build())\n        ';
    ['showTestName','showCurrentStep','showPipeline','showTimestamps','showEventLog','showNetwork','showRetries','showWaits','showAssertions'].forEach(function(key){if(differs(key))text+=line(key,state[key]);});
    if(differs('timestampFormat'))text+=line('timestampFormat','HudTimestampFormat.'+state.timestampFormat);if(state.timestampPattern)text+=line('timestampPattern',javaString(state.timestampPattern));if(state.timestampZone&&state.timestampZone!=='SYSTEM')text+=line('timestampZone','ZoneId.of('+javaString(state.timestampZone)+')');else text+=line('systemTimestampZone','');
    [['background','background'],['accent','accentColor'],['primaryText','primaryTextColor'],['mutedText','mutedTextColor'],['success','successColor'],['warning','warningColor'],['failure','failureColor']].forEach(function(pair){if(differs(pair[0]))text+=line(pair[1],'"'+state[pair[0]]+'"');});
    if(differs('backgroundOpacity'))text+=line('backgroundOpacity',Number(state.backgroundOpacity).toFixed(2));if(differs('branding'))text+=line('branding','HudBranding.'+state.branding);if(differs('logoPlacement'))text+=line('logoPlacement','HudLogoPlacement.'+state.logoPlacement);if(sourceNavigation.enabled)text+='.sourceNavigation(SourceNavigationOptions.builder()\n                .enabled(true)\n                .activationModifier(SourceNavigationModifier.'+sourceNavigation.activationModifier+')\n                .ide(SourceIde.'+sourceNavigation.ide+')\n                .build())\n        ';if(customLogoName&&(state.branding==='CUSTOM'||state.branding==='BOTH'))text+=line('customLogo','Path.of('+javaString(document.getElementById('runtime-logo-path').value)+')');return text+'.build();';
  }
  function highlightCode(){return 'HighlightOptions highlights = HighlightOptions.builder()\n        .enabled('+highlightState.enabled+')\n        .automaticFeedback('+highlightState.automaticFeedback+')\n        .actionColor('+javaString(highlightState.actionColor)+')\n        .waitingColor('+javaString(highlightState.waitingColor)+')\n        .retryColor('+javaString(highlightState.retryColor)+')\n        .successColor('+javaString(highlightState.successColor)+')\n        .failureColor('+javaString(highlightState.failureColor)+')\n        .durationMs('+highlightState.durationMs+')\n        .borderWidthPx('+highlightState.borderWidthPx+')\n        .showLabels('+highlightState.showLabels+')\n        .build();';}
  function updateCode(){if(!presets)return;var imports='import io.github.testlens.HighlightOptions;\nimport io.github.testlens.TestLens;\nimport io.github.testlens.TestLensOptions;\nimport io.github.testlens.hud.*;\nimport io.github.testlens.selenium.evidence.VisualRedactionOptions;\n'+(state.timestampZone&&state.timestampZone!=='SYSTEM'?'import java.time.ZoneId;\n':'')+(customLogoName&&(state.branding==='CUSTOM'||state.branding==='BOTH')?'import java.nio.file.Path;\n':'');document.getElementById('generated-code').textContent=imports+'\n'+optionsCode()+'\n\n'+highlightCode()+'\n\nTestLensOptions options = TestLensOptions.builder()\n        .hud(hud)\n        .highlights(highlights)\n        .visualRedaction(VisualRedactionOptions.defaults())\n        .build();\n\nTestLens lens = TestLens.attach(driver, options);';}
  function copy(only){var text=only?optionsCode()+'\n\n'+highlightCode():document.getElementById('generated-code').textContent;navigator.clipboard.writeText(text).then(function(){document.getElementById('copy-status').textContent='Copied to clipboard.';},function(){document.getElementById('copy-status').textContent='Select the code and copy it manually.';});}
  function validHex(value){return /^#[0-9a-f]{6}$/i.test(value);}
  function acceptLogo(file){var status=document.getElementById('logo-status');if(!file||file.type!=='image/png'||file.size<24||file.size>1048576){status.textContent='Choose a PNG between 24 bytes and 1 MiB.';return;}var probe=new FileReader();probe.onload=function(){var bytes=new Uint8Array(probe.result);var signature=[137,80,78,71,13,10,26,10];var valid=signature.every(function(value,index){return bytes[index]===value;})&&String.fromCharCode(bytes[12],bytes[13],bytes[14],bytes[15])==='IHDR';if(!valid){status.textContent='The selected file is not a valid PNG.';return;}var width=((bytes[16]<<24)>>>0)+(bytes[17]<<16)+(bytes[18]<<8)+bytes[19],height=((bytes[20]<<24)>>>0)+(bytes[21]<<16)+(bytes[22]<<8)+bytes[23];if(!width||!height||width>4096||height>4096||width*height>16777216){status.textContent='PNG dimensions exceed the runtime limits.';return;}var reader=new FileReader();reader.onload=function(){customLogo=String(reader.result);customLogoName=file.name;status.textContent='Local preview only: '+customLogoName+'. Set the runtime path separately.';send();};reader.readAsDataURL(file);};probe.readAsArrayBuffer(file);}
  function bindRange(id,key){document.getElementById(id).addEventListener('input',function(e){var update={};update[key]=Number(e.target.value);manual(update);});}

  document.querySelectorAll('[data-preset]').forEach(function(b){b.addEventListener('click',function(){applyPreset(b.dataset.preset);});});
  document.querySelectorAll('[data-header-layout]').forEach(function(b){b.addEventListener('click',function(){manual({headerLayout:b.dataset.headerLayout});});});
  document.querySelectorAll('[data-key]').forEach(function(i){i.addEventListener('change',function(){var update={};update[i.dataset.key]=i.checked;manual(update);});});
  document.querySelectorAll('[data-color-picker]').forEach(function(i){i.addEventListener('input',function(){var update={};update[i.dataset.colorPicker]=i.value.toLowerCase();manual(update);});});
  document.querySelectorAll('[data-color-text]').forEach(function(i){i.addEventListener('change',function(){var value=i.value.toLowerCase();if(!validHex(value)){i.setCustomValidity('Use #RRGGBB');i.reportValidity();sync();return;}i.setCustomValidity('');var update={};update[i.dataset.colorText]=value;manual(update);});});
  document.querySelectorAll('[data-highlight-picker]').forEach(function(i){i.addEventListener('input',function(){highlightState[i.dataset.highlightPicker]=i.value.toLowerCase();sync();send();});});
  document.querySelectorAll('[data-highlight-text]').forEach(function(i){i.addEventListener('change',function(){var value=i.value.toLowerCase();if(!validHex(value)){i.setCustomValidity('Use #RRGGBB');i.reportValidity();sync();return;}i.setCustomValidity('');highlightState[i.dataset.highlightText]=value;sync();send();});});
  [['highlight-enabled','enabled'],['highlight-automatic','automaticFeedback'],['highlight-labels','showLabels']].forEach(function(pair){document.getElementById(pair[0]).addEventListener('change',function(e){highlightState[pair[1]]=e.target.checked;sync();send();});});
  document.getElementById('highlight-duration').addEventListener('input',function(e){highlightState.durationMs=Number(e.target.value);sync();send();});document.getElementById('highlight-border').addEventListener('input',function(e){highlightState.borderWidthPx=Number(e.target.value);sync();send();});
  document.getElementById('source-navigation-enabled').addEventListener('change',function(e){sourceNavigation.enabled=e.target.checked;if(!sourceNavigation.enabled)sourceNavigation.previewActive=false;sync();send();});document.getElementById('source-navigation-preview-active').addEventListener('change',function(e){sourceNavigation.previewActive=e.target.checked;sync();send();});document.getElementById('source-navigation-ide').addEventListener('change',function(e){sourceNavigation.ide=e.target.value;sync();send();});document.getElementById('source-navigation-modifier').addEventListener('change',function(e){sourceNavigation.activationModifier=e.target.value;sync();send();});
  document.getElementById('reset-timestamps').addEventListener('click',function(){var next=typography(state.typography);next.timestampFontSize=(presets[basePreset].typography&&presets[basePreset].typography.timestampFontSize)||9;manual({showTimestamps:presets[basePreset].showTimestamps,timestampFormat:'ISO_UTC',timestampPattern:null,timestampZone:'SYSTEM',typography:next});});document.getElementById('reset-source-navigation').addEventListener('click',function(){sourceNavigation=Object.assign({},sourceNavigationDefaults);sync();send();});document.getElementById('reset-highlights').addEventListener('click',function(){highlightState=Object.assign({},highlightDefaults);sync();send();});
  [['position','position'],['font-preset','fontPreset'],['logo-placement','logoPlacement']].forEach(function(pair){document.getElementById(pair[0]).addEventListener('change',function(e){var update={};update[pair[1]]=e.target.value;manual(update);});});
  document.getElementById('timestamp-format').addEventListener('change',function(e){manual({timestampFormat:e.target.value,timestampPattern:null});});
  document.getElementById('timestamp-pattern').addEventListener('change',function(e){var input=e.target,error=document.getElementById('timestamp-pattern-error');try{patternTokens(input.value);input.setCustomValidity('');error.textContent='';manual({timestampPattern:input.value});}catch(invalid){var message=invalid.message||'Invalid timestamp pattern.';input.setCustomValidity(message);error.textContent=message;input.reportValidity();}});
  document.getElementById('timestamp-zone').addEventListener('change',function(e){var input=e.target,value=input.value.trim(),error=document.getElementById('timestamp-zone-error');if(!validZone(value)){var message='Unknown IANA time zone.';input.setCustomValidity(message);error.textContent=message;input.reportValidity();return;}input.setCustomValidity('');error.textContent='';manual({timestampZone:value});});
  document.getElementById('scrollbar-style').addEventListener('change',function(e){manual(Object.assign({scrollbarStyle:e.target.value},scrollbarDefaults(e.target.value)));});
  document.querySelectorAll('[data-typography]').forEach(function(input){input.addEventListener('change',function(){var next=typography(state.typography),value=input.value;if(value==='INHERIT')delete next[input.dataset.typography];else next[input.dataset.typography]=value;manual({typography:next});});});
  document.getElementById('timestamp-font').addEventListener('input',function(e){var next=typography(state.typography);next.timestampFontSize=Number(e.target.value);manual({typography:next});});
  document.getElementById('branding').addEventListener('change',function(e){if((e.target.value==='CUSTOM'||e.target.value==='BOTH')&&!customLogo){document.getElementById('logo-status').textContent='Choose a PNG before selecting custom branding.';sync();return;}manual({branding:e.target.value});});
  document.getElementById('runtime-logo-path').addEventListener('input',function(){if(customLogoName){markCustom();updateCode();}});
  [['width','width'],['max-height','maxHeight'],['log-height','maxLogHeight'],['rail-width','railWidth'],['base-font','baseFontSize'],['header-font','headerFontSize'],['scrollbar-width','scrollbarWidth'],['opacity','backgroundOpacity'],['offset-x','offsetX'],['offset-y','offsetY']].forEach(function(pair){bindRange(pair[0],pair[1]);});
  document.getElementById('logo').addEventListener('change',function(e){acceptLogo(e.target.files[0]);});var drop=document.getElementById('logo-drop');['dragenter','dragover'].forEach(function(type){drop.addEventListener(type,function(e){e.preventDefault();drop.classList.add('dragover');});});['dragleave','drop'].forEach(function(type){drop.addEventListener(type,function(e){e.preventDefault();drop.classList.remove('dragover');if(type==='drop')acceptLogo(e.dataTransfer.files[0]);});});
  document.querySelectorAll('[data-viewport]').forEach(function(button){button.addEventListener('click',function(){document.getElementById('preview-frame-wrap').dataset.viewport=button.dataset.viewport;document.querySelectorAll('[data-viewport]').forEach(function(item){var selected=item===button;item.classList.toggle('selected',selected);item.setAttribute('aria-pressed',String(selected));});window.setTimeout(send,220);});});
  document.getElementById('replay').addEventListener('click',function(){if(frameReady)frame.contentWindow.postMessage({type:'hud-replay'},'*');});document.getElementById('copy-options').addEventListener('click',function(){copy(true);});document.getElementById('copy-setup').addEventListener('click',function(){copy(false);});
  window.addEventListener('message',function(event){if(event.source!==frame.contentWindow||!event.data)return;if(event.data.type==='hud-ready'){if(!event.data.presets||!event.data.presets.COMPACT)throw new Error('HUD preset definitions are unavailable');presets=event.data.presets;frameReady=true;applyPreset(basePreset);}if(event.data.type==='hud-rendered')document.body.dataset.hudReady='true';if(event.data.type==='hud-change')manual(event.data.changes);if(event.data.type==='hud-select'){document.querySelectorAll('fieldset').forEach(function(item){item.classList.toggle('selected',item.dataset.section===event.data.section);});var selected=document.querySelector('fieldset.selected');if(selected)selected.scrollIntoView({block:'nearest'});}});
})(window,document);
