package io.github.mmaciekk111.uitestlens.core.trace;

public enum TraceEventType {
    SESSION_STARTED,
    SESSION_FINISHED,
    STEP_STARTED,
    STEP_PASSED,
    STEP_FAILED,
    ACTION_STARTED,
    ACTION_PASSED,
    ACTION_FAILED,
    ASSERTION_STARTED,
    ASSERTION_PASSED,
    ASSERTION_FAILED,
    BUSINESS_ASSERTION_STARTED,
    BUSINESS_ASSERTION_PASSED,
    BUSINESS_ASSERTION_FAILED,
    OVERLAY_DETECTED,
    OVERLAY_HANDLED,
    ACTIONABILITY_CHECK,
    LOCATOR_ACTION,
    ARTIFACT_ATTACHED,
    CUSTOM
}
