package io.github.testlens.migration.tooling;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static io.github.testlens.migration.tooling.MigrationGitPreflight.*;

/** Trusted-host entry point for read-only Git preflight and source fingerprinting. */
public final class MigrationGitService {
    private static final Pattern VERSION=Pattern.compile("git version (\\d+)\\.(\\d+)(?:\\.(\\d+))?.*");
    private final SafeGit git;
    public MigrationGitService(){this("git");}
    public MigrationGitService(String trustedGitExecutable){git=new SafeGit(trustedGitExecutable);}

    public Result inspect(Path trustedStartingDirectory)throws IOException{try{return inspectInternal(trustedStartingDirectory);}catch(SafeGit.GitFailure failure){return failed(RepositoryStatus.ERROR,failure.code);}}
    private Result inspectInternal(Path trustedStartingDirectory)throws IOException{
        Path start=trustedStartingDirectory.toAbsolutePath().normalize().toRealPath();List<Issue>issues=new ArrayList<>();
        GitProcessRunner.Result versionResult=git.execute(SafeGit.Operation.VERSION,start,null);if(versionResult.timedOut()||versionResult.interrupted()||versionResult.outputTruncated())SafeGit.requireComplete(versionResult,"VERSION");if(versionResult.exitCode()!=0)return failed(RepositoryStatus.UNSUPPORTED_GIT_VERSION,"GIT_VERSION_UNAVAILABLE");String gitVersion=SafeGit.text(versionResult);Matcher version=VERSION.matcher(gitVersion);if(!version.matches())return failed(RepositoryStatus.UNSUPPORTED_GIT_VERSION,"UNRECOGNIZED_GIT_VERSION");
        GitProcessRunner.Result rootResult=git.execute(SafeGit.Operation.ROOT,start,null);if(rootResult.timedOut()||rootResult.interrupted()||rootResult.outputTruncated())SafeGit.requireComplete(rootResult,"ROOT");if(rootResult.exitCode()!=0){String error=new String(rootResult.stderr(),java.nio.charset.StandardCharsets.UTF_8);return failed(error.contains("safe.directory")||error.contains("dubious ownership")?RepositoryStatus.NOT_TRUSTED:RepositoryStatus.NOT_A_REPOSITORY,error.contains("safe.directory")||error.contains("dubious ownership")?"GIT_REPOSITORY_NOT_TRUSTED":"NOT_A_GIT_REPOSITORY");}Path root=Path.of(SafeGit.text(rootResult)).toAbsolutePath().normalize().toRealPath();
        Path common=resolved(root,required(SafeGit.Operation.COMMON_DIR,root));String repoRef="migration-repository-binding-v1:sha256:"+MigrationDigests.digest("migration-repository-binding-v1",common.toString());String worktreeRef="migration-worktree-binding-v1:sha256:"+MigrationDigests.digest("migration-worktree-binding-v1",root.toString(),repoRef);
        GitProcessRunner.Result objectResult=git.execute(SafeGit.Operation.OBJECT_FORMAT,root,null);if(objectResult.timedOut()||objectResult.interrupted()||objectResult.outputTruncated())SafeGit.requireComplete(objectResult,"OBJECT_FORMAT");if(objectResult.exitCode()!=0)return failed(RepositoryStatus.UNSUPPORTED_GIT_VERSION,"OBJECT_FORMAT_UNAVAILABLE");String objectFormat=SafeGit.text(objectResult);GitProcessRunner.Result statusResult=git.execute(SafeGit.Operation.STATUS,root,null);if(statusResult.timedOut()||statusResult.interrupted()||statusResult.outputTruncated())SafeGit.requireComplete(statusResult,"STATUS");if(statusResult.exitCode()!=0)return failed(RepositoryStatus.UNSUPPORTED_GIT_VERSION,"PORCELAIN_V2_UNAVAILABLE");GitPorcelainV2Parser.Parsed parsed=new GitPorcelainV2Parser().parse(statusResult.stdout());
        HeadState state;String commit=null,tree=null,branch=null;if("(initial)".equals(parsed.branchOid())||"(unknown)".equals(parsed.branchOid())){state=HeadState.UNBORN;branch=parsed.branchHead();}else{commit=optional(SafeGit.Operation.HEAD_COMMIT,root,null);tree=optional(SafeGit.Operation.HEAD_TREE,root,null);GitProcessRunner.Result branchResult=git.execute(SafeGit.Operation.READ_SYMBOLIC_HEAD,root,null);if(branchResult.exitCode()==0){state=HeadState.NAMED_BRANCH;branch=SafeGit.text(branchResult);}else state=HeadState.DETACHED;}
        String upstream=parsed.upstream();
        List<GitOperation>operations=operations(root);List<Worktree>worktrees=worktrees(root,repoRef,worktreeRef,issues);SparseCheckout sparse=sparse(root);int gitlinks=gitlinks(root,issues);boolean submodules=Files.exists(root.resolve(".gitmodules"),LinkOption.NOFOLLOW_LINKS)||gitlinks>0;
        long total=java.util.stream.Stream.of(parsed.staged(),parsed.unstaged(),parsed.untracked(),parsed.conflicted()).flatMap(List::stream).map(StatusEntry::logicalPath).distinct().count();Completeness completeness=issues.isEmpty()?Completeness.COMPLETE:Completeness.PARTIAL;if(total>MAX_PATHS){issues.add(new Issue("STATUS_PATH_LIMIT_EXCEEDED",Long.toString(total)));completeness=Completeness.INCOMPLETE;}
        MigrationGitPreflight preflight=new MigrationGitPreflight(RepositoryStatus.DETECTED,repoRef,worktreeRef,gitVersion,objectFormat,new Head(state,commit,tree,branch),blank(upstream),limit(parsed.staged()),limit(parsed.unstaged()),limit(parsed.untracked()),limit(parsed.conflicted()),limit(parsed.renames()),operations,worktrees,sparse,new SubmoduleSummary(submodules,submodules?Completeness.PARTIAL:Completeness.COMPLETE,gitlinks,submodules?List.of("SUBMODULE_CONTENT_NOT_INSPECTED"):List.of()),completeness,issues);
        MigrationLocalContext local=new MigrationLocalContext(root,root,common);MigrationSourceStateFingerprint source=new SourceStateFingerprinter(git).fingerprint(preflight,local);if(source.completeness()==MigrationSourceStateFingerprint.Completeness.INCOMPLETE_SOURCE_STATE&&preflight.completeness()==Completeness.COMPLETE)preflight=new MigrationGitPreflight(preflight.repositoryStatus(),preflight.repositoryBindingRef(),preflight.worktreeBindingRef(),preflight.gitVersion(),preflight.objectFormat(),preflight.head(),preflight.upstreamRef(),preflight.staged(),preflight.unstaged(),preflight.untracked(),preflight.conflicted(),preflight.renamesAndCopies(),preflight.ongoingOperations(),preflight.worktrees(),preflight.sparseCheckout(),preflight.submodules(),Completeness.INCOMPLETE,concat(preflight.issues(),new Issue("INCOMPLETE_SOURCE_STATE","Dirty state exceeded hashing bounds or changed while hashing")));
        return new Result(preflight,source,local);
    }
    public boolean validBranchCandidate(Path trustedStartingDirectory,String candidate)throws IOException{GitProcessRunner.Result result=git.execute(SafeGit.Operation.CHECK_BRANCH,trustedStartingDirectory,candidate);if(result.timedOut()||result.interrupted()||result.outputTruncated())SafeGit.requireComplete(result,"CHECK_BRANCH");return result.exitCode()==0;}
    boolean ignored(Path root,String logical)throws IOException{GitProcessRunner.Result result=git.execute(SafeGit.Operation.CHECK_IGNORE,root,logical);if(result.timedOut()||result.interrupted()||result.outputTruncated())SafeGit.requireComplete(result,"CHECK_IGNORE");return result.exitCode()==0;}
    private String required(SafeGit.Operation operation,Path root)throws IOException{GitProcessRunner.Result r=git.execute(operation,root,null);SafeGit.requireComplete(r,operation.name());return SafeGit.text(r);}
    private String optional(SafeGit.Operation operation,Path root,String value)throws IOException{GitProcessRunner.Result r=git.execute(operation,root,value);if(r.outputTruncated()||r.timedOut()||r.interrupted())SafeGit.requireComplete(r,operation.name());return r.exitCode()==0?blank(SafeGit.text(r)):null;}
    private List<GitOperation>operations(Path root)throws IOException{List<GitOperation>out=new ArrayList<>();String[][]markers={{"MERGE_HEAD","MERGE"},{"rebase-merge","REBASE_MERGE"},{"rebase-apply","REBASE_APPLY"},{"CHERRY_PICK_HEAD","CHERRY_PICK"},{"REVERT_HEAD","REVERT"},{"BISECT_LOG","BISECT"}};for(String[]m:markers){String p=requiredPath(root,m[0]);if(Files.exists(Path.of(p),LinkOption.NOFOLLOW_LINKS))out.add(GitOperation.valueOf(m[1]));}return List.copyOf(out);}
    private String requiredPath(Path root,String marker)throws IOException{Path p=Path.of(requiredValue(SafeGit.Operation.GIT_PATH,root,marker));return(p.isAbsolute()?p:root.resolve(p)).toAbsolutePath().normalize().toString();}
    private String requiredValue(SafeGit.Operation operation,Path root,String value)throws IOException{GitProcessRunner.Result r=git.execute(operation,root,value);SafeGit.requireComplete(r,operation.name());return SafeGit.text(r);}
    private List<Worktree>worktrees(Path root,String repositoryRef,String current,List<Issue>issues)throws IOException{GitProcessRunner.Result r=git.execute(SafeGit.Operation.WORKTREES,root,null);if(r.timedOut()||r.interrupted()||r.outputTruncated()){issues.add(new Issue("WORKTREE_PORCELAIN_INCOMPLETE","Git worktree porcelain output is incomplete"));return List.of();}if(r.exitCode()!=0){issues.add(new Issue("WORKTREE_PORCELAIN_UNAVAILABLE","Git worktree porcelain -z is unavailable"));return List.of();}List<Worktree>out=new ArrayList<>();String path=null,head=null,branch=null;boolean detached=false,locked=false,prunable=false;for(String token:GitPorcelainV2Parser.nul(r.stdout())){if(token.isEmpty()){if(path!=null){String ref=worktreeRef(path,repositoryRef);out.add(new Worktree(ref,head,branch,detached,locked,prunable,ref.equals(current)));path=null;head=null;branch=null;detached=locked=prunable=false;}continue;}int space=token.indexOf(' ');String key=space<0?token:token.substring(0,space),value=space<0?"":token.substring(space+1);switch(key){case"worktree"->path=value;case"HEAD"->head=value;case"branch"->branch=value;case"detached"->detached=true;case"locked"->locked=true;case"prunable"->prunable=true;default->{}}}if(path!=null){String ref=worktreeRef(path,repositoryRef);out.add(new Worktree(ref,head,branch,detached,locked,prunable,ref.equals(current)));}if(out.size()>MAX_WORKTREES)issues.add(new Issue("WORKTREE_LIMIT_EXCEEDED",Integer.toString(out.size())));return out.stream().sorted(Comparator.comparing(Worktree::bindingRef)).limit(MAX_WORKTREES).toList();}
    private static String worktreeRef(String path,String repositoryRef){Path value=Path.of(path).toAbsolutePath().normalize();try{if(Files.exists(value,LinkOption.NOFOLLOW_LINKS))value=value.toRealPath();}catch(IOException ignored){ }return"migration-worktree-binding-v1:sha256:"+MigrationDigests.digest("migration-worktree-binding-v1",value.toString(),repositoryRef);}
    private SparseCheckout sparse(Path root)throws IOException{GitProcessRunner.Result r=git.execute(SafeGit.Operation.SPARSE,root,null);if(r.exitCode()!=0)return SparseCheckout.UNKNOWN;String v=SafeGit.text(r);return"true".equalsIgnoreCase(v)?SparseCheckout.ENABLED:"false".equalsIgnoreCase(v)?SparseCheckout.DISABLED:SparseCheckout.UNKNOWN;}
    private int gitlinks(Path root,List<Issue>issues)throws IOException{GitProcessRunner.Result r=git.execute(SafeGit.Operation.INDEX,root,null);if(r.exitCode()!=0||r.outputTruncated()){issues.add(new Issue("INDEX_SUMMARY_UNAVAILABLE","Cannot inspect gitlinks"));return 0;}return(int)GitPorcelainV2Parser.nul(r.stdout()).stream().filter(x->x.startsWith("160000 ")).count();}
    private static Path resolved(Path root,String value)throws IOException{Path p=Path.of(value);if(!p.isAbsolute())p=root.resolve(p);return p.toAbsolutePath().normalize().toRealPath();}
    private static String blank(String v){return v==null||v.isBlank()?null:v;}
    private static <T>List<T>limit(List<T>v){return v.stream().limit(MAX_PATHS).toList();}
    private static List<Issue>concat(List<Issue>a,Issue b){List<Issue>x=new ArrayList<>(a);x.add(b);return x;}
    private Result failed(RepositoryStatus status,String code){MigrationGitPreflight p=new MigrationGitPreflight(status,null,null,null,null,new Head(HeadState.UNBORN,null,null,null),null,List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),List.of(),SparseCheckout.UNKNOWN,new SubmoduleSummary(false,Completeness.PARTIAL,0,List.of()),Completeness.INCOMPLETE,List.of(new Issue(code,"Read-only Git preflight did not complete")));return new Result(p,null,null);}
    public record Result(MigrationGitPreflight preflight,MigrationSourceStateFingerprint sourceState,MigrationLocalContext localContext){ }
}
