package io.github.testlens.migration.tooling;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;

/** Sanitized durable result. Raw process output remains ephemeral unless explicitly stored by the host. */
public record MigrationRunResult(int schemaVersion,int algorithmVersion,String runResultId,String planId,String checkpointBeforeRef,
        Instant startedAt,Instant endedAt,Status status,Integer exitCode,OutputSummary stdout,OutputSummary stderr,
        boolean outputTruncated,ProcessTreeTermination processTreeTermination,List<ArtifactResult>expectedArtifactResults,
        String checkpointAfterRef,List<String>capabilitiesUsed,List<String>issues){
    public MigrationRunResult{if(schemaVersion!=1||algorithmVersion!=1)throw new IllegalArgumentException("unsupported run result");require(planId,"migration-run-plan-v1");require(checkpointBeforeRef,"migration-checkpoint-v1");Objects.requireNonNull(startedAt);Objects.requireNonNull(endedAt);Objects.requireNonNull(status);Objects.requireNonNull(stdout);Objects.requireNonNull(stderr);Objects.requireNonNull(processTreeTermination);expectedArtifactResults=expectedArtifactResults==null?List.of():expectedArtifactResults.stream().sorted(Comparator.comparing(ArtifactResult::logicalPath)).toList();if(checkpointAfterRef!=null)require(checkpointAfterRef,"migration-checkpoint-v1");capabilitiesUsed=capabilitiesUsed==null?List.of():capabilitiesUsed.stream().distinct().sorted().toList();issues=issues==null?List.of():issues.stream().distinct().sorted().toList();if(issues.size()>256)throw new IllegalArgumentException("issue bound");String expected=id(planId,checkpointBeforeRef,status,exitCode,stdout,stderr,processTreeTermination,expectedArtifactResults,checkpointAfterRef,capabilitiesUsed,issues);if(!expected.equals(runResultId))throw new IllegalArgumentException("runResultId does not match semantic content");}
    public static MigrationRunResult create(String plan,String before,Instant started,Instant ended,Status status,Integer exit,OutputSummary stdout,OutputSummary stderr,ProcessTreeTermination termination,List<ArtifactResult>artifacts,String after,List<String>capabilities,List<String>issues){return new MigrationRunResult(1,1,id(plan,before,status,exit,stdout,stderr,termination,artifacts,after,capabilities,issues),plan,before,started,ended,status,exit,stdout,stderr,stdout.truncated()||stderr.truncated(),termination,artifacts,after,capabilities,issues);}
    public enum Status{SUCCESS,FAILED,TIMED_OUT,CANCELLED,START_FAILED,ARTIFACT_VALIDATION_FAILED,SAFE_STOP,INTERRUPTED,UNKNOWN_COMPLETION,ARTIFACTS_PARTIAL}
    public enum ArtifactStatus{VALID,MISSING,STALE,MALFORMED,MODE_MISMATCH,OPTIONAL_ABSENT,OUTPUT_LIMIT_EXCEEDED}
    public enum ProcessTreeTermination{NOT_REQUIRED,TERMINATED,FORCIBLY_TERMINATED,DESCENDANTS_REMAIN,NOT_STARTED}
    public record OutputSummary(String sha256,long byteCount,boolean truncated,String sanitizedSummary){public OutputSummary{if(sha256==null||!sha256.matches("[0-9a-f]{64}"))throw new IllegalArgumentException("output digest");if(byteCount<0)throw new IllegalArgumentException("byteCount");sanitizedSummary=sanitizedSummary==null?"":sanitizedSummary;if(sanitizedSummary.length()>4096)throw new IllegalArgumentException("summary bound");}}
    public record ArtifactResult(String logicalPath,ArtifactStatus status,String digest,long byteCount,String semanticId,List<String>issues){public ArtifactResult{logicalPath=MigrationRunPlan.logical(logicalPath);Objects.requireNonNull(status);if(digest!=null&&!digest.matches("sha256:[0-9a-f]{64}"))throw new IllegalArgumentException("artifact digest");if(byteCount<0)throw new IllegalArgumentException("artifact size");issues=issues==null?List.of():List.copyOf(issues);}}
    private static String id(String plan,String before,Status status,Integer exit,OutputSummary out,OutputSummary err,ProcessTreeTermination termination,List<ArtifactResult>artifacts,String after,List<String>capabilities,List<String>issues){List<String>f=new ArrayList<>(List.of(plan,before,status.name(),exit==null?"":exit.toString(),out.sha256(),Long.toString(out.byteCount()),Boolean.toString(out.truncated()),err.sha256(),Long.toString(err.byteCount()),Boolean.toString(err.truncated()),termination.name(),after==null?"":after));artifacts.stream().sorted(Comparator.comparing(ArtifactResult::logicalPath)).forEach(a->{f.add(a.logicalPath());f.add(a.status().name());f.add(a.digest()==null?"":a.digest());f.add(Long.toString(a.byteCount()));f.add(a.semanticId()==null?"":a.semanticId());f.addAll(a.issues().stream().sorted().toList());});capabilities.stream().sorted().forEach(f::add);issues.stream().sorted().forEach(f::add);return"migration-run-result-v1:sha256:"+MigrationDigests.digest("migration-run-result-v1",f.toArray(String[]::new));}
    private static void require(String value,String domain){if(value==null||!value.matches(java.util.regex.Pattern.quote(domain)+":sha256:[0-9a-f]{64}"))throw new IllegalArgumentException(domain);}
}
