package io.github.testlens.migration.tooling;

import io.github.testlens.compatibility.engine.ComparisonIntent;
import io.github.testlens.compatibility.engine.CompatibilityComparisonReport;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;

/** Immutable, plan-bound post-apply verification contract. */
public record MigrationVerificationPlan(int schemaVersion,int algorithmVersion,String verificationPlanId,
        String applyPlanId,String transactionId,String postApplyCheckpointRef,String postApplySourceStateDigest,
        List<Requirement>requirements,List<Stage>stages,List<TrustedRunBinding>trustedRunBindings,
        List<String>baselineRefs,List<String>expectedArtifactRefs,List<ComparisonPlan>comparisonPlans,
        List<MigrationAuthorization.Capability>requiredCapabilities,Completeness completeness,
        List<String>limitations,String supersedesVerificationPlanId){
    public static final int MAX_STAGES=512,MAX_COMPARISONS=1_000,MAX_ARTIFACT_REFS=1_024,MAX_ISSUES=1_024;
    public MigrationVerificationPlan{
        if(schemaVersion!=1||algorithmVersion!=1)throw new IllegalArgumentException("verification plan version");
        MigrationApplyPlan.require(applyPlanId,"migration-apply-plan-v1");MigrationApplyPlan.require(transactionId,"migration-apply-transaction-v1");MigrationApplyPlan.require(postApplyCheckpointRef,"migration-checkpoint-v1");MigrationApplyPlan.require(postApplySourceStateDigest,"migration-source-state-v1");
        requirements=sorted(requirements,Comparator.comparing(Requirement::requirementRef));stages=sorted(stages,Comparator.comparingInt((Stage x)->x.type().ordinal()).thenComparing(Stage::stageRef));trustedRunBindings=sorted(trustedRunBindings,Comparator.comparing(TrustedRunBinding::stageRef));comparisonPlans=sorted(comparisonPlans,Comparator.comparing(ComparisonPlan::comparisonPlanRef));baselineRefs=strings(baselineRefs);expectedArtifactRefs=strings(expectedArtifactRefs);requiredCapabilities=requiredCapabilities==null?List.of():requiredCapabilities.stream().distinct().sorted().toList();limitations=strings(limitations);Objects.requireNonNull(completeness);
        if(stages.size()>MAX_STAGES||requirements.size()>MAX_STAGES||trustedRunBindings.size()>MAX_STAGES||comparisonPlans.size()>MAX_COMPARISONS||baselineRefs.size()>MAX_ARTIFACT_REFS||expectedArtifactRefs.size()>MAX_ARTIFACT_REFS||limitations.size()>MAX_ISSUES)throw new IllegalArgumentException("verification bound");if(supersedesVerificationPlanId!=null)MigrationApplyPlan.require(supersedesVerificationPlanId,"migration-verification-plan-v1");
        List<String>stageIds=stages.stream().map(Stage::stageRef).toList();if(trustedRunBindings.stream().map(TrustedRunBinding::stageRef).distinct().count()!=trustedRunBindings.size())throw new IllegalArgumentException("duplicate trusted run binding");for(TrustedRunBinding binding:trustedRunBindings)if(!stageIds.contains(binding.stageRef()))throw new IllegalArgumentException("invalid trusted run binding");
        boolean comparisonStage=false;for(Stage stage:stages)if(stage.type()==StageType.COMPATIBILITY_COMPARE)comparisonStage=true;if(!comparisonPlans.isEmpty()&&!comparisonStage)throw new IllegalArgumentException("comparison stage required");
        String expected=id(applyPlanId,transactionId,postApplyCheckpointRef,postApplySourceStateDigest,requirements,stages,trustedRunBindings,baselineRefs,expectedArtifactRefs,comparisonPlans,requiredCapabilities,completeness,limitations,supersedesVerificationPlanId);if(!expected.equals(verificationPlanId))throw new IllegalArgumentException("verificationPlanId");
    }
    public static MigrationVerificationPlan create(MigrationApplyPlan apply,String transaction,String checkpoint,String sourceDigest,List<Requirement>planBound,List<Requirement>stricter,List<TrustedRunBinding>bindings,List<String>baselines,List<String>artifacts,List<ComparisonPlan>comparisons,List<String>limitations,String supersedes){
        List<Requirement>base=dedup(planBound),extra=dedup(stricter);if(!apply.verificationRequirementsDigest().equals(requirementsDigest(base)))throw new IllegalArgumentException("VERIFICATION_PLAN_MISMATCH");List<Requirement>all=new ArrayList<>(base);for(Requirement r:extra)if(all.stream().noneMatch(x->x.dedupKey().equals(r.dedupKey())))all.add(r);all=dedup(all);List<Stage>stages=all.stream().map(Requirement::stage).distinct().toList();List<MigrationAuthorization.Capability>caps=new ArrayList<>();for(TrustedRunBinding b:bindings==null?List.<TrustedRunBinding>of():bindings){caps.add(MigrationAuthorization.Capability.EXECUTE_PROJECT_TEST_COMMAND);if(b.networkPolicy()==NetworkPolicy.NETWORK_AUTHORIZED)caps.add(MigrationAuthorization.Capability.ALLOW_BUILD_TOOL_NETWORK);}String id=id(apply.applyPlanId(),transaction,checkpoint,sourceDigest,all,stages,bindings,baselines,artifacts,comparisons,caps,Completeness.COMPLETE,limitations,supersedes);return new MigrationVerificationPlan(1,1,id,apply.applyPlanId(),transaction,checkpoint,sourceDigest,all,stages,bindings,baselines,artifacts,comparisons,caps,Completeness.COMPLETE,limitations,supersedes);
    }
    public static List<Requirement> requirements(List<MigrationProposal>proposals){List<Requirement>out=new ArrayList<>();for(MigrationProposal p:proposals)for(MigrationProposal.VerificationStep v:p.requiredVerification()){StageType type=switch(v.kind()){case COMPILE_AFFECTED_MODULE->StageType.COMPILE;case RUN_DIRECTLY_AFFECTED_TEST->StageType.DIRECT_TESTS;case RUN_KNOWN_USE_SITE_TESTS->StageType.USE_SITE_TESTS;case RUN_HEADED->StageType.HEADED;case RUN_HEADLESS->StageType.HEADLESS;case RUN_HEADLESS_FAST->StageType.FAST;case CAPTURE_COMPATIBILITY_MANIFEST->StageType.MANIFEST_VALIDATION;case COMPARE_COMPATIBILITY->StageType.COMPATIBILITY_COMPARE;case MANUAL_REVIEW->StageType.SOURCE_STRUCTURE;};MigrationRunPlan.ExecutionMode mode=switch(type){case HEADED->MigrationRunPlan.ExecutionMode.HEADED_STANDARD;case HEADLESS->MigrationRunPlan.ExecutionMode.HEADLESS_STANDARD;case FAST->MigrationRunPlan.ExecutionMode.HEADLESS_FAST;default->null;};Expectation expectation=switch(type){case COMPILE->Expectation.COMMAND_SUCCESS;case DIRECT_TESTS,USE_SITE_TESTS,HEADED,HEADLESS,FAST->Expectation.TEST_PASS;case MANIFEST_VALIDATION->Expectation.MANIFEST_VALID;case COMPATIBILITY_COMPARE->Expectation.COMPARISON_ACCEPTABLE;case SOURCE_STRUCTURE->Expectation.PRESERVE_BASELINE;};SourceScope scope=type==StageType.COMPILE?SourceScope.AFFECTED_MODULE:type==StageType.SOURCE_STRUCTURE?SourceScope.TOUCHED_FILES_ONLY:SourceScope.PROJECT_SOURCE;String subject=v.subjectRef()==null?"-":v.subjectRef();out.add(Requirement.create(v.kind().name(),type,Necessity.REQUIRED,subject,v.subjectRef(),mode,v.sideEffect(),expectation,scope,List.of(p.proposalId())));}return dedup(out);}
    public enum StageType{SOURCE_STRUCTURE,COMPILE,DIRECT_TESTS,USE_SITE_TESTS,HEADED,HEADLESS,FAST,MANIFEST_VALIDATION,COMPATIBILITY_COMPARE}
    public enum Necessity{REQUIRED,OPTIONAL}
    public enum Expectation{COMMAND_SUCCESS,TEST_PASS,PRESERVE_BASELINE,NO_NEW_REGRESSION,TARGET_FINDING_RESOLVED,NO_HEADLESS_REGRESSION,NO_OBSERVABILITY_REGRESSION,MANIFEST_VALID,COMPARISON_ACCEPTABLE}
    public enum SourceScope{TOUCHED_FILES_ONLY,AFFECTED_MODULE,PROJECT_SOURCE}
    public enum Completeness{COMPLETE,PARTIAL}
    public enum NetworkPolicy{NETWORK_NOT_REQUIRED,NETWORK_NOT_AUTHORIZED,OFFLINE,NETWORK_AUTHORIZED}
    public record Requirement(String requirementRef,String sourceKind,StageType stageType,Necessity necessity,String targetRef,String testIdentityRef,MigrationRunPlan.ExecutionMode executionMode,MigrationProposal.SideEffect sideEffect,Expectation expectation,SourceScope sourceScope,List<String>proposalIds){
        public Requirement{Objects.requireNonNull(stageType);Objects.requireNonNull(necessity);Objects.requireNonNull(sideEffect);Objects.requireNonNull(expectation);Objects.requireNonNull(sourceScope);sourceKind=safe(sourceKind);targetRef=safe(targetRef);testIdentityRef=testIdentityRef==null?null:safe(testIdentityRef);proposalIds=strings(proposalIds);if(proposalIds.size()>MigrationApplyPlan.MAX_PROPOSALS)throw new IllegalArgumentException("proposal coverage bound");String e=ref("migration-verification-requirement-v1",sourceKind,stageType.name(),necessity.name(),targetRef,n(testIdentityRef),n(executionMode),sideEffect.name(),expectation.name(),sourceScope.name(),String.join("|",proposalIds));if(!e.equals(requirementRef))throw new IllegalArgumentException("requirementRef");}
        public static Requirement create(String sourceKind,StageType type,Necessity necessity,String target,String test,MigrationRunPlan.ExecutionMode mode,MigrationProposal.SideEffect side,Expectation expectation,SourceScope scope,List<String>proposals){List<String>p=strings(proposals);String r=ref("migration-verification-requirement-v1",sourceKind,type.name(),necessity.name(),target,n(test),n(mode),side.name(),expectation.name(),scope.name(),String.join("|",p));return new Requirement(r,sourceKind,type,necessity,target,test,mode,side,expectation,scope,p);}
        String dedupKey(){return stageType+"|"+targetRef+"|"+n(testIdentityRef)+"|"+n(executionMode)+"|"+sideEffect+"|"+expectation+"|"+sourceScope;}Stage stage(){return Stage.create(stageType,necessity,targetRef,List.of(requirementRef),expectation);}
    }
    public record Stage(String stageRef,StageType type,Necessity necessity,String targetRef,List<String>requirementRefs,Expectation expectation){public Stage{Objects.requireNonNull(type);Objects.requireNonNull(necessity);targetRef=safe(targetRef);requirementRefs=strings(requirementRefs);Objects.requireNonNull(expectation);String e=ref("migration-verification-stage-v1",type.name(),necessity.name(),targetRef,String.join("|",requirementRefs),expectation.name());if(!e.equals(stageRef))throw new IllegalArgumentException("stageRef");}static Stage create(StageType t,Necessity n,String target,List<String>r,Expectation e){List<String>x=strings(r);return new Stage(ref("migration-verification-stage-v1",t.name(),n.name(),target,String.join("|",x),e.name()),t,n,target,x,e);}}
    public record TrustedRunBinding(String bindingRef,String stageRef,String runPlanId,String checkpointRef,WrapperBinding wrapper,NetworkPolicy networkPolicy){public TrustedRunBinding{MigrationApplyPlan.require(stageRef,"migration-verification-stage-v1");MigrationApplyPlan.require(runPlanId,"migration-run-plan-v1");MigrationApplyPlan.require(checkpointRef,"migration-checkpoint-v1");Objects.requireNonNull(networkPolicy);if(wrapper!=null&&networkPolicy==NetworkPolicy.NETWORK_NOT_REQUIRED)throw new IllegalArgumentException("wrapper network policy required");String e=ref("migration-verification-run-binding-v1",stageRef,runPlanId,checkpointRef,wrapper==null?"":wrapper.bindingRef(),networkPolicy.name());if(!e.equals(bindingRef))throw new IllegalArgumentException("bindingRef");}public static TrustedRunBinding create(String stage,String run,String checkpoint,WrapperBinding wrapper,NetworkPolicy network){return new TrustedRunBinding(ref("migration-verification-run-binding-v1",stage,run,checkpoint,wrapper==null?"":wrapper.bindingRef(),network.name()),stage,run,checkpoint,wrapper,network);}}
    public record WrapperBinding(String bindingRef,WrapperKind kind,String javaExecutableRef,String jarLogicalPath,String jarSha256,String propertiesLogicalPath,String propertiesSha256){public WrapperBinding{Objects.requireNonNull(kind);javaExecutableRef=safe(javaExecutableRef);jarLogicalPath=MigrationRunPlan.logical(jarLogicalPath);propertiesLogicalPath=MigrationRunPlan.logical(propertiesLogicalPath);MigrationApplyPlan.require(jarSha256,"sha256");MigrationApplyPlan.require(propertiesSha256,"sha256");String e=ref("migration-wrapper-binding-v1",kind.name(),javaExecutableRef,jarLogicalPath,jarSha256,propertiesLogicalPath,propertiesSha256);if(!e.equals(bindingRef))throw new IllegalArgumentException("wrapper binding");}public static WrapperBinding create(WrapperKind kind,String javaRef,String jar,String jarDigest,String properties,String propertiesDigest){return new WrapperBinding(ref("migration-wrapper-binding-v1",kind.name(),javaRef,jar,jarDigest,properties,propertiesDigest),kind,javaRef,jar,jarDigest,properties,propertiesDigest);}public enum WrapperKind{GRADLE_WRAPPER_MAIN,MAVEN_WRAPPER_MAIN}}
    public record ComparisonPlan(String comparisonPlanRef,ComparisonIntent intent,String baselineManifestRef,String variantManifestRef,List<CompatibilityComparisonReport.Outcome>acceptableOutcomes,boolean allowBehavioralDelta,boolean requireComparable,List<String>targetedFindingIds,List<String>proposalIds){public ComparisonPlan{Objects.requireNonNull(intent);baselineManifestRef=MigrationRunPlan.logical(baselineManifestRef);variantManifestRef=MigrationRunPlan.logical(variantManifestRef);acceptableOutcomes=acceptableOutcomes==null?List.of():acceptableOutcomes.stream().distinct().sorted().toList();targetedFindingIds=strings(targetedFindingIds);proposalIds=strings(proposalIds);if(targetedFindingIds.size()>MAX_COMPARISONS||proposalIds.size()>MigrationApplyPlan.MAX_PROPOSALS)throw new IllegalArgumentException("comparison bound");String e=ref("migration-verification-comparison-v1",intent.axis().name(),baselineManifestRef,variantManifestRef,String.join("|",acceptableOutcomes.stream().map(Enum::name).toList()),Boolean.toString(allowBehavioralDelta),Boolean.toString(requireComparable),String.join("|",targetedFindingIds),String.join("|",proposalIds));if(!e.equals(comparisonPlanRef))throw new IllegalArgumentException("comparisonPlanRef");}public static ComparisonPlan create(ComparisonIntent intent,String baseline,String variant,List<CompatibilityComparisonReport.Outcome>accepted,boolean allowDelta,boolean requireComparable,List<String>findings,List<String>proposals){List<CompatibilityComparisonReport.Outcome>a=accepted==null?List.of():accepted.stream().distinct().sorted().toList();List<String>f=strings(findings),p=strings(proposals);String ref=MigrationVerificationPlan.ref("migration-verification-comparison-v1",intent.axis().name(),baseline,variant,String.join("|",a.stream().map(Enum::name).toList()),Boolean.toString(allowDelta),Boolean.toString(requireComparable),String.join("|",f),String.join("|",p));return new ComparisonPlan(ref,intent,baseline,variant,a,allowDelta,requireComparable,f,p);}}
    public static String requirementsDigest(List<Requirement>r){List<String>f=r.stream().map(x->x.sourceKind()+"|"+x.sideEffect().name()+"|"+("-".equals(x.targetRef())?"":x.targetRef())).distinct().sorted().toList();return"migration-verification-requirements-v1:sha256:"+MigrationDigests.digest("migration-verification-requirements-v1",f.toArray(String[]::new));}
    private static List<Requirement>dedup(List<Requirement>r){if(r==null)return List.of();java.util.Map<String,Requirement>m=new java.util.TreeMap<>();for(Requirement x:r){Requirement old=m.get(x.dedupKey());if(old==null){m.put(x.dedupKey(),x);continue;}Necessity necessity=old.necessity()==Necessity.REQUIRED||x.necessity()==Necessity.REQUIRED?Necessity.REQUIRED:Necessity.OPTIONAL;List<String>proposals=new ArrayList<>(old.proposalIds());proposals.addAll(x.proposalIds());m.put(x.dedupKey(),Requirement.create(old.sourceKind(),old.stageType(),necessity,old.targetRef(),old.testIdentityRef(),old.executionMode(),old.sideEffect(),old.expectation(),old.sourceScope(),proposals));}return List.copyOf(m.values());}
    private static String id(String apply,String tx,String cp,String source,List<Requirement>r,List<Stage>s,List<TrustedRunBinding>b,List<String>base,List<String>a,List<ComparisonPlan>c,List<MigrationAuthorization.Capability>caps,Completeness complete,List<String>limits,String supersedes){List<String>f=new ArrayList<>(List.of(apply,tx,cp,source,complete.name(),n(supersedes)));r.stream().sorted(Comparator.comparing(Requirement::requirementRef)).forEach(x->f.add(x.requirementRef()));s.stream().sorted(Comparator.comparing(Stage::stageRef)).forEach(x->f.add(x.stageRef()));if(b!=null)b.stream().sorted(Comparator.comparing(TrustedRunBinding::bindingRef)).forEach(x->f.add(x.bindingRef()));strings(base).forEach(f::add);strings(a).forEach(f::add);if(c!=null)c.stream().sorted(Comparator.comparing(ComparisonPlan::comparisonPlanRef)).forEach(x->f.add(x.comparisonPlanRef()));caps.stream().map(Enum::name).sorted().forEach(f::add);strings(limits).forEach(f::add);return ref("migration-verification-plan-v1",f.toArray(String[]::new));}
    static String ref(String domain,String...fields){return domain+":sha256:"+MigrationDigests.digest(domain,fields);}
    private static String safe(String v){if(v==null||v.isBlank()||v.length()>512||v.chars().anyMatch(Character::isISOControl))throw new IllegalArgumentException("bounded value");return v;}
    private static String n(Object v){return v==null?"":v instanceof Enum<?>e?e.name():v.toString();}
    private static List<String>strings(List<String>v){return v==null?List.of():v.stream().filter(Objects::nonNull).distinct().sorted().toList();}
    private static<T>List<T>sorted(List<T>v,Comparator<T>c){return v==null?List.of():v.stream().sorted(c).toList();}
}
