package io.github.testlens.migration.tooling;

import java.time.Duration;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.TreeMap;

/** Immutable shell-free plan. Executable and paths are trusted-host references, never imported report values. */
public record MigrationRunPlan(int schemaVersion,int algorithmVersion,String planId,String executableRef,List<String>args,
        String trustedWorkingDirectoryBinding,Map<EnvironmentKey,String>environmentOverlay,List<String>secretReferenceNames,
        Duration timeout,OutputBounds outputBounds,List<ExpectedArtifact>expectedArtifacts,ExecutionMode executionMode,
        Scope scope,SideEffectClassification sideEffectClassification,List<MigrationAuthorization.Capability>requiredApprovals,
        String checkpointRef,BaselineRole baselineRole){
    public static final int MAX_ARGS=256,MAX_ARG_CHARS=16_384,MAX_ENV=32,MAX_SECRETS=32,MAX_ARTIFACTS=1_000;
    public MigrationRunPlan{if(schemaVersion!=1||algorithmVersion!=1)throw new IllegalArgumentException("unsupported run-plan version");executableRef=safe(executableRef,512);binding(trustedWorkingDirectoryBinding,"migration-worktree-binding-v1");args=bounded(args,MAX_ARGS,MAX_ARG_CHARS,"argument");environmentOverlay=environmentOverlay==null?Map.of():java.util.Collections.unmodifiableMap(new TreeMap<>(environmentOverlay));if(environmentOverlay.size()>MAX_ENV)throw new IllegalArgumentException("environment bound");environmentOverlay.forEach((k,v)->{Objects.requireNonNull(k);safe(v,4096);});secretReferenceNames=bounded(secretReferenceNames,MAX_SECRETS,128,"secret reference").stream().distinct().sorted().toList();if(timeout==null||timeout.isZero()||timeout.isNegative()||timeout.compareTo(Duration.ofHours(24))>0)throw new IllegalArgumentException("finite timeout required");Objects.requireNonNull(outputBounds);expectedArtifacts=expectedArtifacts==null?List.of():expectedArtifacts.stream().sorted(Comparator.comparing(ExpectedArtifact::logicalPath)).toList();if(expectedArtifacts.size()>MAX_ARTIFACTS)throw new IllegalArgumentException("artifact bound");Objects.requireNonNull(executionMode);Objects.requireNonNull(scope);Objects.requireNonNull(sideEffectClassification);requiredApprovals=required(sideEffectClassification,requiredApprovals);checkpoint(checkpointRef);Objects.requireNonNull(baselineRole);String expected=id(executableRef,args,trustedWorkingDirectoryBinding,environmentOverlay,secretReferenceNames,timeout,outputBounds,expectedArtifacts,executionMode,scope,sideEffectClassification,requiredApprovals,checkpointRef,baselineRole);if(!expected.equals(planId))throw new IllegalArgumentException("planId does not match semantic content");}
    public static MigrationRunPlan create(String executableRef,List<String>args,String worktreeBinding,Map<EnvironmentKey,String>environment,List<String>secretRefs,Duration timeout,OutputBounds bounds,List<ExpectedArtifact>artifacts,ExecutionMode mode,Scope scope,SideEffectClassification sideEffect,String checkpoint,BaselineRole baseline){List<MigrationAuthorization.Capability>required=required(sideEffect,List.of());String id=id(executableRef,args,worktreeBinding,environment,secretRefs,timeout,bounds,artifacts,mode,scope,sideEffect,required,checkpoint,baseline);return new MigrationRunPlan(1,1,id,executableRef,args,worktreeBinding,environment,secretRefs,timeout,bounds,artifacts,mode,scope,sideEffect,required,checkpoint,baseline);}
    public enum ExecutionMode{HEADED_STANDARD,HEADLESS_STANDARD,HEADLESS_FAST,CUSTOM_TRUSTED}
    public enum BaselineRole{ORIGINAL_BASELINE,INSTRUMENTED_BASELINE,VARIANT}
    public enum Scope{SINGLE_TEST,TEST_CLASS,TEST_GROUP,SUITE,CUSTOM_TRUSTED}
    public enum SideEffectClassification{READ_ONLY,KNOWN_MUTATING,UNKNOWN}
    public enum EnvironmentKey{TEST_LENS_HEADLESS("TEST_LENS_HEADLESS"),TEST_LENS_OBSERVABILITY("TEST_LENS_OBSERVABILITY"),CI("CI"),LANG("LANG"),LC_ALL("LC_ALL");private final String processName;EnvironmentKey(String n){processName=n;}public String processName(){return processName;}}
    public enum ArtifactRoot{PROJECT_OUTPUT,STATE_ROOT}
    public enum ArtifactFreshness{MUST_BE_CREATED,MUST_CHANGE,MAY_REUSE,OPTIONAL}
    public enum ArtifactKind{COMPATIBILITY_RUN_MANIFEST,TRACE_BUNDLE,FAILURE_BUNDLE,GENERIC}
    public record OutputBounds(int stdoutBytes,int stderrBytes){public OutputBounds{if(stdoutBytes<1||stdoutBytes>8*1024*1024||stderrBytes<1||stderrBytes>8*1024*1024)throw new IllegalArgumentException("output bound");}public static OutputBounds defaults(){return new OutputBounds(8*1024*1024,8*1024*1024);}}
    public record ExpectedArtifact(String logicalPath,ArtifactRoot root,ArtifactFreshness freshness,ArtifactKind kind,long maxBytes,String expectedTestIdentityRef){public ExpectedArtifact{logicalPath=logical(logicalPath);Objects.requireNonNull(root);if(root==ArtifactRoot.PROJECT_OUTPUT&&!logicalPath.startsWith("target/")&&!logicalPath.startsWith("build/"))throw new IllegalArgumentException("project artifacts require a trusted output root");Objects.requireNonNull(freshness);Objects.requireNonNull(kind);if(maxBytes<1||maxBytes>64L*1024*1024)throw new IllegalArgumentException("artifact byte bound");if(expectedTestIdentityRef!=null)safe(expectedTestIdentityRef,512);}}
    private static List<MigrationAuthorization.Capability>required(SideEffectClassification sideEffect,List<MigrationAuthorization.Capability>given){List<MigrationAuthorization.Capability>r=new ArrayList<>();r.add(MigrationAuthorization.Capability.EXECUTE_PROJECT_TEST_COMMAND);r.add(switch(sideEffect){case READ_ONLY->MigrationAuthorization.Capability.RUN_READ_ONLY_TEST;case KNOWN_MUTATING->MigrationAuthorization.Capability.RUN_MUTATING_TEST;case UNKNOWN->MigrationAuthorization.Capability.RUN_UNKNOWN_SIDE_EFFECT_TEST;});List<MigrationAuthorization.Capability>canonical=r.stream().distinct().sorted(Comparator.comparing(Enum::name)).toList();if(given!=null&&!given.isEmpty()&&!canonical.equals(given.stream().distinct().sorted(Comparator.comparing(Enum::name)).toList()))throw new IllegalArgumentException("required approvals are derived");return canonical;}
    private static String id(String executable,List<String>args,String binding,Map<EnvironmentKey,String>environment,List<String>secrets,Duration timeout,OutputBounds bounds,List<ExpectedArtifact>artifacts,ExecutionMode mode,Scope scope,SideEffectClassification side,List<MigrationAuthorization.Capability>approvals,String checkpoint,BaselineRole baseline){List<String>f=new ArrayList<>(List.of(safe(executable,512),binding,Long.toString(timeout.toMillis()),Integer.toString(bounds.stdoutBytes()),Integer.toString(bounds.stderrBytes()),mode.name(),scope.name(),side.name(),checkpoint,baseline.name()));args.forEach(x->{f.add("ARG");f.add(x);});new TreeMap<>(environment).forEach((k,v)->{f.add("ENV");f.add(k.name());f.add(v);});secrets.stream().sorted().forEach(x->{f.add("SECRET_REF");f.add(x);});artifacts.stream().sorted(Comparator.comparing(ExpectedArtifact::logicalPath)).forEach(x->{f.add("ARTIFACT");f.add(x.logicalPath());f.add(x.root().name());f.add(x.freshness().name());f.add(x.kind().name());f.add(Long.toString(x.maxBytes()));f.add(x.expectedTestIdentityRef()==null?"":x.expectedTestIdentityRef());});approvals.stream().map(Enum::name).sorted().forEach(f::add);return"migration-run-plan-v1:sha256:"+MigrationDigests.digest("migration-run-plan-v1",f.toArray(String[]::new));}
    private static List<String>bounded(List<String>values,int count,int chars,String label){values=values==null?List.of():List.copyOf(values);if(values.size()>count)throw new IllegalArgumentException(label+" count bound");for(String v:values)safe(v,chars);return values;}
    private static String safe(String value,int length){if(value==null||value.isBlank()||value.length()>length||value.indexOf('\0')>=0)throw new IllegalArgumentException("unsafe value");return value;}
    static String logical(String value){value=safe(value,1024).replace('\\','/');if(value.startsWith("/")||value.matches("^[A-Za-z]:.*")||value.equals(".git")||value.startsWith(".git/")||java.util.Arrays.asList(value.split("/",-1)).contains(".."))throw new IllegalArgumentException("unsafe artifact path");return value;}
    private static void binding(String value,String domain){if(value==null||!value.matches(java.util.regex.Pattern.quote(domain)+":sha256:[0-9a-f]{64}"))throw new IllegalArgumentException(domain);}
    private static void checkpoint(String value){if(value==null||!value.matches("migration-checkpoint-v1:sha256:[0-9a-f]{64}"))throw new IllegalArgumentException("checkpointRef");}
}
