package io.github.testlens.migration.tooling;

import tools.jackson.core.JsonGenerator;import tools.jackson.core.ObjectWriteContext;import tools.jackson.core.json.JsonFactory;
import java.io.ByteArrayOutputStream;import java.io.IOException;import java.util.ArrayList;import java.util.EnumSet;import java.util.HashSet;import java.util.List;import java.util.Map;import java.util.Set;
import static io.github.testlens.migration.tooling.MigrationSourceStateFingerprint.*;

/** Strict deterministic Jackson-Core checkpoint codec. */
public final class MigrationCheckpointJson{
 private static final JsonFactory FACTORY=JsonFactory.builder().build();
 public byte[]write(MigrationCheckpoint c){try{Bounded out=new Bounded();try(JsonGenerator g=FACTORY.createGenerator(ObjectWriteContext.empty(),out)){value(g,c);g.writeRaw('\n');}return out.toByteArray();}catch(IOException e){throw new Format("Checkpoint serialization failed",e);}}
 public MigrationCheckpoint read(byte[]bytes){return parse(MigrationStrictJson.object(bytes));}
 private void value(JsonGenerator g,MigrationCheckpoint c)throws IOException{g.writeStartObject();g.writeNumberProperty("schemaVersion",c.schemaVersion());g.writeNumberProperty("algorithmVersion",c.algorithmVersion());g.writeStringProperty("checkpointId",c.checkpointId());g.writeStringProperty("repositoryBindingRef",c.repositoryBindingRef());g.writeStringProperty("worktreeBindingRef",c.worktreeBindingRef());g.writeObjectPropertyStart("head");g.writeStringProperty("state",c.head().state().name());nullable(g,"commit",c.head().commit());nullable(g,"tree",c.head().tree());nullable(g,"branch",c.head().branch());g.writeEndObject();enums(g,"gitOperations",c.gitOperations());g.writeStringProperty("statusSnapshotDigest",c.statusSnapshotDigest());source(g,c.sourceState());config(g,c.configuration());g.writeArrayPropertyStart("artifacts");for(MigrationArtifactRef a:c.artifacts().stream().sorted(java.util.Comparator.comparing(MigrationArtifactRef::logicalRef)).toList()){g.writeStartObject();g.writeStringProperty("type",a.type().name());g.writeNumberProperty("schemaVersion",a.schemaVersion());g.writeStringProperty("digest",a.digest());g.writeStringProperty("logicalRef",a.logicalRef());g.writeStringProperty("completeness",a.completeness().name());g.writeEndObject();}g.writeEndArray();nullable(g,"proposalSetRef",c.proposalSetRef());nullable(g,"decisionsRef",c.decisionsRef());g.writeStringProperty("completeness",c.completeness().name());strings(g,"issues",c.issues());g.writeEndObject();}
 private void source(JsonGenerator g,MigrationSourceStateFingerprint s)throws IOException{g.writeObjectPropertyStart("sourceState");g.writeNumberProperty("algorithmVersion",s.algorithmVersion());g.writeStringProperty("sourceStateDigest",s.sourceStateDigest());nullable(g,"headTree",s.headTree());g.writeNumberProperty("hashedBytes",s.hashedBytes());g.writeStringProperty("completeness",s.completeness().name());g.writeArrayPropertyStart("files");for(FileState f:s.files()){g.writeStartObject();g.writeStringProperty("logicalPath",f.logicalPath());strings(g,"roles",f.roles().stream().sorted().toList());g.writeArrayPropertyStart("relations");for(PathRelation relation:f.relations()){g.writeStartObject();g.writeStringProperty("originalLogicalPath",relation.originalLogicalPath());g.writeStringProperty("kind",relation.kind().name());g.writeEndObject();}g.writeEndArray();if(f.index()!=null){g.writeObjectPropertyStart("index");g.writeStringProperty("mode",f.index().mode());g.writeNumberProperty("stage",f.index().stage());g.writeStringProperty("objectId",f.index().objectId());g.writeStringProperty("sha256",f.index().sha256());g.writeNumberProperty("size",f.index().size());g.writeEndObject();}else g.writeNullProperty("index");if(f.worktree()!=null){g.writeObjectPropertyStart("worktree");g.writeStringProperty("state",f.worktree().state().name());nullable(g,"sha256",f.worktree().sha256());g.writeNumberProperty("size",f.worktree().size());nullable(g,"linkTargetDigest",f.worktree().linkTargetDigest());g.writeEndObject();}else g.writeNullProperty("worktree");g.writeEndObject();}g.writeEndArray();strings(g,"issues",s.issues());g.writeEndObject();}
 private void config(JsonGenerator g,MigrationCheckpoint.Configuration c)throws IOException{g.writeObjectPropertyStart("configuration");g.writeStringProperty("isolationChoice",c.isolationChoice().name());g.writeStringProperty("intendedMode",c.intendedMode().name());g.writeStringProperty("stateStorage",c.stateStorage().name());g.writeStringProperty("configurationDigest",c.configurationDigest());g.writeEndObject();}
 private MigrationCheckpoint parse(Map<String,Object>m){known(m,Set.of("schemaVersion","algorithmVersion","checkpointId","repositoryBindingRef","worktreeBindingRef","head","gitOperations","statusSnapshotDigest","sourceState","configuration","artifacts","proposalSetRef","decisionsRef","completeness","issues"));Map<String,Object>h=obj(m,"head");known(h,Set.of("state","commit","tree","branch"));MigrationCheckpoint.Head head=new MigrationCheckpoint.Head(en(MigrationGitPreflight.HeadState.class,str(h,"state")),opt(h,"commit"),opt(h,"tree"),opt(h,"branch"));List<MigrationGitPreflight.GitOperation>ops=list(m,"gitOperations").stream().map(x->en(MigrationGitPreflight.GitOperation.class,(String)x)).toList();MigrationSourceStateFingerprint source=parseSource(obj(m,"sourceState"));Map<String,Object>c=obj(m,"configuration");known(c,Set.of("isolationChoice","intendedMode","stateStorage","configurationDigest"));MigrationCheckpoint.Configuration config=new MigrationCheckpoint.Configuration(en(MigrationIsolationPlan.Choice.class,str(c,"isolationChoice")),en(MigrationCheckpoint.IntendedMode.class,str(c,"intendedMode")),en(MigrationCheckpoint.StateStorage.class,str(c,"stateStorage")),str(c,"configurationDigest"));List<MigrationArtifactRef>artifacts=new ArrayList<>();for(Object raw:list(m,"artifacts")){Map<String,Object>a=cast(raw);known(a,Set.of("type","schemaVersion","digest","logicalRef","completeness"));artifacts.add(new MigrationArtifactRef(en(MigrationArtifactRef.Type.class,str(a,"type")),integer(a,"schemaVersion"),str(a,"digest"),str(a,"logicalRef"),en(MigrationArtifactRef.Completeness.class,str(a,"completeness"))));}return new MigrationCheckpoint(integer(m,"schemaVersion"),integer(m,"algorithmVersion"),str(m,"checkpointId"),str(m,"repositoryBindingRef"),str(m,"worktreeBindingRef"),head,ops,str(m,"statusSnapshotDigest"),source,config,artifacts,opt(m,"proposalSetRef"),opt(m,"decisionsRef"),en(MigrationCheckpoint.Completeness.class,str(m,"completeness")),stringList(m,"issues"));}
 private MigrationSourceStateFingerprint parseSource(Map<String,Object>m){known(m,Set.of("algorithmVersion","sourceStateDigest","headTree","hashedBytes","completeness","files","issues"));List<FileState>files=new ArrayList<>();for(Object raw:list(m,"files")){Map<String,Object>f=cast(raw);known(f,Set.of("logicalPath","roles","relations","index","worktree"));List<PathRelation>relations=new ArrayList<>();for(Object relationRaw:list(f,"relations")){Map<String,Object>relation=cast(relationRaw);known(relation,Set.of("originalLogicalPath","kind"));relations.add(new PathRelation(str(relation,"originalLogicalPath"),en(MigrationGitPreflight.ChangeKind.class,str(relation,"kind"))));}IndexState index=null;if(f.get("index")!=null){Map<String,Object>i=cast(f.get("index"));known(i,Set.of("mode","stage","objectId","sha256","size"));index=new IndexState(str(i,"mode"),integer(i,"stage"),str(i,"objectId"),str(i,"sha256"),lng(i,"size"));}WorktreeContent worktree=null;if(f.get("worktree")!=null){Map<String,Object>w=cast(f.get("worktree"));known(w,Set.of("state","sha256","size","linkTargetDigest"));worktree=new WorktreeContent(en(WorktreeState.class,str(w,"state")),opt(w,"sha256"),lng(w,"size"),opt(w,"linkTargetDigest"));}files.add(new FileState(str(f,"logicalPath"),new HashSet<>(stringList(f,"roles")),relations,index,worktree));}return new MigrationSourceStateFingerprint(integer(m,"algorithmVersion"),str(m,"sourceStateDigest"),opt(m,"headTree"),files,lng(m,"hashedBytes"),en(Completeness.class,str(m,"completeness")),stringList(m,"issues"));}
 private static void known(Map<String,Object>m,Set<String>allowed){for(String k:m.keySet())if(!allowed.contains(k))throw new Format("Unknown field "+k);}
 @SuppressWarnings("unchecked")private static Map<String,Object>cast(Object o){if(!(o instanceof Map<?,?>))throw new Format("Expected object");return(Map<String,Object>)o;}private static Map<String,Object>obj(Map<String,Object>m,String k){return cast(req(m,k));}@SuppressWarnings("unchecked")private static List<Object>list(Map<String,Object>m,String k){Object o=req(m,k);if(!(o instanceof List<?>))throw new Format("Expected array "+k);return(List<Object>)o;}private static List<String>stringList(Map<String,Object>m,String k){return list(m,k).stream().map(x->{if(!(x instanceof String s))throw new Format("Expected string");return s;}).toList();}private static Object req(Map<String,Object>m,String k){if(!m.containsKey(k))throw new Format("Missing "+k);return m.get(k);}private static String str(Map<String,Object>m,String k){Object o=req(m,k);if(!(o instanceof String s))throw new Format("Expected string "+k);return s;}private static String opt(Map<String,Object>m,String k){Object o=m.get(k);if(o==null)return null;if(!(o instanceof String s))throw new Format("Expected optional string "+k);return s;}private static int integer(Map<String,Object>m,String k){long v=lng(m,k);if(v<Integer.MIN_VALUE||v>Integer.MAX_VALUE)throw new Format("Integer range");return(int)v;}private static long lng(Map<String,Object>m,String k){Object o=req(m,k);if(!(o instanceof Number n))throw new Format("Expected number "+k);return n.longValue();}private static<E extends Enum<E>>E en(Class<E>t,String v){try{return Enum.valueOf(t,v);}catch(Exception e){throw new Format("Unknown enum "+v);}}
 private static void nullable(JsonGenerator g,String n,String v)throws IOException{if(v==null)g.writeNullProperty(n);else g.writeStringProperty(n,v);}private static void strings(JsonGenerator g,String n,List<String>v)throws IOException{g.writeArrayPropertyStart(n);for(String x:v.stream().distinct().sorted().toList())g.writeString(x);g.writeEndArray();}private static void enums(JsonGenerator g,String n,List<? extends Enum<?>>v)throws IOException{g.writeArrayPropertyStart(n);for(Enum<?>x:v.stream().sorted(java.util.Comparator.comparing(Enum::name)).toList())g.writeString(x.name());g.writeEndArray();}
 private static final class Bounded extends ByteArrayOutputStream{void check(int n){if(count+(long)n>MigrationStrictJson.MAX_BYTES)throw new Format("Checkpoint exceeds 16 MiB");}@Override public synchronized void write(int b){check(1);super.write(b);}@Override public synchronized void write(byte[]b,int o,int l){check(l);super.write(b,o,l);}}
 public static final class Format extends IllegalArgumentException{Format(String m){super(m);}Format(String m,Throwable c){super(m,c);}}
}
