package io.github.testlens.migration.tooling;

import tools.jackson.core.JsonParser;import tools.jackson.core.JsonToken;import tools.jackson.core.ObjectReadContext;import tools.jackson.core.StreamReadConstraints;import tools.jackson.core.StreamReadFeature;import tools.jackson.core.json.JsonFactory;
import java.io.ByteArrayInputStream;import java.io.IOException;import java.util.ArrayList;import java.util.LinkedHashMap;import java.util.List;import java.util.Map;

final class MigrationStrictJson{
 static final long MAX_BYTES=16L*1024*1024;private static final JsonFactory FACTORY=JsonFactory.builder().enable(StreamReadFeature.STRICT_DUPLICATE_DETECTION).streamReadConstraints(StreamReadConstraints.builder().maxDocumentLength(MAX_BYTES).maxNestingDepth(32).maxStringLength(65_536).maxNameLength(256).maxNumberLength(64).maxTokenCount(2_000_000).build()).build();private MigrationStrictJson(){}
 static Map<String,Object>object(byte[]bytes){if(bytes==null||bytes.length==0||bytes.length>MAX_BYTES)throw new Format("JSON input size is invalid");try(JsonParser p=FACTORY.createParser(ObjectReadContext.empty(),new ByteArrayInputStream(bytes))){if(p.nextToken()!=JsonToken.START_OBJECT)throw new Format("JSON root must be object");@SuppressWarnings("unchecked")Map<String,Object>r=(Map<String,Object>)read(p,0);if(p.nextToken()!=null)throw new Format("Trailing JSON content");return r;}catch(IOException e){throw new Format("Malformed JSON",e);}}
 private static Object read(JsonParser p,int depth)throws IOException{if(depth>32)throw new Format("JSON nesting exceeds limit");return switch(p.currentToken()){case START_OBJECT->{Map<String,Object>m=new LinkedHashMap<>();while(p.nextToken()!=JsonToken.END_OBJECT){String n=p.currentName();p.nextToken();m.put(n,read(p,depth+1));}yield m;}case START_ARRAY->{List<Object>l=new ArrayList<>();while(p.nextToken()!=JsonToken.END_ARRAY){if(l.size()>=200_000)throw new Format("JSON array exceeds limit");l.add(read(p,depth+1));}yield List.copyOf(l);}case VALUE_STRING->p.getString();case VALUE_NUMBER_INT->p.getLongValue();case VALUE_NUMBER_FLOAT->p.getDoubleValue();case VALUE_TRUE->true;case VALUE_FALSE->false;case VALUE_NULL->null;default->throw new Format("Unexpected JSON token");};}
 static final class Format extends IllegalArgumentException{Format(String m){super(m);}Format(String m,Throwable c){super(m,c);}}
}
