package io.github.testlens.migration.tooling;

import io.github.testlens.compatibility.engine.CompatibilityComparisonReport;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;

/** Content-derived result for one explicit verification attempt; source Apply is not repeated. */
public record MigrationVerificationResult(int schemaVersion,int algorithmVersion,String verificationResultId,
        String transactionId,String applyPlanId,String verificationPlanId,String sourceCheckpointRef,
        Status status,List<StageResult>stageResults,List<String>runResultRefs,List<String>manifestRefs,
        List<ComparisonResult>comparisonResults,List<ProposalResult>proposalResults,int requiredPassed,
        int requiredTotal,List<String>limitations,List<String>issues,String supersedesResultId){
    public MigrationVerificationResult{if(schemaVersion!=1||algorithmVersion!=1)throw new IllegalArgumentException("result version");MigrationApplyPlan.require(transactionId,"migration-apply-transaction-v1");MigrationApplyPlan.require(applyPlanId,"migration-apply-plan-v1");MigrationApplyPlan.require(verificationPlanId,"migration-verification-plan-v1");MigrationApplyPlan.require(sourceCheckpointRef,"migration-checkpoint-v1");Objects.requireNonNull(status);stageResults=stageResults==null?List.of():stageResults.stream().sorted(Comparator.comparingInt(x->x.stageType().ordinal())).toList();runResultRefs=strings(runResultRefs);manifestRefs=strings(manifestRefs);comparisonResults=comparisonResults==null?List.of():List.copyOf(comparisonResults);proposalResults=proposalResults==null?List.of():List.copyOf(proposalResults);limitations=strings(limitations);issues=strings(issues);if(stageResults.size()>MigrationVerificationPlan.MAX_STAGES||runResultRefs.size()>MigrationVerificationPlan.MAX_STAGES||manifestRefs.size()>MigrationVerificationPlan.MAX_ARTIFACT_REFS||comparisonResults.size()>MigrationVerificationPlan.MAX_COMPARISONS||proposalResults.size()>MigrationApplyPlan.MAX_PROPOSALS||issues.size()>MigrationVerificationPlan.MAX_ISSUES||limitations.size()>MigrationVerificationPlan.MAX_ISSUES||requiredPassed<0||requiredTotal<requiredPassed)throw new IllegalArgumentException("result bound");if(supersedesResultId!=null)MigrationApplyPlan.require(supersedesResultId,"migration-verification-result-v1");String e=id(transactionId,applyPlanId,verificationPlanId,sourceCheckpointRef,status,stageResults,runResultRefs,manifestRefs,comparisonResults,proposalResults,requiredPassed,requiredTotal,limitations,issues,supersedesResultId);if(!e.equals(verificationResultId))throw new IllegalArgumentException("verificationResultId");}
    public static MigrationVerificationResult create(String tx,String apply,String plan,String checkpoint,Status status,List<StageResult>stages,List<String>runs,List<String>manifests,List<ComparisonResult>comparisons,List<ProposalResult>proposals,List<String>limitations,List<String>issues,String supersedes){int total=(int)stages.stream().filter(x->x.necessity()==MigrationVerificationPlan.Necessity.REQUIRED).count(),passed=(int)stages.stream().filter(x->x.necessity()==MigrationVerificationPlan.Necessity.REQUIRED&&x.status()==StageStatus.PASSED).count();String id=id(tx,apply,plan,checkpoint,status,stages,runs,manifests,comparisons,proposals,passed,total,limitations,issues,supersedes);return new MigrationVerificationResult(1,1,id,tx,apply,plan,checkpoint,status,stages,runs,manifests,comparisons,proposals,passed,total,limitations,issues,supersedes);}
    public enum Status{VERIFIED,FAILED,INCONCLUSIVE,BLOCKED,INTERRUPTED}
    public enum StageStatus{NOT_REQUIRED,NOT_RUN,PASSED,FAILED,BLOCKED,INCONCLUSIVE,INTERRUPTED}
    public enum ProposalStatus{VERIFIED,FAILED,INCONCLUSIVE,BLOCKED}
    public record StageResult(String stageRef,MigrationVerificationPlan.StageType stageType,MigrationVerificationPlan.Necessity necessity,StageStatus status,String runResultRef,List<String>artifactRefs,List<String>issues){public StageResult{MigrationApplyPlan.require(stageRef,"migration-verification-stage-v1");Objects.requireNonNull(stageType);Objects.requireNonNull(necessity);Objects.requireNonNull(status);if(runResultRef!=null)MigrationApplyPlan.require(runResultRef,"migration-run-result-v1");artifactRefs=strings(artifactRefs);issues=strings(issues);}}
    public record ComparisonResult(String comparisonPlanRef,io.github.testlens.compatibility.engine.ComparisonIntent.Axis axis,CompatibilityComparisonReport.Outcome outcome,CompatibilityComparisonReport.Comparability comparability,StageStatus status,List<String>targetedFindingStates,List<String>issues){public ComparisonResult{MigrationApplyPlan.require(comparisonPlanRef,"migration-verification-comparison-v1");Objects.requireNonNull(axis);Objects.requireNonNull(outcome);Objects.requireNonNull(comparability);Objects.requireNonNull(status);targetedFindingStates=strings(targetedFindingStates);issues=strings(issues);}}
    public record ProposalResult(String proposalId,ProposalStatus status,List<String>stageRefs,List<String>issues){public ProposalResult{MigrationApplyPlan.require(proposalId,"migration-proposal-v1");Objects.requireNonNull(status);stageRefs=strings(stageRefs);issues=strings(issues);}}
    private static String id(String tx,String apply,String plan,String checkpoint,Status status,List<StageResult>s,List<String>runs,List<String>manifests,List<ComparisonResult>c,List<ProposalResult>p,int passed,int total,List<String>limitations,List<String>issues,String supersedes){List<String>f=new ArrayList<>(List.of(tx,apply,plan,checkpoint,status.name(),Integer.toString(passed),Integer.toString(total),supersedes==null?"":supersedes));s.forEach(x->{f.add(x.stageRef());f.add(x.status().name());f.add(x.runResultRef()==null?"":x.runResultRef());x.artifactRefs().forEach(f::add);x.issues().forEach(f::add);});strings(runs).forEach(f::add);strings(manifests).forEach(f::add);c.forEach(x->{f.add(x.comparisonPlanRef());f.add(x.outcome().name());f.add(x.comparability().name());f.add(x.status().name());});p.forEach(x->{f.add(x.proposalId());f.add(x.status().name());});strings(limitations).forEach(f::add);strings(issues).forEach(f::add);return MigrationVerificationPlan.ref("migration-verification-result-v1",f.toArray(String[]::new));}
    private static List<String>strings(List<String>v){return v==null?List.of():v.stream().filter(Objects::nonNull).distinct().sorted().toList();}
}
