package io.github.testlens.migration.tooling;

import java.nio.charset.StandardCharsets;

/** Deterministic standalone read-only HTML projection; exact diff/source bytes are never embedded. */
public final class MigrationApplyReportHtml{
    public byte[]render(MigrationApplyReport r){StringBuilder h=new StringBuilder("<!doctype html>\n<html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Migration Apply Report</title><style>body{font:14px system-ui;margin:2rem;max-width:1100px}table{border-collapse:collapse;width:100%;margin:1rem 0}th,td{border:1px solid #bbb;padding:.4rem;text-align:left;vertical-align:top}code{overflow-wrap:anywhere}.warn{color:#8a4800}.bad{color:#a00000}</style></head><body>\n");h.append("<h1>Migration Apply Report</h1><dl><dt>Report</dt><dd><code>").append(e(r.reportId())).append("</code></dd><dt>Status</dt><dd>").append(r.status()).append("</dd><dt>Current relation</dt><dd>").append(r.currentStateRelation()).append("</dd><dt>Manual commit</dt><dd>").append(r.commitReadiness().state()).append("</dd></dl>\n");
        h.append("<h2>Proposals</h2><table><thead><tr><th>ID</th><th>Category</th><th>Problem</th><th>Target</th><th>Verification</th></tr></thead><tbody>");for(var p:r.proposals())h.append("<tr><td><code>").append(e(p.proposalId())).append("</code></td><td>").append(p.category()).append("</td><td>").append(e(p.problemCode())).append("</td><td>").append(e(p.semanticTarget())).append("</td><td>").append(p.verificationStatus()==null?"NOT_RUN":p.verificationStatus()).append("</td></tr>");h.append("</tbody></table>\n");
        h.append("<h2>Apply files and rollback</h2><p>Owned diff: <code>").append(e(r.ownedDiffRef())).append("</code> / ").append(e(r.ownedDiffDigest())).append(" / ").append(r.ownedDiffBytes()).append(" bytes. Exact hunks are local-sensitive and intentionally omitted.</p><table><thead><tr><th>Path</th><th>Apply</th><th>Current</th><th>Rollback</th><th>Edits</th><th>Pre-dirty</th></tr></thead><tbody>");for(var f:r.files())h.append("<tr><td><code>").append(e(f.logicalPath())).append("</code></td><td>").append(f.applyStatus()).append("</td><td>").append(f.currentState()).append("</td><td>").append(f.rollbackState()).append("</td><td>").append(f.editCount()).append("</td><td>").append(f.preDirtyTouched()).append("</td></tr>");h.append("</tbody></table>\n");
        h.append("<h2>Verification coverage</h2><p>Required passed: ").append(r.verification().requiredPassed()).append(" / ").append(r.verification().requiredTotal()).append("; result: ").append(r.verification().status()==null?"NOT_RUN":r.verification().status()).append(".</p><table><thead><tr><th>Stage</th><th>Requirement</th><th>Status</th><th>Issues</th></tr></thead><tbody>");for(var s:r.verification().stages())h.append("<tr><td>").append(s.stageType()).append("</td><td>").append(s.necessity()).append("</td><td>").append(s.status()).append("</td><td>").append(e(String.join(", ",s.issues()))).append("</td></tr>");h.append("</tbody></table>\n");
        h.append("<h2>Compatibility</h2><table><thead><tr><th>Axis</th><th>Outcome</th><th>Comparability</th><th>Target findings</th></tr></thead><tbody>");for(var c:r.verification().comparisons())h.append("<tr><td>").append(c.axis()).append("</td><td>").append(c.outcome()).append("</td><td>").append(c.comparability()).append("</td><td>").append(e(String.join(", ",c.targetedFindingStates()))).append("</td></tr>");h.append("</tbody></table>\n");
        h.append("<h2>Recovery</h2><p>").append(r.recoverySummary().situation()).append("</p><ul>");for(var a:r.recoverySummary().availableActions())h.append("<li>").append(a).append(" (display only)</li>");h.append("</ul><h2>Next actions</h2><ul>");for(var a:r.nextActions())h.append("<li>").append(a).append("</li>");h.append("</ul><h2>Known NOT_RUN and limitations</h2><table><thead><tr><th>Gap</th><th>Status</th><th>Criticality</th><th>Reason</th></tr></thead><tbody>");for(var g:r.knownNotRun())h.append("<tr><td>").append(e(g.gapCode())).append("</td><td>").append(g.status()).append("</td><td>").append(g.criticality()).append("</td><td>").append(e(g.reason())).append("</td></tr>");h.append("</tbody></table><p>No actions are available from this document.</p></body></html>\n");byte[]b=h.toString().getBytes(StandardCharsets.UTF_8);if(b.length>MigrationApplyReport.MAX_BYTES)throw new IllegalArgumentException("OUTPUT_LIMIT_EXCEEDED");return b;}
    static String e(String s){if(s==null)return"";return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
}
