package io.github.testlens.migration.tooling;

import java.time.Instant;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/** Strict typed codec for executable S11 artifacts. Generic JSON maps never reach the writer. */
public final class MigrationApplyCodec {
    public static final int MAX_BYTES = 16 * 1024 * 1024;
    private final MigrationArtifactJson writer = new MigrationArtifactJson();
    public byte[] write(Object value) { byte[] bytes=writer.write(value);if(bytes.length>MAX_BYTES)throw new IllegalArgumentException("APPLY_LIMIT_EXCEEDED");return bytes; }
    public MigrationApplyPlan readPlan(byte[] bytes) {
        Map<String,Object>m=object(bytes);known(m,"schemaVersion","algorithmVersion","applyPlanId","repositoryBindingRef","worktreeBindingRef","proposalSetId","selectedProposalIds","decisionLedgerDigest","effectiveDecisionRefs","dependencyResolutionRefs","evidenceDigests","proposalCheckpointRef","preparationCheckpointRef","filePlans","verificationRequirementsDigest","backupBytes","targetBytes","finalDiffRef","finalDiffDigest","finalDiffBytes","finalDiffBudget","requiredCapabilities","limitations");
        List<MigrationApplyPlan.FilePlan>files=new ArrayList<>();for(Object raw:list(m,"filePlans")){Map<String,Object>f=map(raw);known(f,"logicalPath","originalSha256","proposedSha256","originalArtifact","proposedArtifact","approvedRanges","sourcePreconditionDigests","proposalIds","metadata","writeRequired");List<MigrationApplyPlan.ApprovedRange>ranges=new ArrayList<>();for(Object rr:list(f,"approvedRanges")){Map<String,Object>r=map(rr);known(r,"startUtf16","endUtf16Exclusive","originalConstructDigest","replacementDigest","semanticBeforeRef","semanticAfterRef");ranges.add(new MigrationApplyPlan.ApprovedRange(integer(r,"startUtf16"),integer(r,"endUtf16Exclusive"),str(r,"originalConstructDigest"),str(r,"replacementDigest"),str(r,"semanticBeforeRef"),str(r,"semanticAfterRef")));}Map<String,Object>md=map(req(f,"metadata"));known(md,"dosReadOnly","posixPermissions");files.add(new MigrationApplyPlan.FilePlan(str(f,"logicalPath"),str(f,"originalSha256"),str(f,"proposedSha256"),artifact(map(req(f,"originalArtifact"))),artifact(map(req(f,"proposedArtifact"))),ranges,strings(f,"sourcePreconditionDigests"),strings(f,"proposalIds"),new MigrationApplyPlan.Metadata(bool(md,"dosReadOnly"),strings(md,"posixPermissions")),bool(f,"writeRequired")));}
        return new MigrationApplyPlan(integer(m,"schemaVersion"),integer(m,"algorithmVersion"),str(m,"applyPlanId"),str(m,"repositoryBindingRef"),str(m,"worktreeBindingRef"),str(m,"proposalSetId"),strings(m,"selectedProposalIds"),str(m,"decisionLedgerDigest"),strings(m,"effectiveDecisionRefs"),strings(m,"dependencyResolutionRefs"),strings(m,"evidenceDigests"),str(m,"proposalCheckpointRef"),str(m,"preparationCheckpointRef"),files,str(m,"verificationRequirementsDigest"),lng(m,"backupBytes"),lng(m,"targetBytes"),str(m,"finalDiffRef"),str(m,"finalDiffDigest"),lng(m,"finalDiffBytes"),lng(m,"finalDiffBudget"),strings(m,"requiredCapabilities"),strings(m,"limitations"));
    }
    public MigrationDependencyResolution readResolution(byte[]bytes){Map<String,Object>m=object(bytes);known(m,"schemaVersion","algorithmVersion","resolutionId","proposalId","dependencyCode","dependencySemanticRef","resolutionType","checkpointRef","evidenceDigests","relatedProposalId","hostProvenance","limitations");return new MigrationDependencyResolution(integer(m,"schemaVersion"),integer(m,"algorithmVersion"),str(m,"resolutionId"),str(m,"proposalId"),en(MigrationProposalSet.DependencyCode.class,str(m,"dependencyCode")),str(m,"dependencySemanticRef"),en(MigrationDependencyResolution.ResolutionType.class,str(m,"resolutionType")),str(m,"checkpointRef"),strings(m,"evidenceDigests"),opt(m,"relatedProposalId"),str(m,"hostProvenance"),strings(m,"limitations"));}
    public MigrationApplyTransaction.Event readEvent(byte[]bytes){Map<String,Object>m=object(bytes);known(m,"schemaVersion","algorithmVersion","eventDigest","previousEventDigest","transactionId","sequence","type","logicalPath","observedDigest","issue","operationalTimestamp");return new MigrationApplyTransaction.Event(integer(m,"schemaVersion"),integer(m,"algorithmVersion"),str(m,"eventDigest"),opt(m,"previousEventDigest"),str(m,"transactionId"),lng(m,"sequence"),en(MigrationApplyTransaction.EventType.class,str(m,"type")),opt(m,"logicalPath"),opt(m,"observedDigest"),opt(m,"issue"),Instant.parse(str(m,"operationalTimestamp")));}
    public MigrationApplyTransaction.OwnershipRegistry readRegistry(byte[]bytes){Map<String,Object>m=object(bytes);known(m,"schemaVersion","algorithmVersion","registryDigest","transactionId","applyPlanId","files");List<MigrationApplyTransaction.OwnershipFile>files=new ArrayList<>();for(Object raw:list(m,"files")){Map<String,Object>f=map(raw);known(f,"logicalPath","originalSha256","proposedSha256","originalArtifactRef","proposedArtifactRef","proposalIds","approvedRanges","metadata");List<MigrationApplyPlan.ApprovedRange>ranges=new ArrayList<>();for(Object rr:list(f,"approvedRanges")){Map<String,Object>r=map(rr);known(r,"startUtf16","endUtf16Exclusive","originalConstructDigest","replacementDigest","semanticBeforeRef","semanticAfterRef");ranges.add(new MigrationApplyPlan.ApprovedRange(integer(r,"startUtf16"),integer(r,"endUtf16Exclusive"),str(r,"originalConstructDigest"),str(r,"replacementDigest"),str(r,"semanticBeforeRef"),str(r,"semanticAfterRef")));}Map<String,Object>md=map(req(f,"metadata"));known(md,"dosReadOnly","posixPermissions");files.add(new MigrationApplyTransaction.OwnershipFile(str(f,"logicalPath"),str(f,"originalSha256"),str(f,"proposedSha256"),str(f,"originalArtifactRef"),str(f,"proposedArtifactRef"),strings(f,"proposalIds"),ranges,new MigrationApplyPlan.Metadata(bool(md,"dosReadOnly"),strings(md,"posixPermissions"))));}return new MigrationApplyTransaction.OwnershipRegistry(integer(m,"schemaVersion"),integer(m,"algorithmVersion"),str(m,"registryDigest"),str(m,"transactionId"),str(m,"applyPlanId"),files);}
    private static MigrationApplyPlan.SourceArtifact artifact(Map<String,Object>m){known(m,"logicalRef","sha256","byteCount");return new MigrationApplyPlan.SourceArtifact(str(m,"logicalRef"),str(m,"sha256"),lng(m,"byteCount"));}
    private static Map<String,Object>object(byte[]bytes){return MigrationStrictJson.object(bytes,MAX_BYTES);}
    private static void known(Map<String,Object>m,String...names){Set<String>a=Set.of(names);for(String k:m.keySet())if(!a.contains(k))throw new IllegalArgumentException("unknown field "+k);for(String n:names)if(!m.containsKey(n))throw new IllegalArgumentException("missing field "+n);}
    @SuppressWarnings("unchecked")private static Map<String,Object>map(Object o){if(!(o instanceof Map<?,?>))throw new IllegalArgumentException("object required");return(Map<String,Object>)o;}
    @SuppressWarnings("unchecked")private static List<Object>list(Map<String,Object>m,String k){Object o=req(m,k);if(!(o instanceof List<?>))throw new IllegalArgumentException("array required");return(List<Object>)o;}
    private static List<String>strings(Map<String,Object>m,String k){return list(m,k).stream().map(x->{if(!(x instanceof String s))throw new IllegalArgumentException("string required");return s;}).toList();}
    private static Object req(Map<String,Object>m,String k){if(!m.containsKey(k))throw new IllegalArgumentException("missing "+k);return m.get(k);}
    private static String str(Map<String,Object>m,String k){Object o=req(m,k);if(!(o instanceof String s))throw new IllegalArgumentException("string "+k);return s;}
    private static String opt(Map<String,Object>m,String k){Object o=req(m,k);if(o==null)return null;if(!(o instanceof String s))throw new IllegalArgumentException("string "+k);return s;}
    private static long lng(Map<String,Object>m,String k){Object o=req(m,k);if(!(o instanceof Number n))throw new IllegalArgumentException("number "+k);return n.longValue();}
    private static int integer(Map<String,Object>m,String k){long v=lng(m,k);if(v<Integer.MIN_VALUE||v>Integer.MAX_VALUE)throw new IllegalArgumentException("integer range");return(int)v;}
    private static boolean bool(Map<String,Object>m,String k){Object o=req(m,k);if(!(o instanceof Boolean b))throw new IllegalArgumentException("boolean "+k);return b;}
    private static<E extends Enum<E>>E en(Class<E>t,String v){try{return Enum.valueOf(t,v);}catch(RuntimeException e){throw new IllegalArgumentException("unknown enum "+v,e);}}
}
