package io.github.testlens.migration.tooling;

import java.io.IOException;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/** Explicit B3 orchestration: authorize, run, validate artifacts, then checkpoint fresh Git/source state. */
public final class MigrationRunOrchestrator {
    private final MigrationGitService git;private final MigrationTrustedProcessRunner runner;private final MigrationRunArtifactValidator artifacts=new MigrationRunArtifactValidator();
    public MigrationRunOrchestrator(){this(new MigrationGitService(),new MigrationTrustedProcessRunner());}
    public MigrationRunOrchestrator(MigrationGitService git,MigrationTrustedProcessRunner runner){this.git=git;this.runner=runner;}
    public Result execute(MigrationRunPlan plan,MigrationCheckpoint before,MigrationStateStore store,MigrationTrustedProcessRunner.LocalExecution local,MigrationAuthorization authorization,MigrationTrustedProcessRunner.Cancellation cancellation)throws IOException{
        if(!before.checkpointId().equals(plan.checkpointRef()))return safeStop(plan,before,"CHECKPOINT_REF_MISMATCH");MigrationGitService.Result inspected=git.inspect(local.workingDirectory());if(inspected.localContext()==null||!inspected.preflight().worktreeBindingRef().equals(local.worktreeBindingRef())||!before.repositoryBindingRef().equals(inspected.preflight().repositoryBindingRef()))return safeStop(plan,before,"REPOSITORY_OR_WORKTREE_BINDING_CHANGED");
        Map<String,MigrationRunArtifactValidator.Snapshot>snapshot;try{snapshot=artifacts.snapshot(plan,inspected.localContext().worktreeRoot(),store.root());}catch(IOException|IllegalArgumentException e){return safeStop(plan,before,"ARTIFACT_PRECHECK_FAILED:"+e.getClass().getSimpleName());}MigrationTrustedProcessRunner.Raw raw=runner.run(plan,local,authorization,cancellation);List<MigrationRunResult.ArtifactResult>validated=artifacts.validate(plan,inspected.localContext().worktreeRoot(),store.root(),snapshot);MigrationGitService.Result fresh=git.inspect(local.workingDirectory());List<String>issues=new ArrayList<>(raw.issues());String afterRef=null;
        if(fresh.localContext()!=null){MigrationCheckpoint after=MigrationCheckpoint.create(fresh.preflight(),fresh.sourceState(),before.configuration(),before.artifacts(),before.proposalSetRef(),before.decisionsRef());store.write(after);afterRef=after.checkpointId();if(!before.sourceState().sourceStateDigest().equals(fresh.sourceState().sourceStateDigest()))issues.add("SOURCE_STATE_CHANGED_BY_RUN");}
        boolean invalid=validated.stream().anyMatch(x->!List.of(MigrationRunResult.ArtifactStatus.VALID,MigrationRunResult.ArtifactStatus.OPTIONAL_ABSENT).contains(x.status()));MigrationRunResult.Status status=switch(raw.status()){case SAFE_STOP->MigrationRunResult.Status.SAFE_STOP;case START_FAILED->MigrationRunResult.Status.START_FAILED;case TIMED_OUT->MigrationRunResult.Status.TIMED_OUT;case CANCELLED->MigrationRunResult.Status.CANCELLED;case FINISHED->invalid?MigrationRunResult.Status.ARTIFACT_VALIDATION_FAILED:raw.exitCode()!=null&&raw.exitCode()==0?MigrationRunResult.Status.SUCCESS:MigrationRunResult.Status.FAILED;};if(issues.contains("SOURCE_STATE_CHANGED_BY_RUN")&&status==MigrationRunResult.Status.SUCCESS)status=MigrationRunResult.Status.ARTIFACT_VALIDATION_FAILED;
        MigrationRunResult result=MigrationRunResult.create(plan.planId(),before.checkpointId(),raw.started(),raw.ended(),status,raw.exitCode(),summary(raw.stdout(),raw.stdoutCount(),raw.stdoutTruncated()),summary(raw.stderr(),raw.stderrCount(),raw.stderrTruncated()),raw.termination(),validated,afterRef,plan.requiredApprovals().stream().filter(authorization::allows).map(Enum::name).toList(),issues);return new Result(result,raw.stdout(),raw.stderr());
    }
    /** Conservative resume classification for a plan left RUNNING when the prior host process disappeared. */
    public MigrationRunResult.Status classifyInterrupted(MigrationRunPlan plan,MigrationCheckpoint before,MigrationStateStore store,Path workingDirectory)throws IOException{var inspected=git.inspect(workingDirectory);if(inspected.localContext()==null||!before.repositoryBindingRef().equals(inspected.preflight().repositoryBindingRef()))return MigrationRunResult.Status.UNKNOWN_COMPLETION;Map<String,MigrationRunArtifactValidator.Snapshot>empty=new java.util.HashMap<>();for(var a:plan.expectedArtifacts())empty.put(a.logicalPath(),new MigrationRunArtifactValidator.Snapshot(false,null,0));List<MigrationRunResult.ArtifactResult>r=artifacts.validate(plan,inspected.localContext().worktreeRoot(),store.root(),empty);long present=r.stream().filter(x->x.status()!=MigrationRunResult.ArtifactStatus.MISSING&&x.status()!=MigrationRunResult.ArtifactStatus.OPTIONAL_ABSENT).count();return present==0?MigrationRunResult.Status.INTERRUPTED:present==r.size()?MigrationRunResult.Status.UNKNOWN_COMPLETION:MigrationRunResult.Status.ARTIFACTS_PARTIAL;}
    private static MigrationRunResult.OutputSummary summary(byte[]retained,long total,boolean truncated){return new MigrationRunResult.OutputSummary(MigrationDigests.rawBytes(retained),total,truncated,"");}
    private static Result safeStop(MigrationRunPlan plan,MigrationCheckpoint before,String issue){Instant now=Instant.now();var empty=new MigrationRunResult.OutputSummary(MigrationDigests.rawBytes(new byte[0]),0,false,"");return new Result(MigrationRunResult.create(plan.planId(),before.checkpointId(),now,now,MigrationRunResult.Status.SAFE_STOP,null,empty,empty,MigrationRunResult.ProcessTreeTermination.NOT_STARTED,List.of(),null,List.of(),List.of(issue)),new byte[0],new byte[0]);}
    /** Raw bounded output is deliberately ephemeral; persistence is a separate explicit state-store action. */
    public record Result(MigrationRunResult durableResult,byte[]boundedStdout,byte[]boundedStderr){public Result{boundedStdout=boundedStdout.clone();boundedStderr=boundedStderr.clone();}public byte[]boundedStdout(){return boundedStdout.clone();}public byte[]boundedStderr(){return boundedStderr.clone();}}
}
