package io.github.testlens.migration.tooling;

import io.github.testlens.compatibility.engine.ComparisonIntent;
import io.github.testlens.compatibility.engine.CompatibilityComparisonReport;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;

/** Strict bounded Jackson-Core codec for read-only final migration reports. */
public final class MigrationApplyReportJson{
    private final MigrationArtifactJson writer=new MigrationArtifactJson();
    public byte[]write(MigrationApplyReport report){byte[]b=writer.write(report);if(b.length>MigrationApplyReport.MAX_BYTES)throw new IllegalArgumentException("OUTPUT_LIMIT_EXCEEDED");return b;}
    public MigrationApplyReport read(byte[]bytes){Map<String,Object>r=MigrationStrictJson.object(bytes,MigrationApplyReport.MAX_BYTES);exact(r,"schemaVersion","algorithmVersion","reportId","repositoryBindingRef","worktreeBindingRef","proposalSetRef","selectedProposalIds","decisionRefs","applyPlanRef","transactionRef","status","applyStatus","proposals","files","transactionEvents","postApplyCheckpointRef","recoverySummary","recoveryActionPlanRef","verification","acceptedVerificationResultRef","verificationHistoryRefs","compatibilityEvidenceRefs","ownedDiffRef","ownedDiffDigest","ownedDiffBytes","preExistingUserState","currentIndex","currentStateRelation","commitReadiness","nextActions","limitations","knownNotRun","issues","releaseHardeningHandoffRef");return new MigrationApplyReport(integer(r,"schemaVersion"),integer(r,"algorithmVersion"),str(r,"reportId"),str(r,"repositoryBindingRef"),str(r,"worktreeBindingRef"),str(r,"proposalSetRef"),strings(r,"selectedProposalIds"),strings(r,"decisionRefs"),str(r,"applyPlanRef"),str(r,"transactionRef"),en(r,"status",MigrationApplyReport.Status.class),en(r,"applyStatus",MigrationApplyResult.Status.class),objects(r,"proposals").stream().map(this::proposal).toList(),objects(r,"files").stream().map(this::file).toList(),objects(r,"transactionEvents").stream().map(this::event).toList(),opt(r,"postApplyCheckpointRef"),recovery(map(req(r,"recoverySummary"))),str(r,"recoveryActionPlanRef"),verification(map(req(r,"verification"))),opt(r,"acceptedVerificationResultRef"),strings(r,"verificationHistoryRefs"),strings(r,"compatibilityEvidenceRefs"),str(r,"ownedDiffRef"),str(r,"ownedDiffDigest"),lng(r,"ownedDiffBytes"),pre(map(req(r,"preExistingUserState"))),index(map(req(r,"currentIndex"))),en(r,"currentStateRelation",MigrationApplyReport.CurrentStateRelation.class),readiness(map(req(r,"commitReadiness"))),ens(r,"nextActions",MigrationApplyReport.NextAction.class),strings(r,"limitations"),objects(r,"knownNotRun").stream().map(this::gap).toList(),strings(r,"issues"),str(r,"releaseHardeningHandoffRef"));}
    private MigrationApplyReport.ProposalSummary proposal(Map<String,Object>m){exact(m,"proposalId","category","problemCode","semanticTarget","requiredStageRefs","verificationStatus");return new MigrationApplyReport.ProposalSummary(str(m,"proposalId"),en(m,"category",MigrationProposal.Category.class),str(m,"problemCode"),str(m,"semanticTarget"),strings(m,"requiredStageRefs"),optEn(m,"verificationStatus",MigrationVerificationResult.ProposalStatus.class));}
    private MigrationApplyReport.FileSummary file(Map<String,Object>m){exact(m,"logicalPath","applyStatus","currentState","rollbackState","observedDigest","editCount","preDirtyTouched","backupValid","proposalIds","issues");return new MigrationApplyReport.FileSummary(str(m,"logicalPath"),en(m,"applyStatus",MigrationApplyResult.FileStatus.class),en(m,"currentState",MigrationApplyReport.CurrentFileState.class),en(m,"rollbackState",MigrationApplyReport.RollbackState.class),opt(m,"observedDigest"),integer(m,"editCount"),bool(m,"preDirtyTouched"),bool(m,"backupValid"),strings(m,"proposalIds"),strings(m,"issues"));}
    private MigrationApplyReport.TransactionEventSummary event(Map<String,Object>m){exact(m,"sequence","type","logicalPath","observedDigest","issue");return new MigrationApplyReport.TransactionEventSummary(lng(m,"sequence"),en(m,"type",MigrationApplyTransaction.EventType.class),opt(m,"logicalPath"),opt(m,"observedDigest"),opt(m,"issue"));}
    private MigrationRecoverySummary recovery(Map<String,Object>m){exact(m,"situation","files","availableActions","issues");return new MigrationRecoverySummary(en(m,"situation",MigrationRecoverySummary.Situation.class),objects(m,"files").stream().map(x->{exact(x,"logicalPath","state","rollbackAvailable","reason");return new MigrationRecoverySummary.FileRecovery(str(x,"logicalPath"),en(x,"state",MigrationRecoveryPlan.TargetState.class),bool(x,"rollbackAvailable"),str(x,"reason"));}).toList(),ens(m,"availableActions",MigrationRecoveryActionPlan.Action.class),strings(m,"issues"));}
    private MigrationApplyReport.VerificationCoverage verification(Map<String,Object>m){exact(m,"verificationPlanRef","verificationResultRef","status","requiredPassed","requiredTotal","stages","proposals","comparisons");return new MigrationApplyReport.VerificationCoverage(opt(m,"verificationPlanRef"),opt(m,"verificationResultRef"),optEn(m,"status",MigrationVerificationResult.Status.class),integer(m,"requiredPassed"),integer(m,"requiredTotal"),objects(m,"stages").stream().map(this::stage).toList(),objects(m,"proposals").stream().map(this::proposalCoverage).toList(),objects(m,"comparisons").stream().map(this::comparison).toList());}
    private MigrationApplyReport.StageCoverage stage(Map<String,Object>m){exact(m,"stageRef","stageType","necessity","status","issues");return new MigrationApplyReport.StageCoverage(str(m,"stageRef"),en(m,"stageType",MigrationVerificationPlan.StageType.class),en(m,"necessity",MigrationVerificationPlan.Necessity.class),en(m,"status",MigrationVerificationResult.StageStatus.class),strings(m,"issues"));}
    private MigrationApplyReport.ProposalCoverage proposalCoverage(Map<String,Object>m){exact(m,"proposalId","status","stageRefs","issues");return new MigrationApplyReport.ProposalCoverage(str(m,"proposalId"),en(m,"status",MigrationVerificationResult.ProposalStatus.class),strings(m,"stageRefs"),strings(m,"issues"));}
    private MigrationApplyReport.CompatibilityCoverage comparison(Map<String,Object>m){exact(m,"comparisonPlanRef","axis","outcome","comparability","status","targetedFindingStates","issues");return new MigrationApplyReport.CompatibilityCoverage(str(m,"comparisonPlanRef"),en(m,"axis",ComparisonIntent.Axis.class),en(m,"outcome",CompatibilityComparisonReport.Outcome.class),en(m,"comparability",CompatibilityComparisonReport.Comparability.class),en(m,"status",MigrationVerificationResult.StageStatus.class),strings(m,"targetedFindingStates"),strings(m,"issues"));}
    private MigrationApplyReport.PreExistingUserState pre(Map<String,Object>m){exact(m,"staged","unstaged","untracked","conflicted");return new MigrationApplyReport.PreExistingUserState(strings(m,"staged"),strings(m,"unstaged"),strings(m,"untracked"),strings(m,"conflicted"));}
    private MigrationApplyReport.IndexState index(Map<String,Object>m){exact(m,"staged","unstaged","untracked","conflicted");return new MigrationApplyReport.IndexState(strings(m,"staged"),strings(m,"unstaged"),strings(m,"untracked"),strings(m,"conflicted"));}
    private MigrationCommitReadiness readiness(Map<String,Object>m){exact(m,"state","reasons","guidance","suggestedMessage");return new MigrationCommitReadiness(en(m,"state",MigrationCommitReadiness.State.class),strings(m,"reasons"),strings(m,"guidance"),opt(m,"suggestedMessage"));}
    private MigrationReleaseGap gap(Map<String,Object>m){exact(m,"gapCode","stage","status","reason","criticality","owner","evidenceRef");return new MigrationReleaseGap(str(m,"gapCode"),en(m,"stage",MigrationReleaseGap.Stage.class),en(m,"status",MigrationReleaseGap.Status.class),str(m,"reason"),en(m,"criticality",MigrationReleaseGap.Criticality.class),str(m,"owner"),opt(m,"evidenceRef"));}
    private static void exact(Map<String,Object>m,String...names){Set<String>s=Set.of(names);if(!m.keySet().equals(s))throw new IllegalArgumentException("report fields mismatch");}private static Object req(Map<String,Object>m,String k){if(!m.containsKey(k))throw new IllegalArgumentException("missing "+k);return m.get(k);}private static String str(Map<String,Object>m,String k){Object o=req(m,k);if(!(o instanceof String s))throw new IllegalArgumentException("string "+k);return s;}private static String opt(Map<String,Object>m,String k){Object o=req(m,k);if(o==null)return null;if(!(o instanceof String s))throw new IllegalArgumentException("string "+k);return s;}private static long lng(Map<String,Object>m,String k){Object o=req(m,k);if(!(o instanceof Number n))throw new IllegalArgumentException("number "+k);return n.longValue();}private static int integer(Map<String,Object>m,String k){long n=lng(m,k);if(n<0||n>Integer.MAX_VALUE)throw new IllegalArgumentException("integer "+k);return(int)n;}private static boolean bool(Map<String,Object>m,String k){Object o=req(m,k);if(!(o instanceof Boolean b))throw new IllegalArgumentException("boolean "+k);return b;}@SuppressWarnings("unchecked")private static Map<String,Object>map(Object o){if(!(o instanceof Map<?,?>))throw new IllegalArgumentException("object");return(Map<String,Object>)o;}@SuppressWarnings("unchecked")private static List<Object>list(Map<String,Object>m,String k){Object o=req(m,k);if(!(o instanceof List<?>l))throw new IllegalArgumentException("array "+k);return(List<Object>)l;}private static List<Map<String,Object>>objects(Map<String,Object>m,String k){return list(m,k).stream().map(MigrationApplyReportJson::map).toList();}private static List<String>strings(Map<String,Object>m,String k){return list(m,k).stream().map(x->{if(!(x instanceof String s))throw new IllegalArgumentException("string array");return s;}).toList();}private static<E extends Enum<E>>E en(Map<String,Object>m,String k,Class<E>t){return value(str(m,k),t);}private static<E extends Enum<E>>E optEn(Map<String,Object>m,String k,Class<E>t){String v=opt(m,k);return v==null?null:value(v,t);}private static<E extends Enum<E>>List<E>ens(Map<String,Object>m,String k,Class<E>t){List<E>r=new ArrayList<>();for(String v:strings(m,k))r.add(value(v,t));return List.copyOf(r);}private static<E extends Enum<E>>E value(String v,Class<E>t){try{return Enum.valueOf(t,v);}catch(RuntimeException e){throw new IllegalArgumentException("enum "+v,e);}}
}
