package io.github.testlens.migration.tooling;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** Durable semantic checkpoint. It contains no absolute repository paths. */
public record MigrationCheckpoint(int schemaVersion,int algorithmVersion,String checkpointId,
        String repositoryBindingRef,String worktreeBindingRef,Head head,List<MigrationGitPreflight.GitOperation>gitOperations,
        String statusSnapshotDigest,MigrationSourceStateFingerprint sourceState,Configuration configuration,
        List<MigrationArtifactRef>artifacts,String proposalSetRef,String decisionsRef,
        Completeness completeness,List<String>issues){
    public static final int SCHEMA_VERSION=1,ALGORITHM_VERSION=1,MAX_ARTIFACTS=10_000;
    public MigrationCheckpoint{if(schemaVersion!=1||algorithmVersion!=1)throw new IllegalArgumentException("unsupported checkpoint version");if(checkpointId==null||!checkpointId.matches("migration-checkpoint-v1:sha256:[0-9a-f]{64}"))throw new IllegalArgumentException("checkpointId");binding(repositoryBindingRef,"migration-repository-binding-v1");binding(worktreeBindingRef,"migration-worktree-binding-v1");if(statusSnapshotDigest==null||!statusSnapshotDigest.matches("migration-status-v1:sha256:[0-9a-f]{64}"))throw new IllegalArgumentException("statusSnapshotDigest");Objects.requireNonNull(head);gitOperations=gitOperations.stream().distinct().sorted(java.util.Comparator.comparing(Enum::name)).toList();Objects.requireNonNull(sourceState);Objects.requireNonNull(configuration);artifacts=artifacts.stream().sorted(java.util.Comparator.comparing(MigrationArtifactRef::logicalRef)).toList();if(artifacts.size()>MAX_ARTIFACTS)throw new IllegalArgumentException("artifact bound");Objects.requireNonNull(completeness);issues=issues==null?List.of():issues.stream().distinct().sorted().toList();if(issues.size()>256||issues.stream().anyMatch(x->x==null||x.length()>8_192||x.indexOf('\0')>=0))throw new IllegalArgumentException("issue bound");String expected=id(repositoryBindingRef,worktreeBindingRef,head,gitOperations,statusSnapshotDigest,sourceState,configuration,artifacts,proposalSetRef,decisionsRef,completeness,issues);if(!expected.equals(checkpointId))throw new IllegalArgumentException("checkpointId does not match semantic content");}
    public enum Completeness{COMPLETE,INCOMPLETE}
    public enum IntendedMode{PREFLIGHT_ONLY,BASELINE_PREPARATION,MIGRATION_REVIEW}
    public enum StateStorage{EXPLICIT_TRUSTED_ROOT,IGNORED_PROJECT_TARGET,EXTERNAL_TOOL_ROOT}
    public record Head(MigrationGitPreflight.HeadState state,String commit,String tree,String branch){public Head{Objects.requireNonNull(state);}}
    public record Configuration(MigrationIsolationPlan.Choice isolationChoice,IntendedMode intendedMode,StateStorage stateStorage,String configurationDigest){public Configuration{Objects.requireNonNull(isolationChoice);Objects.requireNonNull(intendedMode);Objects.requireNonNull(stateStorage);String expected="migration-configuration-v1:sha256:"+MigrationDigests.digest("migration-configuration-v1",isolationChoice.name(),intendedMode.name(),stateStorage.name());if(!expected.equals(configurationDigest))throw new IllegalArgumentException("configurationDigest");}public static Configuration create(MigrationIsolationPlan.Choice choice,IntendedMode mode,StateStorage storage){return new Configuration(choice,mode,storage,"migration-configuration-v1:sha256:"+MigrationDigests.digest("migration-configuration-v1",choice.name(),mode.name(),storage.name()));}}
    public static MigrationCheckpoint create(MigrationGitPreflight p,MigrationSourceStateFingerprint source,Configuration configuration,List<MigrationArtifactRef>artifacts,String proposalSetRef,String decisionsRef){Head h=new Head(p.head().state(),p.head().commit(),p.head().tree(),p.head().branch());String status=statusDigest(p);Completeness c=p.completeness()==MigrationGitPreflight.Completeness.COMPLETE&&source.completeness()==MigrationSourceStateFingerprint.Completeness.COMPLETE?Completeness.COMPLETE:Completeness.INCOMPLETE;List<String>issues=new ArrayList<>();p.issues().forEach(i->issues.add(i.code()));issues.addAll(source.issues());String id=id(p.repositoryBindingRef(),p.worktreeBindingRef(),h,p.ongoingOperations(),status,source,configuration,artifacts,proposalSetRef,decisionsRef,c,issues);return new MigrationCheckpoint(1,1,id,p.repositoryBindingRef(),p.worktreeBindingRef(),h,p.ongoingOperations(),status,source,configuration,artifacts,proposalSetRef,decisionsRef,c,issues);}
    static String statusDigest(MigrationGitPreflight p){List<String>f=new ArrayList<>();add(f,"S",p.staged());add(f,"W",p.unstaged());add(f,"U",p.untracked());add(f,"C",p.conflicted());p.renamesAndCopies().stream().sorted(java.util.Comparator.comparing(MigrationGitPreflight.RenameCopy::logicalPath).thenComparing(MigrationGitPreflight.RenameCopy::originalLogicalPath)).forEach(x->{f.add("R");f.add(x.kind().name());f.add(x.originalLogicalPath());f.add(x.logicalPath());});return"migration-status-v1:sha256:"+MigrationDigests.digest("migration-status-v1",f.toArray(String[]::new));}
    private static void add(List<String>out,String role,List<MigrationGitPreflight.StatusEntry>entries){entries.stream().sorted(java.util.Comparator.comparing(MigrationGitPreflight.StatusEntry::logicalPath)).forEach(x->{out.add(role);out.add(x.logicalPath());out.add(x.kind().name());out.add(n(x.indexCode()));out.add(n(x.worktreeCode()));out.add(n(x.indexMode()));out.add(n(x.indexObjectId()));});}
    private static String id(String repo,String worktree,Head head,List<MigrationGitPreflight.GitOperation>ops,String status,MigrationSourceStateFingerprint source,Configuration config,List<MigrationArtifactRef>artifacts,String proposals,String decisions,Completeness completeness,List<String>issues){List<String>f=new ArrayList<>(List.of(repo,worktree,head.state().name(),n(head.commit()),n(head.tree()),n(head.branch()),status,source.sourceStateDigest(),config.configurationDigest(),completeness.name(),n(proposals),n(decisions)));ops.stream().map(Enum::name).sorted().forEach(f::add);artifacts.stream().sorted(java.util.Comparator.comparing(MigrationArtifactRef::logicalRef)).forEach(a->{f.add("ARTIFACT");f.add(a.type().name());f.add(Integer.toString(a.schemaVersion()));f.add(a.digest());f.add(a.logicalRef());f.add(a.completeness().name());});issues.stream().sorted().forEach(issue->{f.add("ISSUE");f.add(issue);});return"migration-checkpoint-v1:sha256:"+MigrationDigests.digest("migration-checkpoint-v1",f.toArray(String[]::new));}
    private static void binding(String value,String domain){if(value==null||!value.matches(java.util.regex.Pattern.quote(domain)+":sha256:[0-9a-f]{64}"))throw new IllegalArgumentException(domain);}
    private static String n(String v){return v==null?"":v;}
}
