package io.github.testlens.migration.tooling;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/** Non-executing orchestration extension to the S10 dry-run. Secret values and exact source patches are absent. */
public record MigrationOrchestrationDryRunReport(String orchestrationDryRunId,String proposalDryRunRef,List<RunPlanView>runPlans,List<GitActionView>gitActions,List<String>limitations){
    public MigrationOrchestrationDryRunReport{runPlans=runPlans==null?List.of():runPlans.stream().sorted(Comparator.comparing(RunPlanView::planId)).toList();gitActions=gitActions==null?List.of():gitActions.stream().sorted(Comparator.comparing(x->x.operation().name())).toList();limitations=limitations==null?List.of():limitations.stream().distinct().sorted().toList();String expected=id(proposalDryRunRef,runPlans,gitActions,limitations);if(!expected.equals(orchestrationDryRunId))throw new IllegalArgumentException("orchestrationDryRunId");}
    public record RunPlanView(String planId,String executableRef,List<String>arguments,List<String>environmentKeyNames,List<String>secretReferenceNames,MigrationRunPlan.SideEffectClassification sideEffect,List<String>requiredCapabilities,List<String>expectedArtifacts,MigrationRunPlan.BaselineRole baselineRole){public RunPlanView{arguments=List.copyOf(arguments);environmentKeyNames=environmentKeyNames.stream().sorted().toList();secretReferenceNames=secretReferenceNames.stream().sorted().toList();requiredCapabilities=requiredCapabilities.stream().sorted().toList();expectedArtifacts=expectedArtifacts.stream().sorted().toList();}}
    public record GitActionView(MigrationGitIsolationAction.Operation operation,String branch,String exactBaseCommit,String trustedDestinationDisplay,MigrationGitIsolationAction.StashScope stashScope,List<String>requiredCapabilities){public GitActionView{requiredCapabilities=requiredCapabilities.stream().sorted().toList();}}
    public static MigrationOrchestrationDryRunReport create(String proposalDryRunRef,List<MigrationRunPlan>plans,List<GitActionView>actions,List<String>limitations){List<RunPlanView>views=plans.stream().map(p->new RunPlanView(p.planId(),p.executableRef(),p.args(),p.environmentOverlay().keySet().stream().map(MigrationRunPlan.EnvironmentKey::processName).toList(),p.secretReferenceNames(),p.sideEffectClassification(),p.requiredApprovals().stream().map(Enum::name).toList(),p.expectedArtifacts().stream().map(MigrationRunPlan.ExpectedArtifact::logicalPath).toList(),p.baselineRole())).toList();return new MigrationOrchestrationDryRunReport(id(proposalDryRunRef,views,actions,limitations),proposalDryRunRef,views,actions,limitations);}
    private static String id(String proposal,List<RunPlanView>plans,List<GitActionView>actions,List<String>limitations){List<String>f=new ArrayList<>(List.of(proposal==null?"":proposal));plans.stream().sorted(Comparator.comparing(RunPlanView::planId)).forEach(p->{f.add(p.planId());f.add(p.executableRef());f.addAll(p.arguments());f.addAll(p.environmentKeyNames());f.addAll(p.secretReferenceNames());f.add(p.sideEffect().name());f.addAll(p.requiredCapabilities());f.addAll(p.expectedArtifacts());f.add(p.baselineRole().name());});actions.stream().sorted(Comparator.comparing(x->x.operation().name())).forEach(a->{f.add(a.operation().name());f.add(a.branch()==null?"":a.branch());f.add(a.exactBaseCommit()==null?"":a.exactBaseCommit());f.add(a.trustedDestinationDisplay()==null?"":a.trustedDestinationDisplay());f.add(a.stashScope()==null?"":a.stashScope().name());f.addAll(a.requiredCapabilities());});f.addAll(limitations.stream().sorted().toList());return"migration-orchestration-dry-run-v1:sha256:"+MigrationDigests.digest("migration-orchestration-dry-run-v1",f.toArray(String[]::new));}
}
