package io.github.testlens.migration.tooling;

import io.github.testlens.compatibility.engine.CompatibilityCompareEngine;
import io.github.testlens.compatibility.engine.CompatibilityComparisonReport;
import io.github.testlens.compatibility.engine.CompatibilityRunManifest;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Post-apply verification orchestration. It never writes source and never rolls back on failure. */
public final class MigrationVerificationService {
    private final MigrationGitService git;private final MigrationRunOrchestrator runs;private final CompatibilityCompareEngine compare;private final MigrationJavaWrapperMain wrappers;private final MigrationCompatibilityManifestReader manifests;private final MigrationApplyCodec applyCodec=new MigrationApplyCodec();
    private final MigrationVerificationJson verificationJson=new MigrationVerificationJson();
    public MigrationVerificationService(){this(new MigrationGitService(),new MigrationRunOrchestrator(),new CompatibilityCompareEngine(),new MigrationJavaWrapperMain(),new MigrationCompatibilityManifestReader());}
    MigrationVerificationService(MigrationGitService git,MigrationRunOrchestrator runs,CompatibilityCompareEngine compare,MigrationJavaWrapperMain wrappers,MigrationCompatibilityManifestReader manifests){this.git=git;this.runs=runs;this.compare=compare;this.wrappers=wrappers;this.manifests=manifests;}
    public MigrationVerificationResult verify(Input in)throws IOException{
        Objects.requireNonNull(in);validateIdentity(in);persist(in.store(),in.plan());if(!transactionReady(in))return blocked(in,"TRANSACTION_NOT_VERIFICATION_PENDING");try(MigrationTransactionOperationLock ignored=MigrationTransactionOperationLock.tryAcquire(in.store(),in.plan().transactionId())){if(ignored==null)return blocked(in,"VERIFICATION_TRANSACTION_BUSY");Guard initial=guard(in);if(!initial.ok())return blocked(in,initial.issue());append(in,MigrationApplyTransaction.EventType.VERIFICATION_STARTED,in.plan().verificationPlanId());List<MigrationVerificationResult.StageResult>results=new ArrayList<>();List<String>runRefs=new ArrayList<>(),manifestRefs=new ArrayList<>();List<MigrationVerificationResult.ComparisonResult>comparisonResults=new ArrayList<>();boolean stop=false;
            for(MigrationVerificationPlan.Stage stage:in.plan().stages()){
                if(stop){results.add(stage(stage,MigrationVerificationResult.StageStatus.NOT_RUN,null,List.of(),List.of("EARLIER_REQUIRED_STAGE_DID_NOT_PASS")));continue;}
                Guard before=guard(in);if(!before.ok()){results.add(stage(stage,MigrationVerificationResult.StageStatus.BLOCKED,null,List.of(),List.of(before.issue())));stop=stage.necessity()==MigrationVerificationPlan.Necessity.REQUIRED;continue;}
                MigrationVerificationResult.StageResult result;
                if(stage.type()==MigrationVerificationPlan.StageType.SOURCE_STRUCTURE)result=stage(stage,MigrationVerificationResult.StageStatus.PASSED,null,List.of(),List.of());
                else if(stage.type()==MigrationVerificationPlan.StageType.COMPATIBILITY_COMPARE){List<MigrationVerificationResult.ComparisonResult>cr=compare(stage,in);comparisonResults.addAll(cr);MigrationVerificationResult.StageStatus status=cr.stream().allMatch(x->x.status()==MigrationVerificationResult.StageStatus.PASSED)?MigrationVerificationResult.StageStatus.PASSED:cr.stream().anyMatch(x->x.status()==MigrationVerificationResult.StageStatus.FAILED)?MigrationVerificationResult.StageStatus.FAILED:MigrationVerificationResult.StageStatus.INCONCLUSIVE;result=stage(stage,status,null,cr.stream().map(MigrationVerificationResult.ComparisonResult::comparisonPlanRef).toList(),List.of());}
                else if(stage.type()==MigrationVerificationPlan.StageType.MANIFEST_VALIDATION){List<String>issues=new ArrayList<>();for(String ref:in.plan().expectedArtifactRefs()){ManifestEvidence evidence=in.manifestEvidence().get(ref);if(evidence==null){issues.add("MISSING_MANIFEST:"+ref);continue;}try{validateManifest(in.plan(),evidence,true);manifestRefs.add(ref);}catch(RuntimeException e){issues.add("INVALID_MANIFEST:"+ref+":"+message(e));}}result=stage(stage,issues.isEmpty()?MigrationVerificationResult.StageStatus.PASSED:MigrationVerificationResult.StageStatus.INCONCLUSIVE,null,in.plan().expectedArtifactRefs(),issues);}
                else result=execute(stage,in,runRefs);
                results.add(result);if(stage.necessity()==MigrationVerificationPlan.Necessity.REQUIRED&&result.status()!=MigrationVerificationResult.StageStatus.PASSED)stop=true;
                Guard after=guard(in);if(!after.ok()){if(result.status()==MigrationVerificationResult.StageStatus.PASSED)results.set(results.size()-1,stage(stage,MigrationVerificationResult.StageStatus.BLOCKED,result.runResultRef(),result.artifactRefs(),List.of(after.issue())));stop=true;}
            }
            MigrationVerificationResult.Status status=overall(in.plan(),results);List<MigrationVerificationResult.ProposalResult>proposalResults=proposalResults(in.plan(),results);MigrationVerificationResult out=MigrationVerificationResult.create(in.plan().transactionId(),in.plan().applyPlanId(),in.plan().verificationPlanId(),in.plan().postApplyCheckpointRef(),status,results,runRefs,manifestRefs,comparisonResults,proposalResults,in.plan().limitations(),List.of(),in.supersedesResultId());persist(in.store(),out);append(in,event(status),out.verificationResultId());return out;}
    }
    private MigrationVerificationResult.StageResult execute(MigrationVerificationPlan.Stage stage,Input in,List<String>runRefs)throws IOException{
        MigrationVerificationPlan.TrustedRunBinding binding=in.plan().trustedRunBindings().stream().filter(x->x.stageRef().equals(stage.stageRef())).findFirst().orElse(null);if(binding==null)return stage(stage,MigrationVerificationResult.StageStatus.BLOCKED,null,List.of(),List.of("MISSING_TRUSTED_RUN_BINDING"));MigrationRunPlan run=in.runPlans().get(binding.runPlanId());MigrationTrustedProcessRunner.LocalExecution local=in.localExecutions().get(binding.runPlanId());if(run==null||local==null||!run.checkpointRef().equals(in.plan().postApplyCheckpointRef())||!binding.checkpointRef().equals(in.plan().postApplyCheckpointRef())||!bindingMatches(stage,in.plan(),run))return stage(stage,MigrationVerificationResult.StageStatus.BLOCKED,null,List.of(),List.of("STALE_RUN_PLAN"));if(binding.networkPolicy()==MigrationVerificationPlan.NetworkPolicy.NETWORK_NOT_AUTHORIZED)return stage(stage,MigrationVerificationResult.StageStatus.BLOCKED,null,List.of(),List.of("BUILD_NETWORK_NOT_AUTHORIZED_AND_NOT_OFFLINE"));if(binding.networkPolicy()==MigrationVerificationPlan.NetworkPolicy.NETWORK_AUTHORIZED&&!in.authorization().allows(MigrationAuthorization.Capability.ALLOW_BUILD_TOOL_NETWORK))return stage(stage,MigrationVerificationResult.StageStatus.BLOCKED,null,List.of(),List.of("BUILD_NETWORK_APPROVAL_REQUIRED"));if(binding.wrapper()!=null){try{if(!wrapperRunMatches(in.projectRoot(),binding.wrapper(),run,local))return stage(stage,MigrationVerificationResult.StageStatus.BLOCKED,null,List.of(),List.of("STALE_RUN_PLAN"));}catch(IOException e){return stage(stage,MigrationVerificationResult.StageStatus.BLOCKED,null,List.of(),List.of(message(e)));}}
        if(binding.wrapper()!=null&&binding.networkPolicy()==MigrationVerificationPlan.NetworkPolicy.OFFLINE&&!offline(binding.wrapper().kind(),run.args()))return stage(stage,MigrationVerificationResult.StageStatus.BLOCKED,null,List.of(),List.of("OFFLINE_ARGUMENT_REQUIRED"));MigrationRunOrchestrator.Result rr=runs.execute(run,in.postApplyCheckpoint(),in.store(),local,in.authorization(),in.cancellation());MigrationRunResult durable=rr.durableResult();runRefs.add(durable.runResultId());MigrationVerificationResult.StageStatus status=switch(durable.status()){case SUCCESS->MigrationVerificationResult.StageStatus.PASSED;case FAILED,ARTIFACT_VALIDATION_FAILED->MigrationVerificationResult.StageStatus.FAILED;case TIMED_OUT,CANCELLED,INTERRUPTED,UNKNOWN_COMPLETION,ARTIFACTS_PARTIAL->MigrationVerificationResult.StageStatus.INTERRUPTED;case SAFE_STOP,START_FAILED->MigrationVerificationResult.StageStatus.BLOCKED;};return stage(stage,status,durable.runResultId(),durable.expectedArtifactResults().stream().filter(x->x.status()==MigrationRunResult.ArtifactStatus.VALID).map(MigrationRunResult.ArtifactResult::logicalPath).toList(),durable.issues());
    }
    private static boolean bindingMatches(MigrationVerificationPlan.Stage stage,MigrationVerificationPlan plan,MigrationRunPlan run){List<MigrationVerificationPlan.Requirement>requirements=plan.requirements().stream().filter(x->stage.requirementRefs().contains(x.requirementRef())).toList();for(var requirement:requirements){if(requirement.executionMode()!=null&&requirement.executionMode()!=run.executionMode())return false;MigrationRunPlan.SideEffectClassification expected=switch(requirement.sideEffect()){case READ_ONLY->MigrationRunPlan.SideEffectClassification.READ_ONLY;case KNOWN_MUTATING->MigrationRunPlan.SideEffectClassification.KNOWN_MUTATING;case UNKNOWN->MigrationRunPlan.SideEffectClassification.UNKNOWN;};if(expected!=run.sideEffectClassification())return false;}return true;}
    static boolean offline(MigrationVerificationPlan.WrapperBinding.WrapperKind kind,List<String>args){return kind==MigrationVerificationPlan.WrapperBinding.WrapperKind.GRADLE_WRAPPER_MAIN?args.contains("--offline"):args.contains("--offline")||args.contains("-o");}
    boolean wrapperRunMatches(Path projectRoot,MigrationVerificationPlan.WrapperBinding wrapper,MigrationRunPlan run,MigrationTrustedProcessRunner.LocalExecution local)throws IOException{wrappers.revalidate(projectRoot,wrapper);if(!wrapper.javaExecutableRef().equals(run.executableRef())||!wrapper.javaExecutableRef().equals(local.executableRef())||run.args().size()<3)return false;return run.args().subList(0,3).equals(wrappers.commandArguments(projectRoot,wrapper,List.of()));}
    private List<MigrationVerificationResult.ComparisonResult>compare(MigrationVerificationPlan.Stage stage,Input in){List<MigrationVerificationResult.ComparisonResult>out=new ArrayList<>();for(var p:in.plan().comparisonPlans()){ManifestEvidence left=in.manifestEvidence().get(p.baselineManifestRef()),right=in.manifestEvidence().get(p.variantManifestRef());if(left==null||right==null){out.add(new MigrationVerificationResult.ComparisonResult(p.comparisonPlanRef(),p.intent().axis(),CompatibilityComparisonReport.Outcome.INCONCLUSIVE,CompatibilityComparisonReport.Comparability.UNKNOWN,MigrationVerificationResult.StageStatus.INCONCLUSIVE,List.of(),List.of("BASELINE_OR_VARIANT_MISSING")));continue;}try{validateManifest(in.plan(),left,p.intent().axis()!=io.github.testlens.compatibility.engine.ComparisonIntent.Axis.BUILD);validateManifest(in.plan(),right,true);axis(p,left.manifest(),right.manifest());CompatibilityComparisonReport report=compare.compare(List.of(left.manifest()),List.of(right.manifest()),p.intent());CompatibilityComparisonReport.TestComparison one=report.testComparisons().size()==1?report.testComparisons().get(0):null;CompatibilityComparisonReport.Outcome outcome=one==null?CompatibilityComparisonReport.Outcome.INCONCLUSIVE:one.outcome();CompatibilityComparisonReport.Comparability comparability=one==null?CompatibilityComparisonReport.Comparability.UNKNOWN:one.comparability().status();boolean comparable=!p.requireComparable()||List.of(CompatibilityComparisonReport.Comparability.COMPARABLE,CompatibilityComparisonReport.Comparability.COMPARABLE_WITH_LIMITATIONS).contains(comparability);boolean accepted=comparable&&p.acceptableOutcomes().contains(outcome)&&(p.allowBehavioralDelta()||!List.of(CompatibilityComparisonReport.Outcome.PASS_WITH_BEHAVIORAL_DELTA,CompatibilityComparisonReport.Outcome.BOTH_PASS_DIFFERENT_BEHAVIOR).contains(outcome));MigrationVerificationResult.StageStatus status=!comparable||outcome==CompatibilityComparisonReport.Outcome.INCONCLUSIVE||outcome==CompatibilityComparisonReport.Outcome.NOT_COMPARABLE?MigrationVerificationResult.StageStatus.INCONCLUSIVE:accepted?MigrationVerificationResult.StageStatus.PASSED:MigrationVerificationResult.StageStatus.FAILED;List<String>finding=p.targetedFindingIds().stream().map(x->x+":"+(report.findings().stream().anyMatch(f->f.findingId().equals(x))?"STILL_PRESENT":"RESOLVED")).toList();out.add(new MigrationVerificationResult.ComparisonResult(p.comparisonPlanRef(),p.intent().axis(),outcome,comparability,status,finding,List.of()));}catch(RuntimeException e){out.add(new MigrationVerificationResult.ComparisonResult(p.comparisonPlanRef(),p.intent().axis(),CompatibilityComparisonReport.Outcome.INCONCLUSIVE,CompatibilityComparisonReport.Comparability.UNKNOWN,MigrationVerificationResult.StageStatus.INCONCLUSIVE,List.of(),List.of(message(e))));}}return List.copyOf(out);}
    static void axis(MigrationVerificationPlan.ComparisonPlan p,CompatibilityRunManifest left,CompatibilityRunManifest right){String l=source(left),r=source(right);switch(p.intent().axis()){case BUILD->{if(Objects.equals(l,r))throw new IllegalArgumentException("BUILD_AXIS_REQUIRES_DIFFERENT_SOURCE_REVISION");}case HEADLESS_MODE,OBSERVABILITY_MODE->{if(!Objects.equals(l,r))throw new IllegalArgumentException("POST_CHANGE_AXIS_REQUIRES_SAME_SOURCE_REVISION");}default->{}}}
    private void validateManifest(MigrationVerificationPlan plan,ManifestEvidence e,boolean post){var projection=manifests.read(e.bytes());if(!projection.manifestId().equals(e.manifest().manifestId())||!projection.exactDigest().equals(e.exactDigest()))throw new IllegalArgumentException("ARTIFACT_CHANGED");if(post&&(!plan.transactionId().equals(e.transactionId())||!plan.applyPlanId().equals(e.applyPlanId())||!plan.postApplyCheckpointRef().equals(e.checkpointRef())||!plan.postApplySourceStateDigest().equals(e.sourceStateDigest())||!plan.postApplySourceStateDigest().equals(projection.testSourceRevision())))throw new IllegalArgumentException("MANIFEST_SOURCE_RELATION_MISMATCH");}
    private Guard guard(Input in)throws IOException{MigrationGitService.Result current=git.inspect(in.projectRoot());if(current.localContext()==null||!in.applyPlan().repositoryBindingRef().equals(current.preflight().repositoryBindingRef())||!in.applyPlan().worktreeBindingRef().equals(current.preflight().worktreeBindingRef()))return new Guard(false,"POST_APPLY_BINDING_CHANGED");for(var f:in.applyPlan().filePlans()){Path p=current.localContext().worktreeRoot().resolve(f.logicalPath().replace('/',java.io.File.separatorChar)).normalize();if(!Files.exists(p,LinkOption.NOFOLLOW_LINKS)||Files.isSymbolicLink(p)||!f.proposedSha256().equals("sha256:"+MigrationDigests.rawBytes(Files.readAllBytes(p))))return new Guard(false,"POST_APPLY_SOURCE_CHANGED:"+f.logicalPath());}if(!in.plan().postApplySourceStateDigest().equals(current.sourceState().sourceStateDigest()))return new Guard(false,"POST_APPLY_SOURCE_CHANGED");return new Guard(true,null);}
    private static void validateIdentity(Input in){if(!in.applyPlan().applyPlanId().equals(in.plan().applyPlanId())||!MigrationApplyTransaction.id(in.applyPlan()).equals(in.plan().transactionId())||!in.postApplyCheckpoint().checkpointId().equals(in.plan().postApplyCheckpointRef())||!in.postApplyCheckpoint().sourceState().sourceStateDigest().equals(in.plan().postApplySourceStateDigest()))throw new IllegalArgumentException("VERIFICATION_PLAN_MISMATCH");}
    private boolean transactionReady(Input in)throws IOException{String base="apply/transactions/"+in.plan().transactionId().replace(':','-')+"/events/";Path dir=in.store().root().resolve(base.replace('/',java.io.File.separatorChar));if(!Files.isDirectory(dir,LinkOption.NOFOLLOW_LINKS)||Files.isSymbolicLink(dir))return false;List<MigrationApplyTransaction.Event>events=new ArrayList<>();try(var s=Files.list(dir)){for(Path p:s.filter(x->x.getFileName().toString().endsWith(".json")).sorted().toList())events.add(applyCodec.readEvent(Files.readAllBytes(p)));}String previous=null;long sequence=0;for(var e:events){if(e.sequence()!=sequence++||!Objects.equals(previous,e.previousEventDigest())||!e.transactionId().equals(in.plan().transactionId()))return false;previous=e.eventDigest();}boolean pending=events.stream().anyMatch(e->e.type()==MigrationApplyTransaction.EventType.VERIFICATION_PENDING);boolean rolledBack=events.stream().anyMatch(e->e.type()==MigrationApplyTransaction.EventType.ROLLBACK_STARTED||e.type()==MigrationApplyTransaction.EventType.ROLLBACK_COMPLETED);return pending&&!rolledBack;}
    private static MigrationVerificationResult.Status overall(MigrationVerificationPlan p,List<MigrationVerificationResult.StageResult>r){List<MigrationVerificationResult.StageResult>required=r.stream().filter(x->x.necessity()==MigrationVerificationPlan.Necessity.REQUIRED).toList();if(required.stream().anyMatch(x->x.status()==MigrationVerificationResult.StageStatus.INTERRUPTED))return MigrationVerificationResult.Status.INTERRUPTED;if(required.stream().anyMatch(x->x.status()==MigrationVerificationResult.StageStatus.BLOCKED||x.status()==MigrationVerificationResult.StageStatus.NOT_RUN))return MigrationVerificationResult.Status.BLOCKED;if(required.stream().anyMatch(x->x.status()==MigrationVerificationResult.StageStatus.FAILED))return MigrationVerificationResult.Status.FAILED;if(required.stream().anyMatch(x->x.status()==MigrationVerificationResult.StageStatus.INCONCLUSIVE))return MigrationVerificationResult.Status.INCONCLUSIVE;return required.stream().allMatch(x->x.status()==MigrationVerificationResult.StageStatus.PASSED)?MigrationVerificationResult.Status.VERIFIED:MigrationVerificationResult.Status.INCONCLUSIVE;}
    private static List<MigrationVerificationResult.ProposalResult>proposalResults(MigrationVerificationPlan p,List<MigrationVerificationResult.StageResult>results){Map<String,List<MigrationVerificationResult.StageResult>>by=new HashMap<>();for(var requirement:p.requirements())for(String proposal:requirement.proposalIds()){MigrationVerificationResult.StageResult result=results.stream().filter(x->x.stageRef().equals(requirement.stage().stageRef())).findFirst().orElse(null);if(result!=null)by.computeIfAbsent(proposal,x->new ArrayList<>()).add(result);}return by.entrySet().stream().sorted(Map.Entry.comparingByKey()).map(e->{var v=e.getValue();MigrationVerificationResult.ProposalStatus s=v.stream().anyMatch(x->x.status()==MigrationVerificationResult.StageStatus.FAILED)?MigrationVerificationResult.ProposalStatus.FAILED:v.stream().anyMatch(x->x.status()==MigrationVerificationResult.StageStatus.BLOCKED||x.status()==MigrationVerificationResult.StageStatus.NOT_RUN)?MigrationVerificationResult.ProposalStatus.BLOCKED:v.stream().allMatch(x->x.status()==MigrationVerificationResult.StageStatus.PASSED)?MigrationVerificationResult.ProposalStatus.VERIFIED:MigrationVerificationResult.ProposalStatus.INCONCLUSIVE;return new MigrationVerificationResult.ProposalResult(e.getKey(),s,v.stream().map(MigrationVerificationResult.StageResult::stageRef).toList(),List.of());}).toList();}
    private static MigrationVerificationResult.StageResult stage(MigrationVerificationPlan.Stage s,MigrationVerificationResult.StageStatus status,String run,List<String>artifacts,List<String>issues){return new MigrationVerificationResult.StageResult(s.stageRef(),s.type(),s.necessity(),status,run,artifacts,issues);}
    private static String source(CompatibilityRunManifest m){return m.context().testSourceRevision().knowledge()==CompatibilityRunManifest.Knowledge.KNOWN?m.context().testSourceRevision().value():null;}
    private static String message(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}
    private static MigrationApplyTransaction.EventType event(MigrationVerificationResult.Status s){return switch(s){case VERIFIED->MigrationApplyTransaction.EventType.VERIFIED;case FAILED->MigrationApplyTransaction.EventType.VERIFICATION_FAILED;case INCONCLUSIVE->MigrationApplyTransaction.EventType.VERIFICATION_INCONCLUSIVE;case BLOCKED->MigrationApplyTransaction.EventType.VERIFICATION_BLOCKED;case INTERRUPTED->MigrationApplyTransaction.EventType.VERIFICATION_INTERRUPTED;};}
    private MigrationVerificationResult blocked(Input in,String issue)throws IOException{List<MigrationVerificationResult.StageResult>r=in.plan().stages().stream().map(x->stage(x,MigrationVerificationResult.StageStatus.BLOCKED,null,List.of(),List.of(issue))).toList();MigrationVerificationResult out=MigrationVerificationResult.create(in.plan().transactionId(),in.plan().applyPlanId(),in.plan().verificationPlanId(),in.plan().postApplyCheckpointRef(),MigrationVerificationResult.Status.BLOCKED,r,List.of(),List.of(),List.of(),proposalResults(in.plan(),r),in.plan().limitations(),List.of(issue),in.supersedesResultId());persist(in.store(),out);return out;}
    private void persist(MigrationStateStore store,MigrationVerificationPlan plan)throws IOException{byte[]bytes=verificationJson.write(plan);verificationJson.readPlan(bytes);store.writeArtifact("apply/verification/plans/"+plan.verificationPlanId().replace(':','-')+".json",bytes);}
    private void persist(MigrationStateStore store,MigrationVerificationResult result)throws IOException{byte[]bytes=verificationJson.write(result);verificationJson.readResult(bytes);store.writeArtifact("apply/verification/results/"+result.verificationResultId().replace(':','-')+".json",bytes);}
    private void append(Input in,MigrationApplyTransaction.EventType type,String issue)throws IOException{String base="apply/transactions/"+in.plan().transactionId().replace(':','-')+"/events/";Path dir=in.store().root().resolve(base.replace('/',java.io.File.separatorChar));List<MigrationApplyTransaction.Event>events=new ArrayList<>();if(Files.exists(dir))try(var s=Files.list(dir)){for(Path p:s.filter(x->x.getFileName().toString().endsWith(".json")).sorted().toList())events.add(applyCodec.readEvent(Files.readAllBytes(p)));}String previous=events.isEmpty()?null:events.get(events.size()-1).eventDigest();var event=MigrationApplyTransaction.Event.create(previous,in.plan().transactionId(),events.size(),type,null,null,issue);in.store().writeArtifact(base+String.format("%08d-%s.json",event.sequence(),event.eventDigest().substring(event.eventDigest().lastIndexOf(':')+1,event.eventDigest().lastIndexOf(':')+17)),applyCodec.write(event));}
    private record Guard(boolean ok,String issue){}
    public record ManifestEvidence(String logicalRef,String exactDigest,byte[]bytes,CompatibilityRunManifest manifest,String transactionId,String applyPlanId,String checkpointRef,String sourceStateDigest){public ManifestEvidence{logicalRef=MigrationRunPlan.logical(logicalRef);MigrationApplyPlan.require(exactDigest,"sha256");bytes=bytes.clone();Objects.requireNonNull(manifest);}public byte[]bytes(){return bytes.clone();}}
    public record Input(MigrationVerificationPlan plan,MigrationApplyPlan applyPlan,MigrationCheckpoint postApplyCheckpoint,Path projectRoot,MigrationStateStore store,Map<String,MigrationRunPlan>runPlans,Map<String,MigrationTrustedProcessRunner.LocalExecution>localExecutions,Map<String,ManifestEvidence>manifestEvidence,MigrationAuthorization authorization,MigrationTrustedProcessRunner.Cancellation cancellation,String supersedesResultId){public Input{Objects.requireNonNull(plan);Objects.requireNonNull(applyPlan);Objects.requireNonNull(postApplyCheckpoint);projectRoot=projectRoot.toAbsolutePath().normalize();Objects.requireNonNull(store);runPlans=runPlans==null?Map.of():Map.copyOf(runPlans);localExecutions=localExecutions==null?Map.of():Map.copyOf(localExecutions);manifestEvidence=manifestEvidence==null?Map.of():Map.copyOf(manifestEvidence);Objects.requireNonNull(authorization);cancellation=cancellation==null?MigrationTrustedProcessRunner.Cancellation.NEVER:cancellation;if(supersedesResultId!=null)MigrationApplyPlan.require(supersedesResultId,"migration-verification-result-v1");}}
}
