package io.github.testlens.migration.tooling;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;

/** Persistent review decisions. Approval never applies source and is bound to exact proposal inputs. */
public record MigrationDecisionLedger(int schemaVersion,int algorithmVersion,String ledgerSemanticDigest,List<DecisionRecord>decisions){
    public static final int MAX_DECISIONS=100_000,MAX_NOTE_CHARS=4096;
    public MigrationDecisionLedger{if(schemaVersion!=1||algorithmVersion!=1)throw new IllegalArgumentException("ledger version");decisions=decisions.stream().sorted(Comparator.comparing(DecisionRecord::proposalId).thenComparing(DecisionRecord::decisionRef)).toList();if(decisions.size()>MAX_DECISIONS)throw new IllegalArgumentException("decision bound");String expected=digest(decisions);if(!expected.equals(ledgerSemanticDigest))throw new IllegalArgumentException("ledger digest");}
    public static MigrationDecisionLedger create(List<DecisionRecord>records){return new MigrationDecisionLedger(1,1,digest(records),records);}
    public Validation validateApproval(MigrationProposal proposal,String checkpointRef,List<MigrationEvidenceRef>currentEvidence){DecisionRecord approved=decisions.stream().filter(x->x.proposalId().equals(proposal.proposalId())&&x.decision()==Decision.APPROVE_FOR_S11).reduce((a,b)->b).orElse(null);if(approved==null)return new Validation(false,List.of("NO_APPROVAL"));List<String>reasons=new ArrayList<>();if(!approved.proposalSemanticDigest().equals(proposal.proposalId()))reasons.add("PROPOSAL_CHANGED");if(!approved.sourceCheckpointRef().equals(checkpointRef))reasons.add("CHECKPOINT_CHANGED");String pre=preconditions(proposal);if(!approved.sourcePreconditionDigest().equals(pre))reasons.add("SOURCE_PRECONDITION_CHANGED");List<String>digests=currentEvidence.stream().map(MigrationEvidenceRef::canonicalDigest).sorted().toList();if(!approved.evidenceDigests().equals(digests))reasons.add("EVIDENCE_CHANGED");return new Validation(reasons.isEmpty(),reasons);}
    public static DecisionRecord decide(MigrationProposal proposal,String checkpoint,Decision decision,String provenance,String note,String supersedes){if(note!=null&&(note.length()>MAX_NOTE_CHARS||note.chars().anyMatch(c->Character.isISOControl(c)&&c!='\n'&&c!='\r'&&c!='\t')))throw new IllegalArgumentException("note bound");List<String>evidence=proposal.evidenceRefs().stream().map(MigrationEvidenceRef::canonicalDigest).sorted().toList();String pre=preconditions(proposal);String ref="migration-decision-v1:sha256:"+MigrationDigests.digest("migration-decision-v1",proposal.proposalId(),checkpoint,pre,decision.name(),provenance,supersedes==null?"":supersedes);return new DecisionRecord(ref,proposal.proposalId(),proposal.proposalId(),checkpoint,pre,decision,provenance,note,supersedes,evidence);}
    private static String preconditions(MigrationProposal p){List<String>f=new ArrayList<>();p.sourcePreconditions().forEach(x->{f.add(x.logicalPath());f.add(x.fileSha256());f.add(x.originalConstructDigest());f.add(x.proposedSemanticDigest());});return"migration-source-preconditions-v1:sha256:"+MigrationDigests.digest("migration-source-preconditions-v1",f.toArray(String[]::new));}
    private static String digest(List<DecisionRecord>r){List<String>f=new ArrayList<>();r.stream().sorted(Comparator.comparing(DecisionRecord::decisionRef)).forEach(x->{f.add(x.decisionRef());f.add(x.proposalId());f.add(x.proposalSemanticDigest());f.add(x.sourceCheckpointRef());f.add(x.sourcePreconditionDigest());f.add(x.decision().name());f.add(x.decisionProvenance());f.add(x.supersedesDecisionRef()==null?"":x.supersedesDecisionRef());x.evidenceDigests().forEach(f::add);});return"migration-decision-ledger-v1:sha256:"+MigrationDigests.digest("migration-decision-ledger-v1",f.toArray(String[]::new));}
    public enum Decision{APPROVE_FOR_S11,REJECT,DEFER,MANUAL_ONLY_ACKNOWLEDGED}
    public record DecisionRecord(String decisionRef,String proposalId,String proposalSemanticDigest,String sourceCheckpointRef,String sourcePreconditionDigest,Decision decision,String decisionProvenance,String note,String supersedesDecisionRef,List<String>evidenceDigests){public DecisionRecord{Objects.requireNonNull(decisionRef);Objects.requireNonNull(decision);Objects.requireNonNull(decisionProvenance);evidenceDigests=List.copyOf(evidenceDigests);}}
    public record Validation(boolean valid,List<String>reasons){public Validation{reasons=List.copyOf(reasons);}}
}
