package io.github.testlens.migration.tooling;

import io.github.testlens.compatibility.engine.ComparisonIntent;
import io.github.testlens.compatibility.engine.CompatibilityComparisonReport;
import java.util.List;
import java.util.Map;
import java.util.Set;

/** Strict, bounded, typed codec for local-sensitive verification artifacts. */
public final class MigrationVerificationJson {
    public static final int MAX_BYTES=16*1024*1024;
    private final MigrationArtifactJson writer=new MigrationArtifactJson();

    public byte[] write(MigrationVerificationPlan value){return bounded(writer.write(value));}
    public byte[] write(MigrationVerificationResult value){return bounded(writer.write(value));}

    public MigrationVerificationPlan readPlan(byte[] bytes){Map<String,Object>r=root(bytes,Set.of("schemaVersion","algorithmVersion","verificationPlanId","applyPlanId","transactionId","postApplyCheckpointRef","postApplySourceStateDigest","requirements","stages","trustedRunBindings","baselineRefs","expectedArtifactRefs","comparisonPlans","requiredCapabilities","completeness","limitations","supersedesVerificationPlanId"));return new MigrationVerificationPlan(integer(r,"schemaVersion"),integer(r,"algorithmVersion"),string(r,"verificationPlanId"),string(r,"applyPlanId"),string(r,"transactionId"),string(r,"postApplyCheckpointRef"),string(r,"postApplySourceStateDigest"),objects(r,"requirements").stream().map(this::requirement).toList(),objects(r,"stages").stream().map(this::stage).toList(),objects(r,"trustedRunBindings").stream().map(this::binding).toList(),strings(r,"baselineRefs"),strings(r,"expectedArtifactRefs"),objects(r,"comparisonPlans").stream().map(this::comparison).toList(),enums(r,"requiredCapabilities",MigrationAuthorization.Capability.class),value(r,"completeness",MigrationVerificationPlan.Completeness.class),strings(r,"limitations"),nullable(r,"supersedesVerificationPlanId"));}
    public MigrationVerificationResult readResult(byte[] bytes){Map<String,Object>r=root(bytes,Set.of("schemaVersion","algorithmVersion","verificationResultId","transactionId","applyPlanId","verificationPlanId","sourceCheckpointRef","status","stageResults","runResultRefs","manifestRefs","comparisonResults","proposalResults","requiredPassed","requiredTotal","limitations","issues","supersedesResultId"));return new MigrationVerificationResult(integer(r,"schemaVersion"),integer(r,"algorithmVersion"),string(r,"verificationResultId"),string(r,"transactionId"),string(r,"applyPlanId"),string(r,"verificationPlanId"),string(r,"sourceCheckpointRef"),value(r,"status",MigrationVerificationResult.Status.class),objects(r,"stageResults").stream().map(this::stageResult).toList(),strings(r,"runResultRefs"),strings(r,"manifestRefs"),objects(r,"comparisonResults").stream().map(this::comparisonResult).toList(),objects(r,"proposalResults").stream().map(this::proposalResult).toList(),integer(r,"requiredPassed"),integer(r,"requiredTotal"),strings(r,"limitations"),strings(r,"issues"),nullable(r,"supersedesResultId"));}

    private MigrationVerificationPlan.Requirement requirement(Map<String,Object>m){exact(m,Set.of("requirementRef","sourceKind","stageType","necessity","targetRef","testIdentityRef","executionMode","sideEffect","expectation","sourceScope","proposalIds"));return new MigrationVerificationPlan.Requirement(string(m,"requirementRef"),string(m,"sourceKind"),value(m,"stageType",MigrationVerificationPlan.StageType.class),value(m,"necessity",MigrationVerificationPlan.Necessity.class),string(m,"targetRef"),nullable(m,"testIdentityRef"),nullableEnum(m,"executionMode",MigrationRunPlan.ExecutionMode.class),value(m,"sideEffect",MigrationProposal.SideEffect.class),value(m,"expectation",MigrationVerificationPlan.Expectation.class),value(m,"sourceScope",MigrationVerificationPlan.SourceScope.class),strings(m,"proposalIds"));}
    private MigrationVerificationPlan.Stage stage(Map<String,Object>m){exact(m,Set.of("stageRef","type","necessity","targetRef","requirementRefs","expectation"));return new MigrationVerificationPlan.Stage(string(m,"stageRef"),value(m,"type",MigrationVerificationPlan.StageType.class),value(m,"necessity",MigrationVerificationPlan.Necessity.class),string(m,"targetRef"),strings(m,"requirementRefs"),value(m,"expectation",MigrationVerificationPlan.Expectation.class));}
    private MigrationVerificationPlan.TrustedRunBinding binding(Map<String,Object>m){exact(m,Set.of("bindingRef","stageRef","runPlanId","checkpointRef","wrapper","networkPolicy"));return new MigrationVerificationPlan.TrustedRunBinding(string(m,"bindingRef"),string(m,"stageRef"),string(m,"runPlanId"),string(m,"checkpointRef"),m.get("wrapper")==null?null:wrapper(object(m,"wrapper")),value(m,"networkPolicy",MigrationVerificationPlan.NetworkPolicy.class));}
    private MigrationVerificationPlan.WrapperBinding wrapper(Map<String,Object>m){exact(m,Set.of("bindingRef","kind","javaExecutableRef","jarLogicalPath","jarSha256","propertiesLogicalPath","propertiesSha256"));return new MigrationVerificationPlan.WrapperBinding(string(m,"bindingRef"),value(m,"kind",MigrationVerificationPlan.WrapperBinding.WrapperKind.class),string(m,"javaExecutableRef"),string(m,"jarLogicalPath"),string(m,"jarSha256"),string(m,"propertiesLogicalPath"),string(m,"propertiesSha256"));}
    private MigrationVerificationPlan.ComparisonPlan comparison(Map<String,Object>m){exact(m,Set.of("comparisonPlanRef","intent","baselineManifestRef","variantManifestRef","acceptableOutcomes","allowBehavioralDelta","requireComparable","targetedFindingIds","proposalIds"));Map<String,Object>i=object(m,"intent");exact(i,Set.of("axis","baselineRole","variantRole"));ComparisonIntent intent=new ComparisonIntent(value(i,"axis",ComparisonIntent.Axis.class),string(i,"baselineRole"),string(i,"variantRole"));return new MigrationVerificationPlan.ComparisonPlan(string(m,"comparisonPlanRef"),intent,string(m,"baselineManifestRef"),string(m,"variantManifestRef"),enums(m,"acceptableOutcomes",CompatibilityComparisonReport.Outcome.class),bool(m,"allowBehavioralDelta"),bool(m,"requireComparable"),strings(m,"targetedFindingIds"),strings(m,"proposalIds"));}
    private MigrationVerificationResult.StageResult stageResult(Map<String,Object>m){exact(m,Set.of("stageRef","stageType","necessity","status","runResultRef","artifactRefs","issues"));return new MigrationVerificationResult.StageResult(string(m,"stageRef"),value(m,"stageType",MigrationVerificationPlan.StageType.class),value(m,"necessity",MigrationVerificationPlan.Necessity.class),value(m,"status",MigrationVerificationResult.StageStatus.class),nullable(m,"runResultRef"),strings(m,"artifactRefs"),strings(m,"issues"));}
    private MigrationVerificationResult.ComparisonResult comparisonResult(Map<String,Object>m){exact(m,Set.of("comparisonPlanRef","axis","outcome","comparability","status","targetedFindingStates","issues"));return new MigrationVerificationResult.ComparisonResult(string(m,"comparisonPlanRef"),value(m,"axis",ComparisonIntent.Axis.class),value(m,"outcome",CompatibilityComparisonReport.Outcome.class),value(m,"comparability",CompatibilityComparisonReport.Comparability.class),value(m,"status",MigrationVerificationResult.StageStatus.class),strings(m,"targetedFindingStates"),strings(m,"issues"));}
    private MigrationVerificationResult.ProposalResult proposalResult(Map<String,Object>m){exact(m,Set.of("proposalId","status","stageRefs","issues"));return new MigrationVerificationResult.ProposalResult(string(m,"proposalId"),value(m,"status",MigrationVerificationResult.ProposalStatus.class),strings(m,"stageRefs"),strings(m,"issues"));}

    private static byte[] bounded(byte[]b){if(b.length>MAX_BYTES)throw new IllegalArgumentException("OUTPUT_LIMIT_EXCEEDED");return b;}
    private static Map<String,Object>root(byte[]b,Set<String>keys){Map<String,Object>r=MigrationStrictJson.object(b,MAX_BYTES);exact(r,keys);return r;}
    private static void exact(Map<String,Object>m,Set<String>keys){if(!m.keySet().equals(keys))throw new IllegalArgumentException("unexpected or missing JSON field");}
    private static String string(Map<String,Object>m,String k){Object v=m.get(k);if(!(v instanceof String s))throw new IllegalArgumentException(k);return s;}
    private static String nullable(Map<String,Object>m,String k){Object v=m.get(k);if(v==null)return null;if(!(v instanceof String s))throw new IllegalArgumentException(k);return s;}
    private static int integer(Map<String,Object>m,String k){Object v=m.get(k);if(!(v instanceof Number n)||n.longValue()!=n.intValue())throw new IllegalArgumentException(k);return n.intValue();}
    private static boolean bool(Map<String,Object>m,String k){Object v=m.get(k);if(!(v instanceof Boolean b))throw new IllegalArgumentException(k);return b;}
    @SuppressWarnings("unchecked") private static Map<String,Object>object(Map<String,Object>m,String k){Object v=m.get(k);if(!(v instanceof Map<?,?>x))throw new IllegalArgumentException(k);return(Map<String,Object>)x;}
    private static List<Map<String,Object>>objects(Map<String,Object>m,String k){Object v=m.get(k);if(!(v instanceof List<?>l))throw new IllegalArgumentException(k);return l.stream().map(x->{if(!(x instanceof Map<?,?>map))throw new IllegalArgumentException(k);@SuppressWarnings("unchecked")Map<String,Object>r=(Map<String,Object>)map;return r;}).toList();}
    private static List<String>strings(Map<String,Object>m,String k){Object v=m.get(k);if(!(v instanceof List<?>l)||l.stream().anyMatch(x->!(x instanceof String)))throw new IllegalArgumentException(k);return l.stream().map(String.class::cast).toList();}
    private static<T extends Enum<T>>T value(Map<String,Object>m,String k,Class<T>type){try{return Enum.valueOf(type,string(m,k));}catch(RuntimeException e){throw new IllegalArgumentException(k,e);}}
    private static<T extends Enum<T>>T nullableEnum(Map<String,Object>m,String k,Class<T>type){String v=nullable(m,k);try{return v==null?null:Enum.valueOf(type,v);}catch(RuntimeException e){throw new IllegalArgumentException(k,e);}}
    private static<T extends Enum<T>>List<T>enums(Map<String,Object>m,String k,Class<T>type){return strings(m,k).stream().map(x->{try{return Enum.valueOf(type,x);}catch(RuntimeException e){throw new IllegalArgumentException(k,e);}}).toList();}
}
