package io.github.testlens.migration.tooling;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** Exact-digest artifact freshness and bounded schema validation under trusted roots. */
final class MigrationRunArtifactValidator {
    record Snapshot(boolean exists,String digest,long bytes){}
    Map<String,Snapshot>snapshot(MigrationRunPlan plan,Path projectRoot,Path stateRoot)throws IOException{Map<String,Snapshot>r=new LinkedHashMap<>();for(var a:plan.expectedArtifacts())r.put(a.logicalPath(),snapshot(resolve(a,projectRoot,stateRoot),a.maxBytes()));return r;}
    List<MigrationRunResult.ArtifactResult>validate(MigrationRunPlan plan,Path projectRoot,Path stateRoot,Map<String,Snapshot>before)throws IOException{List<MigrationRunResult.ArtifactResult>out=new ArrayList<>();for(var a:plan.expectedArtifacts()){Path p=resolve(a,projectRoot,stateRoot);Snapshot old=before.get(a.logicalPath()),now;try{now=snapshot(p,a.maxBytes());}catch(IOException exceeded){long bytes=Files.exists(p,LinkOption.NOFOLLOW_LINKS)&&Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)?Files.size(p):0;out.add(new MigrationRunResult.ArtifactResult(a.logicalPath(),MigrationRunResult.ArtifactStatus.OUTPUT_LIMIT_EXCEEDED,null,bytes,null,List.of("EXPECTED_ARTIFACT_LIMIT_EXCEEDED")));continue;}MigrationRunResult.ArtifactStatus status;List<String>issues=new ArrayList<>();String semantic=null;if(!now.exists()){status=a.freshness()==MigrationRunPlan.ArtifactFreshness.OPTIONAL?MigrationRunResult.ArtifactStatus.OPTIONAL_ABSENT:MigrationRunResult.ArtifactStatus.MISSING;}else if((a.freshness()==MigrationRunPlan.ArtifactFreshness.MUST_BE_CREATED&&old.exists())||(a.freshness()==MigrationRunPlan.ArtifactFreshness.MUST_CHANGE&&old.exists()&&old.digest().equals(now.digest()))){status=MigrationRunResult.ArtifactStatus.STALE;}else{status=MigrationRunResult.ArtifactStatus.VALID;if(a.kind()==MigrationRunPlan.ArtifactKind.COMPATIBILITY_RUN_MANIFEST){try{semantic=manifest(Files.readAllBytes(p),plan.executionMode(),a.expectedTestIdentityRef());}catch(ModeMismatch e){status=MigrationRunResult.ArtifactStatus.MODE_MISMATCH;issues.add(e.getMessage());}catch(RuntimeException e){status=MigrationRunResult.ArtifactStatus.MALFORMED;issues.add("INVALID_COMPATIBILITY_MANIFEST:"+e.getMessage());}}}out.add(new MigrationRunResult.ArtifactResult(a.logicalPath(),status,now.exists()?"sha256:"+now.digest():null,now.bytes(),semantic,issues));}return List.copyOf(out);}
    private static Snapshot snapshot(Path p,long max)throws IOException{if(!Files.exists(p,LinkOption.NOFOLLOW_LINKS))return new Snapshot(false,null,0);if(Files.isSymbolicLink(p)||!Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS))throw new IllegalArgumentException("unsafe artifact file");long size=Files.size(p);if(size>max)throw new IOException("expected artifact exceeds bound");return new Snapshot(true,MigrationDigests.rawBytes(Files.readAllBytes(p)),size);}
    private static Path resolve(MigrationRunPlan.ExpectedArtifact artifact,Path projectRoot,Path stateRoot)throws IOException{Path root=(artifact.root()==MigrationRunPlan.ArtifactRoot.PROJECT_OUTPUT?projectRoot:stateRoot).toAbsolutePath().normalize().toRealPath();Path p=root.resolve(artifact.logicalPath().replace('/',java.io.File.separatorChar)).normalize();if(!p.startsWith(root))throw new IllegalArgumentException("artifact escapes trusted root");Path cursor=p.getParent();while(cursor!=null&&!Files.exists(cursor,LinkOption.NOFOLLOW_LINKS))cursor=cursor.getParent();if(cursor==null||Files.isSymbolicLink(cursor)||!cursor.toRealPath().startsWith(root))throw new IllegalArgumentException("artifact symlink escape");return p;}
    private static String manifest(byte[]bytes,MigrationRunPlan.ExecutionMode mode,String expectedTest){Map<String,Object>r=MigrationStrictJson.object(bytes);requireKeys(r,List.of("schemaVersion","manifestAlgorithmVersion","manifestId","testIdentity","execution","browser","display","context","configuration","attempts","terminalResult","completeness","issues","evidenceDigests"));if(number(r.get("schemaVersion"))!=1||number(r.get("manifestAlgorithmVersion"))!=1)throw new IllegalArgumentException("unsupported version");String id=string(r.get("manifestId"));if(!id.matches("compatibility-manifest-v1:sha256:[0-9a-f]{64}"))throw new IllegalArgumentException("manifestId");Map<String,Object>execution=object(r.get("execution"));String headless=fact(execution.get("effectiveHeadless")),observability=fact(execution.get("observabilityMode"));String requiredHeadless=switch(mode){case HEADED_STANDARD->"HEADED";case HEADLESS_STANDARD,HEADLESS_FAST->"HEADLESS";case CUSTOM_TRUSTED->null;};String requiredObs=switch(mode){case HEADED_STANDARD,HEADLESS_STANDARD->"DEFAULT";case HEADLESS_FAST->"FAST";case CUSTOM_TRUSTED->null;};if(requiredHeadless!=null&&!requiredHeadless.equals(headless))throw new ModeMismatch("EFFECTIVE_HEADLESS_MISMATCH");if(requiredObs!=null&&!requiredObs.equals(observability))throw new ModeMismatch("OBSERVABILITY_MODE_MISMATCH");if(expectedTest!=null){Map<String,Object>test=factObject(r.get("testIdentity"));if(!expectedTest.equals(string(test.get("testIdentityRef"))))throw new ModeMismatch("TEST_IDENTITY_MISMATCH");}return id;}
    private static void requireKeys(Map<String,Object>m,List<String>required){for(String k:required)if(!m.containsKey(k))throw new IllegalArgumentException("missing "+k);for(String k:m.keySet())if(!required.contains(k)&&!k.startsWith("x-"))throw new IllegalArgumentException("unknown "+k);}
    private static String fact(Object value){Map<String,Object>m=object(value);if(!"KNOWN".equals(m.get("knowledge")))return null;return string(m.get("value"));}
    private static Map<String,Object>factObject(Object value){Map<String,Object>m=object(value);if(!"KNOWN".equals(m.get("knowledge")))throw new IllegalArgumentException("unknown test identity");return object(m.get("value"));}
    @SuppressWarnings("unchecked")private static Map<String,Object>object(Object v){if(!(v instanceof Map<?,?>))throw new IllegalArgumentException("object required");return(Map<String,Object>)v;}
    private static String string(Object v){if(!(v instanceof String s))throw new IllegalArgumentException("string required");return s;}
    private static long number(Object v){if(!(v instanceof Number n))throw new IllegalArgumentException("number required");return n.longValue();}
    private static final class ModeMismatch extends IllegalArgumentException{ModeMismatch(String m){super(m);}}
}
