package io.github.testlens.migration.tooling;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/** Deterministic S12 handoff; it is maintainer policy, not a runtime restriction. */
public record ReleaseHardeningHandoff(int schemaVersion,int algorithmVersion,String handoffId,String releaseVersion,
        String runtimeApiBaseline,int runtimePublicTypes,int runtimePublicCallables,List<String>completedAreas,
        List<MigrationReleaseGap>gaps,List<String>performanceHotspots,List<String>platformLimitations,
        List<String>browserProviderGaps,List<String>docsReleaseTasks,List<String>maintenanceTasks){
    public static final int MAX_GAPS=128,MAX_ITEMS=256;
    public ReleaseHardeningHandoff{if(schemaVersion!=1||algorithmVersion!=1)throw new IllegalArgumentException("handoff version");releaseVersion=safe(releaseVersion);runtimeApiBaseline=safe(runtimeApiBaseline);if(runtimePublicTypes<0||runtimePublicCallables<0)throw new IllegalArgumentException("api counts");completedAreas=strings(completedAreas);gaps=gaps==null?List.of():gaps.stream().sorted(Comparator.comparing(MigrationReleaseGap::gapCode)).toList();performanceHotspots=strings(performanceHotspots);platformLimitations=strings(platformLimitations);browserProviderGaps=strings(browserProviderGaps);docsReleaseTasks=strings(docsReleaseTasks);maintenanceTasks=strings(maintenanceTasks);if(gaps.size()>MAX_GAPS||List.of(completedAreas,performanceHotspots,platformLimitations,browserProviderGaps,docsReleaseTasks,maintenanceTasks).stream().anyMatch(x->x.size()>MAX_ITEMS))throw new IllegalArgumentException("handoff bound");String expected=id(releaseVersion,runtimeApiBaseline,runtimePublicTypes,runtimePublicCallables,completedAreas,gaps,performanceHotspots,platformLimitations,browserProviderGaps,docsReleaseTasks,maintenanceTasks);if(!expected.equals(handoffId))throw new IllegalArgumentException("handoffId");}
    public static ReleaseHardeningHandoff current(){List<MigrationReleaseGap>gaps=List.of(
            gap("WINDOWS_SYMLINK_FIXTURE_SKIPPED",MigrationReleaseGap.Stage.S12_WINDOWS,MigrationReleaseGap.Status.SKIPPED,"Windows environment did not grant symlink creation capability",MigrationReleaseGap.Criticality.DOCUMENTED_LIMITATION),
            gap("BROWSERSTACK_NOT_RUN",MigrationReleaseGap.Stage.S12_BROWSER,MigrationReleaseGap.Status.NOT_RUN,"BrowserStack was not required or available for S11",MigrationReleaseGap.Criticality.OPTIONAL_ENVIRONMENT_VALIDATION),
            gap("REMOTE_GRID_NOT_RUN",MigrationReleaseGap.Stage.S12_BROWSER,MigrationReleaseGap.Status.NOT_RUN,"Remote/Grid provider validation remains for S12 where feasible",MigrationReleaseGap.Criticality.OPTIONAL_ENVIRONMENT_VALIDATION),
            gap("COMPATIBILITY_10K_MEMORY_HIGH",MigrationReleaseGap.Stage.S12_SCALE,MigrationReleaseGap.Status.DEFERRED,"Compatibility 10k high case observed approximately 1.19 GB memory",MigrationReleaseGap.Criticality.HARDENING_REQUIRED),
            gap("COMPATIBILITY_REPORT_NEAR_64MIB",MigrationReleaseGap.Stage.S12_SCALE,MigrationReleaseGap.Status.DEFERRED,"OBSERVABILITY comparison JSON approached the 64 MiB report bound",MigrationReleaseGap.Criticality.HARDENING_REQUIRED),
            gap("POLICY_PREVIEW_100K_SLOW",MigrationReleaseGap.Stage.S12_SCALE,MigrationReleaseGap.Status.DEFERRED,"Selector policy preview at 100k was approximately 44.8 seconds",MigrationReleaseGap.Criticality.HARDENING_REQUIRED),
            gap("MIGRATION_JAVAPARSER_10K_PHYSICAL_FILES_NOT_RUN",MigrationReleaseGap.Stage.S12_SCALE,MigrationReleaseGap.Status.NOT_RUN,"Physical 10k-file JavaParser migration benchmark was not run",MigrationReleaseGap.Criticality.HARDENING_REQUIRED),
            gap("REACTOR_VERSION_SCRIPT_EPHEMERAL_TARGET_PATH_ISSUE",MigrationReleaseGap.Stage.S12_RELEASE,MigrationReleaseGap.Status.KNOWN_LIMITATION,"Recursive reactor-version script encountered an ephemeral target path; bounded equivalent check passed",MigrationReleaseGap.Criticality.HARDENING_REQUIRED),
            gap("CMD_BAT_PS1_RUNNER_UNSUPPORTED",MigrationReleaseGap.Stage.S12_WINDOWS,MigrationReleaseGap.Status.KNOWN_LIMITATION,"Generic cmd, bat, and PowerShell execution remains intentionally unsupported",MigrationReleaseGap.Criticality.DOCUMENTED_LIMITATION));
        return create("0.4.0","v0.3.1",283,2183,List.of("guarded source apply","ownership-checked rollback and recovery","post-apply verification","final migration reporting","local Maven wrapper-main process execution"),gaps,List.of("compatibility 10k memory approximately 1.19 GB","observability JSON near 64 MiB","selector policy preview 100k approximately 44.8 seconds","migration physical 10k JavaParser benchmark missing"),List.of("Windows symlink fixture skipped","cmd bat ps1 runner unsupported"),List.of("BrowserStack not run","Remote Grid not run","S12 must run local Chrome and Firefox headed/headless DEFAULT/FAST matrix"),List.of("release docs and examples","release script robustness","provider matrix evidence"),List.of("PATCH_RELEASE_LANE: after 0.4.0 use main as latest stable 0.4.x, bump to 0.4.1-SNAPSHOT, fix/0.4.1-<topic>, release 0.4.1 tag v0.4.1, then 0.4.2-SNAPSHOT; add maintenance/0.4.x only if 0.5 work begins","After 0.4.0 focus on regression fixes and Selenium/browser compatibility; no new feature development is planned","S12 owns patch-release docs/scripts; no automatic push, tag, or publish"));}
    public static ReleaseHardeningHandoff create(String version,String baseline,int types,int callables,List<String>completed,List<MigrationReleaseGap>gaps,List<String>hotspots,List<String>platform,List<String>browsers,List<String>docs,List<String>maintenance){String id=id(version,baseline,types,callables,completed,gaps,hotspots,platform,browsers,docs,maintenance);return new ReleaseHardeningHandoff(1,1,id,version,baseline,types,callables,completed,gaps,hotspots,platform,browsers,docs,maintenance);}
    private static MigrationReleaseGap gap(String code,MigrationReleaseGap.Stage stage,MigrationReleaseGap.Status status,String reason,MigrationReleaseGap.Criticality criticality){return new MigrationReleaseGap(code,stage,status,reason,criticality,"S12",null);}
    private static String id(String version,String baseline,int types,int callables,List<String>completed,List<MigrationReleaseGap>gaps,List<String>hotspots,List<String>platform,List<String>browsers,List<String>docs,List<String>maintenance){List<String>f=new ArrayList<>(List.of(version,baseline,Integer.toString(types),Integer.toString(callables)));strings(completed).forEach(f::add);gaps.stream().sorted(Comparator.comparing(MigrationReleaseGap::gapCode)).forEach(x->{f.add(x.gapCode());f.add(x.stage().name());f.add(x.status().name());f.add(x.reason());f.add(x.criticality().name());f.add(x.owner());f.add(x.evidenceRef()==null?"":x.evidenceRef());});strings(hotspots).forEach(f::add);strings(platform).forEach(f::add);strings(browsers).forEach(f::add);strings(docs).forEach(f::add);strings(maintenance).forEach(f::add);return MigrationVerificationPlan.ref("migration-release-hardening-handoff-v1",f.toArray(String[]::new));}
    private static List<String>strings(List<String>v){return v==null?List.of():v.stream().distinct().sorted().toList();}private static String safe(String v){if(v==null||v.isBlank()||v.length()>128||v.indexOf('\0')>=0)throw new IllegalArgumentException("handoff value");return v;}
}
