package io.github.testlens.selector.tooling;

import io.github.testlens.selector.engine.*;
import tools.jackson.core.*;
import tools.jackson.core.json.JsonFactory;

import java.io.ByteArrayInputStream;
import java.util.*;

import static io.github.testlens.selector.tooling.SelectorHistoryModel.*;

/** Imports only non-value runtime facts. Report locator values are always RUNTIME_REDACTED trust. */
final class RuntimeReportHistoryImporter {
    private static final JsonFactory FACTORY=JsonFactory.builder().enable(StreamReadFeature.STRICT_DUPLICATE_DETECTION).streamReadConstraints(StreamReadConstraints.builder().maxDocumentLength(SelectorHistoryJson.MAX_DOCUMENT_BYTES).maxNestingDepth(32).maxStringLength(65_536).maxNameLength(256).maxNumberLength(32).maxTokenCount(8_000_000).build()).build();
    ImportResult importReport(byte[]bytes,RunDescriptor supplied,SelectorHistoryAggregator aggregate){if(bytes.length>SelectorHistoryJson.MAX_DOCUMENT_BYTES)throw new SelectorHistoryJson.HistoryFormatException("Runtime report exceeds import limit");String digest="selector-report-import-v1:sha256:"+CanonicalDigests.digestBytes("selector-report-import-v1",bytes);if(!aggregate.beginReport(digest))return new ImportResult(digest,0,true,false);RunDescriptor run=supplied==null?new RunDescriptor(null,null,null,null,digest,0,null,null,null,null,null,null,null):supplied;int observations=0;boolean summaryOnly=false;Set<String>seen=new HashSet<>();try(JsonParser p=FACTORY.createParser(ObjectReadContext.empty(),new ByteArrayInputStream(bytes))){if(p.nextToken()!=JsonToken.START_OBJECT)throw new SelectorHistoryJson.HistoryFormatException("Runtime report root must be object");while(p.nextToken()!=JsonToken.END_OBJECT){String name=p.currentName();JsonToken value=p.nextToken();if(name.equals("retention"))summaryOnly|=retention(p,value);else if(name.equals("events"))observations+=events(p,value,run,digest,aggregate,seen);else if(name.equals("sessions")){SessionResult result=sessions(p,value,run,digest,aggregate,seen);observations+=result.observations;summaryOnly|=result.summaryOnly;}else if(name.equals("session")){SessionResult result=session(p,value,run,digest,aggregate,seen);observations+=result.observations;summaryOnly|=result.summaryOnly;}else p.skipChildren();}}catch(Exception e){if(e instanceof RuntimeException r)throw r;throw new SelectorHistoryJson.HistoryFormatException("Invalid runtime report",e);}if(summaryOnly)aggregate.markSummaryOnly();return new ImportResult(digest,observations,false,summaryOnly);}
    private int events(JsonParser p,JsonToken token,RunDescriptor run,String report,SelectorHistoryAggregator aggregate,Set<String>seen)throws Exception{if(token!=JsonToken.START_ARRAY){p.skipChildren();return 0;}int count=0,index=0;while(p.nextToken()!=JsonToken.END_ARRAY){Event event=event(p,index++);if(event.strategy!=null){String observation="selector-report-observation-v1:sha256:"+CanonicalDigests.digest("selector-report-observation-v1",report,event.id==null?Integer.toString(index):event.id);if(seen.add(observation)){aggregate.add(new RedactedObservation(event.strategy,ComponentIdentity.of("TARGET","primary"),run,ObservationEvidence.Domain.NEW_RUN,observation,null,event.file,event.sourceClass,event.sourceMethod,event.line,event.outcome,event.matchCount,report));count++;}}}return count;}
    private Event event(JsonParser p,int index)throws Exception{if(p.currentToken()!=JsonToken.START_OBJECT){p.skipChildren();return new Event();}Event e=new Event();while(p.nextToken()!=JsonToken.END_OBJECT){String n=p.currentName();JsonToken v=p.nextToken();if(n.equals("id")&&v==JsonToken.VALUE_STRING)e.id=p.getString();else if(n.equals("locatorObservation"))locator(p,v,e);else p.skipChildren();}return e;}
    private void locator(JsonParser p,JsonToken token,Event e)throws Exception{if(token!=JsonToken.START_OBJECT){p.skipChildren();return;}while(p.nextToken()!=JsonToken.END_OBJECT){String n=p.currentName();JsonToken v=p.nextToken();switch(n){case"locator"->locatorValue(p,v,e);case"usageSource"->source(p,v,e);case"outcome"->{if(v==JsonToken.VALUE_STRING)e.outcome=p.getString();else p.skipChildren();}case"matchCount"->count(p,v,e);default->p.skipChildren();}}}
    private void locatorValue(JsonParser p,JsonToken token,Event e)throws Exception{if(token!=JsonToken.START_OBJECT){p.skipChildren();return;}while(p.nextToken()!=JsonToken.END_OBJECT){String n=p.currentName();JsonToken v=p.nextToken();if(n.equals("strategy")&&v==JsonToken.VALUE_STRING)e.strategy=SelectorSubject.normalizeStrategy(p.getString());else p.skipChildren();}}
    private void source(JsonParser p,JsonToken token,Event e)throws Exception{if(token!=JsonToken.START_OBJECT){p.skipChildren();return;}while(p.nextToken()!=JsonToken.END_OBJECT){String n=p.currentName();JsonToken v=p.nextToken();if(v==JsonToken.VALUE_STRING){switch(n){case"className"->e.sourceClass=p.getString();case"methodName"->e.sourceMethod=p.getString();case"fileName"->e.file=p.getString();default->{}}}else if(n.equals("line")&&v==JsonToken.VALUE_NUMBER_INT)e.line=p.getIntValue();else p.skipChildren();}}
    private void count(JsonParser p,JsonToken token,Event e)throws Exception{if(token!=JsonToken.START_OBJECT){p.skipChildren();return;}while(p.nextToken()!=JsonToken.END_OBJECT){String n=p.currentName();JsonToken v=p.nextToken();if(n.equals("value")&&v==JsonToken.VALUE_NUMBER_INT)e.matchCount=p.getIntValue();else p.skipChildren();}}
    private boolean retention(JsonParser p,JsonToken token)throws Exception{if(token!=JsonToken.START_OBJECT){p.skipChildren();return false;}boolean summary=false;while(p.nextToken()!=JsonToken.END_OBJECT){String n=p.currentName();JsonToken v=p.nextToken();if(n.equals("passedSessionRetention")&&v==JsonToken.VALUE_STRING)summary="SUMMARY_ONLY".equals(p.getString());else p.skipChildren();}return summary;}
    private SessionResult session(JsonParser p,JsonToken token,RunDescriptor run,String report,SelectorHistoryAggregator aggregate,Set<String>seen)throws Exception{if(token!=JsonToken.START_OBJECT){p.skipChildren();return new SessionResult(0,false);}int observations=0;boolean summary=false;while(p.nextToken()!=JsonToken.END_OBJECT){String n=p.currentName();JsonToken v=p.nextToken();if(n.equals("events"))observations+=events(p,v,run,report,aggregate,seen);else if(n.equals("retention"))summary|=retention(p,v);else p.skipChildren();}return new SessionResult(observations,summary);}
    private SessionResult sessions(JsonParser p,JsonToken token,RunDescriptor run,String report,SelectorHistoryAggregator aggregate,Set<String>seen)throws Exception{if(token!=JsonToken.START_ARRAY){p.skipChildren();return new SessionResult(0,false);}int observations=0;boolean summary=false;while(p.nextToken()!=JsonToken.END_ARRAY){SessionResult result=session(p,p.currentToken(),run,report,aggregate,seen);observations+=result.observations;summary|=result.summaryOnly;}return new SessionResult(observations,summary);}
    record ImportResult(String reportDigest,int observations,boolean duplicate,boolean summaryOnly){}
    private record SessionResult(int observations,boolean summaryOnly){}
    private static final class Event{String id,strategy,file,sourceClass,sourceMethod,outcome;Integer line,matchCount;}
}
