package io.github.testlens.selector.tooling;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.Comparator;

import static io.github.testlens.selector.tooling.SelectorAuditModel.*;

/** Minimal standalone viewer over the already-computed sanitized AuditReport. */
final class SelectorAuditHtml {
    private SelectorAuditHtml(){}
    static byte[] render(AuditReport report){StringBuilder out=new StringBuilder(64_000);out.append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>Test Lens Selector Audit</title><style>")
            .append("body{font:14px system-ui;margin:0;color:#18202b;background:#f5f7fa}header,main{max-width:1200px;margin:auto;padding:20px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:10px}.card,details,.panel{background:white;border:1px solid #d8dee8;border-radius:8px;padding:12px;margin:10px 0}.ERROR{border-left:5px solid #b42318}.WARNING{border-left:5px solid #f79009}.REVIEW{border-left:5px solid #6172f3}.INFO{border-left:5px solid #98a2b3}.tag{font:12px ui-monospace;background:#eef2f7;padding:2px 5px;border-radius:4px}.muted{color:#667085}.hidden{display:none}button{margin:3px;padding:6px 9px}summary{cursor:pointer;font-weight:600}code{overflow-wrap:anywhere}")
            .append("</style></head><body><header><h1>Selector Audit</h1><p class=\"muted\">").append(esc(report.analysisMode().name())).append(" · ").append(esc(report.overallCompleteness().name())).append("</p><div class=\"cards\">");
        card(out,"Declarations",report.summary().declarationsAudited());card(out,"Review",report.summary().activeReviewFindings());card(out,"Warnings",report.summary().warnings());card(out,"Errors",report.summary().errors());card(out,"Conflicts",report.summary().conflicts());card(out,"Families",report.summary().families());out.append("</div></header><main><section id=\"coverage\"><h2>Coverage</h2><div class=\"cards\">");dimension(out,"Static",report.coverage().staticCoverage());dimension(out,"Runtime",report.coverage().runtimeCoverage());dimension(out,"History",report.coverage().historyCoverage());dimension(out,"Policy",report.coverage().policyCoverage());dimension(out,"Candidate",report.coverage().candidateCoverage());dimension(out,"Output",report.coverage().outputCoverage());out.append("</div></section>");
        out.append("<section><h2>Filters</h2><div id=\"filters\">");for(Severity s:Severity.values())out.append("<button type=\"button\" data-filter=\"").append(s.name()).append("\">").append(s.name()).append("</button>");out.append("<button type=\"button\" data-filter=\"ALL\">ALL</button></div></section>");
        out.append("<section><h2>Project issues</h2>");if(report.projectIssues().isEmpty())out.append("<p class=\"muted\">None</p>");for(ProjectIssue x:report.projectIssues())out.append("<div class=\"panel ").append(x.severity()).append("\" data-severity=\"").append(x.severity()).append("\"><strong>").append(esc(x.code().name())).append("</strong><p>").append(esc(x.explanation())).append("</p></div>");out.append("</section>");
        out.append("<section><h2>Declarations</h2>");for(DeclarationAudit d:report.declarations()){String severity=d.findings().stream().map(AuditFinding::severity).max(Comparator.comparingInt(Enum::ordinal)).orElse(Severity.INFO).name();out.append("<details class=\"").append(severity).append("\" data-severity=\"").append(severity).append("\"><summary>").append(esc(d.source().logicalPath())).append(":").append(d.source().startLine()).append(" · ").append(esc(d.declarationKind())).append(" · ").append(esc(d.primaryRecommendation().name())).append("</summary><p><span class=\"tag\">").append(esc(d.declarationRef())).append("</span></p><p>Resolution: ").append(esc(d.resolutionStatus())).append(" · Freshness: ").append(esc(d.freshness().name())).append("</p><h3>Findings</h3>");for(AuditFinding f:d.findings())out.append("<div class=\"panel ").append(f.severity()).append("\"><strong>").append(esc(f.code().name())).append("</strong> <span class=\"tag\">").append(f.severity()).append(" / ").append(f.state()).append("</span><p>").append(esc(f.explanation())).append("</p></div>");out.append("<h3>Evidence and policy</h3><p>Evidence: ").append(esc(d.evidenceSummary().state())).append(" · Policy matches: ").append(d.policySummary().matchedRuleIds().size()).append(" · Usage count: ").append(d.usageSummary().count()).append("</p>");if(d.candidateSummary()!=null)out.append("<h3>Candidates</h3><p>").append(esc(d.candidateSummary().recommendation())).append(" · total ").append(d.candidateSummary().totalCandidateCount()).append(" · original validation ").append(esc(String.valueOf(d.candidateSummary().originalValidationState()))).append("</p>");out.append("</details>");}out.append("</section>");
        out.append("<section><h2>Families</h2>");for(FamilyAudit f:report.families())out.append("<details><summary>").append(esc(f.relationClass())).append(" · ").append(f.totalMembers()).append(" members</summary><p><code>").append(esc(f.familyFingerprint())).append("</code></p><p>Declarations: ").append(f.declarationCount()).append(" · History: ").append(f.runtimeHistorySubjectCount()).append(" · Conflicts: ").append(f.evidenceConflicts()).append("</p></details>");out.append("</section>");
        if(!report.outputLimitations().isEmpty()){out.append("<section><h2>Output limitations</h2><ul>");for(String x:report.outputLimitations())out.append("<li>").append(esc(x)).append("</li>");out.append("</ul></section>");}
        out.append("</main><script>document.querySelectorAll('[data-filter]').forEach(function(b){b.addEventListener('click',function(){var f=b.getAttribute('data-filter');document.querySelectorAll('[data-severity]').forEach(function(n){n.classList.toggle('hidden',f!=='ALL'&&n.getAttribute('data-severity')!==f);});});});</script></body></html>\n");byte[]bytes=out.toString().getBytes(StandardCharsets.UTF_8);if(bytes.length>MAX_SERIALIZED_BYTES)throw new SelectorAuditJson.AuditOutputException("OUTPUT_LIMIT_EXCEEDED","Audit HTML exceeds hard 64 MiB limit",null);return bytes;}
    static void writeLocal(AuditReport report,Path projectRoot,Path output)throws IOException{Path destination=SelectorAuditJson.safeDestination(projectRoot,output,"audit-v1.html");SelectorAuditJson.atomic(destination,render(report),"selector-audit-html-");}
    private static void card(StringBuilder out,String name,long value){out.append("<div class=\"card\"><strong>").append(value).append("</strong><br>").append(esc(name)).append("</div>");}
    private static void dimension(StringBuilder out,String name,DimensionCoverage d){out.append("<div class=\"card\"><strong>").append(esc(name)).append("</strong><br>").append(esc(d.status().name())).append("</div>");}
    private static String esc(String value){if(value==null)return "";StringBuilder out=new StringBuilder(value.length());for(int i=0;i<value.length();i++){char c=value.charAt(i);switch(c){case'&'->out.append("&amp;");case'<'->out.append("&lt;");case'>'->out.append("&gt;");case'\"'->out.append("&quot;");case'\''->out.append("&#39;");default->{if(c<0x20&&c!='\n'&&c!='\t')out.append("&#").append((int)c).append(';');else out.append(c);}}}return out.toString();}
}
