package io.github.testlens.selector.tooling;

import tools.jackson.core.JsonGenerator;
import tools.jackson.core.ObjectWriteContext;
import tools.jackson.core.json.JsonFactory;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.*;
import java.util.List;

import static io.github.testlens.selector.tooling.SelectorAuditModel.*;

/** Deterministic sanitized Audit JSON. The model itself contains no raw locator/source values. */
final class SelectorAuditJson {
    private static final JsonFactory FACTORY=JsonFactory.builder().build();
    private SelectorAuditJson(){}

    static byte[] serialize(AuditReport report){try{BoundedOutput out=new BoundedOutput(MAX_SERIALIZED_BYTES);try(JsonGenerator g=FACTORY.createGenerator(ObjectWriteContext.empty(),out)){write(g,report);g.writeRaw('\n');}return out.bytes();}catch(IOException e){throw new AuditOutputException("OUTPUT_LIMIT_EXCEEDED",e.getMessage(),e);}}
    static void writeLocal(AuditReport report,Path projectRoot,Path output)throws IOException{Path destination=safeDestination(projectRoot,output,"audit-v1.json");byte[]bytes=serialize(report);atomic(destination,bytes,"selector-audit-json-");}
    static Path safeDestination(Path projectRoot,Path output,String defaultName)throws IOException{Path root=projectRoot.toAbsolutePath().normalize().toRealPath(),allowed=root.resolve("target").normalize();Path requested=output==null?Path.of("target/test-lens/selector-audit",defaultName):output;Path destination=(requested.isAbsolute()?requested:root.resolve(requested)).normalize();Path parent=destination.getParent();if(parent==null||!destination.startsWith(allowed))throw new IllegalArgumentException("Audit output must stay under project target/");if(!Files.exists(allowed))Files.createDirectory(allowed);Path allowedReal=allowed.toRealPath();if(!allowedReal.startsWith(root))throw new IllegalArgumentException("Project target escapes through a link");Path current=allowed;for(Path part:allowed.relativize(parent)){current=current.resolve(part);if(!Files.exists(current))Files.createDirectory(current);if(!current.toRealPath().startsWith(allowedReal))throw new IllegalArgumentException("Audit output escapes project target through a link");}if(Files.exists(destination)&&!destination.toRealPath().startsWith(allowedReal))throw new IllegalArgumentException("Audit destination escapes through a link");return destination;}
    static void atomic(Path destination,byte[]bytes,String prefix)throws IOException{Path temporary=Files.createTempFile(destination.getParent(),prefix,".tmp");try{Files.write(temporary,bytes);try{Files.move(temporary,destination,StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}catch(AtomicMoveNotSupportedException ignored){Files.move(temporary,destination,StandardCopyOption.REPLACE_EXISTING);}}finally{Files.deleteIfExists(temporary);}}

    private static void write(JsonGenerator g,AuditReport r)throws IOException{g.writeStartObject();g.writeNumberProperty("auditSchemaVersion",r.auditSchemaVersion());g.writeNumberProperty("auditAlgorithmVersion",r.auditAlgorithmVersion());engine(g,r.engineVersions());project(g,r.project());generated(g,r.generatedFrom());g.writeStringProperty("analysisMode",r.analysisMode().name());g.writeStringProperty("overallCompleteness",r.overallCompleteness().name());summary(g,r.summary());coverage(g,r.coverage());g.writeArrayPropertyStart("projectIssues");for(ProjectIssue x:r.projectIssues())issue(g,x);g.writeEndArray();g.writeArrayPropertyStart("declarations");for(DeclarationAudit x:r.declarations())declaration(g,x);g.writeEndArray();g.writeArrayPropertyStart("runtimeOnlySubjects");for(RuntimeOnlyAudit x:r.runtimeOnlySubjects())runtime(g,x);g.writeEndArray();g.writeArrayPropertyStart("families");for(FamilyAudit x:r.families())family(g,x);g.writeEndArray();strings(g,"outputLimitations",r.outputLimitations());g.writeEndObject();}
    private static void engine(JsonGenerator g,EngineVersions x)throws IOException{g.writeObjectPropertyStart("engineVersions");g.writeStringProperty("auditVersion",x.auditVersion());g.writeStringProperty("selectorEngineVersion",x.selectorEngineVersion());g.writeNumberProperty("detectorCatalogVersion",x.detectorCatalogVersion());g.writeNumberProperty("canonicalizationVersion",x.canonicalizationVersion());number(g,"historySchemaVersion",x.historySchemaVersion());number(g,"familyFingerprintVersion",x.familyFingerprintVersion());number(g,"correlationAlgorithmVersion",x.correlationAlgorithmVersion());number(g,"candidateSchemaVersion",x.candidateSchemaVersion());strings(g,"limitations",x.limitations());g.writeEndObject();}
    private static void project(JsonGenerator g,Project x)throws IOException{g.writeObjectPropertyStart("project");field(g,"projectFingerprint",x.projectFingerprint());field(g,"sourceRevision",x.sourceRevision());strings(g,"sourceRoots",x.sourceRoots());g.writeEndObject();}
    private static void generated(JsonGenerator g,GeneratedFrom x)throws IOException{g.writeObjectPropertyStart("generatedFrom");field(g,"selectorIndexFingerprint",x.selectorIndexFingerprint());field(g,"historyFingerprint",x.historyFingerprint());field(g,"policyFingerprint",x.policyFingerprint());g.writeNumberProperty("candidateAnalyses",x.candidateAnalyses());g.writeEndObject();}
    private static void summary(JsonGenerator g,Summary x)throws IOException{g.writeObjectPropertyStart("summary");g.writeNumberProperty("declarationsAudited",x.declarationsAudited());g.writeNumberProperty("runtimeOnlySubjects",x.runtimeOnlySubjects());g.writeNumberProperty("activeReviewFindings",x.activeReviewFindings());g.writeNumberProperty("warnings",x.warnings());g.writeNumberProperty("errors",x.errors());g.writeNumberProperty("conflicts",x.conflicts());g.writeNumberProperty("observedVariable",x.observedVariable());g.writeNumberProperty("generatedLooking",x.generatedLooking());g.writeNumberProperty("generatedLookingCoveredByPolicy",x.generatedLookingCoveredByPolicy());g.writeNumberProperty("liveValidatedDeclarations",x.liveValidatedDeclarations());g.writeNumberProperty("alternativesAvailable",x.alternativesAvailable());g.writeNumberProperty("unresolvedOrUnsupported",x.unresolvedOrUnsupported());g.writeNumberProperty("historyIncomplete",x.historyIncomplete());g.writeNumberProperty("orphanedPolicies",x.orphanedPolicies());g.writeNumberProperty("families",x.families());g.writeEndObject();}
    private static void coverage(JsonGenerator g,Coverage x)throws IOException{g.writeObjectPropertyStart("coverage");dimension(g,"static",x.staticCoverage());dimension(g,"runtime",x.runtimeCoverage());dimension(g,"history",x.historyCoverage());dimension(g,"policy",x.policyCoverage());dimension(g,"candidate",x.candidateCoverage());dimension(g,"output",x.outputCoverage());g.writeEndObject();}
    private static void dimension(JsonGenerator g,String name,DimensionCoverage x)throws IOException{g.writeObjectPropertyStart(name);g.writeStringProperty("status",x.status().name());g.writeObjectPropertyStart("counts");for(Count c:x.counts())g.writeNumberProperty(c.name(),c.value());g.writeEndObject();strings(g,"limitations",x.limitations());g.writeEndObject();}
    private static void issue(JsonGenerator g,ProjectIssue x)throws IOException{g.writeStartObject();g.writeStringProperty("issueId",x.issueId());g.writeStringProperty("code",x.code().name());g.writeStringProperty("severity",x.severity().name());strings(g,"reasonCodes",x.reasonCodes());strings(g,"references",x.references());g.writeStringProperty("explanation",x.explanation());g.writeEndObject();}
    private static void declaration(JsonGenerator g,DeclarationAudit x)throws IOException{g.writeStartObject();g.writeStringProperty("declarationRef",x.declarationRef());source(g,x.source());g.writeStringProperty("declarationKind",x.declarationKind());g.writeStringProperty("resolutionStatus",x.resolutionStatus());g.writeStringProperty("expressionKind",x.expressionKind());g.writeStringProperty("expressionDigest",x.expressionDigest());g.writeStringProperty("freshness",x.freshness().name());g.writeArrayPropertyStart("components");for(ComponentAudit c:x.components())component(g,c);g.writeEndArray();correlation(g,x.correlationSummary());usage(g,x.usageSummary());g.writeArrayPropertyStart("findings");for(AuditFinding f:x.findings())finding(g,f);g.writeEndArray();policy(g,x.policySummary());evidence(g,x.evidenceSummary());if(x.candidateSummary()!=null)candidate(g,x.candidateSummary());similar(g,x.similarSummary());g.writeStringProperty("primaryRecommendation",x.primaryRecommendation().name());enums(g,"supportingActions",x.supportingActions());strings(g,"limitations",x.limitations());g.writeEndObject();}
    private static void source(JsonGenerator g,SourceRef x)throws IOException{g.writeObjectPropertyStart("source");g.writeStringProperty("logicalPath",x.logicalPath());g.writeNumberProperty("startLine",x.startLine());g.writeNumberProperty("startColumn",x.startColumn());g.writeNumberProperty("endLine",x.endLine());g.writeNumberProperty("endColumn",x.endColumn());g.writeNumberProperty("startOffset",x.startOffset());g.writeNumberProperty("endOffsetExclusive",x.endOffsetExclusive());g.writeStringProperty("offsetUnit","UTF16_CODE_UNIT");g.writeBooleanProperty("generated",x.generated());g.writeBooleanProperty("readOnly",x.readOnly());g.writeEndObject();}
    private static void component(JsonGenerator g,ComponentAudit x)throws IOException{g.writeStartObject();g.writeStringProperty("componentRef",x.componentRef());g.writeStringProperty("componentRole",x.componentRole());strings(g,"componentPath",x.componentPath());g.writeStringProperty("strategy",x.strategy());field(g,"exactDigest",x.exactDigest());enums(g,"appearanceFamilies",x.appearanceFamilies());field(g,"structuralFamilyFingerprint",x.structuralFamilyFingerprint());g.writeStringProperty("effectiveDisposition",x.effectiveDisposition());g.writeEndObject();}
    private static void correlation(JsonGenerator g,CorrelationSummary x)throws IOException{g.writeObjectPropertyStart("correlationSummary");g.writeStringProperty("strongestConfidence",x.strongestConfidence().name());g.writeNumberProperty("exact",x.exact());g.writeNumberProperty("strong",x.strong());g.writeNumberProperty("ambiguous",x.ambiguous());g.writeNumberProperty("unknown",x.unknown());strings(g,"limitations",x.limitations());g.writeEndObject();}
    private static void usage(JsonGenerator g,UsageSummary x)throws IOException{g.writeObjectPropertyStart("usageSummary");g.writeNumberProperty("count",x.count());g.writeArrayPropertyStart("samples");for(UsageSample u:x.samples()){g.writeStartObject();g.writeStringProperty("usageRef",u.usageRef());field(g,"logicalPath",u.logicalPath());field(g,"usageClassDigest",u.usageClassDigest());field(g,"usageMethodDigest",u.usageMethodDigest());number(g,"line",u.line());g.writeEndObject();}g.writeEndArray();g.writeBooleanProperty("truncated",x.truncated());g.writeEndObject();}
    private static void finding(JsonGenerator g,AuditFinding x)throws IOException{g.writeStartObject();g.writeStringProperty("findingId",x.findingId());g.writeStringProperty("category",x.category().name());g.writeStringProperty("code",x.code().name());g.writeStringProperty("severity",x.severity().name());g.writeStringProperty("state",x.state().name());field(g,"componentRef",x.componentRef());strings(g,"reasonCodes",x.reasonCodes());strings(g,"evidenceRefs",x.evidenceRefs());strings(g,"policyRuleIds",x.policyRuleIds());strings(g,"candidateIds",x.candidateIds());strings(g,"familyFingerprints",x.familyFingerprints());g.writeStringProperty("explanation",x.explanation());g.writeEndObject();}
    private static void policy(JsonGenerator g,PolicySummary x)throws IOException{g.writeObjectPropertyStart("policySummary");strings(g,"matchedRuleIds",x.matchedRuleIds());strings(g,"selectedRuleIds",x.selectedRuleIds());strings(g,"decisions",x.decisions());g.writeNumberProperty("conflictCount",x.conflictCount());g.writeEndObject();}
    private static void evidence(JsonGenerator g,EvidenceSummary x)throws IOException{g.writeObjectPropertyStart("evidenceSummary");g.writeStringProperty("state",x.state());g.writeNumberProperty("comparableDomains",x.comparableDomains());g.writeNumberProperty("changedDomains",x.changedDomains());g.writeNumberProperty("distinctValueDigests",x.distinctValueDigests());g.writeBooleanProperty("incomplete",x.incomplete());strings(g,"domains",x.domains());strings(g,"limitations",x.limitations());g.writeEndObject();}
    private static void candidate(JsonGenerator g,CandidateSummary x)throws IOException{g.writeObjectPropertyStart("candidateSummary");field(g,"originalCandidateId",x.originalCandidateId());g.writeStringProperty("recommendation",x.recommendation());field(g,"originalValidationState",x.originalValidationState());g.writeNumberProperty("totalCandidateCount",x.totalCandidateCount());g.writeArrayPropertyStart("alternatives");for(CandidateDetail c:x.alternatives()){g.writeStartObject();g.writeStringProperty("candidateId",c.candidateId());strings(g,"origins",c.origins());g.writeStringProperty("validationState",c.validationState());g.writeNumberProperty("matchCount",c.matchCount());strings(g,"reasonCodes",c.reasonCodes());strings(g,"limitations",c.limitations());g.writeEndObject();}g.writeEndArray();g.writeBooleanProperty("candidatesTruncated",x.candidatesTruncated());strings(g,"limitations",x.limitations());g.writeEndObject();}
    private static void similar(JsonGenerator g,SimilarSummary x)throws IOException{g.writeObjectPropertyStart("similarSummary");strings(g,"familyFingerprints",x.familyFingerprints());g.writeNumberProperty("relatedCount",x.relatedCount());strings(g,"patternProposalKinds",x.patternProposalKinds());g.writeNumberProperty("previewMatches",x.previewMatches());g.writeEndObject();}
    private static void runtime(JsonGenerator g,RuntimeOnlyAudit x)throws IOException{g.writeStartObject();g.writeStringProperty("subjectRef",x.subjectRef());g.writeStringProperty("correlationConfidence",x.correlationConfidence().name());strings(g,"supportingSignals",x.supportingSignals());strings(g,"conflictingSignals",x.conflictingSignals());g.writeArrayPropertyStart("findings");for(AuditFinding f:x.findings())finding(g,f);g.writeEndArray();evidence(g,x.evidenceSummary());usage(g,x.usageSummary());strings(g,"limitations",x.limitations());g.writeEndObject();}
    private static void family(JsonGenerator g,FamilyAudit x)throws IOException{g.writeStartObject();g.writeStringProperty("familyFingerprint",x.familyFingerprint());g.writeStringProperty("relationClass",x.relationClass());g.writeNumberProperty("declarationCount",x.declarationCount());g.writeNumberProperty("runtimeHistorySubjectCount",x.runtimeHistorySubjectCount());strings(g,"modules",x.modules());strings(g,"paths",x.paths());enums(g,"appearanceFamilies",x.appearanceFamilies());g.writeNumberProperty("policyCoveredMembers",x.policyCoveredMembers());g.writeNumberProperty("evidenceConflicts",x.evidenceConflicts());if(x.patternProposal()!=null){PatternSummary p=x.patternProposal();g.writeObjectPropertyStart("patternProposal");strings(g,"segmentKinds",p.segmentKinds());g.writeNumberProperty("matchedStatic",p.matchedStatic());g.writeNumberProperty("matchedHistory",p.matchedHistory());g.writeNumberProperty("excluded",p.excluded());g.writeNumberProperty("conflicts",p.conflicts());strings(g,"affectedDeclarationRefs",p.affectedDeclarationRefs());g.writeEndObject();}strings(g,"memberRefs",x.memberRefs());g.writeNumberProperty("totalMembers",x.totalMembers());g.writeBooleanProperty("membersTruncated",x.membersTruncated());g.writeEndObject();}
    private static void strings(JsonGenerator g,String name,List<String>values)throws IOException{g.writeArrayPropertyStart(name);for(String value:values)g.writeString(value);g.writeEndArray();}
    private static void enums(JsonGenerator g,String name,List<? extends Enum<?>>values)throws IOException{g.writeArrayPropertyStart(name);for(Enum<?>value:values)g.writeString(value.name());g.writeEndArray();}
    private static void field(JsonGenerator g,String name,String value)throws IOException{if(value!=null)g.writeStringProperty(name,value);}
    private static void number(JsonGenerator g,String name,Integer value)throws IOException{if(value!=null)g.writeNumberProperty(name,value);}
    static final class AuditOutputException extends IllegalStateException{final String code;AuditOutputException(String code,String message,Throwable cause){super(message,cause);this.code=code;}String code(){return code;}}
    private static final class BoundedOutput extends OutputStream{private final long limit;private final ByteArrayOutputStream delegate=new ByteArrayOutputStream();BoundedOutput(long limit){this.limit=limit;}@Override public void write(int value)throws IOException{ensure(1);delegate.write(value);}@Override public void write(byte[]b,int off,int len)throws IOException{ensure(len);delegate.write(b,off,len);}private void ensure(int added)throws IOException{if(delegate.size()+(long)added>limit)throw new IOException("Audit JSON exceeds hard 64 MiB limit");}byte[]bytes(){return delegate.toByteArray();}}
}
