package io.github.testlens.selector.tooling;

import io.github.testlens.selector.engine.*;

import java.util.*;
import java.util.stream.Stream;

import static io.github.testlens.selector.tooling.SelectorAuditModel.*;
import static io.github.testlens.selector.tooling.SelectorHistoryModel.*;
import static io.github.testlens.selector.tooling.SelectorIndexModel.*;

/** Offline declaration-first orchestration. It performs no browser, build, Git, or source parsing work. */
final class SelectorAuditOrchestrator {
    static final String AUDIT_VERSION="0.4.0";
    private final SelectorStabilityEngine stability=new SelectorStabilityEngine();
    private final SimilarityFederation federation=new SimilarityFederation();

    record CandidateInput(CandidateAnalysis analysis,SimilaritySubject.Confidence confidence,String declarationRef){
        CandidateInput(CandidateAnalysis analysis){this(analysis,SimilaritySubject.Confidence.EXACT,analysis==null?null:analysis.declarationRef());}
    }
    record Request(SelectorIndex index,CompiledPolicySet policies,History history,List<CandidateInput> candidates,
                   String projectFingerprint,Map<String,String> currentContentHashes,
                   Map<String,FederatedPatternPreview.Result> patternPreviews,String selectorIndexFingerprint,
                   String historyFingerprint,String policyFingerprint,List<ProjectIssue> inputIssues){
        Request{Objects.requireNonNull(index,"selector-index is required");policies=policies==null?CompiledPolicySet.empty():policies;candidates=candidates==null?List.of():List.copyOf(candidates);currentContentHashes=currentContentHashes==null?Map.of():Map.copyOf(currentContentHashes);patternPreviews=patternPreviews==null?Map.of():Map.copyOf(patternPreviews);inputIssues=inputIssues==null?List.of():List.copyOf(inputIssues);}
        static Request staticOnly(SelectorIndex index){return new Request(index,CompiledPolicySet.empty(),null,List.of(),null,Map.of(),Map.of(),null,null,null,List.of());}
    }

    AuditReport audit(Request request){
        validateIndex(request.index());
        List<DeclarationRecord> declarations=request.index().files().stream().flatMap(f->f.declarations().stream()).sorted(declarationOrder()).toList();
        if(declarations.size()>MAX_DECLARATIONS)throw new AuditInputException("Declaration limit exceeded");
        Map<String,DeclarationRecord>byRef=new HashMap<>();for(DeclarationRecord d:declarations)if(byRef.put(d.declarationRef(),d)!=null)throw new AuditInputException("Duplicate declarationRef: "+d.declarationRef());
        List<ProjectIssue>projectIssues=new ArrayList<>(request.inputIssues());coverageIssues(request.index(),projectIssues);
        History acceptedHistory=request.history();if(acceptedHistory!=null&&request.projectFingerprint()!=null&&acceptedHistory.project().projectFingerprint()!=null&&!request.projectFingerprint().equals(acceptedHistory.project().projectFingerprint())){projectIssues.add(issue(ProjectIssueCode.PROJECT_FINGERPRINT_MISMATCH,Severity.WARNING,List.of("KNOWN_PROJECT_IDENTITIES_DIFFER"),List.of(request.projectFingerprint(),acceptedHistory.project().projectFingerprint()),"History belongs to a different known project and was not merged"));acceptedHistory=null;}
        if(acceptedHistory!=null&&acceptedHistory.coverage().summaryOnlyRuns()>0)projectIssues.add(issue(ProjectIssueCode.SUMMARY_ONLY_HISTORY,Severity.REVIEW,List.of("SUMMARY_ONLY_HAS_NO_DETAILED_LOCATORS"),List.of(),"Summary-only runs make selector history incomplete"));
        if(acceptedHistory!=null&&acceptedHistory.retention().pruned())projectIssues.add(issue(ProjectIssueCode.HISTORY_PRUNED,Severity.REVIEW,List.of("HISTORY_RETENTION_PRUNED"),List.of(),"History retention removed detail; evidence coverage is incomplete"));
        SourceFreshnessState freshness=freshness(request,projectIssues);
        HistoryAttachment history=attachHistory(acceptedHistory,declarations,byRef,projectIssues);
        CandidateAttachment candidates=attachCandidates(request.candidates(),byRef,projectIssues);
        List<SimilaritySubject>staticSubjects=new ArrayList<>();for(DeclarationRecord d:declarations)staticSubjects.addAll(federation.staticSubjects(d));
        Map<String,List<SimilaritySubject>>staticByDeclaration=staticSubjects.stream().collect(java.util.stream.Collectors.groupingBy(s->s.subject().declarationRef()));
        Map<String,FamilyWork>familyWork=buildFamilies(staticSubjects,history.allSubjects,request.patternPreviews());
        Map<String,Integer>exactCounts=new HashMap<>();for(SimilaritySubject s:staticSubjects)if(s.exactDigest()!=null)exactCounts.merge(s.subject().strategy()+'\0'+s.exactDigest(),1,Integer::sum);
        Request effective=acceptedHistory==request.history()?request:new Request(request.index(),request.policies(),acceptedHistory,request.candidates(),request.projectFingerprint(),request.currentContentHashes(),request.patternPreviews(),request.selectorIndexFingerprint(),null,request.policyFingerprint(),request.inputIssues());
        List<DeclarationAudit>out=new ArrayList<>();for(DeclarationRecord d:declarations)out.add(declaration(effective,d,staticByDeclaration.getOrDefault(d.declarationRef(),List.of()),history.attached.getOrDefault(d.declarationRef(),List.of()),candidates.attached.get(d.declarationRef()),freshness.byPath.getOrDefault(d.logicalPath(),SourceFreshness.UNKNOWN),familyWork,exactCounts,projectIssues));
        for(DeclarationAudit declaration:out)for(ComponentAudit component:declaration.components())if(component.structuralFamilyFingerprint()!=null){FamilyWork family=familyWork.get(component.structuralFamilyFingerprint());if(family!=null){if("DECLARED_STABLE".equals(component.effectiveDisposition()))family.policyCovered.add(declaration.declarationRef());if("POLICY_EVIDENCE_CONFLICT".equals(component.effectiveDisposition()))family.evidenceConflicts++;}}
        out.sort(auditOrder());
        List<RuntimeOnlyAudit>runtimeOnly=history.runtimeOnly.stream().map(this::runtimeOnly).sorted(Comparator.comparing(RuntimeOnlyAudit::subjectRef)).limit(MAX_RUNTIME_ONLY).toList();
        if(history.runtimeOnly.size()>MAX_RUNTIME_ONLY)projectIssues.add(issue(ProjectIssueCode.OUTPUT_TRUNCATED,Severity.REVIEW,List.of("RUNTIME_ONLY_LIMIT"),List.of(),"Runtime-only entries exceeded the durable report bound"));
        List<FamilyAudit>families=familyWork.values().stream().map(FamilyWork::freeze).sorted(Comparator.comparing(FamilyAudit::familyFingerprint)).limit(MAX_FAMILIES).toList();
        if(familyWork.size()>MAX_FAMILIES)projectIssues.add(issue(ProjectIssueCode.OUTPUT_TRUNCATED,Severity.REVIEW,List.of("FAMILY_LIMIT"),List.of(),"Family summaries exceeded the durable report bound"));
        orphanedPolicies(request.policies(),byRef,projectIssues);
        AnalysisMode mode=acceptedHistory==null&&request.candidates().isEmpty()&&request.policies().rules().isEmpty()?AnalysisMode.STATIC_ONLY:AnalysisMode.ENRICHED_OFFLINE;
        SelectorAuditModel.Coverage coverage=coverage(effective,history,candidates,projectIssues,out,runtimeOnly,families);
        CompletenessStatus complete=overall(coverage,projectIssues);
        List<ProjectIssue>sortedIssues=projectIssues.stream().distinct().sorted(Comparator.comparingInt((ProjectIssue x)->x.severity().ordinal()).reversed().thenComparing(x->x.code().name()).thenComparing(ProjectIssue::issueId)).toList();
        Summary summary=summary(out,runtimeOnly,families,sortedIssues);
        List<String>versionLimits=request.candidates().isEmpty()?List.of():List.of("CANDIDATE_GENERATOR_AND_RANKING_VERSION_UNAVAILABLE");
        EngineVersions versions=new EngineVersions(AUDIT_VERSION,SelectorStabilityEngine.ENGINE_VERSION,AppearanceClassifier.DETECTOR_CATALOG_VERSION,CanonicalDigests.CANONICALIZATION_VERSION,acceptedHistory==null?null:acceptedHistory.schemaVersion(),acceptedHistory==null?null:acceptedHistory.familyFingerprintVersion(),acceptedHistory==null?null:acceptedHistory.correlationAlgorithmVersion(),request.candidates().isEmpty()?null:CandidateAnalysis.SCHEMA_VERSION,versionLimits);
        SelectorAuditModel.Project project=new SelectorAuditModel.Project(request.projectFingerprint(),request.index().project().sourceRevision(),request.index().project().sourceRoots());
        GeneratedFrom generated=new GeneratedFrom(request.selectorIndexFingerprint(),request.historyFingerprint(),request.policyFingerprint(),request.candidates().size());
        List<String>outputLimitations=Stream.concat(out.stream().flatMap(x->x.limitations().stream()),families.stream().filter(FamilyAudit::membersTruncated).map(x->"FAMILY_MEMBERS_TRUNCATED:"+x.familyFingerprint())).distinct().sorted().toList();
        return new AuditReport(SelectorAuditModel.SCHEMA_VERSION,ALGORITHM_VERSION,versions,project,generated,mode,complete,summary,coverage,sortedIssues,out,runtimeOnly,families,outputLimitations);
    }

    private DeclarationAudit declaration(Request request,DeclarationRecord d,List<SimilaritySubject>subjects,List<Subject>history,
                                         CandidateInput candidate,SourceFreshness freshness,Map<String,FamilyWork>families,
                                         Map<String,Integer>exactCounts,List<ProjectIssue>projectIssues){
        List<AuditFinding>findings=new ArrayList<>();List<ComponentAudit>components=new ArrayList<>();List<StabilityAssessment>assessments=new ArrayList<>();List<String>limits=new ArrayList<>();
        sourceFinding(d,request.index(),findings,projectIssues);
        for(SimilaritySubject s:subjects){List<Subject>componentHistory=history.stream().filter(h->h.componentRef().equals(s.component().componentRef())||subjects.size()==1).toList();ObservationEvidence evidence=evidence(componentHistory);StabilityAssessment a=stability.analyzeIndexed(s.subject(),s.appearanceSignals(),s.exactDigest(),s.structuralFamily(),evidence,request.policies());assessments.add(a);stabilityFindings(s,a,componentHistory,request.history(),findings);String family=s.structuralFamily()==null?null:s.structuralFamily().fingerprint();components.add(new ComponentAudit(s.component().componentRef(),s.component().componentRole(),s.component().componentPath(),s.subject().strategy(),s.exactDigest(),s.appearanceSignals().stream().map(AppearanceSignal::family).distinct().sorted().toList(),family,a.effectiveDisposition().name()));if(s.exactDigest()!=null&&exactCounts.getOrDefault(s.subject().strategy()+'\0'+s.exactDigest(),0)>1)findings.add(finding(d.declarationRef(),s.component().componentRef(),Category.STRUCTURAL,FindingCode.DUPLICATE_EXACT_LOCATOR,Severity.INFO,FindingState.INFORMATIONAL,List.of("SAME_STRATEGY_AND_EXACT_DIGEST"),List.of(),List.of(),List.of(),List.of(),"The same exact locator occurs in multiple declarations; this may be intentional"));if(family!=null&&families.get(family)!=null&&families.get(family).members.size()>1)findings.add(finding(d.declarationRef(),s.component().componentRef(),Category.STRUCTURAL,FindingCode.RELATED_GENERATED_FAMILY,Severity.INFO,FindingState.INFORMATIONAL,List.of("STRUCTURAL_FAMILY"),List.of(),List.of(),List.of(),List.of(family),"Related selector subjects share a structural family"));}
        if(history.isEmpty())findings.add(finding(d.declarationRef(),null,Category.EVIDENCE,FindingCode.EVIDENCE_NOT_AVAILABLE,Severity.INFO,FindingState.INCOMPLETE,List.of("NO_HISTORY_SUBJECT"),List.of(),List.of(),List.of(),List.of(),"No cross-run history is available; stability is not established"));
        for(SimilaritySubject subject:subjects){FederatedPatternPreview.Result preview=request.patternPreviews().get(subject.subjectRef());if(preview!=null&&preview.matchedStaticSubjects().size()+preview.matchedHistorySubjects().size()>1)findings.add(finding(d.declarationRef(),subject.component().componentRef(),Category.STRUCTURAL,FindingCode.BROAD_PATTERN_IMPACT,Severity.REVIEW,FindingState.ACTIVE,List.of("PATTERN_PREVIEW_AFFECTS_MULTIPLE_SUBJECTS"),List.of(),List.of(),List.of(),family(subject),"A detector-backed pattern proposal affects multiple supplied subjects and requires preview review"));}
        CandidateSummary candidateSummary=candidate==null?null:candidate(candidate,d,findings,limits);
        if(candidate!=null&&candidate.confidence()!=SimilaritySubject.Confidence.EXACT)limits.add("CANDIDATE_ATTACHMENT_"+candidate.confidence());
        List<AuditFinding>bounded=boundFindings(findings,limits);
        Recommendation primary=recommend(bounded,candidateSummary,candidate==null?null:candidate.confidence());List<Recommendation>supporting=supporting(bounded,primary);
        SourceRange r=d.sourceRange();SourceRef source=new SourceRef(d.logicalPath(),r.startLine(),r.startColumn(),r.endLine(),r.endColumn(),r.startOffset(),r.endOffsetExclusive(),d.generated(),d.readOnly());
        CorrelationSummary correlations=correlation(history,candidate);SelectorAuditModel.UsageSummary usage=usage(history);
        PolicySummary policy=policy(assessments);EvidenceSummary evidence=summaryEvidence(history,request.history());
        List<String>familyRefs=components.stream().map(ComponentAudit::structuralFamilyFingerprint).filter(Objects::nonNull).distinct().sorted().toList();int related=familyRefs.stream().mapToInt(x->Math.max(0,families.get(x).members.size()-1)).sum();List<String>proposalKinds=subjects.stream().map(s->new PatternProposal().propose(s.subject())).filter(PatternProposal.Result::useful).flatMap(x->x.pattern().segments().stream()).map(x->x.kind().name()).distinct().sorted().toList();int preview=subjects.stream().map(SimilaritySubject::subjectRef).map(request.patternPreviews()::get).filter(Objects::nonNull).mapToInt(x->x.matchedStaticSubjects().size()+x.matchedHistorySubjects().size()).sum();SimilarSummary similar=new SimilarSummary(familyRefs,related,proposalKinds,preview);
        String expressionDigest="selector-audit-expression-v1:sha256:"+CanonicalDigests.digest("selector-audit-expression-v1",d.locatorExpression().normalizedExpression());
        return new DeclarationAudit(d.declarationRef(),source,d.declarationKind().name(),d.resolutionStatus().name(),d.locatorExpression().kind().name(),expressionDigest,freshness,components,correlations,usage,bounded,policy,evidence,candidateSummary,similar,primary,supporting,limits.stream().distinct().sorted().toList());
    }

    private void sourceFinding(DeclarationRecord d,SelectorIndex index,List<AuditFinding>out,List<ProjectIssue>projectIssues){
        List<Issue>issues=index.files().stream().filter(f->f.logicalPath().equals(d.logicalPath())).flatMap(f->f.issues().stream()).toList();boolean unresolved=issues.stream().anyMatch(i->i.code().equals("SYMBOL_UNRESOLVED"));
        switch(d.resolutionStatus()){
            case RESOLVED->{}case PARTIALLY_RESOLVED->out.add(finding(d.declarationRef(),null,Category.SOURCE,unresolved?FindingCode.SOURCE_UNRESOLVED_DECLARATION:FindingCode.SOURCE_PARTIALLY_RESOLVED_DECLARATION,Severity.REVIEW,FindingState.INCOMPLETE,issues.stream().map(Issue::code).distinct().sorted().toList(),List.of(),List.of(),List.of(),List.of(),"Static resolution is incomplete; this is not proof of a locator failure"));
            case DYNAMIC->out.add(finding(d.declarationRef(),null,Category.SOURCE,FindingCode.SOURCE_DYNAMIC_DECLARATION,Severity.INFO,FindingState.INFORMATIONAL,List.of("RUNTIME_DEPENDENCY"),List.of(),List.of(),List.of(),List.of(),"The declaration depends on runtime data; dynamic does not mean defective"));
            case CUSTOM->out.add(finding(d.declarationRef(),null,Category.SOURCE,FindingCode.SOURCE_CUSTOM_LOCATOR,Severity.INFO,FindingState.UNSUPPORTED,List.of("CUSTOM_SEMANTICS_OPAQUE"),List.of(),List.of(),List.of(),List.of(),"Custom locator semantics are outside V1 static interpretation"));
            case UNSUPPORTED->out.add(finding(d.declarationRef(),null,Category.SOURCE,FindingCode.SOURCE_UNSUPPORTED_DECLARATION,Severity.REVIEW,FindingState.UNSUPPORTED,issues.stream().map(Issue::code).distinct().sorted().toList(),List.of(),List.of(),List.of(),List.of(),"This declaration form is unsupported by static discovery"));
            case ERROR->{boolean proven=issues.stream().anyMatch(i->i.code().equals("FINDBY_MULTIPLE_STRATEGIES")||i.code().equals("ANNOTATION_CHILDREN_MISSING"));Severity severity=proven?Severity.ERROR:Severity.REVIEW;FindingState state=proven?FindingState.ACTIVE:FindingState.INCOMPLETE;out.add(finding(d.declarationRef(),null,Category.SOURCE,FindingCode.SOURCE_RESOLUTION_ERROR,severity,state,issues.stream().map(Issue::code).distinct().sorted().toList(),List.of(),List.of(),List.of(),List.of(),proven?"The source declaration is structurally invalid according to Selenium annotation semantics":"Static analysis could not resolve the declaration; no current locator failure is proven"));if(!proven)projectIssues.add(issue(ProjectIssueCode.STATIC_ANALYSIS_INTERNAL_ERROR,Severity.REVIEW,List.of("UNCLASSIFIED_STATIC_RESOLUTION_ERROR"),List.of(d.declarationRef()),"Static resolution failed without proof that the locator itself is invalid"));}
        }
    }

    private void stabilityFindings(SimilaritySubject s,StabilityAssessment a,List<Subject>history,History all,List<AuditFinding>out){String component=s.component().componentRef();List<String>detectors=s.appearanceSignals().stream().map(x->x.family().name()+":"+x.confidence()).distinct().sorted().toList();List<String>rules=a.policyEvaluation().matchedRuleIds();List<String>evidence=a.evidenceSummary().comparisons().stream().map(ObservationEvidence.Comparison::evidenceRef).toList();
        if(!s.appearanceSignals().isEmpty()){boolean covered=a.effectiveDisposition()==StabilityAssessment.EffectiveDisposition.DECLARED_STABLE;out.add(finding(s.subject().declarationRef(),component,Category.APPEARANCE,FindingCode.APPEARANCE_GENERATED_LOOKING,covered?Severity.INFO:Severity.REVIEW,covered?FindingState.COVERED_BY_POLICY:FindingState.ACTIVE,detectors,evidence,rules,List.of(),family(s),covered?"Generated-looking appearance is retained and covered by project policy; stability is not verified":"Generated-looking appearance requires review; it is not proof of variability"));}
        switch(a.effectiveDisposition()){
            case DECLARED_STABLE->out.add(finding(s.subject().declarationRef(),component,Category.POLICY,FindingCode.POLICY_DECLARED_STABLE,Severity.INFO,FindingState.INFORMATIONAL,List.of("EXPLICIT_STABLE"),evidence,rules,List.of(),List.of(),"Project policy declares this component stable; validation remains separate"));
            case DECLARED_UNSTABLE->out.add(finding(s.subject().declarationRef(),component,Category.POLICY,FindingCode.POLICY_DECLARED_UNSTABLE,Severity.WARNING,FindingState.ACTIVE,List.of("EXPLICIT_UNSTABLE"),evidence,rules,List.of(),List.of(),"Project policy declares this component unstable"));
            case POLICY_POLICY_CONFLICT->out.add(finding(s.subject().declarationRef(),component,Category.POLICY,FindingCode.POLICY_POLICY_CONFLICT,Severity.WARNING,FindingState.CONFLICTED,List.of("EQUAL_PRECEDENCE_OPPOSITE_DECISIONS"),evidence,rules,List.of(),List.of(),"Equal-precedence policies disagree"));
            case POLICY_EVIDENCE_CONFLICT->out.add(finding(s.subject().declarationRef(),component,Category.POLICY,FindingCode.POLICY_EVIDENCE_CONFLICT,Severity.WARNING,FindingState.CONFLICTED,List.of("STABLE_POLICY_CHANGED_EVIDENCE"),evidence,rules,List.of(),List.of(),"Declared stability conflicts with comparable changed evidence"));
            case OBSERVED_VARIABLE->out.add(finding(s.subject().declarationRef(),component,Category.EVIDENCE,FindingCode.EVIDENCE_OBSERVED_VARIABLE,Severity.WARNING,FindingState.ACTIVE,List.of("COMPARABLE_CHANGED_VALUE"),evidence,rules,List.of(),List.of(),"Comparable history observed a changed value"));default->{}
        }
        if(history.stream().anyMatch(h->h.domainSummaries().stream().anyMatch(d->d.comparability()==Comparability.State.UNKNOWN)))out.add(finding(s.subject().declarationRef(),component,Category.EVIDENCE,FindingCode.EVIDENCE_COMPARABILITY_UNKNOWN,Severity.REVIEW,FindingState.INCOMPLETE,List.of("COMPARABILITY_UNKNOWN"),evidence,List.of(),List.of(),List.of(),"History exists but comparability cannot be established"));
        if(!history.isEmpty()&&history.stream().allMatch(h->h.valueDigests().isEmpty()))out.add(finding(s.subject().declarationRef(),component,Category.EVIDENCE,FindingCode.EVIDENCE_RUNTIME_VALUE_REDACTED,Severity.INFO,FindingState.INCOMPLETE,List.of("VALUE_UNAVAILABLE_OR_REDACTED"),evidence,List.of(),List.of(),List.of(),"Runtime history has no trusted exact value"));
        if(all!=null&&(all.coverage().incomplete()||all.retention().pruned()))out.add(finding(s.subject().declarationRef(),component,Category.EVIDENCE,FindingCode.EVIDENCE_HISTORY_INCOMPLETE,Severity.REVIEW,FindingState.INCOMPLETE,List.of(all.retention().pruned()?"HISTORY_PRUNED":"HISTORY_INCOMPLETE"),evidence,List.of(),List.of(),List.of(),"History coverage is incomplete"));
    }

    private CandidateSummary candidate(CandidateInput input,DeclarationRecord d,List<AuditFinding>findings,List<String>limits){CandidateAnalysis a=input.analysis();List<CandidateAnalysis.Candidate>ordered=a.candidates();CandidateAnalysis.Candidate original=ordered.stream().filter(x->Objects.equals(x.candidateId(),a.originalCandidateId())).findFirst().orElse(null);boolean exact=input.confidence()==SimilaritySubject.Confidence.EXACT&&Objects.equals(input.declarationRef(),d.declarationRef());if(exact&&original!=null)currentFinding(d.declarationRef(),original,findings);else if(original!=null)limits.add("CURRENT_VALIDATION_NOT_DECLARATION_FACT_"+input.confidence());
        if(exact)switch(a.recommendation()){case KEEP_CURRENT->findings.add(finding(d.declarationRef(),null,Category.IMPROVEMENT,FindingCode.CURRENT_LOCATOR_ALREADY_BEST,Severity.INFO,FindingState.INFORMATIONAL,List.of("CANDIDATE_ENGINE_KEEP_CURRENT"),List.of(),List.of(),List.of(a.originalCandidateId()),List.of(),"Candidate engine recommends retaining the current locator"));case CONSIDER_REPLACEMENT->findings.add(finding(d.declarationRef(),null,Category.IMPROVEMENT,FindingCode.ALTERNATIVE_AVAILABLE,Severity.REVIEW,FindingState.ACTIVE,List.of("CANDIDATE_ENGINE_CONSIDER_REPLACEMENT"),List.of(),List.of(),ordered.stream().filter(x->!x.original()).map(CandidateAnalysis.Candidate::candidateId).limit(MAX_CANDIDATES).toList(),List.of(),"Candidate engine found a validated alternative worth considering"));case REVIEW_REQUIRED->findings.add(finding(d.declarationRef(),null,Category.IMPROVEMENT,FindingCode.ALTERNATIVE_REQUIRES_REVIEW,Severity.REVIEW,FindingState.ACTIVE,List.of("CANDIDATE_ENGINE_REVIEW_REQUIRED"),List.of(),List.of(),List.of(),List.of(),"Candidate alternatives require review"));case NO_VALID_CANDIDATE->findings.add(finding(d.declarationRef(),null,Category.IMPROVEMENT,FindingCode.NO_VALID_ALTERNATIVE,Severity.INFO,FindingState.INFORMATIONAL,List.of("CANDIDATE_ENGINE_NO_VALID_CANDIDATE"),List.of(),List.of(),List.of(),List.of(),"Candidate analysis found no valid alternative"));case TARGET_REQUIRED->findings.add(finding(d.declarationRef(),null,Category.VALIDATION,FindingCode.CURRENT_TARGET_REQUIRED,Severity.REVIEW,FindingState.INCOMPLETE,List.of("TARGET_REQUIRED"),List.of(),List.of(),List.of(),List.of(),"A trustworthy live target is required for validation"));}
        List<CandidateDetail>details=ordered.stream().filter(x->!x.original()).limit(MAX_CANDIDATES).map(x->new CandidateDetail(x.candidateId(),x.origins().stream().map(Enum::name).sorted().toList(),x.validation().state().name(),x.validation().matchCount(),x.reasons().stream().map(CandidateAnalysis.Reason::code).distinct().sorted().toList(),x.limitations())).toList();return new CandidateSummary(a.originalCandidateId(),a.recommendation().name(),original==null?null:original.validation().state().name(),ordered.size(),details,ordered.stream().filter(x->!x.original()).count()>MAX_CANDIDATES,input.confidence()==SimilaritySubject.Confidence.EXACT?List.of():List.of("SUPPORTING_ATTACHMENT_ONLY_"+input.confidence()));}
    private void currentFinding(String declarationRef,CandidateAnalysis.Candidate c,List<AuditFinding>out){FindingCode code;Severity severity;FindingState state;switch(c.validation().state()){case VERIFIED_IN_SCOPE->{code=FindingCode.CURRENT_VERIFIED_IN_SCOPE;severity=Severity.INFO;state=FindingState.INFORMATIONAL;}case VALID_BUT_AMBIGUOUS->{code=FindingCode.CURRENT_VALID_BUT_AMBIGUOUS;severity=Severity.REVIEW;state=FindingState.ACTIVE;}case WRONG_TARGET->{code=FindingCode.CURRENT_WRONG_TARGET;severity=Severity.ERROR;state=FindingState.ACTIVE;}case NO_MATCH->{code=FindingCode.CURRENT_NO_MATCH;severity=Severity.ERROR;state=FindingState.ACTIVE;}case INVALID_SELECTOR->{code=FindingCode.CURRENT_INVALID_SELECTOR;severity=Severity.ERROR;state=FindingState.ACTIVE;}case STALE_TARGET->{code=FindingCode.CURRENT_STALE_TARGET;severity=Severity.REVIEW;state=FindingState.INCOMPLETE;}case NOT_LIVE_VALIDATED->{code=FindingCode.CURRENT_NOT_LIVE_VALIDATED;severity=Severity.INFO;state=FindingState.INCOMPLETE;}default->{return;}}out.add(finding(declarationRef,null,Category.VALIDATION,code,severity,state,List.of(c.validation().state().name()),List.of(),List.of(),List.of(c.candidateId()),List.of(),"Current locator validation state: "+c.validation().state()));}

    private HistoryAttachment attachHistory(History history,List<DeclarationRecord>declarations,Map<String,DeclarationRecord>byRef,List<ProjectIssue>issues){Map<String,List<Subject>>attached=new HashMap<>();List<Subject>runtime=new ArrayList<>();List<Subject>all=history==null?List.of():history.subjects();if(history==null)return new HistoryAttachment(attached,runtime,all);for(Subject h:history.subjects()){if(h.declarationRef()!=null){if(byRef.containsKey(h.declarationRef()))attached.computeIfAbsent(h.declarationRef(),x->new ArrayList<>()).add(h);else{runtime.add(h);issues.add(issue(ProjectIssueCode.ORPHANED_HISTORY_SUBJECT,Severity.INFO,List.of("DECLARATION_REF_NOT_CURRENT"),List.of(h.historySubjectId(),h.declarationRef()),"History references a declaration absent from the current index"));}continue;}if(h.correlation().confidence()==SimilaritySubject.Confidence.STRONG&&!h.usageSummary().samples().isEmpty()){SimilaritySubject.UsageReference usage=h.usageSummary().samples().get(0);List<DeclarationRecord>matches=declarations.stream().filter(d->usage.logicalPath()!=null&&pathMatches(d.logicalPath(),usage.logicalPath())&&usage.line()!=null&&usage.line()>=d.sourceRange().startLine()&&usage.line()<=d.sourceRange().endLine()).toList();if(matches.size()==1){attached.computeIfAbsent(matches.get(0).declarationRef(),x->new ArrayList<>()).add(h);continue;}}runtime.add(h);}return new HistoryAttachment(attached,runtime,all);}
    private CandidateAttachment attachCandidates(List<CandidateInput>inputs,Map<String,DeclarationRecord>byRef,List<ProjectIssue>issues){
        Map<String,CandidateInput>attached=new HashMap<>();int rejected=0,exact=0,strong=0,ambiguous=0;
        for(CandidateInput input:inputs){
            if(input==null||input.analysis()==null||input.analysis().schemaVersion()!=CandidateAnalysis.SCHEMA_VERSION||input.confidence()==null){rejected++;issues.add(issue(ProjectIssueCode.CANDIDATE_INPUT_REJECTED,Severity.REVIEW,List.of("INVALID_CANDIDATE_INPUT"),List.of(),"Candidate analysis input is malformed or incompatible"));continue;}
            String ref=input.declarationRef()!=null?input.declarationRef():input.analysis().declarationRef();
            boolean directExact=input.confidence()!=SimilaritySubject.Confidence.EXACT||(input.analysis().declarationRef()!=null&&input.analysis().declarationRef().equals(ref));
            if(ref==null||!byRef.containsKey(ref)||!directExact||input.confidence()==SimilaritySubject.Confidence.AMBIGUOUS||input.confidence()==SimilaritySubject.Confidence.UNKNOWN){rejected++;if(input.confidence()==SimilaritySubject.Confidence.AMBIGUOUS)ambiguous++;issues.add(issue(ProjectIssueCode.CANDIDATE_INPUT_REJECTED,Severity.REVIEW,List.of(!directExact?"EXACT_REQUIRES_DIRECT_DECLARATION_REF":"CANDIDATE_ATTACHMENT_"+input.confidence()),ref==null?List.of():List.of(ref),"Candidate analysis could not be attached unambiguously"));continue;}
            CandidateInput normalized=new CandidateInput(input.analysis(),input.confidence(),ref);CandidateInput previous=attached.putIfAbsent(ref,normalized);
            if(previous!=null){rejected++;issues.add(issue(ProjectIssueCode.CANDIDATE_INPUT_REJECTED,Severity.REVIEW,List.of("DUPLICATE_CANDIDATE_ANALYSIS"),List.of(ref),"Only one candidate analysis per declaration is accepted in V1"));continue;}
            if(input.confidence()==SimilaritySubject.Confidence.EXACT)exact++;else strong++;
        }
        return new CandidateAttachment(attached,inputs.size(),rejected,exact,strong,ambiguous);
    }

    private static ObservationEvidence evidence(List<Subject>subjects){List<ObservationEvidence.Comparison>comparisons=new ArrayList<>();for(Subject h:subjects)for(DomainSummary d:h.domainSummaries())comparisons.add(new ObservationEvidence.Comparison(h.historySubjectId()+":"+d.domain(),d.domain(),d.comparability()==Comparability.State.COMPARABLE,d.changed()&&d.comparability()==Comparability.State.COMPARABLE));return ObservationEvidence.of(comparisons);}
    private RuntimeOnlyAudit runtimeOnly(Subject h){List<AuditFinding>findings=new ArrayList<>();if(h.correlation().confidence()==SimilaritySubject.Confidence.AMBIGUOUS)findings.add(finding(h.historySubjectId(),h.componentRef(),Category.EVIDENCE,FindingCode.EVIDENCE_AMBIGUOUS_CORRELATION,Severity.REVIEW,FindingState.INCOMPLETE,List.of("AMBIGUOUS_CORRELATION"),List.of(),List.of(),List.of(),List.of(),"Runtime/history subject cannot be attached to one declaration"));if(h.valueDigests().isEmpty())findings.add(finding(h.historySubjectId(),h.componentRef(),Category.EVIDENCE,FindingCode.EVIDENCE_RUNTIME_VALUE_REDACTED,Severity.INFO,FindingState.INCOMPLETE,List.of("VALUE_UNAVAILABLE_OR_REDACTED"),List.of(),List.of(),List.of(),List.of(),"Runtime value is unavailable for exact conclusions"));return new RuntimeOnlyAudit(h.historySubjectId(),h.correlation().confidence(),h.correlation().supportingSignals(),h.correlation().conflictingSignals(),findings,summaryEvidence(List.of(h),null),usage(List.of(h)),List.of("NOT_ATTACHED_TO_CURRENT_DECLARATION"));}
    private Map<String,FamilyWork>buildFamilies(List<SimilaritySubject>staticSubjects,List<Subject>history,Map<String,FederatedPatternPreview.Result>previews){Map<String,FamilyWork>out=new TreeMap<>();for(SimilaritySubject s:staticSubjects)if(s.structuralFamily()!=null)out.computeIfAbsent(s.structuralFamily().fingerprint(),FamilyWork::new).add(s,previews.get(s.subjectRef()));for(Subject h:history)for(Family f:h.structuralFamilies())out.computeIfAbsent(f.fingerprint(),FamilyWork::new).add(h);return out;}

    private static AuditFinding finding(String subject,String component,Category category,FindingCode code,Severity severity,FindingState state,List<String>reasons,List<String>evidence,List<String>rules,List<String>candidates,List<String>families,String explanation){List<String>causes=Stream.of(rules,evidence,candidates,families,reasons).flatMap(Collection::stream).filter(Objects::nonNull).distinct().sorted().toList();String cause=CanonicalDigests.digest("selector-audit-finding-cause-v1",causes.toArray(String[]::new));String id="selector-audit-finding-v1:sha256:"+CanonicalDigests.digest("selector-audit-finding-v1",Integer.toString(SelectorAuditModel.SCHEMA_VERSION),Integer.toString(ALGORITHM_VERSION),subject==null?"":subject,component==null?"NONE":component,category.name(),code.name(),cause);return new AuditFinding(id,category,code,severity,state,component,distinct(reasons),distinct(evidence),distinct(rules),distinct(candidates),distinct(families),explanation);}
    static ProjectIssue issue(ProjectIssueCode code,Severity severity,List<String>reasons,List<String>refs,String explanation){String stable=Stream.concat(reasons.stream(),refs.stream()).sorted().findFirst().orElse("NONE");String id="selector-audit-issue-v1:sha256:"+CanonicalDigests.digest("selector-audit-issue-v1",code.name(),stable);return new ProjectIssue(id,code,severity,distinct(reasons),distinct(refs),explanation);}
    private static List<String>distinct(List<String>v){return v.stream().filter(Objects::nonNull).distinct().sorted().toList();}
    private static List<String>family(SimilaritySubject s){return s.structuralFamily()==null?List.of():List.of(s.structuralFamily().fingerprint());}
    private static boolean pathMatches(String a,String b){String x=a.replace('\\','/'),y=b.replace('\\','/');return x.equals(y)||x.endsWith('/'+y);}

    private static List<AuditFinding>boundFindings(List<AuditFinding>findings,List<String>limits){List<AuditFinding>unique=findings.stream().collect(java.util.stream.Collectors.toMap(AuditFinding::findingId,x->x,(a,b)->a,LinkedHashMap::new)).values().stream().sorted(findingOrder()).toList();if(unique.size()<=MAX_FINDINGS)return unique;List<AuditFinding>essential=unique.stream().filter(x->x.severity()==Severity.ERROR||x.severity()==Severity.WARNING).toList();if(essential.size()>MAX_FINDINGS){limits.add("ESSENTIAL_FINDINGS_EXCEED_DISPLAY_BOUND");return essential;}limits.add("FINDINGS_TRUNCATED");return Stream.concat(essential.stream(),unique.stream().filter(x->x.severity()!=Severity.ERROR&&x.severity()!=Severity.WARNING).limit(MAX_FINDINGS-essential.size())).distinct().sorted(findingOrder()).toList();}
    private static Comparator<AuditFinding>findingOrder(){return Comparator.comparingInt((AuditFinding f)->f.severity().ordinal()).reversed().thenComparing(f->f.category().ordinal()).thenComparing(f->f.code().name()).thenComparing(f->f.componentRef()==null?"":f.componentRef()).thenComparing(AuditFinding::findingId);}
    private static Comparator<DeclarationRecord>declarationOrder(){return Comparator.comparing(DeclarationRecord::logicalPath).thenComparingInt(d->d.sourceRange().startOffset()).thenComparing(DeclarationRecord::declarationRef);}
    private static Comparator<DeclarationAudit>auditOrder(){return Comparator.comparingInt(SelectorAuditOrchestrator::attention).reversed().thenComparing(d->d.source().logicalPath()).thenComparingInt(d->d.source().startOffset()).thenComparing(DeclarationAudit::declarationRef);}
    private static int attention(DeclarationAudit d){return d.findings().stream().mapToInt(f->f.severity().ordinal()*10+switch(f.state()){case ACTIVE,CONFLICTED->3;case INCOMPLETE->2;default->0;}).max().orElse(0);}
    private static Recommendation recommend(List<AuditFinding>f,CandidateSummary c,SimilaritySubject.Confidence confidence){boolean failure=has(f,FindingCode.CURRENT_INVALID_SELECTOR,FindingCode.CURRENT_WRONG_TARGET,FindingCode.CURRENT_NO_MATCH);if(failure)return c!=null&&"CONSIDER_REPLACEMENT".equals(c.recommendation())?Recommendation.CONSIDER_REPLACEMENT:Recommendation.MANUAL_REVIEW;if(has(f,FindingCode.POLICY_POLICY_CONFLICT))return Recommendation.REVIEW_POLICY;if(has(f,FindingCode.POLICY_EVIDENCE_CONFLICT,FindingCode.EVIDENCE_OBSERVED_VARIABLE,FindingCode.POLICY_DECLARED_UNSTABLE))return c!=null&&confidence==SimilaritySubject.Confidence.EXACT&&"CONSIDER_REPLACEMENT".equals(c.recommendation())?Recommendation.CONSIDER_REPLACEMENT:Recommendation.REVIEW;if(c!=null&&confidence==SimilaritySubject.Confidence.EXACT)return switch(c.recommendation()){case"KEEP_CURRENT"->Recommendation.KEEP_CURRENT;case"CONSIDER_REPLACEMENT"->Recommendation.CONSIDER_REPLACEMENT;case"REVIEW_REQUIRED"->Recommendation.REVIEW;case"TARGET_REQUIRED"->Recommendation.LIVE_VALIDATE;default->Recommendation.NONE;};if(has(f,FindingCode.SOURCE_PARTIALLY_RESOLVED_DECLARATION,FindingCode.SOURCE_UNRESOLVED_DECLARATION,FindingCode.SOURCE_UNSUPPORTED_DECLARATION,FindingCode.SOURCE_RESOLUTION_ERROR))return Recommendation.MANUAL_REVIEW;if(has(f,FindingCode.APPEARANCE_GENERATED_LOOKING))return Recommendation.REVIEW_POLICY;return Recommendation.NONE;}
    private static List<Recommendation>supporting(List<AuditFinding>f,Recommendation primary){List<Recommendation>x=new ArrayList<>();if(has(f,FindingCode.EVIDENCE_NOT_AVAILABLE,FindingCode.EVIDENCE_HISTORY_INCOMPLETE,FindingCode.EVIDENCE_COMPARABILITY_UNKNOWN))x.add(Recommendation.COLLECT_MORE_EVIDENCE);if(has(f,FindingCode.CURRENT_NOT_LIVE_VALIDATED,FindingCode.CURRENT_TARGET_REQUIRED))x.add(Recommendation.LIVE_VALIDATE);if(has(f,FindingCode.APPEARANCE_GENERATED_LOOKING)&&primary!=Recommendation.REVIEW_POLICY)x.add(Recommendation.REVIEW_POLICY);return x.stream().filter(r->r!=primary).distinct().toList();}
    private static boolean has(List<AuditFinding>f,FindingCode...codes){Set<FindingCode>s=Set.of(codes);return f.stream().anyMatch(x->s.contains(x.code()));}

    private static PolicySummary policy(List<StabilityAssessment>a){List<String>matched=a.stream().flatMap(x->x.policyEvaluation().matchedRuleIds().stream()).distinct().sorted().toList();List<String>selected=a.stream().map(x->x.policyEvaluation().selectedRuleId()).filter(Objects::nonNull).distinct().sorted().toList();List<String>decisions=a.stream().map(x->x.policyEvaluation().selectedDecision()).filter(Objects::nonNull).map(Enum::name).distinct().sorted().toList();return new PolicySummary(matched,selected,decisions,(int)a.stream().filter(x->x.policyEvaluation().conflict()||x.effectiveDisposition()==StabilityAssessment.EffectiveDisposition.POLICY_EVIDENCE_CONFLICT).count());}
    private static EvidenceSummary summaryEvidence(List<Subject>history,History all){int comparable=0,changed=0,digests=0;Set<String>domains=new TreeSet<>();List<String>limits=new ArrayList<>();for(Subject h:history){digests+=h.valueDigests().size();for(DomainSummary d:h.domainSummaries()){domains.add(d.domain().name());if(d.comparability()==Comparability.State.COMPARABLE)comparable++;if(d.changed()&&d.comparability()==Comparability.State.COMPARABLE)changed++;if(d.comparability()==Comparability.State.UNKNOWN)limits.add("COMPARABILITY_UNKNOWN");}}boolean incomplete=all!=null&&(all.coverage().incomplete()||all.retention().pruned());if(incomplete)limits.add("HISTORY_INCOMPLETE");String state=changed>0?"CHANGED":comparable>0?"UNCHANGED_IN_SCOPE":history.isEmpty()?"NOT_AVAILABLE":"INSUFFICIENT";return new EvidenceSummary(state,comparable,changed,digests,incomplete,List.copyOf(domains),distinct(limits));}
    private static SelectorAuditModel.UsageSummary usage(List<Subject>history){Map<String,UsageSample>u=new TreeMap<>();int total=0;for(Subject h:history){total+=h.usageSummary().count();for(SimilaritySubject.UsageReference x:h.usageSummary().samples()){String cls=x.usageClass()==null?null:CanonicalDigests.digest("selector-audit-usage-class-v1",x.usageClass());String method=x.usageMethod()==null?null:CanonicalDigests.digest("selector-audit-usage-method-v1",x.usageMethod());u.putIfAbsent(x.usageRef(),new UsageSample(x.usageRef(),x.logicalPath(),cls,method,x.line()));}}return new SelectorAuditModel.UsageSummary(total,u.values().stream().limit(MAX_SAMPLES).toList(),u.size()>MAX_SAMPLES);}
    private static CorrelationSummary correlation(List<Subject>history,CandidateInput candidate){int e=0,s=0,a=0,u=0;for(Subject h:history)switch(h.correlation().confidence()){case EXACT->e++;case STRONG->s++;case AMBIGUOUS->a++;case UNKNOWN->u++;}if(candidate!=null)switch(candidate.confidence()){case EXACT->e++;case STRONG->s++;case AMBIGUOUS->a++;case UNKNOWN->u++;}SimilaritySubject.Confidence strongest=e>0?SimilaritySubject.Confidence.EXACT:s>0?SimilaritySubject.Confidence.STRONG:a>0?SimilaritySubject.Confidence.AMBIGUOUS:SimilaritySubject.Confidence.UNKNOWN;List<String>limits=new ArrayList<>();if(s>0)limits.add("STRONG_IS_NOT_DIRECT_IDENTITY");if(a>0)limits.add("AMBIGUOUS_NOT_HARD_EVIDENCE");return new CorrelationSummary(strongest,e,s,a,u,limits);}

    private static SelectorAuditModel.Coverage coverage(Request r,HistoryAttachment h,CandidateAttachment c,List<ProjectIssue>issues,List<DeclarationAudit>d,List<RuntimeOnlyAudit>runtime,List<FamilyAudit>families){SelectorIndexModel.Coverage s=r.index().coverage();boolean staticPartial=s.filesFailed()>0||s.unsupportedLanguageFiles()>0||s.incompleteClasspath()||s.errors()>0;DimensionCoverage sc=new DimensionCoverage(staticPartial?DimensionStatus.PARTIAL:DimensionStatus.COMPLETE,List.of(new Count("sourceRootsRequested",s.sourceRootsRequested()),new Count("sourceRootsFound",s.sourceRootsFound()),new Count("filesDiscovered",s.filesDiscovered()),new Count("filesParsed",s.filesParsed()),new Count("filesFailed",s.filesFailed()),new Count("filesExcluded",s.filesExcluded()),new Count("generatedFilesExcluded",s.generatedFilesExcluded()),new Count("unsupportedLanguageFiles",s.unsupportedLanguageFiles()),new Count("declarationsFound",s.declarationsFound()),new Count("resolved",s.resolved()),new Count("partiallyResolved",s.partiallyResolved()),new Count("dynamic",s.dynamic()),new Count("custom",s.custom()),new Count("unsupported",s.unsupported()),new Count("errors",s.errors()),new Count("symbolResolutionIssues",s.symbolResolutionIssues())),s.incompleteClasspath()?List.of("INCOMPLETE_CLASSPATH"):List.of());
        History history=r.history();DimensionCoverage rc=history==null?new DimensionCoverage(DimensionStatus.NOT_PROVIDED,List.of(),List.of()):new DimensionCoverage(history.coverage().incomplete()?DimensionStatus.PARTIAL:DimensionStatus.COMPLETE,List.of(new Count("reportsImported",history.coverage().reportsImported()),new Count("reportsSkipped",history.coverage().reportsSkipped()),new Count("observationsAccepted",history.coverage().observationsAccepted()),new Count("redactedObservations",history.coverage().redactedObservations()),new Count("ambiguousCorrelations",history.coverage().ambiguousCorrelations()),new Count("summaryOnlyRuns",history.coverage().summaryOnlyRuns())),history.coverage().issues());DimensionCoverage hc=history==null?new DimensionCoverage(DimensionStatus.NOT_PROVIDED,List.of(),List.of()):new DimensionCoverage(history.coverage().incomplete()||history.retention().pruned()?DimensionStatus.PARTIAL:DimensionStatus.COMPLETE,List.of(new Count("runs",history.runs().size()),new Count("subjects",history.subjects().size()),new Count("buckets",history.retention().bucketsRetained()),new Count("chronologyUnknown",history.retention().chronologyIncomplete()?1:0),new Count("pruned",history.retention().pruned()?1:0)),Stream.concat(history.coverage().issues().stream(),history.retention().issues().stream()).distinct().sorted().toList());
        long conflicts=d.stream().flatMap(x->x.findings().stream()).filter(x->x.state()==FindingState.CONFLICTED).count();DimensionCoverage pc=r.policies().rules().isEmpty()?new DimensionCoverage(DimensionStatus.NOT_PROVIDED,List.of(),List.of()):new DimensionCoverage(DimensionStatus.COMPLETE,List.of(new Count("rulesLoaded",r.policies().rules().size()),new Count("rulesRejected",0),new Count("matches",d.stream().mapToLong(x->x.policySummary().matchedRuleIds().size()).sum()),new Count("conflicts",conflicts),new Count("orphanedDeclarationRules",issues.stream().filter(x->x.code()==ProjectIssueCode.ORPHANED_POLICY_RULE).count())),List.of());DimensionCoverage cc=r.candidates().isEmpty()?new DimensionCoverage(DimensionStatus.NOT_PROVIDED,List.of(),List.of()):new DimensionCoverage(c.rejected>0?DimensionStatus.PARTIAL:DimensionStatus.COMPLETE,List.of(new Count("analysesSupplied",c.supplied),new Count("accepted",c.attached.size()),new Count("rejected",c.rejected),new Count("exactAttachments",c.exact),new Count("strongAttachments",c.strong),new Count("ambiguous",c.ambiguous),new Count("liveValidatedDeclarations",d.stream().filter(x->x.candidateSummary()!=null&&x.candidateSummary().originalValidationState()!=null&&!x.candidateSummary().originalValidationState().equals("NOT_LIVE_VALIDATED")).count()),new Count("notLiveValidated",d.stream().filter(x->x.candidateSummary()!=null&&"NOT_LIVE_VALIDATED".equals(x.candidateSummary().originalValidationState())).count())),List.of());long candidateOmitted=d.stream().filter(x->x.candidateSummary()!=null&&x.candidateSummary().candidatesTruncated()).count(),membersOmitted=families.stream().filter(FamilyAudit::membersTruncated).count(),samplesOmitted=d.stream().filter(x->x.usageSummary().truncated()).count();DimensionCoverage oc=new DimensionCoverage(candidateOmitted+membersOmitted+samplesOmitted>0?DimensionStatus.PARTIAL:DimensionStatus.COMPLETE,List.of(new Count("candidateDetailsOmitted",candidateOmitted),new Count("familyMemberListsTruncated",membersOmitted),new Count("usageSamplesTruncated",samplesOmitted),new Count("runtimeOnlyEntries",runtime.size())),List.of());return new SelectorAuditModel.Coverage(sc,rc,hc,pc,cc,oc);}
    private static CompletenessStatus overall(SelectorAuditModel.Coverage c,List<ProjectIssue>issues){if(c.staticCoverage().status()==DimensionStatus.PARTIAL||issues.stream().anyMatch(x->x.code()==ProjectIssueCode.STALE_SELECTOR_INDEX||x.code()==ProjectIssueCode.PROJECT_FINGERPRINT_MISMATCH))return CompletenessStatus.LIMITED;if(Stream.of(c.runtimeCoverage(),c.historyCoverage(),c.policyCoverage(),c.candidateCoverage(),c.outputCoverage()).anyMatch(x->x.status()==DimensionStatus.PARTIAL)||issues.stream().anyMatch(x->x.code()==ProjectIssueCode.MALFORMED_OPTIONAL_HISTORY||x.code()==ProjectIssueCode.MALFORMED_OPTIONAL_POLICY||x.code()==ProjectIssueCode.CANDIDATE_INPUT_REJECTED||x.code()==ProjectIssueCode.UNSUPPORTED_INPUT_VERSION||x.code()==ProjectIssueCode.SUMMARY_ONLY_HISTORY||x.code()==ProjectIssueCode.HISTORY_PRUNED||x.code()==ProjectIssueCode.OUTPUT_TRUNCATED))return CompletenessStatus.PARTIAL;return CompletenessStatus.COMPLETE_FOR_REQUESTED_INPUTS;}
    private static Summary summary(List<DeclarationAudit>d,List<RuntimeOnlyAudit>runtime,List<FamilyAudit>families,List<ProjectIssue>issues){List<AuditFinding>f=d.stream().flatMap(x->x.findings().stream()).toList();return new Summary(d.size(),runtime.size(),(int)f.stream().filter(x->x.severity()==Severity.REVIEW&&x.state()!=FindingState.INFORMATIONAL&&x.state()!=FindingState.COVERED_BY_POLICY).count(),(int)f.stream().filter(x->x.severity()==Severity.WARNING).count(),(int)f.stream().filter(x->x.severity()==Severity.ERROR).count(),(int)f.stream().filter(x->x.state()==FindingState.CONFLICTED).count(),(int)f.stream().filter(x->x.code()==FindingCode.EVIDENCE_OBSERVED_VARIABLE).count(),(int)f.stream().filter(x->x.code()==FindingCode.APPEARANCE_GENERATED_LOOKING).count(),(int)f.stream().filter(x->x.code()==FindingCode.APPEARANCE_GENERATED_LOOKING&&x.state()==FindingState.COVERED_BY_POLICY).count(),(int)d.stream().filter(x->x.candidateSummary()!=null&&x.candidateSummary().originalValidationState()!=null&&!x.candidateSummary().originalValidationState().equals("NOT_LIVE_VALIDATED")).count(),(int)f.stream().filter(x->x.code()==FindingCode.ALTERNATIVE_AVAILABLE).count(),(int)f.stream().filter(x->x.state()==FindingState.UNSUPPORTED||x.code()==FindingCode.SOURCE_UNRESOLVED_DECLARATION).count(),(int)f.stream().filter(x->x.code()==FindingCode.EVIDENCE_HISTORY_INCOMPLETE).count(),(int)issues.stream().filter(x->x.code()==ProjectIssueCode.ORPHANED_POLICY_RULE).count(),families.size());}

    private static void validateIndex(SelectorIndex index){if(index.files().stream().flatMap(f->f.declarations().stream()).anyMatch(d->d.schemaVersion()!=SelectorIndexModel.SCHEMA_VERSION))throw new AuditInputException("Unsupported declaration schemaVersion");}
    private static void coverageIssues(SelectorIndex index,List<ProjectIssue>issues){SelectorIndexModel.Coverage c=index.coverage();if(c.filesFailed()>0||c.sourceRootsFound()<c.sourceRootsRequested())issues.add(issue(ProjectIssueCode.STATIC_COVERAGE_INCOMPLETE,Severity.REVIEW,List.of("STATIC_FILES_OR_ROOTS_INCOMPLETE"),List.of(),"Static source coverage is incomplete"));if(c.unsupportedLanguageFiles()>0)issues.add(issue(ProjectIssueCode.UNSUPPORTED_SOURCE_LANGUAGE,Severity.REVIEW,List.of("JAVA_ONLY_V1"),List.of(),"Requested roots contain unsupported source languages"));if(c.incompleteClasspath())issues.add(issue(ProjectIssueCode.INCOMPLETE_CLASSPATH,Severity.REVIEW,List.of("SYMBOL_RESOLUTION_INCOMPLETE"),List.of(),"Static classpath coverage is incomplete"));}
    private static SourceFreshnessState freshness(Request request,List<ProjectIssue>issues){Map<String,SourceFreshness>map=new HashMap<>();for(SourceFileIndex f:request.index().files()){SourceFreshness state;if(request.currentContentHashes().isEmpty())state=SourceFreshness.UNKNOWN;else{String current=request.currentContentHashes().get(f.logicalPath());state=current==null?SourceFreshness.UNKNOWN:Objects.equals(current,f.contentHash())?SourceFreshness.CURRENT:SourceFreshness.STALE_INDEX;}map.put(f.logicalPath(),state);if(state==SourceFreshness.STALE_INDEX)issues.add(issue(ProjectIssueCode.STALE_SELECTOR_INDEX,Severity.WARNING,List.of("CONTENT_HASH_MISMATCH"),List.of(f.logicalPath()),"Current source content does not match the selector index"));}return new SourceFreshnessState(map);}
    private static void orphanedPolicies(CompiledPolicySet policies,Map<String,DeclarationRecord>current,List<ProjectIssue>issues){for(SelectorPolicy.Rule rule:policies.rules())if(rule.scope().declarationRef()!=null&&!current.containsKey(rule.scope().declarationRef()))issues.add(issue(ProjectIssueCode.ORPHANED_POLICY_RULE,rule.decision()==SelectorPolicy.Decision.UNSTABLE?Severity.REVIEW:Severity.INFO,List.of("DECLARATION_SCOPE_NOT_CURRENT"),List.of(rule.ruleId(),rule.scope().declarationRef()),"Declaration-scoped policy references no current declaration"));}

    private static final class FamilyWork{final String fingerprint;final Map<String,SimilaritySubject>members=new TreeMap<>();final Set<String>runtime=new TreeSet<>(),modules=new TreeSet<>(),paths=new TreeSet<>();final Set<AppearanceSignal.Family>appearance=new TreeSet<>();final Set<String>policyCovered=new TreeSet<>();int evidenceConflicts;FederatedPatternPreview.Result preview;FamilyWork(String f){fingerprint=f;}void add(SimilaritySubject s,FederatedPatternPreview.Result p){members.put(s.subjectRef(),s);if(s.subject().modulePath()!=null)modules.add(s.subject().modulePath());if(s.subject().logicalPath()!=null)paths.add(s.subject().logicalPath());s.appearanceSignals().forEach(x->appearance.add(x.family()));if(p!=null)preview=p;}void add(Subject s){runtime.add(s.historySubjectId());s.appearanceFamilies().stream().map(AppearanceSignal.Family::valueOf).forEach(appearance::add);evidenceConflicts+=(int)s.samples().stream().filter(Sample::conflictExemplar).count();}FamilyAudit freeze(){List<String>refs=Stream.concat(members.values().stream().map(x->x.subject().declarationRef()).filter(Objects::nonNull),runtime.stream()).distinct().sorted().limit(MAX_FAMILY_MEMBERS).toList();int total=members.size()+runtime.size();PatternSummary p=preview==null?null:new PatternSummary(preview.proposal().pattern()==null?List.of():preview.proposal().pattern().segments().stream().map(x->x.kind().name()).toList(),preview.matchedStaticSubjects().size(),preview.matchedHistorySubjects().size(),preview.excludedNearMatches().size(),preview.policyConflicts().size()+preview.evidenceConflicts().size(),preview.affectedDeclarationRefs());return new FamilyAudit(fingerprint,"SAME_STRUCTURAL_FAMILY",(int)members.values().stream().map(x->x.subject().declarationRef()).filter(Objects::nonNull).distinct().count(),runtime.size(),modules.stream().limit(16).toList(),paths.stream().limit(32).toList(),List.copyOf(appearance),policyCovered.size(),evidenceConflicts,p,refs,total,total>MAX_FAMILY_MEMBERS);}}
    private record HistoryAttachment(Map<String,List<Subject>>attached,List<Subject>runtimeOnly,List<Subject>allSubjects){}
    private record CandidateAttachment(Map<String,CandidateInput>attached,int supplied,int rejected,int exact,int strong,int ambiguous){}
    private record SourceFreshnessState(Map<String,SourceFreshness>byPath){}
    static final class AuditInputException extends IllegalArgumentException{AuditInputException(String message){super(message);}}
}
