package io.github.testlens.selector.tooling;

import io.github.testlens.selector.engine.*;

import java.util.ArrayList;
import java.util.List;

import static io.github.testlens.selector.tooling.SelectorHistoryModel.*;
import static io.github.testlens.selector.tooling.SelectorIndexModel.*;

/** Adapts existing source-index and history records into one neutral query catalog. */
final class SimilarityFederation {
    List<SimilaritySubject> staticSubjects(DeclarationRecord declaration){List<SelectorSubject>base=SelectorEngineAdapter.subjects(declaration);List<SimilaritySubject>out=new ArrayList<>();for(int i=0;i<base.size();i++){SelectorSubject subject=base.get(i);ComponentIdentity component=base.size()==1?ComponentIdentity.of("TARGET","primary"):ComponentIdentity.of("COMPOSITE_CHILD","children",Integer.toString(i));SimilaritySubject.Correlation correlation=new SimilaritySubject.Correlation(SimilaritySubject.Confidence.EXACT,List.of("DECLARATION_REF"),List.of(),List.of(),1);out.add(SimilaritySubject.create(subject,component,declaration.locatorExpression().normalizedExpression(),List.of(),List.of(),semanticFamily(subject),null,List.of(),correlation,SimilaritySubject.SourceState.CURRENT));}return List.copyOf(out);}
    List<SimilaritySubject> historySubjects(History history){List<SimilaritySubject>out=new ArrayList<>();for(Subject h:history.subjects()){List<SimilaritySubject.UsageReference>usages=h.usageSummary().samples();String path=usages.isEmpty()?null:usages.get(0).logicalPath();SelectorSubject subject=new SelectorSubject(SelectorSubject.SubjectKind.RUNTIME_OBSERVATION,h.strategy(),SelectorSubject.ValueState.UNAVAILABLE,null,h.declarationRef(),module(path),path,null,null,null,h.contextFingerprint(),SelectorSubject.InputTrust.RUNTIME_REDACTED,h.templateFingerprint());ComponentIdentity component=new ComponentIdentity(h.componentRole(),h.componentPath(),h.componentRef());List<AppearanceSignal>signals=h.appearanceFamilies().stream().map(name->new AppearanceSignal(AppearanceSignal.Family.valueOf(name),AppearanceSignal.Confidence.LOW,"history-family-v1",1,"VALUE",0,0,"sha256:"+CanonicalDigests.digest("selector-history-appearance-v1",name),"PERSISTED_TRUSTED_FAMILY","Persisted trusted appearance family")).toList();StructuralFamily family=h.structuralFamilies().isEmpty()?null:family(h.structuralFamilies().get(0),h.strategy(),h.componentRef());out.add(new SimilaritySubject(subject,h.historySubjectId(),component,h.templateFingerprint(),family,signals,h.valueDigests().size()==1?h.valueDigests().get(0).digest():null,List.of(),List.of(),null,null,usages,h.correlation(),h.sourceState()));}return List.copyOf(out);}
    SimilarityIndex index(List<DeclarationRecord>declarations,History history){List<SimilaritySubject>staticCatalog=new ArrayList<>();declarations.forEach(d->staticCatalog.addAll(staticSubjects(d)));List<SimilaritySubject>all=new ArrayList<>(staticCatalog);if(history!=null)for(SimilaritySubject subject:historySubjects(history))all.add(correlate(subject,declarations,staticCatalog));boolean complete=history==null||(!history.coverage().incomplete()&&!history.retention().pruned());List<String>limitations=complete?List.of():List.of("HISTORY_INCOMPLETE_OR_PRUNED");return new SimilarityIndex(all,complete,limitations);}
    private static SimilaritySubject correlate(SimilaritySubject history,List<DeclarationRecord>declarations,List<SimilaritySubject>staticCatalog){
        if(history.subject().declarationRef()!=null)return history;
        SimilaritySubject.UsageReference usage=history.usages().isEmpty()?null:history.usages().get(0);if(usage==null||usage.logicalPath()==null||usage.line()==null)return withCorrelation(history,new SimilaritySubject.Correlation(SimilaritySubject.Confidence.UNKNOWN,List.of(),List.of(),List.of("USAGE_SOURCE_INSUFFICIENT"),1));
        List<DeclarationRecord>matches=declarations.stream().filter(d->pathMatches(d.logicalPath(),usage.logicalPath())&&contains(d.sourceRange(),usage.line())).toList();
        if(matches.size()!=1)return withCorrelation(history,new SimilaritySubject.Correlation(matches.isEmpty()?SimilaritySubject.Confidence.UNKNOWN:SimilaritySubject.Confidence.AMBIGUOUS,List.of("USAGE_SOURCE_RANGE"),matches.size()>1?List.of("MULTIPLE_DECLARATION_CANDIDATES"):List.of(),matches.isEmpty()?List.of("DECLARATION_NOT_FOUND"):List.of(),1));
        List<SimilaritySubject>resolved=staticCatalog.stream().filter(s->matches.get(0).declarationRef().equals(s.subject().declarationRef())).toList();if(resolved.size()!=1)return withCorrelation(history,new SimilaritySubject.Correlation(SimilaritySubject.Confidence.AMBIGUOUS,List.of("USAGE_SOURCE_RANGE"),List.of("COMPOSITE_DECLARATION_COMPONENT_AMBIGUITY"),List.of(),1));
        SimilaritySubject declaration=resolved.get(0);SelectorSubject original=history.subject();SelectorSubject correlated=new SelectorSubject(original.kind(),original.strategy(),original.valueState(),original.canonicalValue(),null,declaration.subject().modulePath(),declaration.subject().logicalPath(),declaration.subject().declaringSymbol(),original.usageClass(),original.usageMethod(),original.contextFingerprint(),original.inputTrust(),original.templateInformation());
        return new SimilaritySubject(correlated,history.subjectRef(),history.component(),declaration.templateFingerprint(),history.structuralFamily(),history.appearanceSignals(),history.exactDigest(),history.explicitPatternRefs(),history.candidateOrigins(),history.semanticAttributeFamily(),history.usageSourceFamily(),history.usages(),new SimilaritySubject.Correlation(SimilaritySubject.Confidence.STRONG,List.of("UNIQUE_USAGE_SOURCE_RANGE","CURRENT_STATIC_TEMPLATE"),List.of(),List.of("DIRECT_DECLARATION_REF_UNAVAILABLE"),1),history.sourceState());
    }
    private static SimilaritySubject withCorrelation(SimilaritySubject subject,SimilaritySubject.Correlation correlation){return new SimilaritySubject(subject.subject(),subject.subjectRef(),subject.component(),subject.templateFingerprint(),subject.structuralFamily(),subject.appearanceSignals(),subject.exactDigest(),subject.explicitPatternRefs(),subject.candidateOrigins(),subject.semanticAttributeFamily(),subject.usageSourceFamily(),subject.usages(),correlation,subject.sourceState());}
    private static boolean pathMatches(String declaration,String usage){String d=declaration.replace('\\','/'),u=usage.replace('\\','/');return d.equals(u)||d.endsWith('/'+u);}
    private static boolean contains(SourceRange range,int line){return line>=range.startLine()&&line<=range.endLine();}
    private static StructuralFamily family(Family f,String strategy,String componentRef){return new StructuralFamily(StructuralFamily.VERSION,strategy,componentRef,f.segments().stream().map(s->new StructuralFamily.Segment(StructuralFamily.Kind.valueOf(s.kind()),s.length(),s.literalDigest())).toList(),f.fingerprint(),f.prefixFingerprint());}
    private static String semanticFamily(SelectorSubject s){return switch(s.strategy()){case"id"->"ID";case"name"->"NAME";case"class name"->"CLASS_TOKEN";case"css selector"->"CSS";case"xpath"->"XPATH";default->s.strategy().toUpperCase(java.util.Locale.ROOT);};}
    private static String module(String path){if(path==null)return null;int slash=path.indexOf('/');return slash<0?null:path.substring(0,slash);}
}
