package io.github.testlens.application.mapper;

import io.github.testlens.application.model.ApplicationIds;
import io.github.testlens.application.model.ApplicationModel;

import java.time.Instant;
import java.util.*;

final class ApplicationAggregator {
    private final String applicationId,applicationName;private final ApplicationMapperOptions options;private final Instant generatedAt;
    private final Map<String,ApplicationModel.PageModel>pages=new TreeMap<>();private final Map<String,ApplicationModel.Transition>transitions=new TreeMap<>();
    private final List<ApplicationModel.Limitation>limitations=new ArrayList<>();private int observations,discovered,analyzed,skipped,selectorAnalyses;private boolean truncated;
    ApplicationAggregator(String applicationId,String applicationName,ApplicationMapperOptions options){this.applicationId=applicationId;this.applicationName=applicationName;this.options=options;this.generatedAt=Instant.now(options.clock());}
    MergeOutcome merge(PageScanResult scan){int before=limitations.size();observations++;discovered+=scan.discoveredNodes();analyzed+=scan.page().elements().size();skipped+=scan.skipped();selectorAnalyses+=scan.selectorAnalyses();truncated|=scan.truncated();limitations.addAll(scan.limitations());
        ApplicationModel.PageModel old=pages.get(scan.page().pageId());if(old==null){if(pages.size()>=options.maxPages()){truncated=true;limitations.add(new ApplicationModel.Limitation("MAX_PAGES","Page was not retained because maxPages was reached"));return outcome(false,false,before);}pages.put(scan.page().pageId(),scan.page());return outcome(true,true,before);}pages.put(old.pageId(),mergePage(old,scan.page()));boolean stateRetained=pages.get(old.pageId()).states().stream().anyMatch(state->scan.page().states().stream().anyMatch(candidate->candidate.stateId().equals(state.stateId())));return outcome(true,stateRetained,before);}
    MergeOutcome transition(ApplicationModel.Transition value){int before=limitations.size();if(transitions.size()>=options.maxTransitions()&&!transitions.containsKey(value.transitionId())){truncated=true;limitations.add(new ApplicationModel.Limitation("MAX_TRANSITIONS","Transition was not retained because maxTransitions was reached"));return outcome(false,false,before);}transitions.put(value.transitionId(),value);return outcome(true,true,before);}
    MergeOutcome limitation(String code,String detail){int before=limitations.size();ApplicationModel.Limitation value=new ApplicationModel.Limitation(code,detail);if(!limitations.contains(value))limitations.add(value);truncated=true;return outcome(false,false,before);}
    ApplicationModel model(){List<ApplicationModel.PageModel>base=new ArrayList<>(pages.values());List<ApplicationModel.SharedComponent>shared=shared(base);Map<String,List<String>>refs=new HashMap<>();for(ApplicationModel.SharedComponent component:shared)for(String page:component.pageIds())refs.computeIfAbsent(page,x->new ArrayList<>()).add(component.componentId());
        List<ApplicationModel.PageModel>withRefs=base.stream().map(p->new ApplicationModel.PageModel(p.pageId(),p.canonicalName(),p.identity(),p.titles(),p.fingerprints(),p.states(),p.regions(),p.elements(),refs.getOrDefault(p.pageId(),List.of()),p.transitions(),p.provenance(),p.limitations())).toList();
        int states=withRefs.stream().mapToInt(p->p.states().size()).sum();ApplicationModel.Completeness completeness=truncated?ApplicationModel.Completeness.PARTIAL:ApplicationModel.Completeness.COMPLETE_FOR_OBSERVED_CONTEXT;
        return new ApplicationModel(ApplicationModel.SCHEMA_VERSION,applicationId,applicationName,"0.5.0",generatedAt,withRefs,shared,new ArrayList<>(transitions.values()),new ApplicationModel.Coverage(completeness,observations,withRefs.size(),states,discovered,analyzed,skipped,selectorAnalyses,transitions.size(),truncated),limitations,new ApplicationModel.Provenance(ApplicationModel.EvidenceSource.OBSERVED,"aggregate","caller-owned",List.of("GUIDED_OBSERVATIONS"),Map.of("mode",options.mode().name())));}
    private ApplicationModel.PageModel mergePage(ApplicationModel.PageModel a,ApplicationModel.PageModel b){Map<String,ApplicationModel.PageState>states=by(a.states(),ApplicationModel.PageState::stateId);if(states.size()<options.maxPageStates())b.states().forEach(x->states.putIfAbsent(x.stateId(),x));else if(b.states().stream().anyMatch(x->!states.containsKey(x.stateId()))){truncated=true;limitations.add(new ApplicationModel.Limitation("MAX_PAGE_STATES","New state omitted for "+a.pageId()));}
        Map<String,ApplicationModel.ElementModel>elements=by(a.elements(),ApplicationModel.ElementModel::elementId);for(ApplicationModel.ElementModel e:b.elements()){ApplicationModel.ElementModel old=elements.get(e.elementId());elements.put(e.elementId(),old==null?e:prefer(old,e));}
        Map<String,ApplicationModel.Region>regions=by(a.regions(),ApplicationModel.Region::regionId);b.regions().forEach(x->regions.putIfAbsent(x.regionId(),x));
        return new ApplicationModel.PageModel(a.pageId(),a.canonicalName(),a.identity(),union(a.titles(),b.titles()),union(a.fingerprints(),b.fingerprints()),new ArrayList<>(states.values()),new ArrayList<>(regions.values()),new ArrayList<>(elements.values()),union(a.sharedComponentRefs(),b.sharedComponentRefs()),unionTransitions(a.transitions(),b.transitions()),a.provenance(),unionLimits(a.limitations(),b.limitations()));}
    private static ApplicationModel.ElementModel prefer(ApplicationModel.ElementModel a,ApplicationModel.ElementModel b){return b;}
    private List<ApplicationModel.SharedComponent>shared(List<ApplicationModel.PageModel>pages){Map<String,List<PageRegion>>groups=new TreeMap<>();for(ApplicationModel.PageModel page:pages)for(ApplicationModel.Region region:page.regions()){boolean explicit=options.overrides().sharedRegionFingerprints().contains(region.fingerprint());String key=explicit?"declared|"+region.fingerprint():"observed|"+componentFingerprint(page,region);groups.computeIfAbsent(key,x->new ArrayList<>()).add(new PageRegion(page,region));}List<ApplicationModel.SharedComponent>out=new ArrayList<>();for(var entry:groups.entrySet()){Set<String>pageIds=new TreeSet<>();Set<String>elementIds=new TreeSet<>();for(PageRegion pr:entry.getValue()){pageIds.add(pr.page.pageId());pr.page.elements().stream().filter(e->Objects.equals(e.regionId(),pr.region.regionId())).map(ApplicationModel.ElementModel::elementId).forEach(elementIds::add);}boolean explicit=entry.getKey().startsWith("declared|");if(pageIds.size()<2&&!explicit)continue;String regionFingerprint=entry.getValue().get(0).region.fingerprint();String id=ApplicationIds.id("component-v1",entry.getKey());String name=SemanticNaming.javaIdentifier(entry.getValue().get(0).region.semanticName(),"SharedComponent");out.add(new ApplicationModel.SharedComponent(id,name,new ArrayList<>(pageIds),new ArrayList<>(elementIds),List.of(regionFingerprint),explicit?ApplicationModel.EvidenceSource.USER_DECLARED:ApplicationModel.EvidenceSource.INFERRED,entry.getValue().get(0).region.provenance()));}return out;}
    private static String componentFingerprint(ApplicationModel.PageModel page,ApplicationModel.Region region){String[]signals=java.util.stream.Stream.concat(java.util.stream.Stream.of(region.fingerprint()),page.elements().stream().filter(e->Objects.equals(e.regionId(),region.regionId())).map(e->e.type().name()+"|"+e.semanticRole()+"|"+e.semanticName()).sorted()).toArray(String[]::new);return ApplicationIds.id("component-structure-v1",signals);}
    private static <T>Map<String,T>by(List<T>values,java.util.function.Function<T,String>id){Map<String,T>out=new TreeMap<>();values.forEach(v->out.put(id.apply(v),v));return out;}
    private static List<String>union(List<String>a,List<String>b){return java.util.stream.Stream.concat(a.stream(),b.stream()).distinct().sorted().toList();}
    private static List<ApplicationModel.Transition>unionTransitions(List<ApplicationModel.Transition>a,List<ApplicationModel.Transition>b){Map<String,ApplicationModel.Transition>m=by(a,ApplicationModel.Transition::transitionId);b.forEach(x->m.putIfAbsent(x.transitionId(),x));return new ArrayList<>(m.values());}
    private static List<ApplicationModel.Limitation>unionLimits(List<ApplicationModel.Limitation>a,List<ApplicationModel.Limitation>b){return java.util.stream.Stream.concat(a.stream(),b.stream()).distinct().toList();}
    private MergeOutcome outcome(boolean retained,boolean stateRetained,int before){return new MergeOutcome(retained,stateRetained,List.copyOf(limitations.subList(before,limitations.size())));}
    record MergeOutcome(boolean retained,boolean stateRetained,List<ApplicationModel.Limitation>limitations){}
    record PageScanResult(ApplicationModel.PageModel page,int discoveredNodes,int skipped,int selectorAnalyses,boolean truncated,List<ApplicationModel.Limitation>limitations,Map<String,PageScanner.DiscoveredElement>targets,long discoveryNanos,long selectorNanos){}
    private record PageRegion(ApplicationModel.PageModel page,ApplicationModel.Region region){}
}
